/* make-figures.js — emit figures.tex (pgfplots) from out/page.json.
   Nothing is retyped. node make-figures.js && tectonic occultation-paper.tex */
'use strict';
const fs = require('fs'), path = require('path');
const D = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'out', 'page.json'), 'utf8'));
const R1 = D.ladder.find(r => r.nsig === 1);
const pos = D.sites.filter(s => s.status === 'positive');
const neg = D.sites.filter(s => s.status === 'negative').filter(s => Math.abs(+s.y) < 200);

const co = P => P.map(p => `(${p[0].toFixed(4)},${p[1].toFixed(4)})`).join(' ');
const bars = pos.map(s => `\\addplot[only marks,mark=*,mark size=1.4pt,black,error bars/.cd,y dir=both,y explicit]
  coordinates {(${(+s.y).toFixed(2)},${(+s.len).toFixed(2)}) +- (0,${(+s.err).toFixed(2)})};`).join('\n');
const negm = neg.map(s => `\\addplot[only marks,mark=|,mark size=4pt,gray] coordinates {(${(+s.y).toFixed(2)},0)};`).join('\n');

const fig1 = `\\begin{tikzpicture}
\\begin{axis}[width=\\linewidth,height=6.4cm,xlabel={cross-track position on the sky plane (km)},
 ylabel={chord length $w$ (km)},xmin=${(R1.capLo - 15).toFixed(0)},xmax=${(R1.capHi + 15).toFixed(0)},ymin=0,
 tick label style={font=\\scriptsize},label style={font=\\small},
 legend style={font=\\scriptsize,at={(0.02,0.03)},anchor=south west,draw=none,fill=none}]
\\addplot[black,thick] coordinates {${co(R1.polyHi)}};
\\addlegendentry{ceiling}
\\addplot[black,thick] coordinates {${co(R1.polyLo)}};
\\addlegendentry{floor}
\\addplot[gray,densely dashed] coordinates {${co(R1.polyDots)}};
\\addlegendentry{joining the dots (an assumption)}
${bars}
${negm}
\\end{axis}
\\end{tikzpicture}`;

const rows = D.ladder;
const fig2 = `\\begin{tikzpicture}
\\begin{axis}[width=\\linewidth,height=5.6cm,xlabel={area-equivalent diameter (km)},
 ytick={${rows.map((_, i) => i + 1).join(',')}},
 yticklabels={${rows.map(r => r.nsig === 0 ? 'as published' : `$${r.nsig}\\sigma$`).join(',')}},
 ymin=0.4,ymax=${rows.length + 0.6},xmin=130,xmax=320,
 tick label style={font=\\scriptsize},label style={font=\\small},y tick label style={font=\\tiny}]
\\addplot[draw=none] coordinates {(130,1)};
\\draw[gray,densely dashed] (axis cs:${D.ellipse[0].DeqKm},0.4) -- (axis cs:${D.ellipse[0].DeqKm},${rows.length + 0.6});
\\draw[gray,densely dashed] (axis cs:${D.published.radiometric[0].DKm},0.4) -- (axis cs:${D.published.radiometric[0].DKm},${rows.length + 0.6});
${rows.map((r, i) => `\\draw[${r.feasible.ok ? 'very thick' : 'very thick,densely dotted'}] (axis cs:${r.DeqLo.toFixed(2)},${i + 1}) -- (axis cs:${r.DeqHi.toFixed(2)},${i + 1});`).join('\n')}
\\end{axis}
\\end{tikzpicture}`;

fs.writeFileSync(path.join(__dirname, 'figures.tex'),
  `% generated by make-figures.js — do not edit\n\\newcommand{\\figEnvelope}{${fig1}}\n\\newcommand{\\figLadder}{${fig2}}\n`);
console.log('figures.tex written');
