"""F-213 — "Complex Matrix Multiplication Below 2.258 and Rectangular Bounds" (openai/math family 107, tier B).

THE CLAIM (build/main.tex:63-70, abstract; build/introduction.tex:72-78, Theorem thm:main): "Over C, the arithmetic
matrix-multiplication exponents satisfy omega < 1129/500 = 2.258, alpha > 0.465, w(0.709) < 2.092", transferred to
every field of characteristic zero (and all but finitely many positive characteristics for the strict square and
k = 0.709 bounds). The square bound rests on Theorem thm:certificate (tex/certificate.tex:20-31):
F_beta(alpha_*) >= 1.098619383270680538 > log 3 at beta = 1129/500, proved by a chart P = P_{780,500} (an integer
recursion, published as the 18 MB file qP780_gmp), a 52-coefficient barrier phi (inputs/newc22, Table
cert:barrier-coefficients), an interior lemma (L phi > -1 + 9.8e-8 on the closed domain, a branch-and-bound over
128 x 128 polar boxes to depth 28), a boundary lemma (F_beta >= phi + 5.5e-6 on the boundary, from a face bound built on
a three-state seed U and a cap bound) and a comparison principle. The rectangular bounds rest on three explicit
label-tree witnesses (rectangular/07-certificates.tex).

VERDICT: REFUSED. The whole square certificate cannot be completed here, for two exact reasons.
  (1) MISSING DATA. The boundary lemma (certificate.tex:562-890) and the W seed (certificate-w.tex:430-498) bound U from
      below by a finite library of completion/parity records. The records are not published: the inputs are only the
      barrier and the two charts (verification/certificate/inputs/), and the paper specifies the library by its program —
      "The supplied finite program fixes all these selection choices, including ties" (certificate-w.tex:272-273),
      "Its deterministic integer implementation is menu.hpp" (certificate-w.tex:240-241). The recorded gaps
      (W-seed minimum -4180063084/2^52, face minimum 128315602072/2^52, cap 152568202355/2^52; reproducibility.tex:88-95)
      are outputs of that program. A clean-room decision would have to rebuild a record library of comparable quality
      from the prose menu protocol, which is underdetermined (lookup radius, rounded exponential weights, ties).
  (2) COST. The interior lemma (certificate.tex:380-560) is a validated-numerics branch-and-bound: five fields of degree
      < 320 with < 52,000 monomials, 16,384 initial polar boxes, degree-14 x 14 Taylor arrays generated by an 84-order
      trigonometric recurrence at scale 2^115 and Horner substitution at scale 2^69, bisection to depth 28. The number of
      boxes actually visited is not published (interior-sectors.json records only exit codes and "128" per sector). The
      Horner stage alone is about 320 x 225 x 5 = 3.6e5 big-integer operations per box, ~6e9 before any subdivision —
      hours of pure-Python CPU per pass, with an unknown subdivision multiplier; the geometry tests (230,400 centers of a
      degree-40 chart with derivatives, certificate.tex:267-296, ~1e9 operations) were likewise not attempted.

WHAT IS DECIDED HERE (finite components, exact): all are checks inside the REFUSED verdict; a failure of any of them
would be a REFUTED of the published object.
  SQUARE, the published objects:
   - the barrier: the 52 decimals of Table cert:barrier-coefficients equal inputs/newc22 entry for entry; the index set
     I = {j <= i, i+j <= 22, i-j = 0 mod 3} has 52 elements in the printed order; phi(0) = a_00 = 1.098619383270680538;
     phi(0) - log 3 > 7.094e-6 and > 7.0946e-6 (rigorous log 3); the five fourth-derivative sums (certificate.tex:706-715)
     are < 435e6 with maximum < 434439204; the radial sums weighted by d^k (certificate.tex:686-690, read as
     sum |a_ij| R^(i+j) (i+j)^k) are below the five printed bounds.
   - the charts: qP420_gmp (88,831 coefficients) and qP780_gmp (305,371) are each verified to be the fixed point of the
     recursion of certificate.tex:111-149 — pure coefficients, symmetry, and every A_ij = rnd(-S_ij/(C_00 i j))
     recomputed from the file's own lower-degree entries (~7.7e9 big-integer products for the 780 chart, run in
     parallel), so by induction on degree each file IS the recursion's output (decide(regen420=True) also regenerates
     P_{420,224} from nothing, ~100 s, and matches the file entry for entry); 21 < C_00/Q < 22 for both; p of
     Theorem thm:certificate equals A_00/2^500; E_1(0) = 1/3 - P(0) > .1471.
   - the residual: rho + sum_{s} sum_{k+m>N} D_{s,k} V_{s,m} (certificate.tex:182-212), computed EXACTLY as a rational
     from the verified chart, is < 3.328667e-22 (the paper's eps); 6 eps/eta < 9.987e-13 < 1e-12 with eta = 2e-9.
   - the chart comparisons: the five rows of the |P - P^ref| table (certificate.tex:234-243), the jet bounds .592 / 3.05
     for both charts, the degree-40 truncation bounds .0002 / .006, and the reference chart's disk sums (.414, k^2 < 6).
     Not checked: the ".921" absolute majorant of the 861 degree-40 coefficients (certificate.tex:290-292), whose
     quantity is not defined precisely enough to recompute (the plain disk sum of those coefficients is printed in the
     detail for comparison).
   - the W-seed polynomial H_W: the rational recursion (certificate-w.tex:92-108) with 6441 monomials, its residual
     b_ij = 0 exactly for i+j <= 110 and sum |b_ij| R_W^(i+j) < 6.739223e-13; S_0, S_1, S_2 below the printed bounds;
     the shell constants r_*, r_1, r_2, rho >= .20947544, |z'|, |z''| and |(H_W o z)''| < 30.348.
   - the library error recurrences (certificate-w.tex:313-362): e_14 = 3637206/B < 8.5e-10, f_14 < 3.635e-9, and the
     initial recurrence's f_12 <= 1159.991/B.
  RECTANGULAR (rectangular/07-certificates.tex), in fixed-point interval arithmetic with rigorous log/exp enclosures:
   - the dual witness: the seven completions -2,+2,+2,-3,+2,-2,+3 run through Lemma lem:uniform-update exactly as
     stated (rho exactly rational, the h's as intervals), centers B,A,C,B,C,B,A; every printed bound of the b = 8 / 24 /
     48 / 96 / 288 table; D_288 also re-derived by the delta/z shortcut (eq. delta-D); 2 D_288 / log 2 > 0.465 and the
     printed rational 1548637/3327360; the reference value 0.466101554898.
   - the curve: the fiber histogram (8, 12, 6, 1 at d = 1, 2, 4, 19; 75 leaves) re-enumerated from the stated rule; the
     cube-root brackets, Z, g, h at t = 2/3; 2g/h > 0.709 and 6 log 3/h < 2.092; reference values.
   - the finite-family square witness: the completion counts (the printed 3-step and 4-step vectors, N exactly),
     N > 2.95e45, 216 log 3 / log N < 2.267; reference value.
   - the elementary log/exp table of subsec:log-certificate.

WHAT IS NOT DECIDED: the interior lemma and the geometry tests (cost), the boundary lemma and the W-seed finite check
(the library is not published), hence Lemma cert:boundary-lemma and Theorem thm:certificate; and all theory: the
attainable-value function F_beta and its closure/concavity, Theorem thm:ap and the comparison argument, Propositions
face / matching / monotonicity, the asymptotic sum inequality, the characteristic transfer, Theorem thm:entropy,
Corollary cor:balance and Lemma lem:uniform-update (the rectangular formulas are evaluated as stated, not proved).
The rectangular components certify the finite witnesses of alpha > 0.465 and w(0.709) < 2.092, not the bounds.

RESULT (2026-10-10): every one of the 36 decided checks passes, so the verdict is REFUSED (not REFUTED). The 780 chart's
fixed-point verification took 1354 s wall on 6 forked workers on a heavily loaded machine; everything else takes under
a minute (P_{420,224} regenerated from nothing: ~100-220 s). The exact residual bound is eps <= 3.328666321e-22 (the
paper: < 3.328667e-22, computed with 2^160 upward rounding). The rectangular values: 2 D_288/log 2 = 0.46610155489847...,
2g/h = 0.70969893251..., 6 log 3/h = 2.09125183562..., 216 log 3/log N = 2.26618743899... All five forges are REFUTED.

READ AFTER THIS DECIDER RAN (verification/, never executed). chart_gmp.cpp regenerates both charts with GMP;
certify_chart.py reads a chart, asserts only its symmetry, and computes eps and the |P - P^ref| sums with 2^160 upward
rounding — so the link between the shipped bytes and the recursion rests on regeneration, which --reuse-charts skips (the
paper says as much, reproducibility.tex:51-58); here it is verified independently, in Python, as a fixed point. ib.cpp
builds the W-seed record library at run time through menu.hpp (int64 at scale 2^52 with int128 products): the records
exist only as program state, never as data. rooLS.py / rooLS.cpp generate and check the interior Taylor arrays;
run_interior.py still names paths from the authors' workspace (source/dynamic-edit-recovery/full-cat) that the driver
substitutes; the final summary takes the analytic margins 9.8e-8, 5.5e-6 and 1.3e-6 as inputs. For the rectangular
part, verify_rational.py checks the displayed rational chain starting from the printed bounds (it does not re-run
Lemma lem:uniform-update's h-recursion, which is done here), and verify_construction.py enumerates the 75-monomial
support from the base tensor (stronger than the histogram re-enumeration from the stated rule done here).

RELATED (manuscript #212, preprints/Matrix-Multiplication-Nine-Fourths-October-2-2026, read 2026-10-10 for this row):
it claims omega <= 9/4 (paper.tex:45-49), which is stronger than this row's omega < 2.258. Its directory holds only
README.md, paper.pdf and build/paper.tex (1,022 lines): no verification directory, no data file, no verbatim, tabular
or listing block. The proof is a spectral argument (detecting tensor characters, a Fourier separation lemma, a
polynomial-multiplication profile P(a,b) with P(a,3h+a-1) >= 3P(a,h), paper.tex:114-132) with no explicit tensor and no
numerical certificate. There is nothing finite to decide there.
"""
import itertools
import json
import math
import multiprocessing
import os
import re
import sys
import time
from fractions import Fraction
from operator import mul

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import Sources, check  # noqa: E402

DIR = 'preprints/Complex-Matrix-Multiplication-Below-2.258-and-Rectangular-Bounds-September-24-2026/'
MAIN = DIR + 'build/main.tex'
INTRO = DIR + 'build/introduction.tex'
CERT = DIR + 'build/tex/certificate.tex'
CERTW = DIR + 'build/tex/certificate-w.tex'
BARRIER_TEX = DIR + 'build/tex/barrier-coefficients.tex'
REPRO = DIR + 'build/tex/reproducibility.tex'
RECT = DIR + 'build/rectangular/07-certificates.tex'
NEWC22 = DIR + 'verification/certificate/inputs/newc22'
QP420 = DIR + 'verification/certificate/inputs/qP420_gmp'
QP780 = DIR + 'verification/certificate/inputs/qP780_gmp'
OTHER = 'preprints/Matrix-Multiplication-Nine-Fourths-October-2-2026/'

# ---------------------------------------------------------------- fixed-point intervals (integers / 2^P)
P = 256
G = 32
Q_ = P + G


def iratio(n, d):
    if d < 0:
        n, d = -n, -d
    return ((n << P) // d, -((-n << P) // d))


def ifrac(fr):
    fr = Fraction(fr)
    return iratio(fr.numerator, fr.denominator)


def iadd(a, b):
    return (a[0] + b[0], a[1] + b[1])


def isub(a, b):
    return (a[0] - b[1], a[1] - b[0])


def iscale(a, k):
    return (a[0] * k, a[1] * k) if k >= 0 else (a[1] * k, a[0] * k)


def imul(a, b):
    ps = (a[0] * b[0], a[0] * b[1], a[1] * b[0], a[1] * b[1])
    return (min(ps) >> P, -((-max(ps)) >> P))


def idiv(a, b):
    if b[0] <= 0:
        raise ValueError('division by an interval that is not positive')
    return (min((x << P) // y for x in a for y in b), max(-((-x << P) // y) for x in a for y in b))


def ipow(a, m):
    r = (1 << P, 1 << P)
    for _ in range(m):
        r = imul(r, a)
    return r


def _atanh(num, den, terms, upper, tail_factor):
    if upper:
        z = -((-num << Q_) // den)
        z2 = -((-(z * z)) >> Q_)
    else:
        z = (num << Q_) // den
        z2 = (z * z) >> Q_
    pw, s = z, 0
    for j in range(terms):
        s += -((-pw) // (2 * j + 1)) if upper else pw // (2 * j + 1)
        pw = -((-(pw * z2)) >> Q_) if upper else (pw * z2) >> Q_
    return s + (tail_factor * pw if upper else 0)


_N3 = Q_ // 3 + 8
LN2Q = (2 * _atanh(1, 3, _N3, False, 0), 2 * _atanh(1, 3, _N3, True, 2))       # tail <= 9/8 z^(2n+1) < 2 z^(2n+1)
LNTAB = [(2 * _atanh(m, 64 + m, _N3, False, 0), 2 * _atanh(m, 64 + m, _N3, True, 2)) for m in range(32)]
_NT = Q_ // 12 + 3


def _ln_bound(v, upper):
    """bound of ln(v / 2^P) * 2^Q_; ln = e ln 2 + ln(1 + m/32) + 2 atanh(z), z < 1/64, tail <= z^(2n+1)"""
    k = v.bit_length() - 1
    m = ((v << 5) >> k) - 32
    e = k - P
    num = 32 * v - ((32 + m) << k)
    den = 32 * v + ((32 + m) << k)
    if upper:
        return 2 * _atanh(num, den, _NT, True, 1) + LNTAB[m][1] + (e * LN2Q[1] if e >= 0 else e * LN2Q[0])
    return 2 * _atanh(num, den, _NT, False, 0) + LNTAB[m][0] + (e * LN2Q[0] if e >= 0 else e * LN2Q[1])


def ilog(a):
    if a[0] <= 0:
        raise ValueError('log of a non-positive interval')
    return (_ln_bound(a[0], False) >> G, -((-_ln_bound(a[1], True)) >> G))


def iexp(a):
    """exp of an interval: halve until |x| <= 1/2, Taylor to 80 terms with remainder 2|x|^80/80!, square back"""
    lim = max(abs(a[0]), abs(a[1]))
    s = 0
    while lim > (1 << (P - 1)):
        lim >>= 1
        s += 1
    x = (a[0] >> s, -((-a[1]) >> s))           # outward
    one = (1 << P, 1 << P)
    t, tot = one, one
    for n in range(1, 80):
        t = idiv(imul(t, x), (n << P, n << P))
        tot = iadd(tot, t)
    xm = max(abs(x[0]), abs(x[1]))
    rem = -((-(2 * xm ** 80)) // (math.factorial(80) * (1 << (79 * P)))) + 1
    tot = (tot[0] - rem, tot[1] + rem)
    for _ in range(s):
        tot = imul(tot, tot)
    return tot


def iint(k):
    return (k << P, k << P)


LN2 = ilog(iint(2))
LN3 = ilog(iint(3))


def gtF(iv, fr):
    fr = Fraction(fr)
    return iv[0] * fr.denominator > fr.numerator << P


def ltF(iv, fr):
    fr = Fraction(fr)
    return iv[1] * fr.denominator < fr.numerator << P


def inside(iv, a, b):
    return gtF(iv, a) and ltF(iv, b)


def dec(iv, d=15):
    sc = 10 ** d
    lo, hi = (iv[0] * sc) >> P, -((-(iv[1] * sc)) >> P)

    def f(q):
        s = '-' if q < 0 else ''
        q = abs(q)
        return '%s%d.%0*d' % (s, q // sc, d, q % sc)
    return '[%s, %s]' % (f(lo), f(hi))


def near(iv, center, tol):
    c = Fraction(center)
    return inside(iv, c - Fraction(tol), c + Fraction(tol))


def tight_agree(a, b, eps=Fraction(1, 10 ** 60)):
    """two enclosures of what the paper says is one number agree to 1e-60 (a consistency check, not an identity proof)"""
    return inside(isub(a, b), -eps, eps)


# ---------------------------------------------------------------- RECTANGULAR witnesses (07-certificates.tex)
def dual_witness(script=(-2, 2, 2, -3, 2, -2, 3)):
    """Lemma lem:uniform-update as stated; rho exact, h's intervals; returns the trajectory"""
    rho = Fraction(1, 2)
    b = 1
    zero = (0, 0)
    h = {'A': zero, 'B': zero, 'C': zero}
    traj = []
    for step in script:
        m = abs(step)
        rec = {'step': step}
        if step < 0:
            r2 = rho ** m
            hB = h['B']
            new = {'B': iscale(hB, m)}
            for i in ('A', 'C'):
                new[i] = iscale(iadd(imul(ifrac((rho - r2) / (1 - r2)), hB), imul(ifrac((1 - rho) / (1 - r2)), h[i])), m)
            rec['center'] = 'B'
            rec['z'] = None
        else:
            hA, hC = h['A'], h['C']
            if hA == hC == zero:
                i = 'A'                          # the paper's tie choice (07-certificates.tex:153)
            elif hA[0] > hC[1]:
                i = 'A'
            elif hC[0] > hA[1]:
                i = 'C'
            else:
                raise ValueError('undecided comparison of h_A and h_C')
            j = 'C' if i == 'A' else 'A'
            r2 = 1 - (1 - rho) ** m
            new = {'B': iscale(iadd(imul(ifrac(rho / r2), h['B']), imul(ifrac((r2 - rho) / r2), h[i])), m),
                   i: iscale(h[i], m)}
            ex = iexp(isub(h[j], h[i]))
            z = ilog(isub(ipow(iadd(iint(1), ex), m), iint(1)))
            new[j] = iadd(iscale(h[i], m), z)
            rec['center'] = i
            rec['z'] = z
        rho, b, h = r2, b * m, new
        dl = isub(h['A'], h['C'])
        delta = dl if dl[0] >= 0 else (-dl[1], -dl[0])
        if dl[0] < 0 < dl[1]:
            delta = (0, max(-dl[0], dl[1]))
        mx = h['A'] if h['A'][0] > h['C'][1] else (h['C'] if h['C'][0] > h['A'][1] else (min(h['A'][0], h['C'][0]), max(h['A'][1], h['C'][1])))
        D = idiv(iadd(imul(ifrac(rho), h['B']), imul(ifrac(1 - rho), mx)), iint(b))
        rec.update(rho=rho, b=b, h=dict(h), delta=delta, D=D)
        traj.append(rec)
    return traj


def dual_shortcut(script=(-2, 2, 2, -3, 2, -2, 3)):
    """the delta / z / D recursion of eq. (delta-D), started from b = 8 as printed (a second derivation of D_288)"""
    rho = Fraction(1) - Fraction(3, 4) ** 4
    b = 8
    delta = isub(ilog(iint(9)), ilog(iint(7)))
    D = imul(ifrac(Fraction(5625, 40000)), LN3)
    zs = {}
    for step in script[3:]:
        m = abs(step)
        if step < 0:
            r2 = rho ** m
            delta = imul(ifrac(m * (1 - rho) / (1 - r2)), delta)
        else:
            r2 = 1 - (1 - rho) ** m
            z = ilog(isub(ipow(iadd(iint(1), iexp((-delta[1], -delta[0]))), m), iint(1)))
            zs[b * m] = z
            zpos = z if z[0] >= 0 else (0, max(0, z[1]))
            D = iadd(D, imul(ifrac((1 - r2) / (m * b)), zpos))
            delta = z if z[0] >= 0 else (-z[1], -z[0])
        rho, b = r2, b * m
    return rho, b, delta, D, zs


def rect_checks(checks, rect, script=(-2, 2, 2, -3, 2, -2, 3), zero_fiber=None, claimed_alpha='0.465'):
    sq = re.sub(r'\s+', '', rect)
    traj = dual_witness(script)
    by_b = {r['b']: r for r in traj}
    check(checks, 'R1 dual witness: the script -2,+2,+2,-3,+2,-2,+3 and centers B,A,C,B,C,B,A (07-certificates.tex:145-154)',
          [r['center'] for r in traj] == ['B', 'A', 'C', 'B', 'C', 'B', 'A'] and '-2,\\quad+2,\\quad+2,\\quad-3,\\quad+2,\\quad-2,\\quad+3' in sq,
          str([r['center'] for r in traj]))
    r8 = by_b.get(8)
    zs = [r['z'] for r in traj if r['z'] is not None]
    if r8 is not None and len(zs) >= 2:
        ok8 = (r8['rho'] == 1 - Fraction(3, 4) ** 4 and tight_agree(r8['delta'], isub(ilog(iint(9)), ilog(iint(7))))
               and tight_agree(r8['D'], imul(ifrac(Fraction(5625, 40000)), LN3))
               and tight_agree(zs[0], LN3) and tight_agree(zs[1], isub(ilog(iint(7)), ilog(iint(9)))))
    else:
        ok8 = False
    check(checks, 'R1 at b = 8: rho_8 = 1-(3/4)^4 exactly; delta_8, D_8 = (0.5625/4) log 3 and the two z (log 3, log 7/9) agree to 1e-60',
          ok8)
    alpha = idiv(iscale(traj[-1]['D'], 2), LN2)
    rat = Fraction(2) / Fraction('0.6932') * (Fraction('0.5625') * Fraction('1.098') / 4 + Fraction('0.463') * Fraction('0.635') / 48
                                              + Fraction('0.360') * Fraction('0.628') / 288)
    check(checks, 'R1 the printed rational: (2/0.6932)[0.5625*1.098/4 + 0.463*0.635/48 + 0.360*0.628/288] = 1548637/3327360 > 0.465',
          rat == Fraction(1548637, 3327360) and rat > Fraction('0.465') and '\\frac{1548637}{3327360}>0.465' in sq)
    check(checks, 'R1 THE DUAL WITNESS: alpha >= min(1, 2 D_%d/log 2) > 1548637/3327360 > %s' % (traj[-1]['b'], claimed_alpha),
          gtF(alpha, claimed_alpha) and gtF(alpha, rat), dec(alpha, 15))
    check(checks, 'R1 the reference value 2 D_288/log 2 = 0.466101554898 (to 5e-13)', near(alpha, '0.466101554898', '5e-13'))
    r24, r48, r96, r288 = (by_b.get(k) for k in (24, 48, 96, 288))
    if None in (r24, r48, r96, r288):
        check(checks, 'R1 the printed b = 24 / 48 / 96 / 288 table', False, 'the script does not reach b = 288')
    else:
        z48 = traj[4]['z']
        z288 = traj[6]['z']
        rows = [
            ('rho_24 = rho_8^3 in (0.3194, 0.3195)', r24['rho'] == r8['rho'] ** 3 and Fraction('0.3194') < r24['rho'] < Fraction('0.3195')),
            ('0.348 < delta_24 < 0.354', inside(r24['delta'], '0.348', '0.354')),
            ('delta_24 = 3(1-rho_8)/(1-rho_8^3) log(9/7)', tight_agree(r24['delta'], imul(ifrac(3 * (1 - r8['rho']) / (1 - r8['rho'] ** 3)), isub(ilog(iint(9)), ilog(iint(7)))))),
            ('1-rho_48 = (1-rho_24)^2 > 0.463, 0.536 < rho_48 < 0.537', 1 - r48['rho'] == (1 - r24['rho']) ** 2 and 1 - r48['rho'] > Fraction('0.463')
             and Fraction('0.536') < r48['rho'] < Fraction('0.537')),
            ('0.635 < z_48 < 0.651', z48 is not None and inside(z48, '0.635', '0.651')),
            ('rho_96 = rho_48^2, delta_96 = 2 delta_48/(1+rho_48) < 0.86', r96['rho'] == r48['rho'] ** 2
             and tight_agree(r96['delta'], imul(ifrac(Fraction(2) / (1 + r48['rho'])), r48['delta'])) and ltF(r96['delta'], '0.86')),
            ('1-rho_288 = (1-rho_48^2)^3 > 0.360', 1 - r288['rho'] == (1 - r48['rho'] ** 2) ** 3 and 1 - r288['rho'] > Fraction('0.360')),
            ('z_288 > 0.628', z288 is not None and gtF(z288, '0.628')),
        ]
        check(checks, 'R1 the printed table at b = 24, 48, 96, 288 (07-certificates.tex:184-198)', all(g for _, g in rows),
              '; '.join(n for n, g in rows if not g) or 'all eight rows')
        rho_s, b_s, delta_s, D_s, zs_s = dual_shortcut(script)
        check(checks, 'R1 D_288 from the h-recursion agrees with the delta/z shortcut of eq. (delta-D) to 1e-60',
              b_s == 288 and rho_s == r288['rho'] and tight_agree(D_s, r288['D']), dec(r288['D'], 20))

    # R2 the curve
    hist = {}
    total = 0
    for x in itertools.product(range(3), repeat=3):
        if any(x):
            dx = 2 ** x.count(0)
        else:
            dx = 3 ** 3 - 2 ** 3 if zero_fiber is None else zero_fiber
        hist[dx] = hist.get(dx, 0) + 1
        total += dx
    check(checks, 'R2 the fiber histogram re-enumerated from d(x) = 2^#zeros, d(0) = 3^3 - 2^3: {1: 8, 2: 12, 4: 6, 19: 1}, 75 leaves',
          hist == {1: 8, 2: 12, 4: 6, 19: 1} and total == 75, str(hist))
    t = Fraction(2, 3)
    u = iexp(imul(ifrac(t), LN2))
    l19 = ilog(iint(19))
    v = iexp(imul(ifrac(t), l19))
    check(checks, 'R2 cube-root brackets: 1.58739^3 < 4 < 1.58742^3 and 7.1203^3 < 361 < 7.1205^3; u = 2^(2/3), v = 19^(2/3) inside them',
          Fraction('1.58739') ** 3 < 4 < Fraction('1.58742') ** 3 and Fraction('7.1203') ** 3 < 361 < Fraction('7.1205') ** 3
          and inside(u, '1.58739', '1.58742') and inside(v, '7.1203', '7.1205'))
    Zs = {1: 8, 2: 12, 4: 6, 19: 1} if zero_fiber is None else {kk: vv for kk, vv in hist.items()}
    Zt = (0, 0)
    dZ = (0, 0)
    for dd, cnt in Zs.items():
        ld = ilog(iint(dd))
        p = iexp(imul(ifrac(t), ld))
        Zt = iadd(Zt, iscale(p, cnt))
        dZ = iadd(dZ, iscale(imul(p, ld), cnt))
    g = idiv(dZ, Zt)
    hh = isub(ilog(Zt), imul(ifrac(t), g))
    check(checks, 'R2 49.2878 < Z(2/3) < 49.2890, 1.11844 < g < 1.11856, 3.1519 < h < 3.1522',
          inside(Zt, '49.2878', '49.2890') and inside(g, '1.11844', '1.11856') and inside(hh, '3.1519', '3.1522'),
          'Z %s g %s h %s' % (dec(Zt, 6), dec(g, 7), dec(hh, 6)))
    k = idiv(iscale(g, 2), hh)
    wv = idiv(iscale(LN3, 6), hh)
    check(checks, 'R2 THE CURVE WITNESS: 2g/h > 0.709 and 6 log 3/h < 2.092 (and the printed chains 2*1.11844/3.1522 > 0.709, 6*1.0987/3.1519 < 2.092)',
          gtF(k, '0.709') and ltF(wv, '2.092') and Fraction('2.23688') / Fraction('3.1522') > Fraction('0.709')
          and 6 * Fraction('1.0987') / Fraction('3.1519') < Fraction('2.092'), '2g/h %s, 6log3/h %s' % (dec(k, 12), dec(wv, 12)))
    check(checks, 'R2 reference values 2g/h = 0.709698932519 and 6 log 3/h = 2.091251835621 (to 5e-13)',
          near(k, '0.709698932519', '5e-13') and near(wv, '2.091251835621', '5e-13'))

    # R3 the finite-family square witness
    d = {'B': 2, 'A': 2, 'C': 1}
    vecs = []
    for col, m in (('B', 2), ('A', 3), ('C', 2), ('B', 2), ('A', 3)):
        new = {col: d[col] ** m}
        for o in d:
            if o != col:
                new[o] = (d[col] + d[o]) ** m - d[col] ** m
        d = new
        vecs.append((d['B'], d['A'], d['C']))
    Nn = d['B'] + d['C']
    check(checks, 'R3 completion counts: after three steps (20691584, 13993344, 10144225), after four (428141648429056, 774902581936128, 522705468255425)',
          vecs[2] == (20691584, 13993344, 10144225) and vecs[3] == (428141648429056, 774902581936128, 522705468255425))
    check(checks, 'R3 N = 2995461856366867388223311649574852466276480577 >= 10^36 (1202^3 + 1296^3 - 2*774^3) > 2.95e45; b = 72',
          Nn == 2995461856366867388223311649574852466276480577 and Nn >= 10 ** 36 * (1202 ** 3 + 1296 ** 3 - 2 * 774 ** 3)
          and 10 ** 36 * (1202 ** 3 + 1296 ** 3 - 2 * 774 ** 3) > Fraction(295, 100) * 10 ** 45 and 2 * 3 * 2 * 2 * 3 == 72)
    wN = idiv(iscale(LN3, 216), ilog(iint(Nn)))
    check(checks, 'R3 THE FAMILY SQUARE WITNESS: 216 log 3 / log N < 2.267 (and the printed chain 216*1.0987/(1.0817 + 45*2.3025) < 2.267)',
          ltF(wN, '2.267') and 216 * Fraction('1.0987') / (Fraction('1.0817') + 45 * Fraction('2.3025')) < Fraction('2.267'), dec(wN, 12))
    check(checks, 'R3 reference value 216 log 3 / log N = 2.266187438999 (to 5e-13)', near(wN, '2.266187438999', '5e-13'))

    # R4 the elementary table
    l49 = (ilog(ifrac(Fraction('49.2878')))[0], ilog(ifrac(Fraction('49.2890')))[1])
    tab = [inside(LN2, '0.69314', '0.69316'), inside(LN3, '1.098', '1.0987'), inside(l19, '2.9444', '2.9445'),
           inside(l49, '3.89765', '3.89772'), inside(isub(ilog(iint(9)), ilog(iint(7))), '0.250', '0.252'),
           gtF(ilog(iint(10)), '2.3025'), gtF(ilog(ifrac(Fraction('2.95'))), '1.0817'),
           gtF(iexp(ifrac(Fraction('-0.354'))), '0.701'), ltF(iexp(ifrac(Fraction('-0.348'))), '0.707'),
           gtF(iexp(ifrac(Fraction('-0.86'))), '0.4225'),
           gtF(ilog(ifrac(Fraction('1.701') ** 2 - 1)), '0.635'), ltF(ilog(ifrac(Fraction('1.707') ** 2 - 1)), '0.651'),
           gtF(ilog(ifrac(Fraction('1.4225') ** 3 - 1)), '0.628'),
           Fraction(2) * Fraction('0.651') / (1 + Fraction('0.536')) < Fraction('0.86')]
    check(checks, 'R4 the log/exp table of subsec:log-certificate (14 enclosures)', all(tab), str([i for i, x in enumerate(tab) if not x]))
    return traj


# ---------------------------------------------------------------- SQUARE: the barrier
R = Fraction(31, 25)


def parse_barrier_tex(tex):
    rows = re.findall(r'^(\d+) & (\d+) & \$(-?[\d.]+)\\times10\^\{(-?\d+)\}\$ \\\\', tex, re.M)
    return [(int(i), int(j), Fraction(m) * Fraction(10) ** int(e)) for i, j, m, e in rows]


def barrier_checks(checks, btex, newc, cert, repro, const_override=None):
    tab = parse_barrier_tex(btex)
    vals = [Fraction(x) for x in newc.split()]
    I = [(i, j) for i in range(23) for j in range(i + 1) if i + j <= 22 and (i - j) % 3 == 0]
    check(checks, 'S1 barrier: Table cert:barrier-coefficients equals inputs/newc22 entry for entry (52 exact decimals) on the index set I, in order',
          len(tab) == 52 and len(vals) == 52 and [(i, j) for i, j, _ in tab] == I and [a for _, _, a in tab] == vals, '%d table rows, %d file values' % (len(tab), len(vals)))
    a = {(i, j): x for i, j, x in tab}
    if const_override is not None:
        a[(0, 0)] = Fraction(const_override)
    c0 = a[(0, 0)]
    check(checks, 'S1 phi(0) = a_00 = 1.098619383270680538 as printed (certificate.tex:23, 378)',
          c0 == Fraction('1.098619383270680538') and '1.098619383270680538' in cert)
    gap = isub(ifrac(c0), LN3)
    check(checks, 'S1 phi(0) - log 3 > 7.094e-6 (certificate.tex:977) and > 7.0946e-6 (reproducibility.tex:109)',
          gtF(gap, '0.000007094') and gtF(gap, '0.0000070946') and '7.0946\\cdot10^{-6}' in repro, dec(gap, 15))
    sums = []
    for aa in range(5):
        bb = 4 - aa
        s = Fraction(0)
        for (i, j), x in a.items():
            dd = i + j
            if dd >= aa:
                s += abs(x) * Fraction(math.factorial(dd), math.factorial(dd - aa)) * R ** (dd - aa) * abs(i - j) ** bb
        sums.append(s)
    check(checks, 'S1 the five fourth-derivative sums (certificate.tex:706-715) are < 435e6, the largest < 434439204',
          all(s < 435 * 10 ** 6 for s in sums) and max(sums) < 434439204, str([int(s) for s in sums]))
    rad = [sum(abs(x) * R ** (i + j) * (i + j) ** k for (i, j), x in a.items()) for k in range(5)]
    bounds = [35000, 750000, 15000000, 300000000, 6000000000]
    check(checks, 'S1 radial sums sum |a_ij| R^(i+j) (i+j)^k, k = 0..4, below 35000 / 750000 / 1.5e7 / 3e8 / 6e9 (certificate.tex:686-690, read so)',
          all(r < bnd for r, bnd in zip(rad, bounds)), str([int(r) for r in rad]))
    return a


# ---------------------------------------------------------------- SQUARE: the chart recursion
ZK = (18623, -2696, -2677, 194, 393, 17, 1, 8)
CC = {(0, 0): 8, (1, 0): 2, (0, 1): 2, (2, 0): -1, (0, 2): -1, (1, 1): -2}
_G = {}


def _tables(A, N, Qv):
    C = [[0] * (N - i + 1) for i in range(N + 1)]
    AW = [[[0] * (N - i + 1) for i in range(N + 1)] for _ in range(3)]
    for a_ in range(N + 1):
        for c_ in range(N - a_ + 1):
            v = A[a_][c_]
            C[a_][c_] = 72 * v + Qv * CC.get((a_, c_), 0)
            AW[0][a_][c_] = v * c_ * (c_ - 1)
            AW[1][a_][c_] = v * a_ * c_
            AW[2][a_][c_] = v * a_ * (a_ - 1)
    return C, AW


def _S(i, j, C, AW):
    """S_ij of eq. (cert:chart-rec): sum over 0 <= x < i, 0 <= y < j, (x,y) != (0,0) of C_xy A_ac w_h(a,c)"""
    S = 0
    for x in range(i):
        Cx = C[x]
        for h in range(3):
            y0 = (h + x - 1) % 3                 # h = 1 + y - x (mod 3)
            if x == 0 and y0 == 0:
                y0 = 3
            if y0 >= j:
                continue
            n = (j - 1 - y0) // 3 + 1
            a_ = i - x - 1 + h
            c0 = j - y0 + 1 - h
            cl = c0 - 3 * (n - 1)
            S += sum(map(mul, Cx[y0:j:3], reversed(AW[h][a_][cl:c0 + 1:3])))
    return S


def _worker(pairs):
    A, C, AW, C00 = _G['A'], _G['C'], _G['AW'], _G['C00']
    bad = []
    for i, j in pairs:
        S = _S(i, j, C, AW)
        if (-2 * S + C00 * i * j) // (2 * C00 * i * j) != A[i][j]:
            bad.append((i, j))
    return len(pairs), bad


def generate_chart(N, b):
    """the recursion of certificate.tex:111-149, from nothing"""
    Qv = 1 << b
    A = [[0] * (N - i + 1) for i in range(N + 1)]
    C = [[0] * (N - i + 1) for i in range(N + 1)]
    AW = [[[0] * (N - i + 1) for i in range(N + 1)] for _ in range(3)]

    def setc(a_, c_):
        v = A[a_][c_]
        C[a_][c_] = 72 * v + Qv * CC.get((a_, c_), 0)
        AW[0][a_][c_] = v * c_ * (c_ - 1)
        AW[1][a_][c_] = v * a_ * c_
        AW[2][a_][c_] = v * a_ * (a_ - 1)
    for k in range(N + 1):
        zk = ZK[k] if k < 8 else 0
        v = (2 * Qv * zk + 100000) // 200000          # rnd(Q Z_k / 100000)
        A[0][k] = v
        A[k][0] = v
        setc(0, k)
        setc(k, 0)
    C00 = C[0][0]
    for d in range(2, N + 1):
        for i in range(1, d // 2 + 1):
            j = d - i
            S = _S(i, j, C, AW)
            v = (-2 * S + C00 * i * j) // (2 * C00 * i * j)
            A[i][j] = v
            A[j][i] = v
            setc(i, j)
            setc(j, i)
    return A


def unflatten(vals, N):
    """the files list degree by degree, A_{d,0}, A_{d-1,1}, ..., A_{0,d}"""
    A = [[None] * (N - i + 1) for i in range(N + 1)]
    k = 0
    for d in range(N + 1):
        for i in range(d, -1, -1):
            A[i][d - i] = vals[k]
            k += 1
    return A


def verify_chart(vals, N, b, workers):
    """the supplied chart is the fixed point of the recursion: pure coefficients, symmetry, and every A_ij recomputed
    from the file's own lower-degree entries. By induction on degree the file then equals the recursion's output."""
    Qv = 1 << b
    if len(vals) != (N + 1) * (N + 2) // 2:
        return False, 'wrong length %d' % len(vals), None
    A = unflatten(vals, N)
    pure = all(A[0][k] == A[k][0] == (2 * Qv * (ZK[k] if k < 8 else 0) + 100000) // 200000 for k in range(N + 1))
    sym = all(A[i][j] == A[j][i] for i in range(N + 1) for j in range(N + 1 - i))
    C, AW = _tables(A, N, Qv)
    pairs = [(i, d - i) for d in range(2, N + 1) for i in range(1, d // 2 + 1)]
    pairs.sort(key=lambda p: -p[0] * p[1])
    nb = max(1, workers)
    bins = [[] for _ in range(nb)]
    load = [0] * nb
    for p in pairs:
        k = load.index(min(load))
        bins[k].append(p)
        load[k] += p[0] * p[1] + 1
    _G.update(A=A, C=C, AW=AW, C00=C[0][0])
    if nb == 1:
        res = [_worker(bins[0])]
    else:
        ctx = multiprocessing.get_context('fork')
        with ctx.Pool(nb) as pool:
            res = pool.map(_worker, bins)
    checked = sum(r[0] for r in res)
    bad = [x for r in res for x in r[1]]
    _G.clear()
    ok = pure and sym and not bad and checked == len(pairs)
    return ok, 'pure %s, symmetric %s, %d recursion equations checked, %d fail %s' % (pure, sym, checked, len(bad), bad[:3]), A


def residual_bound(A, N, b):
    """rho + sum_s sum_{k+m>N} D_{s,k} V_{s,m} of eq. (cert:residual-sum), as an exact rational"""
    Qv = 1 << b
    Cs = [[0] * (N + 1) for _ in range(3)]
    Vs = [[0] * (N + 1) for _ in range(3)]
    for a_ in range(N + 1):
        for c_ in range(N + 1 - a_):
            k = a_ + c_
            Cv = 72 * A[a_][c_] + Qv * CC.get((a_, c_), 0)
            Cs[(a_ - c_) % 3][k] += abs(Cv)
            av = abs(A[a_][c_])
            Vs[0][k] += av * a_ * c_
            Vs[1][k] += av * c_ * (c_ - 1)
            Vs[2][k] += av * a_ * (a_ - 1)
    # sum_s sum_{k+m>N} (Cs R^k / Q)(Vs R^(m-2) / Q): with R^e = 31^e 25^(N-e) / 25^N, suffix sums over m
    num = 0
    for s_ in range(3):
        suf = [0] * (N + 2)
        for m in range(N, 1, -1):
            suf[m] = suf[m + 1] + Vs[s_][m] * 31 ** (m - 2) * 25 ** (N - m + 2)
        for k in range(N + 1):
            if Cs[s_][k]:
                num += Cs[s_][k] * 31 ** k * 25 ** (N - k) * suf[max(2, N - k + 1)]
    p25 = [1, 25 ** N]
    tail = Fraction(num, p25[1] * p25[1] * Qv * Qv)
    rho = sum(Fraction(36 * (k + 1) * k * k) * R ** (k - 2) for k in range(2, N + 1)) / Qv
    return rho + tail, rho, tail


def weighted_sum(coef, N, scale_bits, weight, lo=0, hi=None):
    """sum_{lo <= i+j <= hi} |coef(i,j)| / 2^scale_bits * R^(i+j) * weight(i+j), exactly (R = 31/25)"""
    hi = N if hi is None else hi
    num = 0
    for k in range(lo, hi + 1):
        m = sum(abs(coef(i, k - i)) for i in range(k + 1))
        if m:
            num += m * weight(k) * 31 ** k * 25 ** (hi - k)
    return Fraction(num, 25 ** hi * (1 << scale_bits))


def chart_checks(checks, A780, A420, N1=780, N2=420):
    """the comparison table and the chart majorants (certificate.tex:218-252, 290-292, 624-627)"""
    out = {}

    def d78(i, j):
        return A780[i][j]

    def d42(i, j):
        return A420[i][j] if i + j <= N2 else 0

    def diff_trunc(cut):
        def f(i, j):
            r = A420[i][j] << 276 if i + j <= cut else 0
            return A780[i][j] - r
        return f
    one = lambda k: 1  # noqa: E731
    D0 = weighted_sum(diff_trunc(N2), N1, 500, one)
    D1 = weighted_sum(diff_trunc(N2), N1, 500, lambda k: k)
    D2 = weighted_sum(diff_trunc(N2), N1, 500, lambda k: k * k)
    D236 = weighted_sum(diff_trunc(236), N1, 500, one)
    D220 = weighted_sum(diff_trunc(220), N1, 500, one)
    rows = [D0 < Fraction('3.517e-17'), D1 / R < Fraction('1.233e-14'), D2 / R ** 2 < Fraction('4.327e-12'),
            D236 < Fraction('1.902e-11'), D220 < Fraction('7e-11')]
    check(checks, 'S4 the |P - P^ref| table: Delta_0 < 3.517e-17, Delta_1/R < 1.233e-14, Delta_2/R^2 < 4.327e-12, <=236: < 1.902e-11, <=220: < 7e-11',
          all(rows), ', '.join('%.4g' % float(x) for x in (D0, D1 / R, D2 / R ** 2, D236, D220)))
    ok = True
    det = []
    for name, f, N, bb in (('P780', d78, N1, 500), ('P420', d42, N2, 224)):
        g1 = weighted_sum(f, N, bb, lambda k: k, lo=1) / R
        g2 = weighted_sum(f, N, bb, lambda k: k * (k - 1), lo=2) / R ** 2
        t0 = weighted_sum(f, N, bb, one, lo=41)
        t1 = weighted_sum(f, N, bb, lambda k: k, lo=41) / R
        ok &= g1 < Fraction('0.592') and g2 < Fraction('3.05') and t0 < Fraction('0.0002') and t1 < Fraction('0.006')
        det.append('%s grad %.4f hess %.4f tail40 %.2e/%.2e' % (name, float(g1), float(g2), float(t0), float(t1)))
    check(checks, 'S4 chart jets |grad p_i| < .592, |D^2 p_i| < 3.05 and degree-40 truncation < .0002 (value), < .006 (gradient), both charts',
          ok, '; '.join(det))
    s220 = weighted_sum(d42, N2, 224, one, hi=220)
    k220 = weighted_sum(d42, N2, 224, lambda k: k * k, hi=220)
    m40 = weighted_sum(d42, N2, 224, one, hi=40)
    check(checks, 'S4 reference chart (degree 220) on the disk: absolute sum < .414 and k^2-weighted sum < 6 (certificate.tex:624-627); 861 coefficients to degree 40',
          s220 < Fraction('0.414') and k220 < 6 and 41 * 42 // 2 == 861, 'sum %.5f, k^2 sum %.4f, degree-40 sum %.5f' % (float(s220), float(k220), float(m40)))
    out.update(D0=D0, m40=m40)
    return out


# ---------------------------------------------------------------- SQUARE: the W-seed polynomial
def hw_checks(checks, certw, s_override=None, dmax=110):
    sq = re.sub(r'\s+', '', certw)
    s = [Fraction(x) for x in ('.0152567903', '.0002597033', '-.0014351728', '-.0017937434', '-.0008593989', '-.0002090472', '-.0000227468')]
    if s_override:
        for k, v in s_override.items():
            s[k] = Fraction(v)
    a = {}
    for k in range(7):
        a[(3 * k, 0)] = s[k] / Fraction(32, 100) ** (3 * k)

    def g(i, j):
        if i < 0 or j < 0:
            return Fraction(0)
        return a.get((i, j), Fraction(0))
    for d in range(dmax + 1):
        for i in range(d + 1):
            j = d - i
            a[(i + 1, j + 1)] = (d * (d - 1) * g(i, j) - (i + 2) * (i + 1) * g(i + 2, j - 1) - (j + 2) * (j + 1) * g(i - 1, j + 2)) / (2 * (i + 1) * (j + 1))
    mon = {(i, j) for i in range(113) for j in range(113 - i)}
    # the residual, from the operator L_W = (zb - z^2) d_z^2 + 2(1 - z zb) d_z d_zb + (z - zb^2) d_zb^2 applied monomialwise
    bco = {}

    def add(key, v):
        if key[0] >= 0 and key[1] >= 0 and v:
            bco[key] = bco.get(key, Fraction(0)) + v
    for (i, j) in mon:
        x = g(i, j)
        if not x:
            continue
        add((i, j), -(i * (i - 1) + 2 * i * j + j * (j - 1)) * x)
        add((i - 2, j + 1), i * (i - 1) * x)
        add((i + 1, j - 2), j * (j - 1) * x)
        add((i - 1, j - 1), 2 * i * j * x)
    RW = Fraction(357, 1000)
    zero_low = all(v == 0 for (i, j), v in bco.items() if i + j <= 110)
    res = sum(abs(v) * RW ** (i + j) for (i, j), v in bco.items())
    check(checks, 'S5 H_W: 6441 monomials; L_W H_W has b_ij = 0 exactly for i+j <= 110 and sum |b_ij| R_W^(i+j) < 6.739223e-13 (certificate-w.tex:123-141)',
          len(mon) == 6441 and zero_low and res < Fraction('6.739223e-13') and '6.739223\\cdot10^{-13}' in sq, 'residual %.7g' % float(res))
    S = []
    for k in range(3):
        tot = Fraction(0)
        for (i, j) in mon:
            dd = i + j
            if dd >= k and g(i, j):
                f = 1
                for t in range(k):
                    f *= dd - t
                tot += abs(g(i, j)) * f * RW ** (dd - k)
        S.append(tot)
    check(checks, 'S5 S_0 < .058178, S_1 < 1.490164, S_2 < 53.686778 (certificate-w.tex:111-121)',
          S[0] < Fraction('.058178') and S[1] < Fraction('1.490164') and S[2] < Fraction('53.686778'), ', '.join('%.7f' % float(x) for x in S))
    c = [Fraction(x) for x in ('.28309034', '-.05388682', '.00841589', '.00450821', '-.00680398')]
    rs = sum(abs(x) for x in c)
    r1 = sum(3 * k * abs(x) for k, x in enumerate(c))
    r2 = sum((3 * k) ** 2 * abs(x) for k, x in enumerate(c))
    rmin = c[0] - sum(abs(x) for x in c[1:])
    zp, zpp = rs + r1, rs + 2 * r1 + r2
    check(checks, 'S5 shell: r_* = .35670524, r_1 = .33437745, r_2 = 2.13289155, rho >= .20947544 > .2, |z\'| <= .69108269, |z\'\'| <= 3.15835169 < 3.16, |(H_W o z)\'\'| < 30.348',
          rs == Fraction('.35670524') and r1 == Fraction('.33437745') and r2 == Fraction('2.13289155') and rmin == Fraction('.20947544')
          and zp == Fraction('.69108269') and zpp == Fraction('3.15835169') and S[2] * zp ** 2 + S[1] * zpp < Fraction('30.348'),
          '%.4f' % float(S[2] * zp ** 2 + S[1] * zpp))
    B = Fraction(2 ** 52)
    e = [Fraction(15 * r) / B for r in range(13)]
    f = Fraction(400) / B
    for r in range(1, 13):
        f = f / 2 + 2 * e[r] + Fraction(250) / B
    eh, fh = Fraction(180) / B, Fraction(1700) / B
    for _ in range(14):
        eh = 2 * eh + Fraction(42) / B
        fh = Fraction(2, 3) * fh + 3 * eh + Fraction(250) / B
    check(checks, 'S6 library error recurrences: f_12^init <= 1159.991/B, e_14 = 3637206/B < 8.5e-10, f_14 < 3.635e-9 < 1e-8 (certificate-w.tex:313-362)',
          f * B <= Fraction('1159.991') and e[12] * B == 180 and eh * B == 3637206 and eh < Fraction('8.5e-10') and fh < Fraction('3.635e-9'),
          'f12 %.3f/B, e14 %s/B, f14 %.4g' % (float(f * B), eh * B, float(fh)))
    return S


# ---------------------------------------------------------------- the decision
REFUSED_BECAUSE = [
    'boundary lemma and W-seed finite check: the three-state record library is not published (inputs are only newc22, '
    'qP420_gmp, qP780_gmp); the paper specifies it by its program menu.hpp ("The supplied finite program fixes all these '
    'selection choices, including ties", certificate-w.tex:272-273) and its recorded gaps are that program\'s output',
    'interior lemma: branch-and-bound over 16,384 initial polar boxes, five fields of degree < 320 and < 52,000 monomials, '
    'degree-14 Taylor arrays, bisection to depth 28; ~6e9 big-integer operations before subdivision (hours of pure-Python '
    'CPU per pass), the subdivision count unpublished',
    'geometry tests: 230,400 centers of the degree-40 chart with derivatives (~1e9 operations) — not attempted',
]


def decide(src=None, full=True, charts=True, workers=None, rect_script=(-2, 2, 2, -3, 2, -2, 3), zero_fiber=None, claimed_alpha='0.465',
           const_override=None, chart420_override=None, s_override=None, hw_dmax=110, regen420=False):
    """full=False skips the 18 MB chart and what depends on it; charts=False also skips the 420 chart (forges only)"""
    t0 = time.time()
    src = src or Sources()
    checks = []
    timing = {}
    main = src.text(MAIN)
    intro = src.text(INTRO)
    cert = src.text(CERT)
    certw = src.text(CERTW)
    btex = src.text(BARRIER_TEX)
    repro = src.text(REPRO)
    rect = src.text(RECT)
    newc = src.text(NEWC22)
    check(checks, 'the headline as printed: omega < 1129/500 = 2.258, alpha > 0.465, w(0.709) < 2.092',
          '\\omega<\\frac{1129}{500}=2.258,\\qquad' in intro and '\\alpha>0.465,\\qquad w(0.709)<2.092' in intro and '\\(\\omega<2.258\\)' in main)
    other = src.text(OTHER + 'build/paper.tex')
    src.text(OTHER + 'README.md')
    check(checks, '#212 (omega <= 9/4) as read: Theorem thm:main states omega <= 9/4; its TeX has no verbatim / tabular / listing block',
          '$\\omega\\leq9/4$' in other and not re.search(r'\\begin\{(verbatim|tabular|lstlisting|longtable)\}', other))

    t = time.time()
    rect_checks(checks, rect, rect_script, zero_fiber, claimed_alpha)
    timing['rectangular'] = round(time.time() - t, 1)
    t = time.time()
    barrier_checks(checks, btex, newc, cert, repro, const_override)
    hw_checks(checks, certw, s_override, hw_dmax)
    timing['barrier_and_W'] = round(time.time() - t, 1)

    workers = workers or max(1, min(6, (os.cpu_count() or 2) - 2))
    value = {}
    if charts:
        t = time.time()
        v420 = [int(x) for x in src.text(QP420).split()]
        if chart420_override:
            for k, delta in chart420_override.items():
                v420[k] += delta
        ok420, det420, A420 = verify_chart(v420, 420, 224, workers)
        check(checks, 'S2 qP420_gmp is the fixed point of the chart recursion (certificate.tex:111-149) at N = 420, b = 224', ok420, det420)
        check(checks, 'S2 21 < C_00/Q < 22 at b = 224', 21 * 2 ** 224 < 72 * v420[0] + 8 * 2 ** 224 < 22 * 2 ** 224)
        timing['P420'] = round(time.time() - t, 1)
        if regen420:
            t = time.time()
            G420 = generate_chart(420, 224)
            check(checks, 'S2 (second derivation) P_{420,224} regenerated from nothing by the recursion equals qP420_gmp, all 88,831 entries',
                  [G420[i][d - i] for d in range(421) for i in range(d, -1, -1)] == v420)
            timing['P420_regenerated'] = round(time.time() - t, 1)
    if charts and full:
        t = time.time()
        v780 = [int(x) for x in src.text(QP780).split()]
        ok780, det780, A780 = verify_chart(v780, 780, 500, workers)
        timing['P780'] = round(time.time() - t, 1)
        check(checks, 'S2 qP780_gmp (18 MB) is the fixed point of the chart recursion at N = 780, b = 500 (so it IS the defined chart P)', ok780, det780)
        pnum = (2 * 2 ** 500 * 18623 + 100000) // 200000
        check(checks, 'S2 21 < C_00/Q < 22 at b = 500; Theorem thm:certificate\'s p = 2^-500 rnd(2^500 18623/100000) = A_00/2^500; E_1(0) = 1/3 - P(0) > .1471',
              21 * 2 ** 500 < 72 * v780[0] + 8 * 2 ** 500 < 22 * 2 ** 500 and v780[0] == pnum
              and Fraction(1, 3) - Fraction(v780[0], 2 ** 500) > Fraction('.1471'))
        t = time.time()
        if ok780:
            eps, rho, tail = residual_bound(A780, 780, 500)
            check(checks, 'S3 eps = sup |L P| <= rho + sum D V < 3.328667e-22 (certificate.tex:209-212), exact rational; 6 eps/eta < 9.987e-13 < 1e-12',
                  eps < Fraction('3.328667e-22') and 6 * Fraction('3.329e-22') / Fraction('2e-9') <= Fraction('9.987e-13')
                  and 6 * eps / Fraction('2e-9') < Fraction('9.987e-13'), 'eps <= %.10g (rho %.4g, products %.4g)' % (float(eps), float(rho), float(tail)))
            value['eps_upper'] = '%.10g' % float(eps)
            chart_checks(checks, A780, A420)
        else:
            check(checks, 'S3 the residual eps (needs the verified chart)', False, 'the chart failed its recursion')
        timing['residual_and_table'] = round(time.time() - t, 1)
    allpass = all(c['pass'] for c in checks)
    verdict = 'REFUSED' if allpass else 'REFUTED'
    value.update(timing=timing, seconds=round(time.time() - t0, 1), workers=workers, full=full, charts=charts,
                 decided=sum(1 for c in checks), refused_because=REFUSED_BECAUSE)
    return {'verdict': verdict, 'checks': checks, 'sources': src.read, 'value': value,
            'decides': 'finite components only: the three rectangular witnesses (alpha > 0.465, w(0.709) < 2.092, family '
                       'omega < 2.267) as finite computations; for omega < 2.258 the barrier, both charts (the 18 MB chart '
                       'verified as the recursion\'s output), the residual eps, the chart comparisons and the W-seed '
                       'polynomial. NOT the interior lemma (cost), NOT the boundary lemma / W-seed library (records not '
                       'published), hence NOT Theorem thm:certificate; no theory'}


def forge():
    """each must NOT come back clean: a decided component must fail (REFUTED), never REFUSED-with-all-green"""
    out = []
    r = decide(full=False, charts=False, const_override='1.0986122')
    out.append(('barrier constant term 1.098619383270680538 -> 1.0986122 (below log 3 + 7.094e-6)', r['verdict']))
    r = decide(full=False, charts=False, rect_script=(-2, 2, 2, -3, 2, -2, 2))
    out.append(('the last completion of the dual script +3 -> +2', r['verdict']))
    r = decide(full=False, charts=False, zero_fiber=18)
    out.append(('the zero-word fiber 19 -> 18 in the curve histogram', r['verdict']))
    r = decide(full=False, chart420_override={50000: 1})
    out.append(('one coefficient of qP420_gmp changed by one unit (entry 50000)', r['verdict']))
    r = decide(full=False, charts=False, hw_dmax=108)
    out.append(('the H_W recursion stopped at d = 108 instead of 110 (the residual is no longer zero through degree 110)', r['verdict']))
    return out


if __name__ == '__main__':
    t = time.time()
    res = decide()
    print(json.dumps({k: res[k] for k in ('verdict', 'value', 'decides')}, indent=1))
    for c in res['checks']:
        print(('PASS ' if c['pass'] else 'FAIL ') + c['check'], '|', c['detail'])
    print('%.1fs' % (time.time() - t))
    t = time.time()
    print(forge())
    print('forges %.1fs' % (time.time() - t))
