/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:181" *)
(* generator = "Amaranth" *)
module core_euclid_strict(u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10
, valid, certified, refuted, refused, u0);
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u1;
  wire signed [2:0] u1;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u2;
  wire signed [2:0] u2;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u3;
  wire signed [2:0] u3;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u4;
  wire signed [2:0] u4;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u5;
  wire signed [2:0] u5;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u6;
  wire signed [2:0] u6;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u7;
  wire signed [2:0] u7;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u8;
  wire signed [2:0] u8;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u9;
  wire signed [2:0] u9;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u10;
  wire signed [2:0] u10;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v0;
  wire signed [2:0] v0;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v1;
  wire signed [2:0] v1;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v2;
  wire signed [2:0] v2;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v3;
  wire signed [2:0] v3;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v4;
  wire signed [2:0] v4;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v5;
  wire signed [2:0] v5;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v6;
  wire signed [2:0] v6;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v7;
  wire signed [2:0] v7;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v8;
  wire signed [2:0] v8;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v9;
  wire signed [2:0] v9;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:161" *)
  input signed [2:0] v10;
  wire signed [2:0] v10;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:169" *)
  input valid;
  wire valid;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:170" *)
  output certified;
  wire certified;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:171" *)
  output refuted;
  wire refuted;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:172" *)
  output refused;
  wire refused;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:160" *)
  input signed [2:0] u0;
  wire signed [2:0] u0;
  wire [5:0] \$1 ;
  wire [5:0] \$10 ;
  wire \$100 ;
  wire \$101 ;
  wire \$102 ;
  wire \$103 ;
  wire \$104 ;
  wire \$105 ;
  wire \$106 ;
  wire \$107 ;
  wire \$108 ;
  wire \$109 ;
  wire [10:0] \$11 ;
  wire \$110 ;
  wire \$111 ;
  wire \$112 ;
  wire \$113 ;
  wire \$114 ;
  wire \$115 ;
  wire \$116 ;
  wire \$117 ;
  wire \$118 ;
  wire \$119 ;
  wire [5:0] \$12 ;
  wire \$120 ;
  wire \$121 ;
  wire \$122 ;
  wire \$123 ;
  wire \$124 ;
  wire \$125 ;
  wire \$126 ;
  wire \$127 ;
  wire \$128 ;
  wire \$129 ;
  wire [11:0] \$13 ;
  wire \$130 ;
  wire \$131 ;
  wire \$132 ;
  wire \$133 ;
  wire \$134 ;
  wire \$135 ;
  wire \$136 ;
  wire \$137 ;
  wire \$138 ;
  wire \$139 ;
  wire [5:0] \$14 ;
  wire [12:0] \$15 ;
  wire [5:0] \$16 ;
  wire [13:0] \$17 ;
  wire [5:0] \$18 ;
  wire [14:0] \$19 ;
  wire [5:0] \$2 ;
  wire [5:0] \$20 ;
  wire [15:0] \$21 ;
  wire [5:0] \$22 ;
  wire [5:0] \$23 ;
  wire [6:0] \$24 ;
  wire [5:0] \$25 ;
  wire [7:0] \$26 ;
  wire [5:0] \$27 ;
  wire [8:0] \$28 ;
  wire [5:0] \$29 ;
  wire [6:0] \$3 ;
  wire [9:0] \$30 ;
  wire [5:0] \$31 ;
  wire [10:0] \$32 ;
  wire [5:0] \$33 ;
  wire [11:0] \$34 ;
  wire [5:0] \$35 ;
  wire [12:0] \$36 ;
  wire [5:0] \$37 ;
  wire [13:0] \$38 ;
  wire [5:0] \$39 ;
  wire [5:0] \$4 ;
  wire [14:0] \$40 ;
  wire [5:0] \$41 ;
  wire [15:0] \$42 ;
  wire [5:0] \$43 ;
  wire [5:0] \$44 ;
  wire [6:0] \$45 ;
  wire [5:0] \$46 ;
  wire [7:0] \$47 ;
  wire [5:0] \$48 ;
  wire [8:0] \$49 ;
  wire [7:0] \$5 ;
  wire [5:0] \$50 ;
  wire [9:0] \$51 ;
  wire [5:0] \$52 ;
  wire [10:0] \$53 ;
  wire [5:0] \$54 ;
  wire [11:0] \$55 ;
  wire [5:0] \$56 ;
  wire [12:0] \$57 ;
  wire [5:0] \$58 ;
  wire [13:0] \$59 ;
  wire [5:0] \$6 ;
  wire [5:0] \$60 ;
  wire [14:0] \$61 ;
  wire [5:0] \$62 ;
  wire [15:0] \$63 ;
  wire [10:0] \$64 ;
  wire [10:0] \$65 ;
  wire \$66 ;
  wire \$67 ;
  wire \$68 ;
  wire \$69 ;
  wire [8:0] \$7 ;
  wire \$70 ;
  wire \$71 ;
  wire \$72 ;
  wire \$73 ;
  wire \$74 ;
  wire \$75 ;
  wire \$76 ;
  wire \$77 ;
  wire \$78 ;
  wire \$79 ;
  wire [5:0] \$8 ;
  wire \$80 ;
  wire \$81 ;
  wire \$82 ;
  wire \$83 ;
  wire \$84 ;
  wire \$85 ;
  wire \$86 ;
  wire \$87 ;
  wire \$88 ;
  wire \$89 ;
  wire [9:0] \$9 ;
  wire \$90 ;
  wire \$91 ;
  wire \$92 ;
  wire \$93 ;
  wire \$94 ;
  wire \$95 ;
  wire \$96 ;
  wire \$97 ;
  wire \$98 ;
  wire \$99 ;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:245" *)
  wire decided;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:87" *)
  wire gt;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:84" *)
  wire [7:0] la;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:84" *)
  wire [7:0] lb;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:86" *)
  wire le;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:176" *)
  wire ok;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:210" *)
  wire signed [9:0] p;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:85" *)
  wire [7:0] ra;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:85" *)
  wire [7:0] rb;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:210" *)
  wire [8:0] s;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:210" *)
  wire [8:0] t;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:206" *)
  wire triv_c;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:207" *)
  wire triv_r;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:88" *)
  wire un;
  assign \$1  = $signed(u0) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v0);
  assign \$2  = $signed(u1) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v1);
  assign \$3  = $signed(\$1 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$2 );
  assign \$4  = $signed(u2) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v2);
  assign \$5  = $signed(\$3 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$4 );
  assign \$6  = $signed(u3) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v3);
  assign \$7  = $signed(\$5 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$6 );
  assign \$8  = $signed(u4) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v4);
  assign \$9  = $signed(\$7 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$8 );
  assign \$10  = $signed(u5) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v5);
  assign \$11  = $signed(\$9 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$10 );
  assign \$12  = $signed(u6) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v6);
  assign \$13  = $signed(\$11 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$12 );
  assign \$14  = $signed(u7) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v7);
  assign \$15  = $signed(\$13 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$14 );
  assign \$16  = $signed(u8) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v8);
  assign \$17  = $signed(\$15 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$16 );
  assign \$18  = $signed(u9) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v9);
  assign \$19  = $signed(\$17 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$18 );
  assign \$20  = $signed(u10) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v10);
  assign \$21  = $signed(\$19 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$20 );
  assign \$22  = $signed(u0) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u0);
  assign \$23  = $signed(u1) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u1);
  assign \$24  = $signed(\$22 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$23 );
  assign \$25  = $signed(u2) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u2);
  assign \$26  = $signed(\$24 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$25 );
  assign \$27  = $signed(u3) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u3);
  assign \$28  = $signed(\$26 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$27 );
  assign \$29  = $signed(u4) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u4);
  assign \$30  = $signed(\$28 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$29 );
  assign \$31  = $signed(u5) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u5);
  assign \$32  = $signed(\$30 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$31 );
  assign \$33  = $signed(u6) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u6);
  assign \$34  = $signed(\$32 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$33 );
  assign \$35  = $signed(u7) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u7);
  assign \$36  = $signed(\$34 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$35 );
  assign \$37  = $signed(u8) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u8);
  assign \$38  = $signed(\$36 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$37 );
  assign \$39  = $signed(u9) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u9);
  assign \$40  = $signed(\$38 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$39 );
  assign \$41  = $signed(u10) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(u10);
  assign \$42  = $signed(\$40 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$41 );
  assign \$43  = $signed(v0) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v0);
  assign \$44  = $signed(v1) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v1);
  assign \$45  = $signed(\$43 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$44 );
  assign \$46  = $signed(v2) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v2);
  assign \$47  = $signed(\$45 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$46 );
  assign \$48  = $signed(v3) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v3);
  assign \$49  = $signed(\$47 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$48 );
  assign \$50  = $signed(v4) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v4);
  assign \$51  = $signed(\$49 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$50 );
  assign \$52  = $signed(v5) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v5);
  assign \$53  = $signed(\$51 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$52 );
  assign \$54  = $signed(v6) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v6);
  assign \$55  = $signed(\$53 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$54 );
  assign \$56  = $signed(v7) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v7);
  assign \$57  = $signed(\$55 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$56 );
  assign \$58  = $signed(v8) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v8);
  assign \$59  = $signed(\$57 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$58 );
  assign \$60  = $signed(v9) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v9);
  assign \$61  = $signed(\$59 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$60 );
  assign \$62  = $signed(v10) * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:191" *) $signed(v10);
  assign \$63  = $signed(\$61 ) + (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:204" *) $signed(\$62 );
  assign triv_c = $signed(\$21 [9:0]) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:214" *) $signed(1'h0);
  assign \$66  = $signed(u0) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$67  = $signed(u0) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$68  = \$66  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$67 ;
  assign \$69  = $signed(u1) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$70  = $signed(u1) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$71  = \$69  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$70 ;
  assign \$72  = $signed(u2) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$73  = $signed(u2) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$74  = \$72  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$73 ;
  assign \$75  = $signed(u3) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$76  = $signed(u3) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$77  = \$75  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$76 ;
  assign \$78  = $signed(u4) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$79  = $signed(u4) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$80  = \$78  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$79 ;
  assign \$81  = $signed(u5) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$82  = $signed(u5) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$83  = \$81  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$82 ;
  assign \$84  = $signed(u6) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$85  = $signed(u6) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$86  = \$84  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$85 ;
  assign \$87  = $signed(u7) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$88  = $signed(u7) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$89  = \$87  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$88 ;
  assign \$90  = $signed(u8) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$91  = $signed(u8) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$92  = \$90  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$91 ;
  assign \$93  = $signed(u9) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$94  = $signed(u9) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$95  = \$93  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$94 ;
  assign \$96  = $signed(u10) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$97  = $signed(u10) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$98  = \$96  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$97 ;
  assign \$99  = $signed(v0) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$100  = $signed(v0) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$101  = \$99  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$100 ;
  assign \$102  = $signed(v1) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$103  = $signed(v1) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$104  = \$102  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$103 ;
  assign \$105  = $signed(v2) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$106  = $signed(v2) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$107  = \$105  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$106 ;
  assign \$108  = $signed(v3) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$109  = $signed(v3) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$110  = \$108  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$109 ;
  assign \$111  = $signed(v4) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$112  = $signed(v4) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$113  = \$111  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$112 ;
  assign \$114  = $signed(v5) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$115  = $signed(v5) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$116  = \$114  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$115 ;
  assign \$117  = $signed(v6) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$118  = $signed(v6) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$119  = \$117  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$118 ;
  assign \$120  = $signed(v7) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$121  = $signed(v7) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$122  = \$120  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$121 ;
  assign \$123  = $signed(v8) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$124  = $signed(v8) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$125  = \$123  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$124 ;
  assign \$126  = $signed(v9) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$127  = $signed(v9) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$128  = \$126  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$127 ;
  assign \$129  = $signed(v10) >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h5);
  assign \$130  = $signed(v10) <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) $signed(3'h3);
  assign \$131  = \$129  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) \$130 ;
  assign ok = & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:177" *) { \$131 , \$128 , \$125 , \$122 , \$119 , \$116 , \$113 , \$110 , \$107 , \$104 , \$101 , \$98 , \$95 , \$92 , \$89 , \$86 , \$83 , \$80 , \$77 , \$74 , \$71 , \$68  };
  assign \$132  = ~ (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:248" *) ok;
  assign \$133  = ~ (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:248" *) decided;
  assign \$134  = \$133  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:248" *) un;
  assign \$135  = \$132  | (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:248" *) \$134 ;
  assign refused = valid & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:248" *) \$135 ;
  assign \$136  = valid & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:249" *) ok;
  assign \$137  = decided ? (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:249" *) triv_c : le;
  assign certified = \$136  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:249" *) \$137 ;
  assign \$138  = valid & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:250" *) ok;
  assign \$139  = decided ? (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:250" *) 1'h0 : gt;
  assign refuted = \$138  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:250" *) \$139 ;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:184" *)
  \core_euclid_strict.cmp  cmp (
    .gt(gt),
    .la(\$64 [7:0]),
    .lb(\$65 [7:0]),
    .le(le),
    .ra(\$42 [7:0]),
    .rb(\$63 [7:0]),
    .wide(un)
  );
  assign p = \$21 [9:0];
  assign s = \$42 [8:0];
  assign t = \$63 [8:0];
  assign triv_r = 1'h0;
  assign la = \$64 [7:0];
  assign lb = \$65 [7:0];
  assign ra = \$42 [7:0];
  assign rb = \$63 [7:0];
  assign \$64  = { \$21 [9:0], 1'h0 };
  assign \$65  = { \$21 [9:0], 1'h0 };
  assign decided = triv_c;
endmodule

(* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:91" *)
(* generator = "Amaranth" *)
module \core_euclid_strict.cmp (rb, la, lb, wide, le, gt, ra);
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:85" *)
  input [7:0] rb;
  wire [7:0] rb;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:84" *)
  input [7:0] la;
  wire [7:0] la;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:84" *)
  input [7:0] lb;
  wire [7:0] lb;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:88" *)
  output wide;
  wire wide;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:86" *)
  output le;
  wire le;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:87" *)
  output gt;
  wire gt;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:85" *)
  input [7:0] ra;
  wire [7:0] ra;
  wire \$1 ;
  wire \$10 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:98" *)
  wire [15:0] lp;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:98" *)
  wire [15:0] rp;
  (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:88" *)
  wire un;
  assign \$1  = la >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:96" *) 9'h100;
  assign \$2  = lb >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:96" *) 9'h100;
  assign \$3  = \$1  | (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:96" *) \$2 ;
  assign \$4  = ra >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:97" *) 9'h100;
  assign \$5  = \$3  | (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:96" *) \$4 ;
  assign \$6  = rb >= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:97" *) 9'h100;
  assign wide = \$5  | (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:96" *) \$6 ;
  assign lp = la * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:100" *) lb;
  assign rp = ra * (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:101" *) rb;
  assign \$7  = ~ (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:111" *) wide;
  assign \$8  = lp <= (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:111" *) rp;
  assign le = \$7  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:111" *) \$8 ;
  assign \$9  = ~ (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:111" *) wide;
  assign \$10  = lp > (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:111" *) rp;
  assign gt = \$9  & (* src = "/Users/carlostoledo/Documents/frontier-apps/experiments/certifier-core/core.py:111" *) \$10 ;
  assign un = wide;
endmodule
