#!/usr/bin/env node
/* tools/paper-numbers/breaking-waves.js — every number the breaking-waves
   manuscript quotes, read from the records that decided it and written as
   LaTeX macros: paper/tex/breaking-waves-numbers.tex.

   Records read (never written):
     certs/breaking-ledger.json              the table decided in exact arithmetic (2026-09-17)
     corpus/blacksea-breaking/claims.json    the paper's printed numbers as transcribed, Table 1
     corpus/blacksea-breaking/meta.json      the pins (archive md5, file sha256s, the paper XML)
     corpus/blacksea-breaking/load_breaking_statistics.py   the authors' loader (pinned), read for
                                             the column-name list and the value assignment
   The manuscript \inputs the file, so it cannot quote a number the machine did
   not record; a record that no longer says what a sentence needs makes this
   refuse (need()), as tools/build-paper-numbers.js does for the other papers.
   The breaking battery runs here so its counts are live (about eight seconds).

   usage: node tools/paper-numbers/breaking-waves.js                          MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex', 'breaking-waves-numbers.tex');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const die = (m) => { console.error('BREAKING-WAVES NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
const sgn = (x, d) => (Number(x) < 0 ? '\\ensuremath{-}' : '') + Math.abs(Number(x)).toFixed(d);   /* usable in text and in math */
const pct = (num, den, d) => (100 * num / den).toFixed(d) + '\\%';
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();

const M = ['%% generated by tools/paper-numbers/breaking-waves.js from certs/breaking-ledger.json, corpus/blacksea-breaking/{claims,meta}.json and the pinned loader script — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));

/* ---- the battery, live ---- */
{
  const r = cp.spawnSync('node', [path.join(ROOT, 'instruments', 'breaking', 'battery.js')], { cwd: ROOT, maxBuffer: 1 << 26 });
  const out = String(r.stdout) + String(r.stderr);
  const m = /breaking battery: (\d+) pass, 0 fail, (\d+)\/(\d+) red controls fired/.exec(out);
  if (r.status !== 0 || !m || m[2] !== m[3]) die('the breaking battery did not pass clean:\n' + out.slice(-600));
  def('BatteryChecks', m[1]); def('BatteryReds', m[2]);
}

/* ---- the records ---- */
const L = J('certs/breaking-ledger.json');
const CL = J('corpus/blacksea-breaking/claims.json');
const ME = J('corpus/blacksea-breaking/meta.json');
const PA = L.paper;
need(L.n === 16369 && L.records.length === 20 && L.corpus.rows === 16369 && L.corpus.columns === 46, 'the table is not 16,369 x 46 in 20 records');
need(PA && PA.doi === '10.1029/2026GL122293' && PA.published === '2026-09-16', 'the paper block is not the GRL paper');
need(L.corpus.doi === ME.record.doi && L.corpus.archiveMd5 === ME.record.md5, 'the ledger and the corpus pins disagree');
need(L.corpus.csvSha256 === ME.files['blacksea_data.csv'].sha256, 'the ledger did not read the pinned CSV');
need(PA.xmlSha256 === ME.paper.files['paper/grl.xml'].sha256, 'the ledger did not read the pinned paper XML');
/* the pinned files still hash to their pins (the ledger runner checks this too; the manuscript says it) */
for (const [rel, m] of Object.entries(Object.assign({}, ME.files, ME.paper.files))) {
  const p = path.join(ROOT, 'corpus', 'blacksea-breaking', rel);
  need(fs.existsSync(p) && crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex') === m.sha256, 'corpus/blacksea-breaking/' + rel + ' does not hash to its pin');
}
def('RepoCommit', git);
def('LedgerGenerated', L.generated); def('LedgerSeconds', dec(L.seconds, 1));
def('CorpusDoi', L.corpus.doi); def('PaperDoi', PA.doi); def('PaperPublished', PA.published); def('PaperFetched', ME.paper.fetched);
def('ArchiveMd', ME.record.md5); def('CsvSha', L.corpus.csvSha256.slice(0, 12)); def('XmlSha', PA.xmlSha256.slice(0, 12));
def('ArchiveGB', dec(ME.record.bytes / 1e9, 1)); def('ArchiveEntries', int(ME.record.entries)); def('ArchiveFetched', ME.record.fetched);
def('NEvents', int(L.n)); def('NRecords', String(L.records.length)); def('NColumns', String(L.corpus.columns));
def('PinnedFiles', String(Object.keys(ME.files).length + Object.keys(ME.paper.files).length));
def('ScriptFiles', String(Object.keys(ME.files).filter((f) => f.endsWith('.py')).length));
def('InitiallyDetected', int(CL.paper.printed.initiallyDetected.value));

/* ---- Table 1 as printed: the ranges the dataset spans ---- */
const T1P = CL.paper.table1.rows;
need(T1P.length === 20 && T1P.reduce((a, r) => a + r[4], 0) === 16369, 'the transcribed Table 1 is not 20 rows summing to 16,369');
const col = (i) => T1P.map((r) => Number(r[i]));
const lo = (a) => Math.min(...a), hi = (a) => Math.max(...a);
def('HsPrintedLo', dec(lo(col(5)), 2)); def('HsPrintedHi', dec(hi(col(5)), 2));
def('TpPrintedLo', dec(lo(col(6)), 1)); def('TpPrintedHi', dec(hi(col(6)), 1));
def('UPrintedLo', dec(lo(col(7)), 1)); def('UPrintedHi', dec(hi(col(7)), 1));
def('DurLo', String(lo(col(2)))); def('DurHi', String(hi(col(2)))); def('AreaLo', String(lo(col(3)))); def('AreaHi', String(hi(col(3))));
def('NbLo', int(lo(col(4)))); def('NbHi', int(hi(col(4))));
def('FpsLo', String(lo(col(1)))); def('FpsHi', String(hi(col(1))));
def('RecordFirst', T1P[0][0].slice(0, 10).replace(/\//g, '-')); def('RecordLast', T1P[19][0].slice(0, 10).replace(/\//g, '-'));

/* ---- the verdicts of the printed numbers ---- */
const byId = Object.fromEntries(PA.items.map((it) => [it.id, it]));
const V = (id) => (byId[id] || die('paper item ' + id + ' missing')).verdict;
const tally = {}; for (const it of PA.items) tally[it.verdict] = (tally[it.verdict] || 0) + 1;
const nRep = tally.REPRODUCED || 0, nTrunc = tally.TRUNCATION || 0, nIntParts = tally.REPRODUCED_AS_TRUNCATION || 0, nNot = tally.NOT_THE_TABLES || 0, nRansac = tally.NOT_DECIDABLE_RANSAC || 0;
need(nRep + nTrunc + nIntParts + nNot + nRansac === PA.items.length, 'the verdicts do not partition the printed numbers');
def('ItemsTotal', String(PA.items.length)); def('ItemsReproduced', String(nRep)); def('ItemsTruncation', String(nTrunc)); def('ItemsIntegerParts', String(nIntParts)); def('ItemsNot', String(nNot)); def('ItemsRansac', String(nRansac));
def('ItemsRoundingOrTruncation', String(nRep + nTrunc + nIntParts));

/* the three laws and the tail */
need(V('fitLb') === 'REPRODUCED' && V('fitLD81') === 'REPRODUCED' && V('fitDz') === 'REPRODUCED', 'the three-fits sentence would be false');
need(byId.fitLb.withinPm && byId.fitLD81.withinPm && byId.fitDz.withinPm, 'a fit lies outside the printed +/-');
def('FitLbPrinted', byId.fitLb.printed); def('FitLbPm', byId.fitLb.pm); def('FitLbExact', dec(byId.fitLb.exact, 4));
def('FitLDPrinted', byId.fitLD81.printed); def('FitLDPm', byId.fitLD81.pm); def('FitLDExact', dec(byId.fitLD81.exact, 4));
def('FitDzPrinted', byId.fitDz.printed); def('FitDzPm', byId.fitDz.pm); def('FitDzExact', dec(byId.fitDz.exact, 4));
need(V('selfSimilarFraction') === 'REPRODUCED' && byId.selfSimilarFraction.undecided.every((u) => u === 0), 'the four-per-cent sentence would be false');
const SF = byId.selfSimilarFraction;
def('SelfSimPrinted', CL.paper.printed.selfSimilarFraction.value + '\\,\\ensuremath{\\pm}\\,' + CL.paper.printed.selfSimilarFraction.pm + '\\%');
def('TailCountA', int(SF.counts[0])); def('TailCountB', int(SF.counts[1])); def('TailCountC', int(SF.counts[2]));
def('TailPctA', pct(SF.counts[0], L.n, 2)); def('TailPctB', pct(SF.counts[1], L.n, 2)); def('TailPctC', pct(SF.counts[2], L.n, 2));
const TL = PA.tails;
for (const [k, K] of [['a', 'A'], ['b', 'B'], ['c', 'C']]) {
  need(TL[k].undecided === 0 && TL[k].above + TL[k].below === L.n, 'tail ' + k + ' does not partition the events');
  def('TailThreshold' + K, dec(TL[k].threshold[0], 4)); def('TailMean' + K, dec(TL[k].mean[0], 4)); def('TailSd' + K, dec(TL[k].sd[0], 4));
}
need(V('fitLbTail') === 'REPRODUCED' && byId.fitLbTail.rVerdict === 'REPRODUCED', 'the tail-fit sentence would be false');
def('FitLbTailPrinted', byId.fitLbTail.printed); def('FitLbTailExact', dec(byId.fitLbTail.exact, 4)); def('TailN', int(byId.fitLbTail.n));
def('TailRPrinted', byId.fitLbTail.rPrinted); def('TailRSq', dec(byId.fitLbTail.rCb2Lb[0], 3)); def('TailRLin', dec(byId.fitLbTail.rCbLb[0], 3));
need(V('fitLbRest') === 'NOT_THE_TABLES' && byId.fitLbRest.rVerdict === 'REPRODUCED', 'the rest-fit sentence would be false');
def('FitLbRestPrinted', byId.fitLbRest.printed); def('FitLbRestExact', dec(byId.fitLbRest.exact, 4)); def('RestN', int(byId.fitLbRest.n));
def('RestRPrinted', byId.fitLbRest.rPrinted); def('RestRSq', dec(byId.fitLbRest.rCb2Lb[0], 3)); def('RestRLin', dec(byId.fitLbRest.rCbLb[0], 3));
def('PooledRcbLb', dec(PA.pooledR.cbLb[0], 3)); def('PooledRcbsqLb', dec(PA.pooledR.cb2Lb[0], 3));

/* the aspect ratio */
need(V('aspectMean') === 'TRUNCATION' && V('aspectSd') === 'REPRODUCED' && V('aspectCV') === 'REPRODUCED', 'the aspect-ratio sentence would be false');
def('AspectMeanPrinted', byId.aspectMean.printed); def('AspectMeanExact', dec(byId.aspectMean.exact.split('..')[0], 4));
def('AspectSdPrinted', byId.aspectSd.printed); def('AspectSdExact', dec(byId.aspectSd.exact.split('..')[0], 4)); def('AspectSdPop', dec(byId.aspectSd.sdPopulation.split('..')[0], 4));
def('AspectCVPrinted', byId.aspectCV.printed); def('AspectCVExact', dec(byId.aspectCV.exact.split('..')[0], 2));
need(V('aspectPeak') === 'NOT_THE_TABLES' && byId.aspectPeak.ties === 1 && !byId.aspectPeak.containsPrinted, 'the histogram-peak sentence would be false');
def('AspectPeakPrinted', byId.aspectPeak.printed); def('AspectPeakBins', String(byId.aspectPeak.nbins)); def('AspectPeakWidth', dec(byId.aspectPeak.width, 4));
def('AspectPeakModeLo', dec(byId.aspectPeak.modeBin[0], 3)); def('AspectPeakModeHi', dec(byId.aspectPeak.modeBin[1], 3)); def('AspectPeakCentre', dec(byId.aspectPeak.exact, 3));
def('AspectPeakCount', int(byId.aspectPeak.modeCount)); def('AspectPeakIqr', dec(byId.aspectPeak.iqr, 3));
{ const w = Number(byId.aspectPeak.width), lo = Number(byId.aspectPeak.modeBin[0]), p = Number(byId.aspectPeak.printed);
  need(lo - 2 * w <= p && p < lo - w, 'the printed peak is no longer two bins to the left of the mode bin'); }
def('DuncanAspectPrinted', CL.paper.printed.duncanAspect.mean + '\\,\\ensuremath{\\pm}\\,' + CL.paper.printed.duncanAspect.sd); def('DuncanAspectCV', CL.paper.printed.duncanAspect.cv);

/* the range of theta: the column, and the angle whose integer parts are the printed pair */
need(V('thetaMin') === 'NOT_THE_TABLES' && V('thetaMax') === 'NOT_THE_TABLES' && V('thetaRangeAlt') === 'REPRODUCED_AS_TRUNCATION' && byId.thetaMax.eventsAbove45 === 0, 'the theta-range sentence would be false');
def('ThetaPrintedLo', CL.paper.printed.thetaRange.lo); def('ThetaPrintedHi', CL.paper.printed.thetaRange.hi);
def('ThetaColMin', dec(byId.thetaMin.exact, 2)); def('ThetaColMax', dec(byId.thetaMax.exact, 2));
const tanLo = Number(/min ([\d.]+)/.exec(byId.thetaRangeAlt.exact)[1]), tanHi = Number(/max ([\d.]+)/.exec(byId.thetaRangeAlt.exact)[1]);
def('ThetaAltTanLo', dec(tanLo, 4)); def('ThetaAltTanHi', dec(tanHi, 4));
def('ThetaAltDegLo', dec(Math.atan(tanLo) * 180 / Math.PI, 2)); def('ThetaAltDegHi', dec(Math.atan(tanHi) * 180 / Math.PI, 2));   /* a reading of the record's tangents, two decimals; the decision is the record's, through enclosed tangents */
def('DuncanAngleLo', CL.references.duncanAngle.lo); def('DuncanAngleHi', CL.references.duncanAngle.hi);

/* the correlations */
need(V('pearsonSpeedMax') === 'NOT_THE_TABLES' && byId.pearsonSpeedMax.pair === 'cm~Dz_max', 'the r < 0.45 sentence would be false');
def('SpeedPairs', String(byId.pearsonSpeedMax.pairs)); def('SpeedPairsBelow', String(byId.pearsonSpeedMax.pairs - 1)); def('SpeedRMax', dec(byId.pearsonSpeedMax.exact, 4)); def('SpeedRPrinted', CL.paper.printed.pearsonSpeedMax.value);
const SP = PA.speedPearson;
const speedBelow = Object.values(SP).filter((v) => Math.abs(Number(v.r[1])) < 0.45).length;
need(speedBelow === byId.pearsonSpeedMax.pairs - 1, 'the 31-of-32 count moved');
for (const [id, name] of [['rAbLb', 'RAbLb'], ['rAbLD81', 'RAbLD'], ['rDzEB', 'RDzEB'], ['rAbDt', 'RAbDt'], ['rLbDt', 'RLbDt'], ['rDzDt', 'RDzDt']]) {
  def(name + 'Printed', byId[id].printed); def(name + 'Exact', dec(byId[id].exact.split('..')[0], 3)); def(name + 'Verdict', byId[id].verdict === 'REPRODUCED' ? 'the rounding' : 'not the rounding');
}
need(V('rAbLb') === 'REPRODUCED' && V('rAbLD81') === 'REPRODUCED' && V('rDzEB') === 'REPRODUCED' && V('rLbDt') === 'REPRODUCED' && V('rDzDt') === 'REPRODUCED', 'a correlation sentence would be false');
need(V('rAbDt') === 'NOT_THE_TABLES' && byId.rAbDt.withAbSumVerdict === 'REPRODUCED', 'the r(Ab, dt) sentence would be false');
def('RAbDtSum', dec(byId.rAbDt.withAbSum[0], 3));
/* the slopes of area on length squared */
need(V('fitAbLD81') === 'NOT_THE_TABLES' && byId.fitAbLD81.withAreaAtMaxLengthVerdict === 'REPRODUCED' && V('fitAbLb') === 'NOT_THE_TABLES', 'the area-on-length sentence would be false');
const kc = Object.fromEntries([...byId.fitAbLD81.exact.matchAll(/(all|rest|tail) ([\d.]+)/g)].map((m) => [m[1], Number(m[2])]));
const kb = Object.fromEntries([...byId.fitAbLb.exact.matchAll(/(all|rest|tail) ([\d.]+)/g)].map((m) => [m[1], Number(m[2])]));
def('FitAbLDPrinted', byId.fitAbLD81.printed); def('FitAbLDAll', dec(kc.all, 4)); def('FitAbLDRest', dec(kc.rest, 4)); def('FitAbLDTail', dec(kc.tail, 4)); def('FitAbLDLmax', dec(byId.fitAbLD81.withAreaAtMaxLength, 4));
def('FitAbLbPrinted', byId.fitAbLb.printed); def('FitAbLbAll', dec(kb.all, 4)); def('FitAbLbRest', dec(kb.rest, 4)); def('FitAbLbTail', dec(kb.tail, 4));
need(dec(kc.all, 2) === byId.fitAbLb.printed, 'the all-events slope of Ab on L_D81^2 no longer rounds to the printed 0.27');
need([kb.all, kb.rest, kb.tail].every((k) => dec(k, 2) !== byId.fitAbLb.printed && dec(k, 2) !== byId.fitAbLD81.printed), 'a slope of Ab on Lb^2 rounds to a printed value');
def('AspectMedian', dec(byId.fitAbLD81.medianRatio, 4));
/* the two RANSAC coefficients */
need(V('fitEAEB') === 'NOT_DECIDABLE_RANSAC' && V('fitAeAb') === 'NOT_DECIDABLE_RANSAC', 'the RANSAC sentence would be false');
need(byId.fitEAEB.rVerdict === 'REPRODUCED' && byId.fitAeAb.rVerdict === 'NOT_THE_TABLES' && byId.fitAeAb.rSumVerdict === 'REPRODUCED', 'the r-beside-RANSAC sentence would be false');
def('FitEAEBPrinted', byId.fitEAEB.printed); def('FitEAEBLs', dec(byId.fitEAEB.exact, 3)); def('FitEAEBRPrinted', byId.fitEAEB.rPrinted); def('FitEAEBR', dec(byId.fitEAEB.r[0], 3));
def('FitAeAbPrinted', byId.fitAeAb.printed); def('FitAeAbLs', dec(byId.fitAeAb.exact, 3)); def('FitAeAbRPrinted', byId.fitAeAb.rPrinted); def('FitAeAbR', dec(byId.fitAeAb.r[0], 3)); def('FitAeAbRSum', dec(byId.fitAeAb.rSumColumns[0], 3));

/* the table of printed numbers */
const WORD = { REPRODUCED: 'the rounding', TRUNCATION: 'the truncation', REPRODUCED_AS_TRUNCATION: 'the integer parts', ON_THE_BOUNDARY: 'a rounding tie', NOT_THE_TABLES: 'not the table\'s', NOT_DECIDABLE_RANSAC: 'not decidable (RANSAC)' };
const NAME = {
  N: '$N$', thetaMin: '$\\theta$, lower end', thetaMax: '$\\theta$, upper end', thetaRangeAlt: '$\\theta$ range as $\\tan^{-1}(\\Delta z_{b}/e_{B})$',
  aspectMean: 'mean $A_b/L_{D81}^2$', aspectSd: 'sd of $A_b/L_{D81}^2$', aspectCV: 'CV of $A_b/L_{D81}^2$ (\\%)', aspectPeak: 'peak of $A_b/L_{D81}^2$',
  fitLb: '$L_b = a\\,c_b^2/g$', fitLD81: '$L_{D81} = a\\,c_b^2/g$', fitDz: '$\\Delta z_b = a\\,c_b^2/g$', pearsonSpeedMax: '$r$(speed, geometry)',
  rAbLb: '$r(A_b, L_b)$', rAbLD81: '$r(A_b, L_{D81})$', rDzEB: '$r(\\Delta z_b, e_B)$', rAbDt: '$r(A_b, \\Delta t_b)$', rLbDt: '$r(L_b, \\Delta t_b)$', rDzDt: '$r(\\Delta z_b, \\Delta t_b)$',
  fitAbLD81: '$A_b = k\\,L_{D81}^2$', fitAbLb: '$A_b = k\\,L_b^2$', fitEAEB: '$e_A = k\\,e_B$', fitAeAb: '$A_e = k\\,A_b$',
  selfSimilarFraction: 'self-similar fraction', fitLbTail: 'tail: $gL_b/c_b^2$', fitLbRest: 'rest: $gL_b/c_b^2$',
};
const exactShort = (it) => {
  const e = String(it.exact);
  if (it.id === 'thetaRangeAlt') return dec(Math.atan(tanLo) * 180 / Math.PI, 2) + '$^\\circ$ to ' + dec(Math.atan(tanHi) * 180 / Math.PI, 2) + '$^\\circ$';
  if (it.id === 'selfSimilarFraction') return e.replace(/ %/g, '\\%').replace(/ · /g, ', ');
  if (it.id === 'pearsonSpeedMax') return dec(e, 4) + ' (speed, $\\Delta z_b$)';
  if (it.id === 'fitAbLD81') return dec(kc.all, 4) + ' (max.\\ area); ' + dec(byId.fitAbLD81.withAreaAtMaxLength, 4) + ' (area at max.\\ length)';
  if (it.id === 'fitAbLb') return dec(kb.all, 4) + ' (all); ' + dec(kb.tail, 4) + ' (tail)';
  if (it.id === 'fitEAEB' || it.id === 'fitAeAb') return dec(e, 3) + ' (least squares); $r$ = ' + dec(it.r[0], 3);
  if (it.id === 'fitLbTail' || it.id === 'fitLbRest') return dec(e, 4) + '; $r$ = ' + dec(it.rCb2Lb[0], 3);
  if (it.id === 'aspectPeak') return 'mode bin [' + dec(it.modeBin[0], 3) + ', ' + dec(it.modeBin[1], 3) + ')';
  if (it.id === 'rAbDt') return dec(e.split('..')[0], 3) + ' ($A_{b,\\max}$); ' + dec(it.withAbSum[0], 3) + ' ($A_{b,\\mathrm{sum}}$)';
  if (/^-?[\d.]+\.\.-?[\d.]+$/.test(e)) return dec(e.split('..')[0], 4);
  const n = Number(e); return Number.isFinite(n) ? (Number.isInteger(n) ? int(n) : dec(n, 4)) : e;
};
const printedShort = (it) => {
  if (it.id === 'selfSimilarFraction') return '4\\,$\\pm$\\,2\\%';
  if (it.id === 'pearsonSpeedMax') return '$<0.45$';
  if (it.id === 'thetaRangeAlt') return '3$^\\circ$ to 71$^\\circ$';
  if (it.id === 'fitLbTail') return it.printed + ', $r$ = ' + it.rPrinted;
  if (it.id === 'fitLbRest') return it.printed + ', $r$ = ' + it.rPrinted;
  if (it.id === 'fitEAEB' || it.id === 'fitAeAb') return it.printed + ', $r$ = ' + it.rPrinted;
  if (it.id === 'N') return int(it.printed);
  if (it.id === 'fitLb' || it.id === 'fitLD81' || it.id === 'fitDz') return it.printed + '\\,$\\pm$\\,' + it.pm;
  return String(it.printed);
};
rows('ItemRows', PA.items.map((it) => [NAME[it.id] || it.id, printedShort(it), exactShort(it), WORD[it.verdict]]));

/* ---- Table 1 read against the table ---- */
const T1 = PA.table1;
need(T1.allFound && T1.cells === 140 && T1.reproduced + T1.truncation + T1.onTheBoundary + T1.notTheTables === T1.cells, 'the Table 1 tally does not partition 140 cells');
need(T1.HsNamedColumnMatches === 0, 'the column named Hs now rounds to a printed Hs somewhere');
const hsSv = T1.rows.filter((r) => r.cells.Hs === 'REPRODUCED' || r.cells.Hs === 'TRUNCATION').length;
need(hsSv === 19, 'the sv_fp2 column no longer rounds or truncates to the printed Hs in 19 of 20 records');
def('TOneCells', String(T1.cells)); def('TOneReproduced', String(T1.reproduced)); def('TOneTruncation', String(T1.truncation)); def('TOneTies', String(T1.onTheBoundary)); def('TOneNot', String(T1.notTheTables));
def('TOneHsSv', String(hsSv)); def('TOneHsNamed', String(T1.HsNamedColumnMatches));
const evExact = T1.rows.every((r) => r.cells.events === 'REPRODUCED' && r.cells.fps === 'REPRODUCED');
need(evExact, 'an event count or frame rate no longer matches');
/* the durations and areas: every cell the rounding but one truncation (an area) */
const durArea = T1.rows.flatMap((r) => [r.cells.duration, r.cells.area]);
need(durArea.filter((c) => c === 'REPRODUCED').length === 39 && durArea.filter((c) => c === 'TRUNCATION').length === 1 && T1.rows.filter((r) => r.cells.area === 'TRUNCATION').length === 1, 'the durations-and-areas sentence would be false');
/* the exact range of the column named sv_fp2 (the printed Hs) */
const sv = T1.rows.map((r) => Number(r.exact.sv_fp2));
def('SvLo', dec(Math.min(...sv), 4)); def('SvHi', dec(Math.max(...sv), 4));
/* the column named Hs: every value a multiple of 1/256 (read from the pinned CSV; exact, since such values are binary fractions) */
{
  const txt = fs.readFileSync(path.join(ROOT, 'corpus', 'blacksea-breaking', 'blacksea_data.csv'), 'utf8');
  const lines = txt.split('\n').filter((l) => l.length);
  const cols = lines[0].split(','), iHs = cols.indexOf('Hs');
  need(iHs >= 0 && lines.length - 1 === L.n, 'the pinned CSV is not the ledger\'s table');
  const distinct = new Set(); for (let i = 1; i < lines.length; i++) distinct.add(lines[i].split(',')[iHs]);
  const vals = [...distinct].map(Number);
  need(vals.length <= 20 && vals.every((v) => v > 0), 'the column named Hs has more than twenty values');
  /* each value within one unit in the last place of the double of a multiple of 1/1024 (the record's prose says 1/256; the table says this) */
  const ulp = (v) => Math.pow(2, Math.floor(Math.log2(v)) - 52);
  need(vals.every((v) => Math.abs(v * 1024 - Math.round(v * 1024)) <= 1024 * ulp(v)), 'the column named Hs is not within one ulp of a multiple of 1/1024 throughout');
  need(!vals.every((v) => Number.isInteger(v * 256)), 'the column named Hs is now exactly multiples of 1/256; the sentence can be sharpened');
  def('HsNamedDistinct', String(vals.length)); def('HsNamedLo', dec(Math.min(...vals), 4)); def('HsNamedHi', dec(Math.max(...vals), 4));
}
const MARK = { REPRODUCED: '', TRUNCATION: '$^{\\mathrm{t}}$', ON_THE_BOUNDARY: '$^{\\mathrm{b}}$', NOT_THE_TABLES: '$^{\\mathrm{n}}$' };
rows('TableOneRows', T1.rows.map((r) => [
  r.time.slice(0, 16).replace(/\//g, '-'), String(r.printed.fps), r.printed.dur + MARK[r.cells.duration], r.printed.area + MARK[r.cells.area], int(r.printed.nb),
  r.printed.hs + MARK[r.cells.Hs], dec(r.exact.sv_fp2, 3), dec(r.exact.HsNamedColumn, 3),
  r.printed.tp + MARK[r.cells.Tp], dec(r.exact.Tp, 2), r.printed.u10 + MARK[r.cells.U10], dec(r.exact.U10, 2),
]));
/* the loader script: the column-name list against the value assignment (read, never run) */
{
  const src = fs.readFileSync(path.join(ROOT, 'corpus', 'blacksea-breaking', 'load_breaking_statistics.py'), 'utf8');
  const m = /\nZstat = \[([\s\S]*?)\]\n/.exec(src);
  need(m, 'the loader\'s Zstat list was not found');
  const names = [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1]);
  need(names.length === 46 && names[31] === 'sv_fp2' && names[33] === 'Hs' && names[32] === 'sv_fb0', 'the loader\'s column names at 31..33 are not sv_fp2, sv_fb0, Hs');
  need(/Zstat\[31\]: Hs_ev, Zstat\[32\]: svfp2_ev, Zstat\[33\]: svfb0_ev/.test(src), 'the loader does not assign Hs_ev, svfp2_ev, svfb0_ev to positions 31..33');
  need(/Hs_ev = np\.append\(Hs_ev, dev\[var_Hs\]\.values\[0\]\)/.test(src) && /svfb0_ev = np\.append\(svfb0_ev, dev\[var_fb0\]\.values\[0\]\)/.test(src), 'the loader\'s Hs_ev and svfb0_ev are not read from var_Hs and var_fb0');
  need(/th_Lmax_ev = np\.append\(th_Lmax_ev, np\.rad2deg\(\s*np\.arctan\(dev\[var_Dz\]\.values\[np\.argmax\(B\)\]\/BDz\.values\[np\.argmax\(B\)\]\)\)\)/.test(src), 'the loader\'s theta is not arctan(Dz/BDz) at the frame of the largest B');
  need(/BDz = np\.sqrt\(dev\[var_Dz\]\.values\*\*2 \+ B\*\*2\)/.test(src) && names[43] === 'LD81' && /Zstat\[43\]: BDz_Lmax_ev/.test(src) && names[44] === 'theta' && /Zstat\[44\]: th_Lmax_ev/.test(src), 'the loader\'s L_D81 is not sqrt(Dz^2 + B^2) at that frame');
  need(names[45] === 'Ab_Lmax' && /Ab_Lmax_ev = np\.append\(Ab_Lmax_ev, dev\[var_Ab\]\.values\[np\.argmax\(B\)\]\)/.test(src), 'the loader\'s Ab_Lmax is not the area at the frame of the largest B');
  def('LoaderSha', ME.files['load_breaking_statistics.py'].sha256.slice(0, 12));
}

/* ---- Duncan's geometry as the record treats it ---- */
const A = L.duncan.angle, S = L.duncan.aspect;
need(A.inside + A.outside === L.n && A.below + A.above === A.outside && A.on === 0, 'the angle band does not partition the events');
need(S.above + S.equal + S.below === L.n, 'the aspect comparison does not partition the events');
def('AngleInside', int(A.inside)); def('AngleInsidePct', pct(A.inside, L.n, 1)); def('AngleBelow', int(A.below)); def('AngleAbove', int(A.above)); def('AngleOn', String(A.on));
def('AngleBelowPct', pct(A.below, L.n, 1)); def('AngleAbovePct', pct(A.above, L.n, 1));
def('AspectAbove', int(S.above)); def('AspectBelow', int(S.below)); def('AspectEqual', String(S.equal)); def('AspectWithinQuarter', int(S.within25pc)); def('AspectWithinHalf', int(S.within50pc));
def('AspectMedianOverDuncan', dec(S.medianOverReference.dec, 2)); def('DuncanAspect', S.reference);
def('AspectMinExact', dec(S.distribution.min.dec, 3)); def('AspectMaxExact', dec(S.distribution.max.dec, 3));

/* ---- the three ratios ---- */
const SS = L.selfSimilarity;
rows('RatioRows', [['$c_b^2/(gL_b)$', SS.a, TL.a], ['$A_b/L_b^2$', SS.b, TL.b], ['$A_b/L_{D81}^2$', SS.c, TL.c]].map(([k, s, t]) => [k, dec(s.q05.dec, 3), dec(s.q25.dec, 3), dec(s.median.dec, 3), dec(s.q75.dec, 3), dec(s.q95.dec, 3), dec(s.spreadIQ.dec, 2), dec(s.spread90.dec, 2), dec(t.threshold[0], 3), int(t.above), pct(t.above, L.n, 2)]));
need(['a', 'b', 'c'].every((k) => Number(SS[k].spreadIQ.dec) > 1.5 && Number(SS[k].spread90.dec) > 4), 'the spread sentence would be false');
def('SpreadIQA', dec(SS.a.spreadIQ.dec, 2)); def('SpreadIQB', dec(SS.b.spreadIQ.dec, 2)); def('SpreadIQC', dec(SS.c.spreadIQ.dec, 2));
def('SpreadNinetyA', dec(SS.a.spread90.dec, 2)); def('SpreadNinetyB', dec(SS.b.spread90.dec, 2)); def('SpreadNinetyC', dec(SS.c.spread90.dec, 2));
def('MedianA', dec(SS.a.median.dec, 3)); def('MedianB', dec(SS.b.median.dec, 3)); def('MedianC', dec(SS.c.median.dec, 3));
/* speed over peak phase speed */
need(Number(L.cmOverCp.median.lo) > 0.25 && Number(L.cmOverCp.median.hi) < 0.32, 'the cb/cp sentence would be false');
def('CbCpMedian', dec(L.cmOverCp.median.lo, 3)); def('CbCpQlo', dec(L.cmOverCp.q05.lo, 3)); def('CbCpQhi', dec(L.cmOverCp.q95.lo, 3)); def('FasterThanHalfCp', int(L.cmOverCp.fasterThanHalfCp));
def('DistinctDT', String(L.distinct.DT));
/* rank correlations: nine pairs */
const CR = L.correlations;
const LAB = { cm: '$c_b$', Lb: '$L_b$', Ab_max: '$A_b$', Dz_max: '$\\Delta z_b$', DT: '$\\Delta t_b$', LD81: '$L_{D81}$', theta: '$\\theta$' };
rows('CorrRows', Object.entries(CR).map(([k, v]) => { const [x, y] = k.split('~'); return [LAB[x] + ' and ' + LAB[y], dec(v.spearman.r.lo, 3), dec(v.pearson.r.lo, 3)]; }));
const speedRho = Object.entries(CR).filter(([k]) => k.startsWith('cm~')).map(([k, v]) => [k, Number(v.spearman.r.hi)]);
const rhoMax = speedRho.reduce((m, p) => (p[1] > m[1] ? p : m));
need(rhoMax[0] === 'cm~Dz_max' && rhoMax[1] < 0.45 && Number(CR['Ab_max~Lb'].spearman.r.lo) > 0.9, 'the rank-correlation contrast would be false');
def('RhoSpeedMax', dec(rhoMax[1], 3)); def('RhoSpeedMaxSq', dec(CR['cm~Dz_max'].spearman.r2.dec, 3)); def('RhoAbLb', dec(CR['Ab_max~Lb'].spearman.r.lo, 3));
def('RhoCbLb', dec(CR['cm~Lb'].spearman.r.lo, 3)); def('RhoCbAb', dec(CR['cm~Ab_max'].spearman.r.lo, 3)); def('RhoCbDt', dec(CR['cm~DT'].spearman.r.lo, 3)); def('RhoCbTheta', dec(CR['cm~theta'].spearman.r.lo, 3));

/* ---- the stratification by sea state ---- */
const PR = PA.perRecord, SEA = PA.seaState;
need(PR.length === 20 && PR.reduce((a, p) => a + p.n, 0) === L.n, 'the per-record table does not partition the events');
need(L.records.every((r) => r.constant), 'a record carries two values of Hs, fp or U10');
need(Number(SEA.slopeSpread) > 1.5 && Number(SEA.slopeMin) < 0.83 && Number(SEA.slopeMax) > 0.83, 'the per-record spread sentence would be false');
const rho = (k) => Number(SEA.spearman[k].rho[0]);
need(rho('slope~Hs') < -0.4 && Math.abs(rho('slope~waveAge')) < 0.1, 'the sea-state rank sentence would be false');
def('SlopeMin', dec(SEA.slopeMin, 3)); def('SlopeMax', dec(SEA.slopeMax, 3)); def('SlopeSpread', dec(SEA.slopeSpread, 2)); def('PooledSlope', dec(SEA.pooledSlope, 4));
for (const [t, T] of [['slope', 'Slope'], ['aspectMean', 'Aspect'], ['medianA', 'MedianA'], ['fractionInBand', 'Band']]) for (const [s, Sn] of [['Hs', 'Hs'], ['Tp', 'Tp'], ['U10', 'U'], ['waveAge', 'Age']]) def('Rho' + T + Sn, sgn(rho(t + '~' + s), 3));
rows('SeaStateRows', [['coefficient $gL_b/c_b^2$', 'slope'], ['mean $A_b/L_{D81}^2$', 'aspectMean'], ['median $c_b^2/(gL_b)$', 'medianA'], ['share of events in 10$^\\circ$--14.7$^\\circ$', 'fractionInBand']].map(([name, t]) => [name].concat(['Hs', 'Tp', 'U10', 'waveAge'].map((s) => sgn(rho(t + '~' + s), 3)))));
const rough = PR.filter((p) => Number(p.Hs) > 1.5).sort((a, b) => Number(a.slopeDec) - Number(b.slopeDec));
const sortedSlopes = PR.map((p) => Number(p.slopeDec)).sort((a, b) => a - b);
need(rough.length === 4 && rough.every((p) => Number(p.slopeDec) <= sortedSlopes[3]), 'the four Hs > 1.5 m records no longer carry the four lowest coefficients');
need(rough.every((p) => p.time.startsWith('2013/10/01')), 'the four roughest records are not the 1 October records');
def('RoughCount', String(rough.length)); def('RoughSlopes', rough.map((p) => dec(p.slopeDec, 3)).join(', '));
def('RoughULo', dec(Math.min(...rough.map((p) => Number(p.U10))), 1)); def('RoughUHi', dec(Math.max(...rough.map((p) => Number(p.U10))), 1));
def('RoughHsLo', dec(Math.min(...rough.map((p) => Number(p.Hs))), 2)); def('RoughHsHi', dec(Math.max(...rough.map((p) => Number(p.Hs))), 2));
def('RoughTailPcts', rough.map((p) => (100 * Number(p.tailFraction)).toFixed(1) + '\\%').join(', '));
def('TailPctOverall', pct(SF.counts[0], L.n, 1));
def('LargestRecordN', int(Math.max(...PR.map((p) => p.n)))); def('SmallestRecordN', int(Math.min(...PR.map((p) => p.n))));
const bandFr = PR.map((p) => Number(p.fractionInBand));
def('BandShareLo', pct(Math.min(...bandFr), 1, 1)); def('BandShareHi', pct(Math.max(...bandFr), 1, 1));
const rSq = PR.map((p) => Number(p.rCb2Lb[0]));
def('RecordRLo', dec(Math.min(...rSq), 3)); def('RecordRHi', dec(Math.max(...rSq), 3));
const aspM = PR.map((p) => Number(p.aspectMeanDec));
def('RecordAspectLo', dec(Math.min(...aspM), 3)); def('RecordAspectHi', dec(Math.max(...aspM), 3));
const tailFr = PR.map((p) => 100 * Number(p.tailFraction));
def('RecordTailLo', dec(Math.min(...tailFr), 1) + '\\%'); def('RecordTailHi', dec(Math.max(...tailFr), 1) + '\\%');
const recDates = new Set(PR.map((p) => p.time.slice(0, 10)));
def('RecordDays', String(recDates.size));
rows('RecordRows', PR.map((p) => [p.time.slice(0, 16).replace(/\//g, '-'), int(p.n), dec(p.Hs, 2), dec(p.Tp, 1), dec(p.U10, 1), dec(p.slopeDec, 3), dec(p.rCb2Lb[0], 3), (100 * Number(p.fractionInBand)).toFixed(1), dec(p.aspectMeanDec, 3), (100 * Number(p.tailFraction)).toFixed(1)]));

fs.writeFileSync(OUT, M.join('\n') + '\n');
console.log('wrote paper/tex/breaking-waves-numbers.tex (' + (M.length - 1) + ' macros)');
