#!/usr/bin/env node
/* paper-numbers/delta3.js — every number the δ₃ pre-paper (paper/tex/delta3.tex) quotes, read
   from the records that decided it and written as LaTeX macros: paper/tex/delta3-numbers.tex.

   Records read: certs/delta3-ledger.json (the clean-room verifier's --record),
   certs/delta3-lemmas.json (the lemma tests and the exact upper-bound counts),
   certs/delta3-mutations.json (the mutation pass), certs/delta3/claimant-vcheck-rerun.log (the
   claimant's verifier re-run here — an exhibit), and the claimant's superseded ladder records
   certs/delta3/frontier/s34/{verify-L*.log, ceilings.json}, quoted as theirs.
   Live, about five seconds: the battery (its PASS lines and red controls are counted from its
   own output). The ledger is checked against the tree first — the certificate hashes and the
   verifier hashes it records must be the files on disk — so the paper cannot quote a run of a
   verifier that is no longer there. A record that no longer says what a sentence needs makes
   this refuse (need()), as tools/build-paper-numbers.js does.

   usage: node tools/paper-numbers/delta3.js                                          MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex', 'delta3-numbers.tex');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const die = (m) => { console.error('DELTA3 PAPER NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const sha = (rel) => crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, rel))).digest('hex');
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const sciM = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return m[1] + '\\times10^{' + Number(m[2]) + '}'; };
const frac = (s) => { const [p, q] = String(s).split('/'); return q ? p + '/' + q : p; };
const num = (s) => { const [p, q] = String(s).split('/'); return Number(p) / (q ? Number(q) : 1); };
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();

const M = ['%% generated by tools/paper-numbers/delta3.js from certs/delta3-ledger.json, certs/delta3-lemmas.json, certs/delta3-mutations.json and the claimant\'s lifted logs — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };

/* ---- the ledger, checked against the tree ----------------------------------- */
const L = J('certs/delta3-ledger.json');
need(L.theorem && L.theorem.verdict === 'VERIFIED' && L.theorem.delta3LowerBound === '117/2192' && L.theorem.Qstar === '-5/137', 'the ledger does not state the theorem as VERIFIED');
need(L.cover && L.cover.complete, 'the cover is not complete');
for (const c of L.certificates) {
  need(c.verdict === 'VERIFIED', c.file + ' is not VERIFIED');
  need(sha(c.file) === c.sha256, c.file + ' changed since the ledger was written');
  if (c.kind === 'slab') need(c.claimMatchesFile === true, c.file + ': the recomputed bound is not the file\'s claim');
}
for (const [f, h] of Object.entries(L.verifier.files)) need(sha(f) === h, 'the ledger was written by a different ' + f);
const certs = L.certificates.slice().sort((a, b) => num(a.region.lo) - num(b.region.lo));
const inner = certs.find((c) => c.kind === 'inner'), slabs = certs.filter((c) => c.kind === 'slab');
need(inner && slabs.length === 4, 'expected one inner certificate and four slabs');
const minSlab = slabs.reduce((m, c) => (!m || Number(c.boundDecimal) < Number(m.boundDecimal) ? c : m), null);

/* 117/2192 to 12 places, by exact long division */
const decimals = (p, q, k) => { let r = BigInt(p), s = ''; const Q = BigInt(q); s += (r / Q).toString() + '.'; r %= Q; for (let i = 0; i < k; i++) { r *= 10n; s += (r / Q).toString(); r %= Q; } return s; };
def('DeltaDec', decimals(117, 2192, 10));
def('QstarVal', '-5/137'.replace('-', '-'));
need(L.phiStar.Q === '-5/137' && L.phiStar.hIntegral === '5/137', 'the phi* facts moved');
def('HIntegral', L.phiStar.hIntegral);
def('MinSlab', sciM(minSlab.boundDecimal, 3));
def('Rin', frac(inner.region.hi));
def('RinDouble', frac(String(2 * Number(inner.region.hi.split('/')[0])) + '/' + inner.region.hi.split('/')[1]));
const grids = [...new Set(certs.map((c) => c.n))].sort((a, b) => a - b);
need(grids.length === 2, 'expected two grids');
def('GridAN', String(grids[0]));
def('GridBN', String(grids[1]));
def('CoverTable', certs.map((c) => '$[' + frac(c.region.lo) + ',\\ ' + frac(c.region.hi) + ']$ & ' + c.n + ' & '
  + (c.kind === 'inner' ? '$0$ (exact at $\\sigma=0$)' : '$' + sciM(c.boundDecimal, 6) + '$') + ' & ' + int(c.counts.forms)
  + (c.counts.triangles ? ' (' + int(c.counts.triangles) + ' triangles)' : '') + ' & verified \\\\').join('\n'));
def('VerifySeconds', Number(L.seconds) < 10 ? Number(L.seconds).toFixed(1) : String(Math.round(L.seconds)));

/* ---- the claimant's verifier, re-run here (an exhibit) ---------------------- */
const RERUN = fs.readFileSync(path.join(ROOT, 'certs', 'delta3', 'claimant-vcheck-rerun.log'), 'utf8');
const rr = /THEOREM VERIFIED[\s\S]*# exit 0 · (\d+) s/.exec(RERUN);
need(rr, 'the claimant verifier\'s re-run log does not end THEOREM VERIFIED with exit 0');
def('ClaimantSeconds', rr[1]);

/* ---- the battery, live ------------------------------------------------------- */
const bat = cp.spawnSync('node', [path.join(ROOT, 'instruments', 'delta3', 'battery.js')], { cwd: ROOT, maxBuffer: 64 << 20 });
const bout = String(bat.stdout) + String(bat.stderr);
const bm = /BATTERY GREEN\s+(\d+) pass, 0 fail/.exec(bout);
need(bat.status === 0 && bm && !/^FAIL\b/m.test(bout), 'the delta3 battery is not green');
const nReds = (bout.match(/^PASS {2}RED\b/gm) || []).length;
need(nReds > 0, 'no red control fired');
def('NChecks', bm[1]);
def('NReds', String(nReds));

/* ---- the mutation pass ------------------------------------------------------- */
const MU = J('certs/delta3-mutations.json');
need(MU.counts.survivedUnexplained === 0, 'a verifier mutation survived unexplained');
for (const [f, h] of Object.entries(MU.verifierFiles)) need(sha(f) === h, 'the mutation pass ran against a different ' + f);
def('MutCaught', int(MU.counts.caught) + ' of ' + int(MU.counts.mutants) + ' are caught by the genuine set or a forgery, and the '
  + (MU.counts.survivedEquivalent === 1 ? 'one survivor removes' : MU.counts.survivedEquivalent + ' survivors remove')
  + ' a rule that is enforced twice');

/* ---- the lemma tests and the counts ----------------------------------------- */
const LM = J('certs/delta3-lemmas.json');
need(LM.allPass && LM.identity.identityHolds === LM.identity.cases && LM.discretisation.holds === LM.discretisation.cases, 'the lemma record is not all-pass');
def('IdentityCases', int(LM.identity.cases));
def('LemmaCases', int(LM.discretisation.cases));
need(LM.bathtub.singlePieceReading && LM.bathtub.singlePieceReading.violations > 0, 'the single-piece bathtub reading is no longer recorded as violated');
def('BathtubViol', int(LM.bathtub.singlePieceReading.violations));
def('BathtubTests', int(LM.bathtub.singlePieceReading.cases));
need(LM.counts.length >= 4, 'too few upper-bound counts');
def('VnRows', LM.counts.map((r) => int(r.n) + ' & ' + int(r.mono) + ' & ' + r.ratioDecimal + ' & $' + r.timesN.replace('-', '-') + '$ \\\\').join('\n'));
def('VnMaxN', int(Math.max(...LM.counts.map((r) => r.n))));

/* ---- the superseded ladder, the claimant's records -------------------------- */
const CEIL = J('certs/delta3/frontier/s34/ceilings.json');
def('LadderRows', [32, 64, 128, 192, 256].map((Lc) => {
  const log = fs.readFileSync(path.join(ROOT, 'certs', 'delta3', 'frontier', 's34', 'verify-L' + Lc + '.log'), 'utf8');
  const m = /VERIFIED\s+Q\* >= (-?[\d.]+)\s+delta_3 >= ([\d.]+)/.exec(log);
  need(m && CEIL[Lc], 'the ladder record for L = ' + Lc + ' is missing');
  need(Number(m[2]) < 117 / 2192 && CEIL[Lc].delta < 117 / 2192, 'a ladder value is not below 117/2192 at L = ' + Lc);
  return Lc + ' & ' + m[2] + ' & ' + CEIL[Lc].delta.toFixed(6) + ' \\\\';
}).join('\n'));
def('RepoCommit', '\\texttt{' + git + '}');

fs.writeFileSync(OUT, M.join('\n') + '\n');
console.log('paper/tex/delta3-numbers.tex written — ' + (M.length - 1) + ' macros (min slab ' + minSlab.boundDecimal + ', battery ' + bm[1] + ' green / ' + nReds + ' reds, mutations ' + MU.counts.caught + '/' + MU.counts.mutants + ')');
