#!/usr/bin/env node
/* paper-numbers/erdos290.js — every number the pre-paper paper/tex/erdos290.tex quotes,
   read from the records that decided it and written as LaTeX macros:
     paper/tex/erdos290-numbers.tex
   plus the data file the figure script draws from:
     paper/tex/fig/erdos290-squeeze.json

   Records read (nothing is remembered, nothing is typed):
     certs/erdos290-tail-ext.json                 the campaign record, l = 61..310, exact δ
     certs/erdos290-tail-shard-*.json             the six shard files merged into it
     legacy/research/challenges/erdos290/         the lifted source-lab instrument and records:
        kernel.js (EXACT_DELTAS, deltaHyperoct, deltaIndex2, conditionalCStar, decimals),
        tail-deltas.json (l = 31..60), narrowing.json (the cited bracket and the 34-digit
        conditional enclosure), galois-exceptions.js (exact discriminants, pair polynomial),
        theorem.js (the exact integer identities; RE-RUN here in a scratch copy, ~15 s)
     machine/erdos290/tail.js                     the ONE place the bracket is assembled
     tools/erdos290-lean-battery.js               the closed-form battery (under a second)
     tools/erdos290-cstar-precision.js            the 110-digit conditional expansion, run from
                                                  a path-patched scratch copy so its b-files land
                                                  in a temp dir and are compared to outreach/
   A record that no longer says what a sentence needs makes this refuse (need()), exactly as
   tools/build-paper-numbers.js does for the Elsevier manuscripts.

   usage: node tools/paper-numbers/erdos290.js                                          MIT */
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const cp = require('child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex');
const FIG = path.join(OUT, 'fig');
const LEG = path.join(ROOT, 'legacy', 'research', 'challenges', 'erdos290');
const die = (m) => { console.error('ERDOS290 PAPER NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const sci = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return '$' + m[1] + '\\times10^{' + Number(m[2]) + '}$'; };
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();
const gitDate = (rel) => { try { return cp.execSync('git log -1 --format=%cs -- ' + rel, { cwd: ROOT }).toString().trim(); } catch (e) { return ''; } };

const M = ['%% generated by tools/paper-numbers/erdos290.js from certs/erdos290-tail-ext.json, certs/erdos290-tail-shard-*.json, legacy/research/challenges/erdos290/{kernel.js,tail-deltas.json,narrowing.json,theorem.js} and machine/erdos290/tail.js — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));

/* ---- the inputs, loaded through the one bracket module -------------------- */
const TAIL = require(path.join(ROOT, 'machine', 'erdos290', 'tail.js'));
const IN = TAIL.loadInputs(ROOT, LEG);
const { Q, K, R, W, EXC, L2, EXACT, EXT, extLs, Lmax } = IN;
const add = Q.add, sub = Q.sub, mul = Q.mul, div = Q.div, cmp = Q.cmp;
const ZERO = R(0n, 1n), ONE = R(1n, 1n);
const bracket = TAIL.makeBracket({ Q, K, L2, EXACT, EXC, W });
const G = require(path.join(LEG, 'galois-exceptions.js'));
const NARROW = JSON.parse(fs.readFileSync(path.join(LEG, 'narrowing.json'), 'utf8'));
const LEGTAIL = JSON.parse(fs.readFileSync(path.join(LEG, 'tail-deltas.json'), 'utf8'));
const dec = (a, kd, mode) => K.decimals(a, kd, mode);            /* floor | ceil, as a string */
const agreedDigits = (lo, hi, kd) => {
  const a = dec(lo, kd, 'floor'), b = dec(hi, kd, 'ceil');
  let n = 0;
  for (let i = 0; i < a.length; i++) { if (a[i] !== b[i]) break; if (i > 1) n++; }
  return n;
};
const invOf = (b) => ({ lo: div(ONE, add(ONE, b.hi)), hi: div(ONE, add(ONE, b.lo)) });
const fact = (n) => { let f = 1n; for (let i = 2n; i <= BigInt(n); i++) f *= i; return f; };
const isSquare = (n) => { if (n < 0n) return false; if (n < 2n) return true; let x = n, y = (x + 1n) / 2n; while (y < x) { x = y; y = (x + n / x) / 2n; } return x * x === n; };
def('RepoCommit', git);

/* ======================================================================= the record */
need(Array.isArray(EXT.open) && EXT.open.length === 0, 'the extension record lists open degrees; the paper says none');
need(extLs.length > 0 && extLs[0] === 61, 'the extension record does not start at l = 61');
for (let i = 1; i < extLs.length; i++) need(extLs[i] === extLs[i - 1] + 1, 'the extension record has a gap at l = ' + (extLs[i - 1] + 1));
const P60 = NARROW.points[NARROW.points.length - 1];
need(P60.d === 2 * P60.K && P60.K === 60, 'the narrowing record\'s last point is not the l = 60 horizon');
const citedL = P60.K;
def('CitedL', String(citedL)); def('CitedD', String(2 * citedL));
def('HorizonL', String(Lmax)); def('HorizonD', String(2 * Lmax));
def('ExtCount', String(extLs.length)); def('ExtFrom', String(extLs[0])); def('ExtTo', String(Lmax));
def('ExtOpen', String(EXT.open.length));
def('ExtGenerated', String(EXT.generatedBy || '').replace(/_/g, '\\_'));
const extGit = /@ git ([0-9a-f]+)/.exec(String(EXT.generatedBy || ''));
need(extGit, 'the record does not name the commit that wrote it');
def('ExtGit', extGit[1]);
def('ExtCommitDate', gitDate('certs/erdos290-tail-ext.json') || 'unknown');
def('NarrowGenerated', String(NARROW.generated));
def('LegTailGenerated', String(LEGTAIL.generated));
const extPrimes = (String(EXT.method || '').match(/nPrimes[:= ]\s*(\d+)/) || [])[1];
need(extPrimes, 'the record\'s method string does not say how many primes the squeeze used');
def('ExtPrimes', extPrimes);

/* survivors: B everywhere, ES0 exactly at l = 2k(k+1) — the law, corroborated by the record */
const names = {};
for (const v of Object.values(EXT.deltas)) names[v.name] = (names[v.name] || 0) + 1;
need(Object.keys(names).sort().join() === 'B,ES0', 'the record names a group other than B or ES0: ' + Object.keys(names).join());
def('ExtB', String(names.B)); def('ExtESzero', String(names.ES0));
const isExcL = (l) => { const s = 2 * l + 1, r = Math.round(Math.sqrt(s)); return r * r === s; };
for (const [ls, v] of Object.entries(EXT.deltas)) {
  const l = Number(ls), got = R(BigInt(v.n), BigInt(v.d));
  need((v.name === 'ES0') === isExcL(l), 'survivor ' + v.name + ' at l = ' + l + ' contradicts the 4k(k+1) law');
  const want = v.name === 'ES0' ? K.deltaIndex2(l) : K.deltaHyperoct(l);
  need(cmp(got, want) === 0, 'δ at l = ' + l + ' is not the closed form of its declared group ' + v.name);
}
for (const [ls, v] of Object.entries(LEGTAIL.deltas)) {
  const l = Number(ls), got = R(BigInt(v.n), BigInt(v.d));
  need((v.name === 'ES0') === isExcL(l), 'legacy survivor ' + v.name + ' at l = ' + l + ' contradicts the law');
  need(cmp(got, v.name === 'ES0' ? K.deltaIndex2(l) : K.deltaHyperoct(l)) === 0, 'legacy δ at l = ' + l + ' is not its closed form');
}
need(Object.keys(LEGTAIL.deltas).length === 30 && LEGTAIL.open.length === 0, 'the lifted tail record is not the closed l = 31..60 block');
def('LegTailCount', String(Object.keys(LEGTAIL.deltas).length));
const top = EXT.deltas[String(Lmax)];
def('DeltaTopNum', int(top.n.length)); def('DeltaTopDen', int(top.d.length));

/* shards: six files, every entry agreeing with the merged record */
const shardFiles = fs.readdirSync(path.join(ROOT, 'certs')).filter((f) => /^erdos290-tail-shard-\d+\.json$/.test(f)).sort();
let shardTotal = 0, shardMin = Infinity, shardMax = 0;
for (const f of shardFiles) {
  const s = JSON.parse(fs.readFileSync(path.join(ROOT, 'certs', f), 'utf8'));
  need(s.open.length === 0, f + ' lists open degrees');
  for (const [ls, v] of Object.entries(s.deltas)) {
    const w = EXT.deltas[ls];
    need(w && w.n === v.n && w.d === v.d && w.name === v.name, f + ': l = ' + ls + ' disagrees with the merged record');
    shardTotal++; shardMin = Math.min(shardMin, Number(ls)); shardMax = Math.max(shardMax, Number(ls));
  }
}
need(shardFiles.length === 6, 'expected six shard files, found ' + shardFiles.length);
def('ShardCount', String(shardFiles.length)); def('ShardTotal', String(shardTotal));
def('ShardFrom', String(shardMin)); def('ShardTo', String(shardMax));
def('SerialCount', String(extLs.length - shardTotal)); def('SerialTo', String(shardMin - 1));

/* the measured cost law, as the runner's header records it */
const runnerHead = fs.readFileSync(path.join(ROOT, 'tools', 'run-erdos290-tail-shard.js'), 'utf8').slice(0, 1500);
const tm = /measured (\d+) s at\s+l = (\d+), (\d+) s at l = (\d+)/.exec(runnerHead);
need(tm, 'the shard runner no longer records its two timing points');
def('TimeLowSecs', tm[1]); def('TimeLowL', tm[2]); def('TimeHighSecs', tm[3]); def('TimeHighL', tm[4]);
def('TimeExponent', (Math.log(Number(tm[3]) / Number(tm[1])) / Math.log(Number(tm[4]) / Number(tm[2]))).toFixed(1));

/* ======================================================================= the exceptional degrees */
const excRows = [];
const andList = (xs) => (xs.length < 2 ? xs.join('') : xs.slice(0, -1).join(', ') + ' and ' + xs[xs.length - 1]);
const excExt = [];
for (let k = 1; 2 * k * (k + 1) <= Lmax; k++) {
  const l = 2 * k * (k + 1), d = 4 * k * (k + 1);
  need(EXACT.has(l), 'no exact density at the exceptional degree d = ' + d);
  const dl = EXACT.get(l);
  need(cmp(dl, K.deltaIndex2(l)) === 0, 'δ at d = ' + d + ' is not the index-2 closed form');
  const src = l <= 30 ? (l === 4 ? 'galois8.js' : 'galois-exceptions.js') : l <= citedL ? 'tail-deltas.json' : 'tail-ext.json';
  const allowDigits = (2n ** BigInt(l) * fact(l)).toString().length - 1;
  excRows.push([String(k), String(d), String(l), '\\texttt{' + src + '}', dec(dl, 12, 'floor'), '$<10^{-' + allowDigits + '}$']);
  if (l > citedL) excExt.push(d);
}
rows('ExcRows', excRows);
def('ExcCount', String(excRows.length)); def('ExcMaxK', String(excRows.length)); def('ExcMaxD', String(4 * excRows.length * (excRows.length + 1)));
def('ExcExtCount', String(excExt.length)); def('ExcExtList', andList(excExt.map(String)));
def('ExcCitedList', andList(excRows.filter((r) => Number(r[2]) <= citedL).map((r) => r[1])));
def('ExcPaperList', andList(excRows.filter((r) => Number(r[2]) <= 30).map((r) => r[1])));

/* ======================================================================= the discriminant table */
const discRows = [];
for (let d = 2; d <= 8; d += 2) {
  const l = d / 2, f = G.fdCoeffs(d), h = G.pairPoly(f, l);
  const df = G.discExact(f), dh = G.discExact(h);
  need(h[h.length - 1] === BigInt(d + 1), 'lead(h) is not d+1 at d = ' + d);
  need(h[0] === (l % 2 === 0 ? 1n : -1n) * fact(l) * fact(l), 'h(0) is not (-1)^l (l!)^2 at d = ' + d);
  need(df === BigInt(d + 1) * ((2n ** BigInt(l)) * fact(l) * dh) ** 2n, 'the identity fails at d = ' + d);
  need(isSquare(df) === isSquare(BigInt(d + 1)), 'square test disagrees at d = ' + d);
  const show = (n) => (n.toString().length <= 30 ? n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '{,}') : n.toString().length + ' digits');
  discRows.push([String(d), String(l), String(d + 1) + (isSquare(BigInt(d + 1)) ? ' $=' + Math.round(Math.sqrt(d + 1)) + '^2$' : ''), show(dh), show(df), isSquare(df) ? 'square' : 'not a square']);
}
rows('DiscRows', discRows);

/* ======================================================================= the theorem, re-run */
const SCR = fs.mkdtempSync(path.join(os.tmpdir(), 'erdos290-paper-'));
fs.cpSync(LEG, SCR, { recursive: true });
const t0 = Date.now();
const th = cp.spawnSync('node', ['theorem.js'], { cwd: SCR, maxBuffer: 1 << 26 });
const thOut = String(th.stdout) + String(th.stderr);
need(th.status === 0 && /ALL PASS/.test(thOut), 'theorem.js did not reach ALL PASS:\n' + thOut.slice(-800));
def('TheoremSecs', String(Math.round((Date.now() - t0) / 1000)));
def('TheoremChecks', String((thOut.match(/^\s+ok\s+/gm) || []).length));
const thFals = (thOut.match(/ok\s+FALSIFIER/g) || []).length;
need(thFals === 3, 'expected three planted falsifiers to fire, saw ' + thFals);
def('TheoremFalsifiers', String(thFals));
const thDeg = /line \(3\):.*all (\d+) degrees/.exec(thOut), thMax = /at every even d <= (\d+)/.exec(thOut), thLaw = /\{even d <= (\d+) : d\+1 square\}/.exec(thOut);
need(thDeg && thMax && thLaw, 'theorem.js output no longer names its sweep bounds');
def('TheoremDegrees', thDeg[1]); def('TheoremMaxD', thMax[1]); def('TheoremLawMaxD', thLaw[1]);
need(/discExact \(CRT\/Hadamard\) agrees with galois8\.js discriminant/.test(thOut) && /even d <= 20/.test(thOut), 'the two-discriminant cross-check is gone');
/* the lifted kernel, re-run: irreducibility witnesses and the sensitivity counts */
const kr = cp.spawnSync('node', ['kernel.js'], { cwd: SCR, maxBuffer: 1 << 26 });
const krOut = String(kr.stdout) + String(kr.stderr);
need(kr.status === 0 && /ALL PASS/.test(krOut), 'kernel.js did not reach ALL PASS:\n' + krOut.slice(-800));
const wit = /irreducibility witnesses \(d:p\) — (.*)$/m.exec(krOut);
need(wit, 'kernel.js no longer prints its witnesses');
const witPairs = wit[1].trim().split(/\s+/).map((s) => s.split(':'));
const witNone = witPairs.filter((p) => p[1] === 'NONE').map((p) => Number(p[0]));
need(JSON.stringify(witNone) === JSON.stringify([8, 24, 48]), 'the witnessless set is not {8, 24, 48}');
def('WitnessCount', String(witPairs.length - witNone.length)); def('WitnessMaxP', String(Math.max(...witPairs.filter((p) => p[1] !== 'NONE').map((p) => Number(p[1])))));
const sens = /d0 = 122\/500\/1000 → (\d+)\/(\d+)\/(\d+)/.exec(krOut);
need(sens, 'kernel.js no longer prints the sensitivity counts');
def('SensOne', sens[1]); def('SensTwo', sens[2]); def('SensThree', sens[3]);
def('KernelChecks', String((krOut.match(/^\s+ok\s+/gm) || []).length));
def('KernelFalsifiers', String((krOut.match(/ok\s+FALSIFIER/g) || []).length));
/* the blind k = 6 instance (pattern-check.js predates the proof and is kept as a confirmation) */
const pc = cp.spawnSync('node', ['pattern-check.js'], { cwd: SCR, maxBuffer: 1 << 26 });
const pcOut = String(pc.stdout) + String(pc.stderr);
need(pc.status === 0 && /ALL PASS/.test(pcOut), 'pattern-check.js did not reach ALL PASS:\n' + pcOut.slice(-800));
const pcDigits = /disc\(f_168\): (\d+) digits/.exec(pcOut), pcCtl = /(\d+) non-member controls/.exec(pcOut), pcRange = /every even non-member in (\d+)\.\.(\d+) certified NONSQUARE/.exec(pcOut);
need(pcDigits && pcCtl && pcRange && /PREDICTION d=168 \(k=6\): disc\(f_168\) is a PERFECT SQUARE/.test(pcOut), 'pattern-check.js output changed shape');
def('PatternDigits', int(pcDigits[1])); def('PatternControls', pcCtl[1]); def('PatternFrom', pcRange[1]); def('PatternTo', pcRange[2]);
def('PatternSecs', String(Math.round(Number((/disc\(f_168\): \d+ digits, (\d+) ms/.exec(pcOut) || [0, 0])[1]) / 1000)));
fs.rmSync(SCR, { recursive: true, force: true });

/* the lean fork's battery */
const lb = cp.spawnSync('node', ['tools/erdos290-lean-battery.js'], { cwd: ROOT, maxBuffer: 1 << 26 });
const lbOut = String(lb.stdout) + String(lb.stderr);
const lbm = /(\d+) pass, (\d+) fail/.exec(lbOut);
need(lb.status === 0 && lbm && Number(lbm[2]) === 0, 'the lean battery did not pass clean');
def('LeanPass', lbm[1]);
const lbMaxL = /l = 1\.\.(\d+)/.exec(lbOut);
need(lbMaxL, 'the lean battery no longer states its enumeration range');
def('LeanMaxL', lbMaxL[1]);

/* ======================================================================= the bracket */
{ /* calibration: the assembly must reproduce the cited record's last point to every digit */
  const saved = extLs.map((l) => [l, EXACT.get(l)]);
  for (const l of extLs) EXACT.delete(l);
  const b60 = bracket(citedL);
  need(Number(dec(b60.lo, 12, 'floor')) === P60.lo && Number(dec(b60.hi, 12, 'ceil')) === P60.hi,
    'the bracket assembly does not reproduce the cited l = 60 record point');
  for (const [l, v] of saved) EXACT.set(l, v);
}
const BX = bracket(Lmax), INV = invOf(BX);
const B60 = bracket(citedL), INV60 = invOf(B60);
const B30 = bracket(30), INV30 = invOf(B30);
def('CLo', dec(BX.lo, 12, 'floor')); def('CHi', dec(BX.hi, 12, 'ceil'));
def('CWidth', sci(Q.toDouble(sub(BX.hi, BX.lo)), 3));
def('CWidthSixty', sci(Q.toDouble(sub(B60.hi, B60.lo)), 3));
def('CWidthThirty', sci(Q.toDouble(sub(B30.hi, B30.lo)), 3));
def('WidthGainPct', (100 * (1 - Q.toDouble(sub(BX.hi, BX.lo)) / Q.toDouble(sub(B60.hi, B60.lo)))).toFixed(0) + '\\%');
def('WidthFactorSixty', (Q.toDouble(sub(B60.hi, B60.lo)) / Q.toDouble(sub(BX.hi, BX.lo))).toFixed(1));
def('InvLo', dec(INV.lo, 12, 'floor')); def('InvHi', dec(INV.hi, 12, 'ceil'));
const invAgreed = agreedDigits(INV.lo, INV.hi, 12), inv60Agreed = agreedDigits(INV60.lo, INV60.hi, 12), inv30Agreed = agreedDigits(INV30.lo, INV30.hi, 12);
need(invAgreed === 3, 'the paper says three unconditional digits; the bracket gives ' + invAgreed);
need(inv60Agreed === 2, 'the paper says two digits at the cited horizon; the record gives ' + inv60Agreed);
def('InvAgreed', String(invAgreed)); def('InvSixtyAgreed', String(inv60Agreed)); def('InvThirtyAgreed', String(inv30Agreed));
def('InvPrefix', dec(INV.lo, 12, 'floor').slice(0, 2 + invAgreed));
def('InvSixtyPrefix', dec(INV60.lo, 12, 'floor').slice(0, 2 + inv60Agreed));
def('InvSixtyLo', dec(INV60.lo, 12, 'floor')); def('InvSixtyHi', dec(INV60.hi, 12, 'ceil'));
def('CSixtyLo', dec(B60.lo, 12, 'floor')); def('CSixtyHi', dec(B60.hi, 12, 'ceil'));
def('CThirtyLo', dec(B30.lo, 12, 'floor')); def('CThirtyHi', dec(B30.hi, 12, 'ceil'));
def('InvThirtyLo', dec(INV30.lo, 12, 'floor')); def('InvThirtyHi', dec(INV30.hi, 12, 'ceil'));
def('InvWidth', sci(Q.toDouble(sub(INV.hi, INV.lo)), 3));
def('InvHiFour', dec(INV.hi, 4, 'ceil')); def('InvLoThree', dec(INV.lo, 3, 'floor'));
need(Number(dec(INV.lo, 3, 'floor')) < Number(dec(INV.lo, 12, 'floor')), 'the three-decimal floor is not strictly below the lower end');
/* the other endpoint of Theorem 8: 1/(2c) decreases in c, so the certified LOWER end of c feeds it */
const TWO = R(2n, 1n);
def('TwoCHi', dec(div(ONE, mul(TWO, BX.lo)), 12, 'ceil'));
def('TwoCSixtyHi', dec(div(ONE, mul(TWO, B60.lo)), 12, 'ceil'));
/* van Doorn's published pair, QUOTED from Theorem 8 and Lemma 32 of arXiv:2411.03073 — never derived */
const VD = { lo: 0.54, hi: 0.61, clo: 0.82, chi: 0.85 };
need(Number(dec(INV.lo, 12, 'floor')) > VD.lo && Number(dec(div(ONE, mul(TWO, BX.lo)), 12, 'ceil')) < VD.hi, 'the bracket no longer sharpens both published endpoints');
need(cmp(BX.lo, R(82n, 100n)) > 0 && cmp(BX.hi, R(85n, 100n)) < 0, 'the bracket left Lemma 32\'s range');
def('VDLo', VD.lo.toFixed(2)); def('VDHi', VD.hi.toFixed(2)); def('VDCLo', VD.clo.toFixed(2)); def('VDCHi', VD.chi.toFixed(2));
def('VDWidth', (VD.hi - VD.lo).toFixed(2));
def('NewWidth', (Number(dec(div(ONE, mul(TWO, BX.lo)), 12, 'ceil')) - Number(dec(INV.lo, 12, 'floor'))).toFixed(4));
/* 1/(1+c) from Lemma 32's own range, so "two decimals" is derived, not asserted */
def('VDInvLo', dec(div(ONE, add(ONE, R(85n, 100n))), 4, 'floor')); def('VDInvHi', dec(div(ONE, add(ONE, R(82n, 100n))), 4, 'ceil'));
def('VDTwoCHi', dec(div(ONE, mul(TWO, R(82n, 100n))), 4, 'ceil'));

/* the components: log 2 (odd d), the pinned even part, the unpinned tail */
def('LogTwoLo', dec(L2.lo, 15, 'floor')); def('LogTwoHi', dec(L2.hi, 15, 'ceil'));
def('LogTwoShare', (100 * Q.toDouble(L2.lo) / Q.toDouble(BX.hi)).toFixed(0) + '\\%');
const noTail = { bounds: () => ({ A: ZERO, B: ZERO }) }, fullTail = { bounds: () => ({ A: ONE, B: ONE }) };
const P0 = bracket(Lmax, noTail), P1 = bracket(Lmax, fullTail);
const evenPinned = sub(P0.lo, L2.lo);
need(cmp(sub(P0.hi, L2.hi), evenPinned) === 0, 'the pinned even part is not a point');
def('EvenPinned', dec(evenPinned, 12, 'floor'));
const TLo = sub(P1.lo, P0.lo), THi = sub(P1.hi, P0.hi);
def('TailLo', dec(TLo, 12, 'floor')); def('TailHi', dec(THi, 12, 'ceil')); def('TailWeight', sci(Q.toDouble(THi), 3));
def('TailApprox', sci(1 / (4 * Lmax), 3));
need(Math.abs(Q.toDouble(sub(sub(BX.hi, BX.lo), THi)) - Q.toDouble(sub(L2.hi, L2.lo))) < 1e-30, 'the width is not the tail weight plus the log 2 slack');

/* the horizon table */
const tableLs = [30, citedL, 90, 120, 190, 250, Lmax].filter((v, i, a) => a.indexOf(v) === i && v <= Lmax);
const horizonRows = [];
for (const L of tableLs) {
  const b = bracket(L), iv = invOf(b);
  horizonRows.push([String(L), String(2 * L), dec(b.lo, 12, 'floor'), dec(b.hi, 12, 'ceil'), sci(Q.toDouble(sub(b.hi, b.lo)), 2),
    dec(iv.lo, 12, 'floor'), dec(iv.hi, 12, 'ceil'), String(agreedDigits(iv.lo, iv.hi, 12))]);
}
rows('HorizonRows', horizonRows);

/* where the third digit closed: the smallest horizon at which both ends of 1/(1+c) agree to
   three decimals (binary search — the bracket nests, so the agreed prefix is monotone) */
const agreedAt = (L) => { const iv = invOf(bracket(L)); return agreedDigits(iv.lo, iv.hi, 12); };
let loL = citedL, hiL = Lmax;
need(agreedAt(loL) < 3 && agreedAt(hiL) >= 3, 'the third digit did not close inside the extension');
while (hiL - loL > 1) { const mid = (loL + hiL) >> 1; if (agreedAt(mid) >= 3) hiL = mid; else loL = mid; }
def('ThirdDigitL', String(hiL)); def('ThirdDigitD', String(2 * hiL));
{ const iv = invOf(bracket(hiL)); def('ThirdDigitLo', dec(iv.lo, 12, 'floor')); def('ThirdDigitHi', dec(iv.hi, 12, 'ceil')); }
{ const iv = invOf(bracket(hiL - 1)); def('ThirdDigitPrevLo', dec(iv.lo, 12, 'floor')); def('ThirdDigitPrevHi', dec(iv.hi, 12, 'ceil')); }

/* ======================================================================= the conditional value */
const CS = K.conditionalCStar(120, 80);
const condDigits = NARROW.conditionalEnclosure34.lo.length - 2;
need(dec(CS.lo, condDigits, 'floor') === NARROW.conditionalEnclosure34.lo && dec(CS.hi, condDigits, 'ceil') === NARROW.conditionalEnclosure34.hi,
  'the lifted kernel no longer reproduces the recorded ' + condDigits + '-digit conditional enclosure');
def('CondDigits', String(condDigits)); def('CondLo', NARROW.conditionalEnclosure34.lo); def('CondHi', NARROW.conditionalEnclosure34.hi);
def('CondInv', dec(div(ONE, add(ONE, CS.hi)), 18, 'floor'));
need(cmp(BX.lo, CS.lo) <= 0 && cmp(CS.hi, BX.hi) <= 0, 'the conditional value left the unconditional bracket');
/* the first assumed degree of that enclosure, read off its width (the report builder's detection) */
const allowW = (l) => mul(R(1n, 2n ** BigInt(l) * fact(l)), W(l));
const condFirstL = (() => { const wid = sub(CS.hi, CS.lo); let acc = ZERO;
  for (let l = 120; l >= 1; l--) { if (EXC.has(l)) continue; const nxt = add(acc, allowW(l)); if (cmp(nxt, wid) > 0) return l + 1; acc = nxt; } return null; })();
need(condFirstL === 31, 'the lifted kernel\'s assumption no longer begins at l = 31');
def('CondFirstL', String(condFirstL)); def('CondFirstD', String(2 * condFirstL));
def('CondAllowFirst', sci(Q.toDouble(allowW(condFirstL)), 2));
def('CondCap', String(Math.floor(-Math.log10(Q.toDouble(sub(CS.hi, CS.lo))))));

/* the 110-digit expansion at the live horizon: the precision tool, run from a path-patched copy */
const PR = fs.mkdtempSync(path.join(os.tmpdir(), 'erdos290-prec-'));
let src = fs.readFileSync(path.join(ROOT, 'tools', 'erdos290-cstar-precision.js'), 'utf8');
const n0 = (src.match(/path\.join\(ROOT, 'outreach', 'b-oeis-/g) || []).length;
need(n0 === 2 && src.includes("const ROOT = path.resolve(__dirname, '..');"), 'the precision tool changed shape; the scratch patch no longer applies');
src = src.replace("const ROOT = path.resolve(__dirname, '..');", 'const ROOT = ' + JSON.stringify(ROOT) + '; const OUTDIR = ' + JSON.stringify(PR) + ';')
  .replace(/path\.join\(ROOT, 'outreach', 'b-oeis-/g, "path.join(OUTDIR, 'b-oeis-");
fs.writeFileSync(path.join(PR, 'cstar.js'), src);
const pr = cp.spawnSync('node', ['cstar.js', '110'], { cwd: PR, maxBuffer: 1 << 26 });
const prOut = String(pr.stdout) + String(pr.stderr);
need(pr.status === 0, 'the precision tool refused:\n' + prOut.slice(-800));
const prHor = /certified horizon l <= (\d+) \(even d <= (\d+)\); assumption enters at l = (\d+)/.exec(prOut);
const prC = /c\* digits agreed: (\d+)\s+c\* = (0\.\d+)/.exec(prOut), prI = /1\/\(1\+c\*\) digits agreed: (\d+)\s+1\/\(1\+c\*\) = (0\.\d+)/.exec(prOut);
const prCal = /agree to (\d+) digits/.exec(prOut), prCut = /cutoff agreement N=(\d+) vs (\d+)/.exec(prOut);
need(prHor && prC && prI && prCal && prCut, 'the precision tool\'s output changed shape');
need(Number(prHor[1]) === Lmax && Number(prHor[3]) === Lmax + 1, 'the precision tool is not at the record\'s horizon');
need(prC[2].startsWith(NARROW.conditionalEnclosure34.lo.slice(0, 30)), 'the 110-digit c* disagrees with the 34-digit enclosure');
need(prI[2].startsWith(dec(div(ONE, add(ONE, CS.hi)), 18, 'floor').slice(0, 17)), 'the 110-digit 1/(1+c*) disagrees with the kernel');
def('CStarDigits', prC[1]); def('CZeroDigits', prI[1]); def('PrecCalib', prCal[1]); def('PrecCutoffA', prCut[1]); def('PrecCutoffB', prCut[2]);
def('CStarForty', prC[2].slice(0, 42)); def('CZeroForty', prI[2].slice(0, 42));
const grouped = (s) => s.slice(2).replace(/(\d{10})(?=\d)/g, '$1\\,');
def('CZeroFull', '0.' + grouped(prI[2])); def('CStarFull', '0.' + grouped(prC[2]));
/* the same digits in two rows of groups, for a display that fits the measure */
const split = (s) => { const g = s.slice(2).match(/\d{1,10}/g); return [g.slice(0, 6).join('\\,'), g.slice(6).join('\\,')]; };
def('CZeroFullA', split(prI[2])[0]); def('CZeroFullB', split(prI[2])[1]); def('CStarFullA', split(prC[2])[0]); def('CStarFullB', split(prC[2])[1]);
for (const f of ['b-oeis-c0.txt', 'b-oeis-cstar.txt']) {
  need(fs.readFileSync(path.join(PR, f)).equals(fs.readFileSync(path.join(ROOT, 'outreach', f))), 'outreach/' + f + ' is stale against the live horizon');
}
def('BfileTerms', String(fs.readFileSync(path.join(ROOT, 'outreach', 'b-oeis-c0.txt'), 'utf8').trim().split('\n').length));
fs.rmSync(PR, { recursive: true, force: true });
/* failure semantics: a first failure of the assumption at d0 = 2(Lmax+1) */
const failD = 2 * (Lmax + 1);
const failW = R(1n, BigInt(failD) * BigInt(failD + 1));
const deriv = div(ONE, mul(add(ONE, BX.lo), add(ONE, BX.lo)));
def('FailD', String(failD)); def('FailC', sci(Q.toDouble(failW), 2)); def('InvDeriv', dec(deriv, 4, 'ceil')); def('FailInv', sci(Q.toDouble(mul(deriv, failW)), 2));

/* ======================================================================= the fourth digit */
/* (i) the δ-window that would pin it at THIS horizon: the cell the conditional value sits in */
const cellLo = R(BigInt(dec(div(ONE, add(ONE, CS.hi)), 4, 'floor').replace('0.', '')), 10000n);
const cellHi = add(cellLo, R(1n, 10000n));
def('CellLo', dec(cellLo, 4, 'floor')); def('CellHi', dec(cellHi, 4, 'floor'));
const Bmax = div(sub(sub(div(ONE, cellLo), ONE), P0.hi), THi);     /* c_hi' ≤ 1/cellLo − 1 */
const Amin = div(sub(sub(div(ONE, cellHi), ONE), P0.lo), TLo);     /* c_lo' > 1/cellHi − 1 */
need(cmp(Amin, ZERO) > 0 && cmp(Amin, Bmax) < 0 && cmp(Bmax, ONE) < 0, 'the fourth-digit window is empty or trivial');
def('WindowA', dec(Amin, 4, 'ceil')); def('WindowB', dec(Bmax, 4, 'floor'));
const LIM = TAIL.limitEnclosure(Q, 40);
def('DeltaLimit', dec(LIM.lo, 7, 'floor'));
need(cmp(LIM.hi, Bmax) < 0 && cmp(LIM.lo, Amin) > 0, 'the limit 1 − e^{−1/2} is not inside the window');
def('WindowMarginHi', dec(sub(Bmax, LIM.hi), 4, 'floor')); def('WindowMarginLo', dec(sub(LIM.lo, Amin), 4, 'floor'));
/* (ii) the horizon brute force would need, IF every further degree closes as the assumption
   predicts (hyperoctahedral, index-2 at 4k(k+1)): fixed-point BigInt, outward at every step */
{
  const SC = 10n ** 60n;
  const fl = (a) => { const q = a.n * SC; return q >= 0n ? q / a.d : -((-q + a.d - 1n) / a.d); };
  const ce = (a) => { const q = a.n * SC; return q >= 0n ? (q + a.d - 1n) / a.d : -(-q / a.d); };
  let pinLo = fl(sub(P0.lo, L2.lo)), pinHi = ce(sub(P0.hi, L2.hi));
  let partial = 0n; for (let l = 1; l <= Lmax; l++) partial += ce(W(l));
  const l2lo = fl(L2.lo), l2hi = ce(L2.hi);
  const oneMinusLog2Hi = SC - l2lo;
  let found = null, widthAt = null;
  for (let L = Lmax + 1; L <= 20000 && !found; L++) {
    /* δ_hyp(L) = 1 − Σ_{i≤L} (−1)^i/(2^i i!), truncated at i = 80 with the first omitted term as error */
    let s = 0n, f = 1n, term = SC, i = 0;
    const top = Math.min(L, 80);
    for (i = 0; i <= top; i++) { if (i > 0) f *= BigInt(i); term = SC / (2n ** BigInt(i) * f); s += (i % 2 === 0) ? term : -term; }
    const err = top < L ? SC / (2n ** BigInt(top + 1) * f * BigInt(top + 1)) + 1n : 1n;
    let dLo = SC - s - err, dHi = SC - s + err;
    if (isExcL(L)) { const al = (2n ** BigInt(L) * fact(L)); dLo -= (SC + al - 1n) / al; dHi -= SC / al; }
    const w = W(L); const wLo = fl(w), wHi = ce(w);
    pinLo += (dLo * wLo) / SC; pinHi += (dHi * wHi) / SC + 1n;
    partial += wHi;
    const tailHi = oneMinusLog2Hi - partial + BigInt(L) * 2n;           /* outward slack for the partial's rounding */
    const cLo = l2lo + pinLo, cHi = l2hi + pinHi + tailHi;
    const ivLo = (SC * SC) / (SC + cHi), ivHi = (SC * SC + SC + cLo - 1n) / (SC + cLo);
    const a = ivLo.toString().padStart(61, '0'), b = ivHi.toString().padStart(61, '0');
    let agreed = 0; for (let k = 1; k <= 12; k++) { if (a[k] === b[k]) agreed++; else break; }
    if (agreed >= 4) { found = L; widthAt = Number(cHi - cLo) / 1e60; }
  }
  need(found, 'no horizon under 20000 pins the fourth digit under the assumption');
  def('FourthL', int(found)); def('FourthD', int(2 * found)); def('FourthWidth', sci(widthAt, 2));
  def('FourthCost', int(Math.round(Math.pow(found / Lmax, 4))));
}

/* ======================================================================= the figure data */
{
  const pts = [];
  for (let L = 30; L <= Lmax; L += (L < citedL ? 5 : 5)) {
    const b = bracket(L), iv = invOf(b);
    pts.push({ L, cLo: Number(dec(b.lo, 12, 'floor')), cHi: Number(dec(b.hi, 12, 'ceil')), invLo: Number(dec(iv.lo, 12, 'floor')), invHi: Number(dec(iv.hi, 12, 'ceil')) });
  }
  if (pts[pts.length - 1].L !== Lmax) { const b = bracket(Lmax), iv = invOf(b); pts.push({ L: Lmax, cLo: Number(dec(b.lo, 12, 'floor')), cHi: Number(dec(b.hi, 12, 'ceil')), invLo: Number(dec(iv.lo, 12, 'floor')), invHi: Number(dec(iv.hi, 12, 'ceil')) }); }
  fs.mkdirSync(FIG, { recursive: true });
  fs.writeFileSync(path.join(FIG, 'erdos290-squeeze.json'), JSON.stringify({
    generatedBy: 'tools/paper-numbers/erdos290.js @ git ' + git,
    what: 'the certified bracket for c and for 1/(1+c) as a function of the knowledge horizon l, every point the bracket module re-assembled in exact rationals (12-digit outward decimals)',
    citedL, thirdDigitL: hiL, Lmax, published: { lo: VD.lo, hi: VD.hi }, conditional: Number(dec(div(ONE, add(ONE, CS.hi)), 12, 'floor')), points: pts
  }, null, 1) + '\n');
}

fs.writeFileSync(path.join(OUT, 'erdos290-numbers.tex'), M.join('\n') + '\n');
console.log('wrote paper/tex/erdos290-numbers.tex (' + (M.length - 1) + ' macros) and paper/tex/fig/erdos290-squeeze.json');
