#!/usr/bin/env node
/* paper-numbers/erdos1038-sup.js — every number the pre-paper
   paper/tex/erdos1038-sup.tex quotes, read from the records that decided it and
   written as LaTeX macros to paper/tex/erdos1038-sup-numbers.tex.

   Records read:
     certs/sublevel-tao179.json          the per-degree theorem ladder, the sweeps, the
                                         cubic champion and the quintic peak (the campaign)
     instruments/sublevel/measure.js     the certifier, re-run here for the witness, the
                                         calibration rows and the two family curves — exactly
                                         as tools/build-report-erdos1038-sup.js re-runs them
                                         at every page build (nothing on the page is remembered)
     instruments/sublevel/battery.js     the green/red battery, run live (about 0.1 s)
     tools/run-sublevel-campaign.js      the budgets each degree was given (read from source)
     legacy/research/challenges/lane/laneb-lemniscate/verify.js
                                         the thirty-decimal verifier of the Darvas–Peng–Tao
                                         constant, staged against instruments/interval and run
                                         live (about 0.1 s), as tools/build-report-lemniscate.js
                                         does at every build; its CLAIMS table is read from source
   The paper \inputs the macro file, so it cannot quote a number the machine did not
   record; a record that no longer says what a sentence needs makes this refuse
   (need()), as tools/build-paper-numbers.js does for the Elsevier manuscripts.
   The one figure is drawn from the curve points this script writes
   (paper/tex/fig/erdos1038-sup-curves.json) by paper-numbers/erdos1038-sup-fig.py.

   usage: node tools/paper-numbers/erdos1038-sup.js                                 MIT */
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const cp = require('child_process');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex');
const FIG = path.join(OUT, 'fig');
const M = require(path.join(ROOT, 'instruments', 'sublevel', 'measure.js'));
const Q = require(path.join(ROOT, 'instruments', 'interval', 'rational.js'));

const die = (m) => { console.error('PAPER NUMBERS REFUSED (erdos1038-sup): ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
/* a small or large number in scientific form, as math: $1.9\times10^{4}$ */
const sci = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return '$' + m[1] + '\\times10^{' + Number(m[2]) + '}$'; };
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();
const WORD = { 1: 'One', 2: 'Two', 3: 'Three', 4: 'Four', 5: 'Five', 6: 'Six', 7: 'Seven', 8: 'Eight', 9: 'Nine', 10: 'Ten' };
/* a wall time in seconds: two decimals below a second, one above */
const secs = (ms) => (ms < 1000 ? dec(ms / 1000, 2) : dec(ms / 1000, 1));

/* exact rational -> decimal string with directed rounding (lo floors, hi ceils) */
function decQ(q, d, dir) {
  const neg = q.n < 0n;
  const num = neg ? -q.n : q.n, den = q.d;
  const scale = 10n ** BigInt(d);
  let t = (num * scale) / den;                    /* truncation of the magnitude */
  const exact = (num * scale) % den === 0n;
  /* outward: a lower end rounds toward -inf, an upper end toward +inf */
  if (!exact && ((dir === 'hi' && !neg) || (dir === 'lo' && neg))) t += 1n;
  const s = t.toString().padStart(d + 1, '0');
  return (neg ? '-' : '') + s.slice(0, s.length - d) + '.' + s.slice(s.length - d);
}
const encl = (r, d) => '[' + decQ(r.lo, d, 'lo') + ',\\ ' + decQ(r.hi, d, 'hi') + ']';

const MAC = ['%% generated by tools/paper-numbers/erdos1038-sup.js from certs/sublevel-tao179.json, the sublevel instrument, the sublevel battery and the lemniscate verifier (run live) — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); MAC.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));
def('RepoCommit', git);

/* ====================================================== the campaign record */
const R = JSON.parse(fs.readFileSync(path.join(ROOT, 'certs', 'sublevel-tao179.json'), 'utf8'));
need(R.theorems && R.sweeps && R.witness && R.cubicChampion && R.quinticPeak && R.meta, 'the record lost one of its sections');
def('RecDate', R.meta.date); def('RecGit', R.meta.git);
def('RecMinutes', dec(R.meta.ms / 60000, 1));

const s8 = M.twoSqrtTwo(60);
need(Q.cmp(s8.lo, s8.hi) < 0, 'twoSqrtTwo is not an interval');
def('TwoSqrtTwo', decQ(s8.lo, 10, 'lo'));           /* 2.8284271247, the first ten decimals */
def('TwoSqrtTwoD', decQ(s8.lo, 7, 'lo'));
const S2 = Q.toDouble(s8.lo);

/* --- the theorems: odd degrees strict, even degrees localized, deg 9 refused --- */
const TH = Object.entries(R.theorems).map(([tag, v]) => Object.assign({ tag }, v));
const done = TH.filter((t) => !t.failed).sort((a, b) => a.n - b.n);
const failed = TH.filter((t) => t.failed);
const odd = done.filter((t) => t.n % 2 === 1), even = done.filter((t) => t.n % 2 === 0);
need(odd.map((t) => t.n).join() === '3,5,7', 'the odd-degree ladder is not 3, 5, 7');
need(even.map((t) => t.n).join() === '4,6,8', 'the even-degree ladder is not 4, 6, 8');
const TODD = odd[0].T, TEVEN = even[0].T;
need(odd.every((t) => t.T === TODD) && even.every((t) => t.T === TEVEN), 'the thresholds differ within a parity');
const qOf = (s) => { const [n, d] = s.split('/'); return Q.R(BigInt(n), BigInt(d)); };
const tOdd = qOf(TODD), tEven = qOf(TEVEN);
need(Q.cmp(tOdd, s8.lo) < 0, 'the odd threshold is not below 2*sqrt(2)');
need(Q.cmp(tEven, s8.hi) > 0, 'the even threshold is not above 2*sqrt(2)');
def('TOddFrac', TODD.replace('/', '/')); def('TOdd', decQ(tOdd, 2, 'lo'));
def('TEvenFrac', TEVEN); def('TEven', decQ(tEven, 5, 'lo'));
need(decQ(tOdd, 2, 'lo') === '2.82' && (tOdd.n * 100n) % tOdd.d === 0n, 'the odd threshold is not exactly 2.82');
need((tEven.n * 100000n) % tEven.d === 0n, 'the even threshold is not an exact five-decimal number');
def('GapOdd', dec(S2 - Q.toDouble(tOdd), 4));                 /* 2*sqrt(2) - 2.82 */
def('GapOddSci', sci(S2 - Q.toDouble(tOdd), 2));
def('SlackEven', sci(Q.toDouble(tEven) - S2, 2));              /* 2.82845 - 2*sqrt(2) */
def('NTheorems', String(done.length)); def('NTheoremsWord', WORD[done.length].toLowerCase());
def('OddDegrees', odd.map((t) => t.n).join(', ')); def('EvenDegrees', even.map((t) => t.n).join(', '));
def('MaxDegree', String(done[done.length - 1].n));
let totalBoxes = 0, totalLeaves = 0, totalMs = 0;
for (const t of done) {
  need(t.explored > 0 && t.leaves > 0 && t.maxDepth > 0 && t.ms >= 0, 'theorem ' + t.tag + ' has no certificate counts');
  const w = WORD[t.n];
  def('Boxes' + w, int(t.explored)); def('Leaves' + w, int(t.leaves)); def('Depth' + w, String(t.maxDepth));
  def('Seconds' + w, secs(t.ms));
  totalBoxes += t.explored; totalLeaves += t.leaves; totalMs += t.ms;
}
def('TotalBoxes', int(totalBoxes)); def('TotalLeaves', int(totalLeaves)); def('TotalSeconds', dec(totalMs / 1000, 0));
rows('TheoremRows', done.map((t) => [
  '$' + t.n + '$',
  t.n % 2 ? '$\\sup_{' + t.n + '} < ' + decQ(tOdd, 2, 'lo') + '$' : '$\\sup_{' + t.n + '} \\in [2\\sqrt2,\\ ' + decQ(tEven, 5, 'lo') + ']$',
  '$' + t.T.replace('/', '/') + '$',
  int(t.explored), int(t.leaves), String(t.maxDepth),
  secs(t.ms),
  t.n % 2 ? 'strict' : 'localized'
]));
/* the refused degree, with the budget it was given (read from the campaign source) */
const campaignSrc = fs.readFileSync(path.join(ROOT, 'tools', 'run-sublevel-campaign.js'), 'utf8');
const budgets = {};
for (const m of campaignSrc.matchAll(/run\((\d+),\s*T_(ODD|EVEN),\s*'[^']*',\s*\{\s*maxDepth:\s*(\d+),\s*maxBoxes:\s*(\d+)\s*\}\)/g)) budgets[Number(m[1])] = { depth: Number(m[3]), boxes: Number(m[4]) };
for (const t of done) need(budgets[t.n] && t.explored <= budgets[t.n].boxes && t.maxDepth <= budgets[t.n].depth, 'theorem ' + t.tag + ' exceeds the budget the campaign source gives it');
need(failed.length === 1 && failed[0].n === 9 && /budget/.test(failed[0].failed), 'the record no longer says that degree 9 alone was refused on its box budget');
def('RefusedDegree', String(failed[0].n)); def('RefusedWhy', failed[0].failed.replace(/_/g, '\\_'));
def('RefusedMinutes', dec(failed[0].ms / 60000, 1));
def('RefusedBudgetBoxes', int(budgets[9].boxes)); def('RefusedBudgetDepth', String(budgets[9].depth));
rows('BudgetRows', [3, 5, 7, 4, 6, 8, 9].map((n) => ['$' + n + '$', int(budgets[n].boxes), String(budgets[n].depth)]));

/* --- the witness and the calibrations, re-certified now --- */
const wit = M.sublevelMeasure([{ n: 1n, m: 1 }, { n: -1n, m: 1 }], 1n);
need(Q.cmp(wit.lo, s8.lo) <= 0 && Q.cmp(s8.hi, wit.hi) <= 0, 'the witness no longer encloses 2*sqrt(2)');
need(R.witness.measure.lo === wit.lo.n + '/' + wit.lo.d && R.witness.measure.hi === wit.hi.n + '/' + wit.hi.d, 'the live witness enclosure differs from the record');
def('WitnessEnclosure', encl(wit, 12)); def('WitnessWidth', sci(wit.hiD - wit.loD, 1));
def('WitnessLoFrac', wit.lo.n + '/' + wit.lo.d); def('WitnessHiFrac', wit.hi.n + '/' + wit.hi.d);
const CAL = [
  ['$x^2-1$', [{ n: 1n, m: 1 }, { n: -1n, m: 1 }], '$2\\sqrt2$'],
  ['$x^2$', [{ n: 0n, m: 2 }], '$2$'],
  ['$x$', [{ n: 0n, m: 1 }], '$2$'],
  ['$(x-1)^2$', [{ n: 1n, m: 2 }], '$2$'],
  ['$(x^2-1)^2$', [{ n: 1n, m: 2 }, { n: -1n, m: 2 }], '$2\\sqrt2$']
];
rows('CalibrationRows', CAL.map(([nm, roots, exact]) => {
  const r = M.sublevelMeasure(roots, 1n);
  const target = exact === '$2$' ? { lo: Q.R(2n), hi: Q.R(2n) } : s8;
  need(Q.cmp(r.lo, target.lo) <= 0 && Q.cmp(target.hi, r.hi) <= 0, 'calibration ' + nm + ' no longer encloses its exact value');
  return [nm, '$' + encl(r, 12) + '$', exact, String(r.boundaryRoots)];
}));

/* --- the sweeps and the two refined champions --- */
const SW = Object.entries(R.sweeps).map(([k, v]) => Object.assign({ key: k }, v));
let sweepConfigs = 0;
rows('SweepRows', SW.map((s) => {
  const m = /n=(\d+) d=(\d+)/.exec(s.key); need(m, 'sweep key ' + s.key);
  const c = s.champion; sweepConfigs += s.configs;
  const gcd = (a, b) => (b ? gcd(b, a % b) : a);
  const roots = c.roots.split(',').map((x) => { const v = Number(x), d = Number(m[2]); const g = gcd(Math.abs(v), d); return v % d === 0 ? String(v / d) : (v / g) + '/' + (d / g); });
  need(/^-?\d+\/-?\d+$/.test(c.lo) && /^-?\d+\/-?\d+$/.test(c.hi), 'sweep champion enclosure is not rational: ' + s.key);
  return ['$' + m[1] + '$', '$' + m[2] + '$', int(s.configs), '$(' + roots.join(',\\ ') + ')$', '$[' + decQ(qOf(c.lo), 6, 'lo') + ',\\ ' + decQ(qOf(c.hi), 6, 'hi') + ']$'];
}));
def('SweepConfigs', int(sweepConfigs));
const cc = R.cubicChampion, qp = R.quinticPeak;
need(/201\/256/.test(cc.config) && /905\/1024/.test(qp.config), 'the champion configurations moved');
const ccLive = M.sublevelMeasure([{ n: -256n, m: 1 }, { n: 201n, m: 1 }, { n: 256n, m: 1 }], 256n);
const qpLive = M.sublevelMeasure([{ n: -1024n, m: 2 }, { n: 1024n, m: 2 }, { n: 905n, m: 1 }], 1024n);
need(cc.measure.lo === ccLive.lo.n + '/' + ccLive.lo.d && qp.measure.hi === qpLive.hi.n + '/' + qpLive.hi.d, 'the live champion enclosures differ from the record');
need(ccLive.hiD < qpLive.loD && qpLive.hiD < Q.toDouble(tOdd), 'the champions are not ordered below the odd threshold');
def('CubicRoot', '201/256'); def('CubicRootD', dec(201 / 256, 4));
def('CubicChampion', encl(ccLive, 6)); def('CubicChampionLo', decQ(ccLive.lo, 6, 'lo')); def('CubicChampionHi', decQ(ccLive.hi, 6, 'hi'));
def('QuinticRoot', '905/1024'); def('QuinticRootD', dec(905 / 1024, 4));
def('QuinticPeak', encl(qpLive, 6)); def('QuinticPeakLo', decQ(qpLive.lo, 6, 'lo')); def('QuinticPeakHi', decQ(qpLive.hi, 6, 'hi'));
def('QuinticRuns', String(qpLive.runs.length));
def('GapThreeToTOdd', dec(Q.toDouble(tOdd) - ccLive.hiD, 4)); def('GapFiveToTOdd', dec(Q.toDouble(tOdd) - qpLive.hiD, 4));

/* --- the two family curves, certified point by point (as the page draws them) --- */
const cubicPts = [], quinticPts = [];
for (let k = 64; k <= 128; k++) {
  const r3 = M.sublevelMeasure([{ n: -128n, m: 1 }, { n: BigInt(k), m: 1 }, { n: 128n, m: 1 }], 128n);
  cubicPts.push({ r: k / 128, k, d: 128, lo: r3.loD, hi: r3.hiD, runs: r3.runs.length });
  const r5 = M.sublevelMeasure([{ n: -128n, m: 2 }, { n: 128n, m: 2 }, { n: BigInt(k), m: 1 }], 128n);
  quinticPts.push({ r: k / 128, k, d: 128, lo: r5.loD, hi: r5.hiD, runs: r5.runs.length });
}
/* the transition, resolved: the page refines at 1/1024; here also at 1/4096 so the
   descent is drawn where it is and its run structure is recorded */
for (let k = 3600; k <= 3664; k += 2) {
  const r5 = M.sublevelMeasure([{ n: -4096n, m: 2 }, { n: 4096n, m: 2 }, { n: BigInt(k), m: 1 }], 4096n);
  quinticPts.push({ r: k / 4096, k, d: 4096, lo: r5.loD, hi: r5.hiD, runs: r5.runs.length, gaps: r5.runs.length > 1 ? r5.runs.slice(0, -1).map((a, i) => [a.to, r5.runs[i + 1].from]) : [] });
}
quinticPts.sort((a, b) => a.r - b.r);
const cubicMax = cubicPts.reduce((b, p) => (p.hi > b.hi ? p : b));
const quinticMax = quinticPts.reduce((b, p) => (p.hi > b.hi ? p : b));
need(cubicMax.hi < S2 && quinticMax.hi < S2, 'a family point reached 2*sqrt(2)');
need(cubicMax.hi <= ccLive.hiD + 1e-9, 'the cubic grid beats the recorded champion');
need(quinticMax.hi <= qpLive.hiD + 1e-9, 'the quintic grid beats the recorded peak');
def('CubicGridMaxR', cubicMax.k + '/' + cubicMax.d); def('CubicGridMax', dec(cubicMax.hi + 5e-7, 6));
def('QuinticGridMaxR', quinticMax.k + '/' + quinticMax.d); def('QuinticGridMax', dec(quinticMax.hi + 5e-7, 6));
/* the descent: the last one-run point and the first two-run point on the fine grid */
const fine = quinticPts.filter((p) => p.d === 4096);
let split = -1; for (let i = 1; i < fine.length; i++) if (fine[i - 1].runs === 1 && fine[i].runs === 2) { split = i; break; }
need(split > 0 && fine[split - 1].k === 3620, 'the quintic sublevel set no longer splits right after r = 905/1024 on the fine grid');
const before = fine[split - 1], after = fine[split];
def('SplitBeforeR', before.k + '/' + before.d); def('SplitBeforeV', dec(before.hi + 5e-7, 6));
def('SplitAfterR', after.k + '/' + after.d); def('SplitAfterV', dec(after.hi + 5e-7, 6));
def('SplitGapLo', dec(after.gaps[0][0], 4)); def('SplitGapHi', dec(after.gaps[0][1], 4));
def('SplitGapWidth', dec(after.gaps[0][1] - after.gaps[0][0], 3));
def('SplitDrop', dec(before.hi - after.lo, 3));
const last = fine[fine.length - 1];
def('FineLastR', last.k + '/' + last.d); def('FineLastV', dec(last.hi + 5e-7, 6)); def('FineLastGapWidth', dec(last.gaps[0][1] - last.gaps[0][0], 3));
def('FineStep', '1/4096'); def('FineFrom', fine[0].k + '/' + fine[0].d); def('FineTo', last.k + '/' + last.d);
/* the cubic family splits the same way: the first grid point past the champion with two runs */
const cubicSplit = cubicPts.find((p) => p.r > 201 / 256 && p.runs === 2);
need(cubicSplit && cubicPts.filter((p) => p.r <= 201 / 256).every((p) => p.runs === 1), 'the cubic sublevel set is not one interval up to the champion and two past it');
def('CubicSplitR', cubicSplit.k + '/' + cubicSplit.d); def('CubicSplitV', dec(cubicSplit.hi + 5e-7, 6));
def('CubicEndV', dec(cubicPts[cubicPts.length - 1].hi + 5e-7, 6)); def('QuinticEndV', dec(quinticPts[quinticPts.length - 1].hi + 5e-7, 6));
def('CurvePoints', int(cubicPts.length + quinticPts.length));
/* the infimum side, read from its own record for the one sentence that places the two ends together */
{
  const I = JSON.parse(fs.readFileSync(path.join(ROOT, 'certs', 'erdos1038-inf.json'), 'utf8'));
  need(I.bracket && I.bracket.lower < I.bracket.upper, 'the infimum record has no ordered bracket');
  def('InfBracketLo', String(I.bracket.lower)); def('InfBracketHi', String(I.bracket.upper));
  need(/Darvas/.test(I.independence) && /Wang/.test(I.independence) && /Budala/.test(I.independence), 'the infimum record lost a claimant name');
  MAC.push('%% InfUpperAboveD is defined after the verifier runs');
  global.__infUpper = I.bracket.upper;
}
fs.mkdirSync(FIG, { recursive: true });
fs.writeFileSync(path.join(FIG, 'erdos1038-sup-curves.json'), JSON.stringify({
  what: 'certified sublevel measures of (x^2-1)(x-r) and (x^2-1)^2(x-r), the plotted value the upper endpoint; written by tools/paper-numbers/erdos1038-sup.js',
  git, twoSqrtTwo: S2, cubic: cubicPts, quintic: quinticPts,
  cubicChampion: { r: 201 / 256, lo: ccLive.loD, hi: ccLive.hiD }, quinticPeak: { r: 905 / 1024, lo: qpLive.loD, hi: qpLive.hiD },
  tOdd: Q.toDouble(tOdd)
}, null, 1) + '\n');

/* --- the battery, live --- */
{
  const r = cp.spawnSync('node', [path.join(ROOT, 'instruments', 'sublevel', 'battery.js')], { cwd: ROOT, maxBuffer: 1 << 24 });
  const out = String(r.stdout) + String(r.stderr);
  const m = /ALL PASS\s+\((\d+) checks, (\d+)\/(\d+) falsifiers\)/.exec(out);
  need(r.status === 0 && m && m[2] === m[3], 'the sublevel battery did not pass clean:\n' + out.slice(-500));
  def('BatteryChecks', m[1]); def('BatteryReds', m[2]);
  const g4 = /G4 .*?\[(\d+) boxes, (\d+) ms\]/.exec(out), g5 = /G5 .*?\[(\d+) boxes, (\d+) ms\]/.exec(out);
  need(g4 && g5 && Number(g4[1]) === done.find((t) => t.n === 3).explored && Number(g5[1]) === done.find((t) => t.n === 4).explored, 'the battery re-proof box counts differ from the record');
  def('BatteryMs', String(Number(g4[2]) + Number(g5[2])));
}

/* =========================================== the thirty decimals, verified live */
{
  const VER = path.join(ROOT, 'legacy', 'research', 'challenges', 'lane', 'laneb-lemniscate', 'verify.js');
  const src = fs.readFileSync(VER, 'utf8');
  /* the manuscript's printed values, as the verifier carries them */
  const claims = [...src.matchAll(/\['([^']+)',\s*'(\w+)',\s*'(-?\d+\.\d+)'\]/g)].map((m) => ({ label: m[1].replace(/\s+/g, ' ').trim(), key: m[2], printed: m[3] }));
  need(claims.length === 10 && claims[0].key === 'D' && claims[0].printed.split('.')[1].length === 30, 'the verifier no longer carries the ten printed values with D to 30 decimals first');
  const centres = { q: /const Q0 = '([\d.]+)'/.exec(src)[1], u: /const U0 = '([\d.]+)'/.exec(src)[1], v: /const V0 = '([\d.]+)'/.exec(src)[1] };
  need(centres.q && centres.u && centres.v && centres.q.split('.')[1].length === 35, 'the box centres are not the 35-decimal values');
  /* stage the verifier beside this repository's interval toolkit, as the page build does */
  const SCR = fs.mkdtempSync(path.join(os.tmpdir(), 'erdos1038-sup-numbers-'));
  fs.copyFileSync(VER, path.join(SCR, 'verify.js'));
  fs.mkdirSync(path.join(SCR, 'core'));
  fs.cpSync(path.join(ROOT, 'instruments', 'interval'), path.join(SCR, 'core', 'interval'), { recursive: true });
  const t0 = Date.now();
  const r = cp.spawnSync('node', ['verify.js'], { cwd: SCR, maxBuffer: 1 << 24 });
  const ms = Date.now() - t0;
  const out = String(r.stdout) + String(r.stderr);
  fs.rmSync(SCR, { recursive: true, force: true });
  need(r.status === 0, 'the lemniscate verifier failed:\n' + out.slice(-600));
  const sm = /checks:\s*(\d+) passed,\s*(\d+) failed;\s*(\d+) mutation controls rejected/.exec(out);
  need(sm && sm[2] === '0' && /VERDICT: CONFIRMED/.test(out) && /all 30 claimed decimals of D/.test(out), 'the verifier summary or verdict moved');
  const passed = Number(sm[1]), mut = Number(sm[3]);
  need(passed >= 26 && mut === 4, 'the verifier counts moved: ' + sm[0]);
  def('VerPassed', String(passed)); def('VerFailed', sm[2]); def('VerMutations', String(mut)); def('VerNamed', String(passed - mut));
  def('VerMs', String(ms));
  const kr = /Krawczyk \(eqcert\) proves existence \+ uniqueness of the triple\s+\[rounds (\d+), maxRad ([\d.e+-]+)\]/.exec(out);
  need(kr, 'the Krawczyk line is gone'); def('KrawczykRounds', kr[1]); def('KrawczykRad', sci(Number(kr[2]), 2));
  const wm = /widths\(quanta 1e-48\):\s*(\d+), (\d+), (\d+)/.exec(out);
  need(wm, 'the refined-width line is gone');
  const widths = wm.slice(1, 4).map((x) => Number(x) * 1e-48);
  def('WidthQ', sci(widths[0], 2)); def('WidthU', sci(widths[1], 2)); def('WidthV', sci(widths[2], 2));
  def('WidthWorst', sci(Math.max(...widths), 2));
  need(Math.max(...widths) < 1e-40, 'a refined width is not below 1e-40');
  /* the certified expansions, 40 decimals, lower and upper ends printed by the verifier */
  const enc = {};
  for (const m of out.matchAll(/^\s{2}(q|u|v|p|alpha|r|z|D)\s+= (-?\d+\.\d{40}) \.\. (-?\d+\.\d{40})$/gm)) enc[m[1]] = { lo: m[2], hi: m[3] };
  need(Object.keys(enc).length === 8, 'the eight certified expansions were not all printed');
  for (const k of Object.keys(enc)) need(enc[k].lo === enc[k].hi, 'the enclosure of ' + k + ' is not thin at 40 decimals');
  def('DForty', enc.D.lo);
  need(global.__infUpper > Number(enc.D.lo), 'the companion upper bound is not above D');
  def('InfUpperAboveD', sci(global.__infUpper - Number(enc.D.lo), 2));
  const D30 = claims[0].printed, Dexp = enc.D.lo;
  need(Dexp.startsWith(D30.slice(0, -1)), 'the certified D does not share the first 29 printed decimals');
  def('DPrintedThirty', D30);
  def('DTwentyNine', D30.slice(0, -1));
  def('DPrintedLastDigit', D30.slice(-1));
  def('DExpansionThirtieth', Dexp.charAt(D30.length - 1));
  def('DExpansionTail', Dexp.slice(D30.length - 1, D30.length + 4));   /* the 30th decimal onward: 47861 */
  need(D30.slice(-1) === '5' && Dexp.charAt(D30.length - 1) === '4', 'the thirtieth-decimal finding (printed 5, expansion 4) no longer holds');
  const modes = {};
  for (const m of out.matchAll(/claimed digits\s+(.+?)\s{2,}\[(rounded|truncation)\]/g)) modes[m[1].replace(/\s+/g, ' ').trim()] = m[2];
  need(Object.keys(modes).length === 10, 'ten claimed-digit rows were not all decided');
  const KEYN = { q: '$q^*$', u: '$u^*$', v: '$v^*$', p: '$p^*$', alpha: '$\\alpha$', r: '$r^*$', z: '$z^*$', D: '$D$' };
  rows('ClaimRows', claims.map((c) => {
    const mode = modes[c.label]; need(mode, 'no decision for ' + c.label);
    const page = /\(([^)]*)\)/.exec(c.label)[1].replace(', 30 dec', '');
    const dps = c.printed.split('.')[1].length;
    const cert = enc[c.key].lo.slice(0, enc[c.key].lo.indexOf('.') + 1 + dps + 3);
    return [KEYN[c.key], page, '$' + c.printed + '$', '$' + cert + '\\ldots$', mode];
  }));
  need(Object.values(modes).filter((m) => m === 'rounded').length === 1 && modes[claims[0].label] === 'rounded', 'exactly the 30-decimal D should be the rounded one');
  const CEN = { q: '$q_0$', u: '$u_0$', v: '$v_0$' };
  rows('CentreRows', ['q', 'u', 'v'].map((k) => [CEN[k], '$' + centres[k] + '$', '$' + enc[k].lo.slice(0, 2 + 35) + '\\ldots$']));
  def('CentreDecimals', String(centres.q.split('.')[1].length));
  const fr = /\(A\.13\) .*?\[F_R faces (-?[\d.]+) \.\. (-?[\d.]+) \| (-?[\d.]+) \.\. (-?[\d.]+)\]/.exec(out);
  need(fr, 'the (A.13) face line is gone');
  def('FaceRLo', sci(Number(fr[1]), 2)); def('FaceRHi', sci(Number(fr[2]), 2));
  const fl = /\(A\.14\) .*?\[F_L faces (-?[\d.]+) \.\. (-?[\d.]+) \| (-?[\d.]+) \.\. (-?[\d.]+)\]/.exec(out);
  need(fl, 'the (A.14) face line is gone');
  const flAbs = [Math.abs(Number(fl[1])), Math.abs(Number(fl[2]))].sort((a, b) => a - b);
  need(Number(fl[1]) < 0 && Number(fl[2]) < 0 && Number(fr[1]) > 0, 'the face signs moved');
  def('FaceLLo', sci(flAbs[0], 2)); def('FaceLHi', sci(flAbs[1], 2));
  const bI = /I_\* = q0 ± 1e-(\d+)/.exec(out), bB = /B_\* = centres ± 1e-(\d+)/.exec(out);
  need(bI && bB, 'the box-radius lines are gone'); def('RadiusI', '10^{-' + bI[1] + '}'); def('RadiusB', '10^{-' + bB[1] + '}');
  /* how many decades the refined enclosure sits inside the manuscript's box: floor(log10(1e-30 / worst width)) */
  const decades = Math.floor(Math.log10(Math.pow(10, -Number(bB[1])) / Math.max(...widths)));
  need(decades >= 10, 'the refined enclosure is no longer far inside the manuscript box');
  def('MarginDecades', String(decades));
  const M2 = /M2 rejected: .*?\[F3_mut = (-?[\d.]+) \.\./.exec(out), M3 = /M3 rejected: .*?\[F_R over shifted box = (-?[\d.]+) \.\./.exec(out), M4 = /M4 rejected: .*?\[F_R_mut = (-?[\d.]+) \.\./.exec(out);
  need(M2 && M3 && M4, 'a mutation line is gone');
  def('MutTwo', dec(M2[1], 3)); def('MutThree', sci(Number(M3[1]), 2)); def('MutFour', sci(Number(M4[1]), 2));
}

fs.writeFileSync(path.join(OUT, 'erdos1038-sup-numbers.tex'), MAC.join('\n') + '\n');
console.log('wrote paper/tex/erdos1038-sup-numbers.tex (' + (MAC.length - 1) + ' macros)');

/* the figure, from the curve points just written */
const py = path.join(ROOT, 'instruments', 'hseva', '.venv', 'bin', 'python');
const fig = cp.spawnSync(fs.existsSync(py) ? py : 'python3', [path.join(__dirname, 'erdos1038-sup-fig.py')], { cwd: ROOT, maxBuffer: 1 << 24 });
if (fig.status !== 0) die('the figure did not draw:\n' + String(fig.stdout) + String(fig.stderr));
process.stdout.write(String(fig.stdout));
