#!/usr/bin/env node
/* paper-numbers/erdos852.js — every number the Erdős #852 pre-paper quotes,
   read from the records that decided it and written as LaTeX macros:
     paper/tex/erdos852-numbers.tex
   and the figure's data, derived from the same record by the same module the
   report page uses (instruments/erdos852h/analyse.js):
     paper/tex/fig/erdos852-data.json      (drawn by tools/paper-numbers/erdos852-fig.py)

   Records read: certs/erdos852-certificate.json (the two constants, detached),
   certs/erdos852-h-records.json (the exhaustive record scan to 5e11),
   corpus/sources/{erdos852_page,erdos852_thread,erdos852_thread_correction-public_2026-08-27}.html
   and corpus/sources/oeis_A0{53597,78515,79007,79889}.txt, all re-hashed against
   corpus/sources/PINS.json; lean/erdos852 (the kernel bridge, counted and grepped).

   Re-decided live here, because they are cheap: the naive IEEE-754 double product
   (it must reproduce the published digits), the exact-integer refutation over the
   odd primes to 4e5 (48 ms), the certified enclosure at loop bound 2e6, the record
   analysis (bands, readings, OEIS agreement), the independent re-proof of the
   length-31 record, the stdlib verifier (0.6 s) and the erdos852 battery (5 s).
   A record that no longer says what a sentence needs makes this refuse (need()),
   exactly as tools/build-paper-numbers.js does.

   usage: node tools/paper-numbers/erdos852.js                                   MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex', 'erdos852-numbers.tex');
const FIGDATA = path.join(ROOT, 'paper', 'tex', 'fig', 'erdos852-data.json');
const SRC = path.join(ROOT, 'corpus', 'sources');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const die = (m) => { console.error('PAPER NUMBERS REFUSED (erdos852): ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
/* a small or large number in scientific form, as math: $6.1\times10^{-13}$ */
const sci = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return '$' + m[1] + '\\times10^{' + Number(m[2]) + '}$'; };
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();
const tex = (s) => String(s).replace(/\\/g, '\\textbackslash{}').replace(/([&%$#_{}])/g, '\\$1');

const M = ['%% generated by tools/paper-numbers/erdos852.js from certs/erdos852-certificate.json, certs/erdos852-h-records.json, corpus/sources (pinned) — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));

/* ---- exact decimal helpers (strings -> BigInt) ---------------------------- */
const parseDec = (s) => { const m = /^(\d+)\.(\d+)$/.exec(s); if (!m) die('not a decimal: ' + s); return { num: BigInt(m[1] + m[2]), den: 10n ** BigInt(m[2].length), k: m[2].length }; };
const sha = (f) => crypto.createHash('sha256').update(fs.readFileSync(path.join(SRC, f))).digest('hex');

/* ======================================================================= pins */
const PINS = J('corpus/sources/PINS.json');
const PINNED = ['erdos852_page.html', 'erdos852_thread.html', 'erdos852_thread_correction-public_2026-08-27.html',
  'oeis_A053597.txt', 'oeis_A078515.txt', 'oeis_A079007.txt', 'oeis_A079889.txt'];
for (const f of PINNED) need(PINS[f] && sha(f) === PINS[f], f + ' has drifted from its pin in corpus/sources/PINS.json');
def('RepoCommit', git);

/* ================================================================ the constants */
const cert = J('certs/erdos852-certificate.json');
for (const f of ['erdos852_page.html', 'erdos852_thread.html']) need(cert.sourcePins[f] === PINS[f], 'the certificate pins ' + f + ' at a different hash than PINS.json');
def('CertGit', tex((/@ git (\w+)/.exec(cert.generatedBy) || [])[1] || die('certificate has no git stamp')));
def('CertSha', crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, 'certs', 'erdos852-certificate.json'))).digest('hex').slice(0, 12));

/* ---- c0 ---- */
const c0 = cert.c0;
need(c0.published.verdict === 'VERIFIED_ROUNDED', 'the c0 audit is no longer VERIFIED_ROUNDED');
need(/^1\.\d+$/.test(c0.certifiedDigits) && c0.certifiedDigits.startsWith('1.3232282768639494'), 'c0 digits moved: ' + c0.certifiedDigits);
const c0dec = c0.certifiedDigits.split('.')[1].length;
def('CzeroDigitsFull', c0.certifiedDigits);
def('CzeroDecimals', String(c0dec));
def('CzeroShort', c0.certifiedDigits.slice(0, 2 + 20));
def('CzeroPublished', c0.published.value);
const c0pub = parseDec(c0.published.value);
def('CzeroPubDecimals', String(c0pub.k));
def('CzeroBits', String(c0.instrument.precisionBits));
def('CzeroBisections', String(c0.instrument.bisections));
/* the bracket starts at [1.25, 1.375] (width 1/8) and halves per bisection */
def('CzeroWidthBound', sci(Math.pow(2, -3 - c0.instrument.bisections), 1));
const b40lo = parseDec(c0.bracket40.lo), b40hi = parseDec(c0.bracket40.hi);
need(b40lo.k === 40 && b40hi.k === 40 && b40hi.num - b40lo.num === 1n, 'bracket40 is not a clean 1e-40 window');
need(c0.certifiedDigits.startsWith(c0.bracket40.lo), 'the 61-digit expansion disagrees with bracket40');
def('CzeroBracketLo', c0.bracket40.lo);
def('CzeroBracketHi', c0.bracket40.hi);
/* the published decimal against the window, exactly: truncation fails, rounding holds */
{
  const lo = b40lo, hi = b40hi, p = c0pub;
  const truncFails = hi.num * p.den < (p.num) * hi.den;                         /* truth < claim */
  const roundOk = (2n * p.num - 1n) * lo.den <= 2n * p.den * lo.num && hi.num * 2n * p.den <= (2n * p.num + 1n) * hi.den;
  need(truncFails && roundOk, 'the published c0 is no longer a correct rounding that fails as a truncation');
}
const cont = c0.certifiedDigits.slice(2 + c0pub.k, 2 + c0pub.k + 4);
need(cont === '9469', 'the c0 expansion no longer continues ...9469 after the published decimals');
def('CzeroPrefix', c0.certifiedDigits.slice(0, 2 + c0pub.k));
def('CzeroContinuation', cont);
def('CzeroRoundedTo', c0.certifiedDigits.slice(0, 2 + c0pub.k - 1) + String(Number(c0.certifiedDigits[2 + c0pub.k - 1]) + 1));

/* ---- C* ---- */
const cs = cert.cstar;
need(cs.published.verdict === 'REFUTED', 'the C* audit is no longer REFUTED');
const csLo = parseDec(cs.enclosure.lo), csHi = parseDec(cs.enclosure.hi);
need(csLo.k === csHi.k && csLo.num < csHi.num, 'the C* enclosure is malformed');
need(cs.enclosure.lo.startsWith('0.075240386178309') && cs.enclosure.hi.startsWith('0.075240386178309'), 'C* enclosure moved');
def('CstarLo', cs.enclosure.lo);
def('CstarHi', cs.enclosure.hi);
const csWidth = Number(csHi.num - csLo.num) / Number(csLo.den);
def('CstarWidth', sci(csWidth, 2));
def('CstarWidthShort', sci(csWidth, 1));
/* the digits the two ends share */
let agreed = '';
for (let i = 0; i < cs.enclosure.lo.length; i++) { if (cs.enclosure.lo[i] === cs.enclosure.hi[i]) agreed += cs.enclosure.lo[i]; else break; }
def('CstarDigits', agreed);
def('CstarAgreedDecimals', String(agreed.length - 2));
const mm = /over (\d+) odd primes to (\d+) at (\d+) bits/.exec(cs.enclosure.method);
need(mm, 'the C* method string no longer states primes/limit/bits');
const csPrimes = Number(mm[1]), csLimit = Number(mm[2]), csBits = Number(mm[3]);
def('CstarPrimes', int(csPrimes)); def('CstarLimit', int(csLimit)); def('CstarLimitSci', sci(csLimit, 0)); def('CstarBits', String(csBits));
const tailS = 1 / (2 * (csLimit - 1) ** 2);
def('CstarTail', sci(tailS, 2));
def('CstarPublished', cs.published.value);
const csPub = parseDec(cs.published.value);
def('CstarPubDecimals', String(csPub.k));
/* first decimal place where the published decimal and the enclosure disagree */
let diffAt = 0;
for (let i = 2; i < cs.published.value.length; i++) { if (cs.published.value[i] !== cs.enclosure.lo[i] || cs.published.value[i] !== cs.enclosure.hi[i]) { diffAt = i - 1; break; } }
need(diffAt === 12, 'the published C* no longer first differs at the 12th decimal place (got ' + diffAt + ')');
def('CstarDiffDecimal', String(diffAt));
def('CstarDiffSignificant', String(diffAt - 1));           /* the leading 0 after the point is not significant */
def('CstarCorrectDecimals', String(diffAt - 1));
def('CstarCorrectSignificant', String(diffAt - 2));
def('CstarPubSignificant', String(csPub.k - 1));
/* the gap from the published decimal to the lower end of the enclosure, and the claim window's upper edge */
const csGap = Number(csLo.num * csPub.den - csPub.num * csLo.den) / Number(csLo.den * csPub.den);
need(csGap > 0, 'the published C* is no longer below the enclosure');
def('CstarGap', sci(csGap, 2));
const edge = { num: csPub.num + 1n, den: csPub.den };
def('CstarEdge', '0.' + edge.num.toString().padStart(csPub.k, '0'));
/* under both readings the claim window is [(2num-1)/(2den), (num+1)/den]; the enclosure must lie wholly above it */
need(csLo.num * edge.den > edge.num * csLo.den, 'the enclosure no longer lies above the claim window');

/* ---- the refutation in exact integers, re-decided here ---- */
const refLimit = cs.refutation.limit;
need(refLimit === 400000 && /752403861778/.test(cs.refutation.statement), 'the refutation recipe moved');
function oddPrimes(limit) {
  const s = new Uint8Array(limit + 1); const out = [];
  for (let i = 2; i * i <= limit; i++) if (!s[i]) for (let j = i * i; j <= limit; j += i) s[j] = 1;
  for (let p = 3; p <= limit; p += 2) if (!s[p]) out.push(p);
  return out;
}
const refPrimes = oddPrimes(refLimit);
const pairs = refPrimes.map((p) => { const q = BigInt(p - 1); const q3 = q * q * q; return [q3 + 1n, q3]; });
const tree = (lo, hi) => { if (hi - lo === 1) return pairs[lo]; const m = (lo + hi) >> 1; const a = tree(lo, m), b = tree(m, hi); return [a[0] * b[0], a[1] * b[1]]; };
const [N, D] = tree(0, pairs.length);
need(5n * (N - D) * 10n ** 12n > 752403861778n * D, 'the exact partial product to 4e5 no longer refutes the published window');
need((N - D) * csPub.den > 2n * csPub.num * D, 'the exact lower bound no longer exceeds the published value itself');
need((N - D) * csLo.den <= 2n * D * csLo.num, 'the exact lower bound is not below the certified enclosure (inconsistent records)');
def('RefLimit', int(refLimit)); def('RefPrimes', int(refPrimes.length)); def('RefNumDigits', int(N.toString().length));
const refLB = ((N - D) * 10n ** 20n) / (2n * D);     /* floor: a strict lower bound of (N/D-1)/2 */
def('RefLowerBound', '0.' + refLB.toString().padStart(20, '0').slice(0, 16));
def('RefInequality', '5\\,(N-D)\\cdot 10^{12} > 752403861778\\,D');

/* ================================================================ the mechanism */
const E = require(path.join(ROOT, 'instruments', 'erdos852', 'constants.js'));
const B = require(path.join(ROOT, 'instruments', 'bigfloat', 'bigfloat.js'));
const NAIVE_LIMIT = 2000000;
const nprimes = E.oddPrimes(NAIVE_LIMIT);
let naive = 1, dropped = 0, logsum = 0;
for (const p of nprimes) { const a = 1 / ((p - 1) ** 3); const f = 1 + a; if (f === 1) dropped++; naive *= f; logsum += Math.log1p(a); }
const naiveC = (naive - 1) / 2, log1pC = Math.expm1(logsum) / 2;
const PUBLISHED_DOUBLE = 0.0752403861777418;
need(Math.abs(naiveC - PUBLISHED_DOUBLE) < 1e-15, 'the naive double product no longer reproduces the published digits: ' + naiveC);
need(naiveC.toFixed(13) === cs.published.value, 'the naive product rounded to 13 places is not the published decimal');
def('NaiveLimit', int(NAIVE_LIMIT)); def('NaiveLimitSci', sci(NAIVE_LIMIT, 0));
def('NaivePrimes', int(nprimes.length)); def('NaiveDropped', int(dropped)); def('NaiveKept', int(nprimes.length - dropped));
def('NaiveDropPct', dec(100 * dropped / nprimes.length, 1));
def('NaiveValue', naiveC.toFixed(16)); def('NaiveValueShort', naiveC.toFixed(13));
def('LogOnePValue', log1pC.toFixed(16));
/* the threshold: the least q with q^3 >= 2^53, where 1 + 1/q^3 rounds to 1.0 */
let q0 = 1n; while (q0 * q0 * q0 < 2n ** 53n) q0++;
need(1 + 1 / Number(q0) ** 3 === 1 && 1 + 1 / Number(q0 - 1n) ** 3 !== 1, 'the 2^53 threshold is not where the record says');
def('Threshold', int(Number(q0))); def('TwoFiftyThree', int(Number(2n ** 53n)));
const firstDropped = nprimes.find((p) => p - 1 >= Number(q0));
def('ThresholdPrime', int(firstDropped));
const lastKept = nprimes.filter((p) => p - 1 < Number(q0)).length;
def('KeptPrimesBelowThreshold', int(lastKept));
/* the missing mass: sum_{p >= firstDropped} 1/(p-1)^3 over primes to 3e7 plus the proved tail */
const bigPrimes = E.oddPrimes(csLimit);
let mass = 0; for (const p of bigPrimes) if (p >= firstDropped) mass += 1 / ((p - 1) ** 3);
mass += tailS;
def('MissingMass', sci(mass, 2));
const certMid = Number(csLo.num + csHi.num) / (2 * Number(csLo.den));
const predictedGap = 0.5 * (1 + 2 * certMid) * mass;     /* d(C*) = (prod/2) d(log prod), prod = 1 + 2 C* */
const observedGap = certMid - naiveC;
def('PredictedGap', sci(predictedGap, 2)); def('ObservedGap', sci(observedGap, 2));
def('GapRatioPct', dec(100 * Math.abs(predictedGap - observedGap) / observedGap, 0));
/* the certified enclosure at the naive loop bound, and its decisions */
const cs2e6 = E.cstar({ limit: NAIVE_LIMIT, P: 192 });
need(E.decideClaimedDigits(cs2e6.enclosure, cs.published.value).verdict === 'REFUTED', 'the refutation no longer holds at loop bound 2e6');
const certTrunc = agreed.slice(0, 2 + csPub.k);          /* the certified digits truncated to the published length */
need(E.decideClaimedDigits(cs2e6.enclosure, certTrunc).verdict === 'VERIFIED', 'the certified ' + csPub.k + '-decimal truncation is not VERIFIED at loop bound 2e6');
def('CstarCertTrunc', certTrunc);
const lo2 = B.toDecimal(cs2e6.enclosure.lo, 16, 'down'), hi2 = B.toDecimal(cs2e6.enclosure.hi, 16, 'up');
def('EncTwoMLo', lo2); def('EncTwoMHi', hi2);
/* the "float-honest" route: a forward log1p sum keeps every factor as a term, but the
   running sum (~0.14) absorbs every term below half its ulp, so it too lands outside;
   a compensated (Kahan) sum of the same terms lands inside. Measured, not assumed. */
need(naiveC < Number(lo2), 'the naive value no longer sits below the 2e6 enclosure');
need(log1pC < Number(lo2), 'the forward log1p sum no longer sits below the 2e6 enclosure (the page\'s "inside" would then be right)');
let absorbed = 0, firstAbsorbed = null, run = 0, kahan = 0, comp = 0;
for (const p of nprimes) {
  const y = Math.log1p(1 / ((p - 1) ** 3));
  const t = run + y; if (t === run) { absorbed++; if (firstAbsorbed === null) firstAbsorbed = p; } run = t;
  const yk = y - comp; const tk = kahan + yk; comp = (tk - kahan) - yk; kahan = tk;
}
const kahanC = Math.expm1(kahan) / 2;
need(kahanC > Number(lo2) && kahanC < Number(hi2), 'the compensated log1p sum no longer lands inside the 2e6 enclosure');
def('LogOnePGap', sci(Number(lo2) - log1pC, 1));
def('LogOnePAbsorbed', int(absorbed)); def('LogOnePAbsorbedPct', dec(100 * absorbed / nprimes.length, 1)); def('LogOnePFirstAbsorbed', int(firstAbsorbed));
def('LogOnePKahan', kahanC.toFixed(16));
def('HalfUlpOfSum', sci(Math.pow(2, -56), 1));
def('LogSumApprox', dec(Math.log(1 + 2 * certMid), 2));   /* the running sum log(prod) = log(1 + 2 C*) */
/* the naive product does not move with the loop bound */
const naiveAt = (L) => { let n = 1; for (const p of E.oddPrimes(L)) n *= 1 + 1 / ((p - 1) ** 3); return (n - 1) / 2; };
const nA = naiveAt(400000), nB = naiveAt(10000000);
need(nA.toFixed(16) === naiveC.toFixed(16) && nB.toFixed(16) === naiveC.toFixed(16), 'the naive product now depends on the loop bound');
def('NaiveOtherBoundLo', sci(400000, 0)); def('NaiveOtherBoundHi', sci(10000000, 0));
rows('MechanismRows', [
  ['naive double product (' + dec(100 * dropped / nprimes.length, 1) + '\\% of the factors equal to $1.0$)', naiveC.toFixed(16), 'the published decimal to all its places; outside'],
  ['forward double \\texttt{log1p} sum (' + dec(100 * absorbed / nprimes.length, 1) + '\\% of the terms absorbed)', log1pC.toFixed(16), 'outside, by ' + sci(Number(lo2) - log1pC, 1)],
  ['compensated \\texttt{log1p} sum (Kahan)', kahanC.toFixed(16), 'inside; a float, so uncertified'],
  ['certified enclosure, same loop bound', '\\begin{tabular}[t]{@{}l@{}}$[' + lo2 + ',$\\\\$\\ ' + hi2 + ']$\\end{tabular}', 'the authority']
]);

/* ================================================================ the batteries */
{
  const r = cp.spawnSync('node', ['instruments/erdos852/battery.js'], { cwd: ROOT, maxBuffer: 1 << 26 });
  const out = String(r.stdout) + String(r.stderr);
  const m = /erdos852 battery: (\d+) pass, (\d+) fail/.exec(out);
  need(r.status === 0 && m && Number(m[2]) === 0, 'the erdos852 battery did not pass clean:\n' + out.slice(-800));
  def('BatteryChecks', m[1]);
  def('BatteryReds', String(out.split('\n').filter((l) => /^PASS\s+RED/.test(l)).length));
}
{
  const t0 = Date.now();
  const r = cp.spawnSync('python3', ['tools/verify_erdos852.py', 'certs/erdos852-certificate.json', '--sources', 'corpus/sources'], { cwd: ROOT, maxBuffer: 1 << 26 });
  const out = String(r.stdout) + String(r.stderr);
  const m = /verify_erdos852: (\d+) failures/.exec(out);
  need(r.status === 0 && m && m[1] === '0', 'the stdlib verifier did not pass clean:\n' + out.slice(-800));
  def('VerifierChecks', String(out.split('\n').filter((l) => /^PASS/.test(l)).length));
  def('VerifierReds', String(out.split('\n').filter((l) => /^PASS\s+RED control/.test(l)).length));
  def('VerifierSeconds', dec((Date.now() - t0) / 1000, 1));
  const mlo = /I0\(lo\) < 1 with margin ([\d.e+-]+)/.exec(out), mhi = /I0\(hi\) > 1 with margin ([\d.e+-]+)/.exec(out);
  need(mlo && mhi, 'the verifier no longer prints the bracket margins');
  def('CzeroMarginLo', sci(Number(mlo[1]), 1)); def('CzeroMarginHi', sci(Number(mhi[1]), 1));
  const mp = /primes <= (\d+)/.exec(out);
  need(mp && Number(mp[1]) === refLimit, 'the verifier refutes at a different limit than the certificate');
}

/* ================================================================ the Lean bridge */
{
  const dir = path.join(ROOT, 'lean', 'erdos852');
  const chunks = fs.readdirSync(path.join(dir, 'Erdos852')).filter((f) => /^Chunk\d+\.lean$/.test(f)).length;
  need(chunks > 0, 'no Lean chunk modules');
  const refut = fs.readFileSync(path.join(dir, 'Erdos852', 'Refutation.lean'), 'utf8');
  need(/cstar_refuted/.test(refut) && /752403861778/.test(refut), 'Refutation.lean no longer states the inequality');
  const mprimes = /odd primes 3\.\.(\d+) \((\d+) of them\)/.exec(refut);
  need(mprimes && Number(mprimes[1]) === refLimit && Number(mprimes[2]) === refPrimes.length, 'the Lean prime list disagrees with the certificate limit');
  need(fs.existsSync(path.join(dir, 'Erdos852', 'Basic.lean')), 'Basic.lean missing');
  const stmt = fs.readFileSync(path.join(dir, 'Erdos852', 'Statement.lean'), 'utf8');
  need(/DistinctRunSetBddAbove/.test(stmt) && /ThreadConjecture/.test(stmt) && /Question2/.test(stmt), 'Statement.lean no longer carries the side-condition and the thread conjecture');
  def('LeanChunks', String(chunks));
  def('LeanToolchain', tex(fs.readFileSync(path.join(dir, 'lean-toolchain'), 'utf8').trim()));
}

/* ================================================================ the thread */
const strip = (f) => fs.readFileSync(path.join(SRC, f), 'utf8').replace(/<[^>]+>/g, '\n').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/\n\s*\n+/g, '\n');
const stamps = (t) => { const out = []; const re = /(\w[\w ]*)\n\s*—\s*\n(\d\d:\d\d on \d+ \w+ \d{4})/g; let m; while ((m = re.exec(t))) out.push({ who: m[1], when: m[2] }); return out; };
const thread0 = strip('erdos852_thread.html'), thread1 = strip('erdos852_thread_correction-public_2026-08-27.html');
const page = strip('erdos852_page.html');
need(thread0.includes(c0.published.value) && thread0.includes(cs.published.value), 'the pinned thread no longer carries both published decimals');
need(thread1.includes('0.0752403861783092'), 'the pinned public snapshot does not carry the correction digits');
need(/for some \$n<x\$/.test(page) && /h\(x\)=o\(\\log x\)/.test(page) && /cannot be resolved with a finite computation/.test(page), 'the problem page no longer reads as transcribed');
need(/A053597/.test(page) && /A078515/.test(page) && /A001223/.test(page), 'the problem page no longer lists the OEIS sequences');
need(/Brun's sieve implies \$h\(x\) \\to \\infty\$/.test(page), 'the problem page no longer states the Brun-sieve remark');
const s0 = stamps(thread0), s1 = stamps(thread1);
const turt = s0.find((s) => s.who === 'DavidTurturean'), choj = s0.find((s) => s.who === 'Przemek Chojecki'), corr = s1.find((s) => s.who === 'carlos_toledo');
need(turt && /24 Apr 2026/.test(turt.when) && choj && /24 Apr 2026/.test(choj.when), 'the constants\' comments are not dated 24 Apr 2026 in the pinned thread');
need(corr && /26 Aug 2026/.test(corr.when), 'the correction comment is not dated 26 Aug 2026 in the public snapshot');
need(s1.length === s0.length + 1, 'the public snapshot does not hold exactly one more comment than the original');
const alex = s0.find((s) => s.who === 'BorisAlexeev');
need(alex && /Dec 2025/.test(alex.when) && /A078515/.test(thread0) && /looks exponential/.test(thread0), 'the December 2025 data comment is not in the pinned thread');
def('ThreadDateData', 'December 2025');
def('ThreadCommentsBefore', String(s0.length)); def('ThreadCommentsAfter', String(s1.length));
def('ThreadDateConstants', '24 April 2026'); def('ThreadDateCorrection', '26 August 2026'); def('ThreadSnapshotDate', '27 August 2026'); def('ThreadFetchDate', '25 August 2026');
const bloom = /accessed (\d{4}-\d\d-\d\d)/.exec(page);
need(bloom && bloom[1] === '2026-08-25', 'the pinned page is not the 2026-08-25 fetch');
def('PageAccessed', bloom[1]);
/* the thread's own bounds, as recorded: the GPT lower bound exponent and the two upper bounds */
need(/\(\\log x\)\^\{1\/3\}/.test(thread0) && /x\^\{0\.41\+\\epsilon\}/.test(thread0) && /x\^\{0\.26\+o\(1\)\}/.test(thread0), 'the thread no longer carries the three bounds the introduction quotes');
need(/1\.32323 \\log x/.test(thread0) && /J\(c\) = C_\* c\^2 \+ O\(c\^3\)/.test(thread0), 'the thread no longer states the conjecture and the role of C*');

/* ================================================================ the data */
const H = J('certs/erdos852-h-records.json');
const A = require(path.join(ROOT, 'instruments', 'erdos852h', 'analyse.js'));
const V = require(path.join(ROOT, 'instruments', 'erdos852h', 'verify-record.js'));
need(A.C0 === Number(c0.certifiedDigits.slice(0, 42)) || Math.abs(A.C0 - Number(c0.certifiedDigits)) < 1e-15, 'analyse.js carries a c0 that is not the certificate\'s');
const R = H.records, Dx = A.distinctIndices(R);
need(A.validate(R).length === 0, 'the record set is malformed: ' + A.validate(R).join('; '));
const oeis = (f) => A.parseOEIS(fs.readFileSync(path.join(SRC, f), 'utf8'));
const A078515 = oeis('oeis_A078515.txt'), A079889 = oeis('oeis_A079889.txt'), A079007 = oeis('oeis_A079007.txt'), A053597 = oeis('oeis_A053597.txt');
const nAgree = Math.min(Dx.length, A078515.length);
need(A078515.length === A079889.length && nAgree === A078515.length, 'the OEIS index/prime sequences differ in length or exceed the scan');
need(Dx.slice(0, nAgree).every((r, i) => r.n === A078515[i]), 'our record indices disagree with A078515 — a finding, not a paper number');
need(Dx.slice(0, nAgree).every((r, i) => r.p === A079889[i]), 'our record start primes disagree with A079889');
/* A079007(n) = the opening prime of the first run of length n, n = 0..30 */
need(A079007[0] === 2, 'A079007(0) is not 2');
const byLen = new Map(R.map((r) => [r.len, r.p]));
for (let len = 1; len < A079007.length; len++) need(byLen.get(len) === A079007[len], 'A079007(' + len + ') disagrees with the scan');
/* A053597(n), the run length at every index n = 1..105, recomputed from the primes here */
{
  const ps = [2]; for (let k = 3; ps.length < 400; k += 2) { let pr = true; for (const q of ps) { if (q * q > k) break; if (k % q === 0) { pr = false; break; } } if (pr) ps.push(k); }
  const g = []; for (let i = 0; i + 1 < ps.length; i++) g.push(ps[i + 1] - ps[i]);
  for (let n = 1; n <= A053597.length; n++) {
    const seen = new Set(); let len = 0;
    for (let i = n - 1; i < g.length; i++) { if (seen.has(g[i])) break; seen.add(g[i]); len++; }
    need(len === A053597[n - 1], 'A053597(' + n + ') disagrees with a direct recomputation');
  }
}
def('HLimit', sci(H.limit, 0)); def('HLimitInt', int(H.limit)); def('HSeconds', int(H.seconds)); def('HMinutes', String(Math.round(H.seconds / 60)));
def('HRecords', String(R.length)); def('HDistinct', String(Dx.length)); def('HMax', String(Dx[Dx.length - 1].len)); def('HMaxNext', String(Dx[Dx.length - 1].len + 1));
/* indices that set two record lengths at once (beyond the trivial n = 1), which is why A079007 repeats a prime */
const doubles = [];
for (let i = 1; i < R.length; i++) if (R[i].n === R[i - 1].n && R[i].n > 1) doubles.push({ n: R[i].n, lens: [R[i - 1].len, R[i].len] });
need(doubles.length === 2 && doubles.every((d) => A079007[d.lens[0]] === A079007[d.lens[1]]), 'the double-record indices are not the two the paper describes');
def('DoubleIndices', doubles.map((d) => int(d.n) + ' (lengths ' + d.lens[0] + ' and ' + d.lens[1] + ')').join(' and '));
def('MissingLengths', doubles.map((d) => String(d.lens[0])).join(' and '));
def('OeisAgree', String(nAgree)); def('OeisAtermsA', String(A078515.length)); def('OeisBterms', String(A079007.length)); def('OeisBtermsLast', String(A079007.length - 1)); def('OeisCterms', String(A053597.length));
def('OeisNewTerms', String(Dx.length - nAgree));
/* OEIS provenance, from the pinned entries */
const oeisLine = (f, tag) => fs.readFileSync(path.join(SRC, f), 'utf8').split('\n').filter((l) => l.startsWith('%' + tag));
const years = [];
for (const f of ['oeis_A053597.txt', 'oeis_A078515.txt', 'oeis_A079007.txt', 'oeis_A079889.txt']) {
  for (const l of oeisLine(f, 'A').concat(oeisLine(f, 'E'))) { const m = /(\w{3} \d\d (\d{4}))/.exec(l); if (m) years.push(Number(m[2])); }
}
need(Math.min(...years) === 2002 && Math.max(...years) === 2012, 'the OEIS entries are not dated 2002..2012 as the paper says');
def('OeisFirstYear', String(Math.min(...years))); def('OeisLastYear', String(Math.max(...years)));
need(/Donovan Johnson/.test(oeisLine('oeis_A078515.txt', 'E').join(' ')), 'A078515 no longer credits its 2012 extension');

/* the bands and the readings, by the page's module */
const bands = A.bands(R), cons = A.consistency(bands);
need(cons.plateaus + 1 === bands.length, 'exactly one band should be open');
need(cons.inside + cons.outsideHigh + cons.outsideLow === cons.plateaus, 'band tally does not add up');
def('BandsClosed', String(cons.plateaus)); def('BandsInside', String(cons.inside)); def('BandsBelow', String(cons.outsideHigh)); def('BandsAbove', String(cons.outsideLow));
def('BandsMinLen', String(bands[0].len));
/* bands wholly above c0 that are plateaus of only two indices (end = start + 1) */
const aboveShort = bands.filter((b) => b.lo !== null && A.C0 < b.lo && b.end - b.start <= 1);
def('BandsAboveShort', String(aboveShort.length));
def('BandsAboveShortIndices', String(Math.max(...aboveShort.map((b) => b.end - b.start + 1))));
const readings = [];
for (let e = 4; e <= 12; e++) {
  const x = Math.pow(10, e); const hi = A.hAtIndex(R, x), hp = A.hAtPrime(R, x);
  if (!hi || x > H.limit) break;
  readings.push({ e, x, hi, hp, ri: hi / Math.log(x), rp: hp / Math.log(x), pred: A.C0 * Math.log(x) });
}
need(readings.length >= 3, 'not enough decades');
def('Decades', String(readings.length)); def('DecadeFirst', String(readings[0].e)); def('DecadeLast', String(readings[readings.length - 1].e));
const ri = readings.map((r) => r.ri), rp = readings.map((r) => r.rp);
def('IndexRatioMin', dec(Math.min(...ri), 2)); def('IndexRatioMax', dec(Math.max(...ri), 2));
def('PrimeRatioMin', dec(Math.min(...rp), 2)); def('PrimeRatioMax', dec(Math.max(...rp), 2));
def('PrimeReadingLast', dec(rp[rp.length - 1], 4)); def('IndexReadingLast', dec(ri[ri.length - 1], 4));
def('IndexRatioMean', dec(ri.reduce((a, b) => a + b, 0) / ri.length, 3)); def('PrimeRatioMean', dec(rp.reduce((a, b) => a + b, 0) / rp.length, 3));
need(Math.min(...ri) > 1.2 && Math.max(...ri) < 1.45 && Math.max(...rp) < 1.2, 'the readings no longer separate as the paper describes');
def('DecadesWithinOne', String(readings.filter((r) => Math.abs(r.hi - r.pred) < 1).length));
def('DecadesWithinOneWord', ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'][readings.filter((r) => Math.abs(r.hi - r.pred) < 1).length] || String(readings.filter((r) => Math.abs(r.hi - r.pred) < 1).length));
rows('ReadingRows', readings.map((r) => ['$10^{' + r.e + '}$', String(r.hi), dec(r.ri, 4), String(r.hp), dec(r.rp, 4), dec(r.pred, 2)]));
/* the asymptotic equivalence of the two readings, measured at the last record */
const last = Dx[Dx.length - 1];
def('LogRatioLast', dec(Math.log(last.n) / Math.log(last.p), 3));
def('LogLogOverLogLast', dec(Math.log(Math.log(last.p)) / Math.log(last.p), 3));
def('CzeroFour', dec(A.C0, 4));
/* the record table */
rows('RecordRows', Dx.map((r, i) => [String(r.len), int(r.n), int(r.p), i < nAgree ? 'A078515, A079889, A079007' : '\\textbf{new}']));
rows('BandRows', bands.map((b) => [String(b.len), int(b.start), b.end === null ? 'open' : int(b.end), dec(b.hi, 4), b.lo === null ? '---' : dec(b.lo, 4),
  b.lo === null ? 'open' : (A.C0 <= b.hi && A.C0 >= b.lo ? 'inside' : (A.C0 > b.hi ? 'band below $c_0$' : 'band above $c_0$'))]));
/* one table for the paper: each record with the plateau it opens (bands start at h = 7) */
const bandByLen = new Map(bands.map((b) => [b.len, b]));
rows('RecordBandRows', Dx.map((r, i) => {
  const b = bandByLen.get(r.len);
  const where = !b ? '---' : (b.lo === null ? 'open' : (A.C0 <= b.hi && A.C0 >= b.lo ? 'inside' : (A.C0 > b.hi ? 'below $c_0$' : 'above $c_0$')));
  return [String(r.len), int(r.n), int(r.p), i < nAgree ? 'yes' : '\\textbf{new}',
    !b ? '---' : (b.end === null ? 'open' : int(b.end)), !b ? '---' : dec(b.hi, 4), !b || b.lo === null ? '---' : dec(b.lo, 4), where];
}));

/* the extension and its control, re-proved here by the independent verifier */
const beyond = Dx.slice(nAgree);
need(beyond.length === 1, 'the paper describes exactly one record past the published terms; the record holds ' + beyond.length);
const ext = beyond[0], ev = V.verify(String(ext.p), ext.len);
need(ev.exact && new Set(ev.gaps).size === ext.len, 'the length-' + ext.len + ' record failed to re-prove');
const ctl = Dx[nAgree - 1], cv = V.verify(String(ctl.p), ctl.len);
need(cv.exact && ctl.p === A079889[nAgree - 1], 'the last published record failed to re-prove as a control');
def('ExtLen', String(ext.len)); def('ExtPrime', int(ext.p)); def('ExtPrimeRaw', String(ext.p)); def('ExtIndex', int(ext.n)); def('ExtSpanEnd', int(ev.spans[1])); def('ExtNextGap', String(ev.nextGap));
def('ExtGaps', ev.gaps.join(', ')); def('ExtMaxGap', String(Math.max(...ev.gaps)));
def('ControlLen', String(ctl.len)); def('ControlPrime', int(ctl.p)); def('ControlIndex', int(ctl.n));
/* the step function at the extension: h = 31 from the closing index on */
def('ExtClose', int(ext.n + ext.len - 1));

/* ================================================================ figure data */
fs.mkdirSync(path.dirname(FIGDATA), { recursive: true });
fs.writeFileSync(FIGDATA, JSON.stringify({
  generatedBy: 'tools/paper-numbers/erdos852.js @ git ' + git, c0: A.C0,
  readings: readings.map((r) => ({ e: r.e, index: r.ri, prime: r.rp })),
  bands: bands.filter((b) => b.lo !== null).map((b) => ({ len: b.len, lo: b.lo, hi: b.hi, inside: A.C0 <= b.hi && A.C0 >= b.lo }))
}, null, 1) + '\n');

fs.writeFileSync(OUT, M.join('\n') + '\n');
console.log('wrote paper/tex/erdos852-numbers.tex (' + (M.length - 1) + ' macros) and paper/tex/fig/erdos852-data.json');
