#!/usr/bin/env node
/* henon-entropy.js — every number the review draft paper/tex/henon-entropy.tex quotes,
   read from the records that decided it and written as LaTeX macros to
   paper/tex/henon-entropy-numbers.tex:
     certs/entropy-henon.json          the certificate: h-sets, covering relations, the bound
     certs/census-high-periods.json    the certified cycle counts that name the ceiling
     instruments/entropy/battery.js    the gate, RUN LIVE here (about twenty seconds): the ln 2
                                       calibration, the red controls, the full re-verification
     instruments/entropy/covering.js   the verifier (its budgets and the two defect comments)
     tools/hunt-entropy.js             the proposer's settings
     git                               the commit that introduced the record and the one that
                                       replaced its tainted interim bound
   The paper \inputs this file, so it cannot quote a number the machine did not record; a
   record that no longer says what a sentence needs makes this refuse (need()), exactly as
   tools/build-paper-numbers.js does. Two computations here are NOT part of the record and
   the paper says so where it quotes them: the one-ulp parameter-interval re-run of the
   certificate, and the exact integer power sweep past the recorded m = 8.
   Also writes paper/tex/fig/henon-entropy-figdata.json for henon-entropy-figs.py (the core
   indices and the two relations the figures draw), so the figure never re-derives a rule.
   usage: node tools/paper-numbers/henon-entropy.js                                    MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const T = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const die = (m) => { console.error('PAPER NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const bigint = (x) => x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
/* truncate toward zero: a printed LOWER bound must never round up */
const trunc = (x, d) => (Math.floor(Number(x) * 10 ** d) / 10 ** d).toFixed(d);
const pct = (x, d) => Number(x).toFixed(d) + '\\%';
const sci = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return '$' + m[1] + '\\times10^{' + Number(m[2]) + '}$'; };
const sh = (c) => cp.execSync(c, { cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
const git = (() => { try { return sh('git rev-parse --short=12 HEAD'); } catch (e) { return 'unknown'; } })();
const E = require(path.join(ROOT, 'instruments', 'entropy', 'covering.js'));
const IV = require(path.join(ROOT, 'instruments', 'interval', 'interval.js'));

const M = ['%% generated by tools/paper-numbers/henon-entropy.js from certs/entropy-henon.json, certs/census-high-periods.json, the entropy battery (run live) and git — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));
def('RepoCommit', git);

/* ======================================================= the certificate */
const cert = J('certs/entropy-henon.json');
need(cert.a === 1.4 && cert.b === 0.3, 'the record is not at the classical parameters');
need(Array.isArray(cert.boxes) && Array.isArray(cert.edges) && cert.boxes.length > 0, 'the record holds no h-sets');
const n = cert.boxes.length, edges = cert.edges;
need(edges.every((e) => e.length === 3 && e[0] >= 0 && e[0] < n && e[1] >= 0 && e[1] < n && e[2] >= 1), 'an edge is malformed');
def('HenonA', String(cert.a)); def('HenonB', String(cert.b));
def('NBoxes', int(n)); def('NEdges', int(edges.length));
def('RecordHLBRaw', String(cert.hLB));
def('ComposedK', String(cert.composedTo));

/* the doubles the record is stated for, and the one-ulp intervals around them */
const exactRational = (x) => { /* a finite double as an exact BigInt fraction p/q */
  const b = new DataView(new ArrayBuffer(8)); b.setFloat64(0, x);
  const bits = b.getBigUint64(0); const sign = bits >> 63n ? -1n : 1n;
  const ex = Number((bits >> 52n) & 0x7ffn); const frac = bits & ((1n << 52n) - 1n);
  const mant = ex === 0 ? frac : frac | (1n << 52n); const e = (ex === 0 ? 1 : ex) - 1075;
  return e >= 0 ? [sign * mant * (1n << BigInt(e)), 1n] : [sign * mant, 1n << BigInt(-e)];
};
const lt = (p, q) => p[0] * q[1] < q[0] * p[1];           /* p/q < r/s exactly */
const aLo = IV.nextDown(cert.a), aHi = IV.nextUp(cert.a), bLo = IV.nextDown(cert.b), bHi = IV.nextUp(cert.b);
need(lt(exactRational(cert.a), [7n, 5n]) && lt([7n, 5n], exactRational(aHi)), 'the rational 7/5 is not inside [a, nextUp(a)]');
need(lt(exactRational(cert.b), [3n, 10n]) && lt([3n, 10n], exactRational(bHi)), 'the rational 3/10 is not inside [b, nextUp(b)]');
def('ADouble', cert.a.toPrecision(20)); def('BDouble', cert.b.toPrecision(20));
def('AUlpLo', aLo.toPrecision(20)); def('AUlpHi', aHi.toPrecision(20)); def('BUlpLo', bLo.toPrecision(20)); def('BUlpHi', bHi.toPrecision(20));

/* geometry: every h-set has the same half-lengths (the hunt's scale) */
const uLen = cert.boxes.map((B) => Math.hypot(B.A[0][0], B.A[1][0])), sLen = cert.boxes.map((B) => Math.hypot(B.A[0][1], B.A[1][1]));
const spread = (v) => Math.max(...v) - Math.min(...v);
need(spread(uLen) < 1e-12 && spread(sLen) < 1e-12, 'the h-sets do not share one pair of half-lengths');
need(Math.abs(uLen[0] - cert.config.delta * cert.config.uHalf) < 1e-12 && Math.abs(sLen[0] - cert.config.delta * cert.config.sHalf) < 1e-12, 'half-lengths disagree with the recorded config');
def('UHalf', dec(uLen[0], 4)); def('SHalf', dec(sLen[0], 4)); def('HuntDelta', String(cert.config.delta));
def('UHalfFrac', String(cert.config.uHalf)); def('SHalfFrac', String(cert.config.sHalf));
def('AspectRatio', dec(uLen[0] / sLen[0], 2));
const xs = cert.boxes.map((B) => B.c[0]), ys = cert.boxes.map((B) => B.c[1]);
def('XMin', dec(Math.min(...xs), 2)); def('XMax', dec(Math.max(...xs), 2)); def('YMin', dec(Math.min(...ys), 2)); def('YMax', dec(Math.max(...ys), 2));

/* the graph: durations, pairs, degrees */
const byK = {}; for (const e of edges) byK[e[2]] = (byK[e[2]] || 0) + 1;
const durations = Object.keys(byK).map(Number).sort((a, b) => a - b);
need(durations.join() === '1,2,3,4,5,6', 'the durations are not 1..6');
def('DurMax', String(durations[durations.length - 1]));
let cum = 0;
rows('EdgeRows', durations.map((k) => { cum += byK[k]; return [String(k), int(byK[k]), int(cum), pct(100 * byK[k] / edges.length, 1)]; }));
for (const k of durations) def('EdgesK' + ['One', 'Two', 'Three', 'Four', 'Five', 'Six'][k - 1], int(byK[k]));
const pairs = new Map(); for (const [i, j, k] of edges) { const key = i + ',' + j; if (!pairs.has(key)) pairs.set(key, []); pairs.get(key).push(k); }
def('NPairs', int(pairs.size)); def('NMultiPairs', int([...pairs.values()].filter((v) => v.length > 1).length));
def('NSelfLoops', int(edges.filter((e) => e[0] === e[1]).length));
const outd = new Array(n).fill(0), ind = new Array(n).fill(0); for (const [i, j] of edges) { outd[i]++; ind[j]++; }
def('NNoOut', int(outd.filter((x) => !x).length)); def('NNoIn', int(ind.filter((x) => !x).length));
def('MaxOut', int(Math.max(...outd))); def('MaxIn', int(Math.max(...ind)));
def('MeanOut', dec(edges.length / n, 1));
const U = Array.from({ length: n }, () => new Array(n).fill(0)); for (const [i, j] of edges) U[i][j] = 1;
const comps = E.sccs(U).map((c) => c.length).sort((a, b) => b - a);
def('UnionSCCs', int(comps.length)); def('UnionSCCLargest', int(comps[0])); def('UnionSCCSingletons', int(comps.filter((c) => c === 1).length));

/* ============================== the composed bound, recomputed two ways */
const Aks = {}; for (const [i, j, k] of edges) { if (!Aks[k]) Aks[k] = Array.from({ length: n }, () => new Array(n).fill(0)); Aks[k][i][j] = 1; }
const bat = T('instruments/entropy/battery.js');
const budget = /certifyGraphMixed\(mapC, cert\.boxes, cert\.edges, \{ cells: (\d+), Kmax: (\d+) \}\)/.exec(bat);
need(budget, 'the battery no longer re-verifies the certificate with a cells/Kmax budget');
const CELLS = Number(budget[1]), KMAX = Number(budget[2]);
def('CellBudget', int(CELLS)); def('KMax', String(KMAX));
const cov = T('instruments/entropy/covering.js');
const mw = /minWidth: \(opts && opts\.minWidth\) \|\| ([\d.e-]+)/.exec(cov); need(mw, 'no minWidth default in covering.js');
def('MinWidth', sci(Number(mw[1]), 0));
const mm = /\(opts && opts\.maxM\) \|\| (\d+)\)/.exec(cov); need(mm, 'no maxM default in covering.js');
const MAXM = Number(mm[1]); def('MaxM', String(MAXM));
const lim = /const LIMIT = 2 \*\* (\d+);/.exec(cov); need(lim, 'no overflow limit in covering.js');
def('LimitExp', lim[1]);
/* (1) the instrument's own routine */
const sb = E.composedUniformLB(Aks, n, KMAX, MAXM);
need(sb.K === cert.composedTo, 'the instrument composes to K = ' + sb.K + ', the record says ' + cert.composedTo);
need(Math.abs(sb.logLB - cert.hLB) < 1e-15, 'the instrument recomputes ' + sb.logLB + ', the record says ' + cert.hLB);
def('PowerM', String(sb.m)); def('CoreSize', int(sb.core)); def('MKProduct', String(sb.m * sb.K));
/* (2) the recurrence re-implemented here, per K, with the min row sum kept */
const I = Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => (i === j ? 1 : 0)));
const B = [I]; const perK = []; const LIMIT = 2 ** Number(lim[1]);
const coreOf = (Mx) => { let keep = Array.from({ length: n }, (_, i) => i); for (;;) { const nx = keep.filter((i) => keep.some((j) => Mx[i][j] > 0) && keep.some((j) => Mx[j][i] > 0)); if (nx.length === keep.length) break; keep = nx; if (!keep.length) break; } return keep; };
const KSHOW = 20;
for (let K = 1; K <= KSHOW; K++) {
  const Mx = Array.from({ length: n }, () => new Array(n).fill(0));
  for (const k of durations) { if (k > K) break; const A = Aks[k], P = B[K - k]; for (let i = 0; i < n; i++) { const Ai = A[i], Mi = Mx[i]; for (let l = 0; l < n; l++) { if (!Ai[l]) continue; const Pl = P[l]; for (let j = 0; j < n; j++) if (Pl[j]) Mi[j] = 1; } } }
  B.push(Mx);
  const keep = coreOf(Mx), kn = keep.length; const ones = Mx.reduce((s, r) => s + r.reduce((a, b) => a + b, 0), 0);
  let best = { logLB: 0, m: 0, minRS: 0 };
  if (kn) {
    let P = keep.map((i) => keep.map((j) => Mx[i][j])); const step = P.map((r) => r.slice());
    for (let m = 1; m <= MAXM; m++) {
      let minRS = Infinity; for (let i = 0; i < kn; i++) { let rs = 0; for (let j = 0; j < kn; j++) rs += P[i][j]; minRS = Math.min(minRS, rs); }
      if (minRS > 0 && minRS < LIMIT) { const lb = Math.log(minRS) / (m * K); if (lb > best.logLB) best = { logLB: lb, m, minRS }; }
      if (m === MAXM) break;
      const N = Array.from({ length: kn }, () => new Array(kn).fill(0)); let overflow = false;
      for (let i = 0; i < kn && !overflow; i++) for (let l = 0; l < kn; l++) { if (!P[i][l]) continue; for (let j = 0; j < kn; j++) { N[i][j] += P[i][l] * step[l][j]; if (N[i][j] > LIMIT) { overflow = true; break; } } }
      if (overflow) break; P = N;
    }
  }
  perK.push({ K, ones, core: kn, m: best.m, minRS: best.minRS, bound: best.logLB, keep });
}
const atK = perK[cert.composedTo - 1];
need(atK && Math.abs(atK.bound - cert.hLB) < 1e-15 && atK.m === sb.m && atK.core === sb.core, 'the re-implemented recurrence disagrees with the instrument at K = ' + cert.composedTo);
need(Number.isInteger(atK.minRS) && atK.minRS < 2 ** 53, 'the min row sum is not an exact integer');
need(perK.every((p) => p.bound <= cert.hLB + 1e-15), 'a uniform iterate below ' + KSHOW + ' beats the recorded K');
def('MinRowSum', bigint(BigInt(atK.minRS))); def('MinRowSumRaw', String(atK.minRS));
def('BKOnes', int(atK.ones)); def('BKDensityPct', pct(100 * atK.ones / (n * n), 1));
def('ExactBound', '\\tfrac{1}{' + (sb.m * sb.K) + '}\\ln ' + bigint(BigInt(atK.minRS)));
def('HLB', trunc(cert.hLB, 6)); def('HLBNine', trunc(cert.hLB, 9));
need(Math.abs(Math.log(atK.minRS) / (sb.m * sb.K) - cert.hLB) < 1e-14, 'ln(minRS)/(mK) is not the recorded bound');
def('KShow', String(KSHOW));
rows('KRows', perK.map((p) => [String(p.K), int(p.ones), int(p.core), p.m ? String(p.m) : '--', p.minRS ? bigint(BigInt(p.minRS)) : '--', p.bound ? dec(p.bound, 6) : '0']));
const firstPositive = perK.find((p) => p.bound > 0); def('FirstPositiveK', String(firstPositive.K));
def('BoundKTwelve', dec(perK[11].bound, 6)); def('BoundKThirteen', dec(perK[12].bound, 6)); def('BoundKTen', dec(perK[9].bound, 6)); def('BoundKTwenty', dec(perK[KSHOW - 1].bound, 6));
def('CoreAtTwenty', int(perK[KSHOW - 1].core));
/* the spectral step past the recorded power — exact integers, vector iteration, NOT part of the record */
{
  const keep = atK.keep, kn = keep.length, Mx = B[cert.composedTo];
  const S = keep.map((i) => keep.map((j) => BigInt(Mx[i][j])));
  let v = new Array(kn).fill(1n); const sweep = [];
  for (let m = 1; m <= 32; m++) {
    const w = new Array(kn).fill(0n); for (let i = 0; i < kn; i++) { let s = 0n; const Si = S[i]; for (let j = 0; j < kn; j++) if (Si[j]) s += v[j]; w[i] = s; }
    v = w; let mn = v[0]; for (const x of v) if (x < mn) mn = x;
    const digits = mn.toString().length;
    const lb = Math.log(Number(mn)) / (m * cert.composedTo);
    if (m === sb.m) need(Number(mn) === atK.minRS, 'the vector iteration disagrees with the matrix power at m = ' + m);
    if ([8, 16, 24, 32].includes(m)) sweep.push([String(m), int(digits), trunc(lb, 4)]);
  }
  rows('MRows', sweep);
  def('BoundMThirtyTwo', sweep[sweep.length - 1][2]);
  /* a float spectral radius of the same core, an indication only */
  let f = new Array(kn).fill(1), lam = 0;
  for (let it = 0; it < 500; it++) { const w = new Array(kn).fill(0); for (let i = 0; i < kn; i++) { let s = 0; for (let j = 0; j < kn; j++) if (S[i][j]) s += f[j]; w[i] = s; } lam = Math.max(...w); for (let i = 0; i < kn; i++) f[i] = w[i] / lam; }
  def('FloatSp', dec(lam, 2)); def('FloatBound', dec(Math.log(lam) / cert.composedTo, 4));
}

/* ================================================ the gate, run live */
const t0 = Date.now();
const br = cp.spawnSync('node', ['instruments/entropy/battery.js'], { cwd: ROOT, maxBuffer: 1 << 26 });
const bout = String(br.stdout) + String(br.stderr);
const tally = /entropy battery: (\d+) pass, (\d+) fail/.exec(bout);
need(br.status === 0 && tally && Number(tally[2]) === 0, 'the entropy battery did not pass clean:\n' + bout.slice(-800));
def('BatteryPass', tally[1]); def('BatterySeconds', String(Math.round((Date.now() - t0) / 1000)));
const rev = /re-certifies \((\d+)\/(\d+)\)/.exec(bout);
need(rev && Number(rev[1]) === edges.length && Number(rev[2]) === edges.length, 'the battery did not re-certify every recorded relation');
const cal = /h >= ln 2 exactly \(([\d.]+)\)/.exec(bout); need(cal, 'no calibration line'); def('LnTwoDigits', cal[1]);
need(Math.abs(Number(cal[1]) - Math.log(2)) < 1e-11, 'the calibration is not ln 2');
const sem = /the bound is ln 2, not more \(([\d.]+), (\d+) relations\)/.exec(bout); need(sem, 'no semantic control line');
def('ControlBound', sem[1]); def('ControlRelations', sem[2]);
def('BatteryReds', int((bout.match(/^PASS  RED/gm) || []).length));
/* which condition decided each refusal control: the battery prints the verifier's reason */
const reasons = [...bout.matchAll(/^PASS  RED: a target [^(]*\(([^)]*)/gm)].map((m) => m[1]);
need(reasons.length === 3, 'expected three refusal controls, saw ' + reasons.length);
const byEdge = reasons.filter((r) => /u-edge/.test(r)).length;
def('RedRefusals', String(reasons.length)); def('RedByEdge', String(byEdge)); def('RedBySlab', String(reasons.filter((r) => /s-lid/.test(r)).length));
/* the calibration h-sets, as the battery defines them */
const cc = /const H = ([\d.]+), w = ([\d.]+), x0 = ([\d.]+), kap = ([\d.]+) \* H \/ \((\d+) \* x0\);/.exec(bat);
need(cc, 'the calibration constants moved');
const CalH = Number(cc[1]), CalW = Number(cc[2]), CalX = Number(cc[3]), CalB = Number(cc[4]), CalDen = Number(cc[5]);
def('CalH', cc[1]); def('CalW', cc[2]); def('CalX', cc[3]); def('CalKappa', dec(CalB * CalH / (CalDen * CalX), 4)); def('CalKappaDen', cc[5]);
const calA = /henonSpec\((\d+), ([\d.]+)\)/.exec(bat); need(calA && calA[2] === String(cert.b), 'the calibration map is not at b = ' + cert.b);
def('CalA', calA[1]);
const calCells = /\[\[0, 0\], \[0, 1\], \[1, 0\], \[1, 1\]\], \{ cells: (\d+) \}/.exec(bat); need(calCells, 'no calibration cell budget');
def('CalCells', int(calCells[1]));
/* which durations the semantic control actually certifies on the horseshoe */
{
  const map6 = E.henonSpec(Number(calA[1]), cert.b);
  const kap = CalB * CalH / (CalDen * CalX);
  const Np = { c: [CalX, 0], A: [[CalW, kap], [0, CalH]] }, Nm = { c: [-CalX, 0], A: [[CalW, -kap], [0, CalH]] };
  let one = 0, two = 0, sameSide = 0;
  for (let i = 0; i < 2; i++) for (let j = 0; j < 2; j++) for (const k of [1, 2]) {
    const c = E.covers(map6, [Np, Nm][i], [Np, Nm][j], { cells: Number(calCells[1]), steps: k });
    if (c.ok) { if (k === 1) one++; else two++; } else if (k === 2 && /same side/.test(c.why)) sameSide++;
  }
  need(one + two === Number(sem[2]), 'the control certifies ' + (one + two) + ' relations, its line says ' + sem[2]);
  def('ControlDurOne', String(one)); def('ControlDurTwo', String(two)); def('ControlDurTwoSameSide', String(sameSide));
}

/* ======================= the parameter-interval re-run (drafting check) */
{
  const IA = [aLo, aHi], IB = [bLo, bHi], ONE = IV.iv(1);
  const mapIV = { name: 'henon-interval', fIV: (X) => [IV.add(IV.sub(ONE, IV.mul(IA, IV.sqr(X[0]))), IV.mul(IB, X[1])), X[0]] };
  const g = E.certifyGraphMixed(mapIV, cert.boxes, cert.edges, { cells: CELLS, Kmax: KMAX });
  need(g.ok, 'the interval re-run refused the h-sets');
  def('IntervalRerunCertified', int(g.certified.length)); def('IntervalRerunBound', trunc(g.hLB, 6));
  def('IntervalRerunAll', g.certified.length === edges.length ? 'all' : 'only');
}

/* ================================================ the ceiling */
const census = J('certs/census-high-periods.json');
need(census.length && census.every((r) => r.ok), 'a census record is not ok');
const crow = census.map((r) => ({ p: r.p, N: r.points, rate: Math.log(r.points) / r.p })).sort((a, b) => a.p - b.p);
rows('CensusRows', crow.map((r) => [String(r.p), int(r.N), dec(r.rate, 4)]));
const ceil = crow.reduce((a, r) => (r.rate > a.rate ? r : a));
const pmax = crow[crow.length - 1];
need(ceil.rate > cert.hLB, 'the ceiling is not above the bound');
def('CensusPMin', String(crow[0].p)); def('CensusPMax', String(pmax.p)); def('CensusCount', String(crow.length));
def('Ceiling', dec(ceil.rate, 4)); def('CeilingP', String(ceil.p)); def('CeilingN', int(ceil.N));
def('RatePMax', dec(pmax.rate, 4)); def('NPMax', int(pmax.N));
def('RatioPct', String(Math.round(100 * cert.hLB / ceil.rate))); def('RatioPctPMax', String(Math.round(100 * cert.hLB / pmax.rate)));
def('GapNats', dec(ceil.rate - cert.hLB, 4));
def('LnTwo', dec(Math.log(2), 4)); def('RatioLnTwoPct', String(Math.round(100 * cert.hLB / Math.log(2))));

/* ================== the two defects, as the verifier's own comments record them */
const d1 = /once produced h ≥ (0\.\d+) for a map whose true entropy is\s+≈ (0\.\d+)/.exec(cov);
need(d1, 'covering.js no longer records the mixed-duration defect');
def('DefectOneBound', d1[1]); def('DefectTrueApprox', d1[2]);
const d2 = /converging to ln phi = (0\.\d+), above the literature value\s+(0\.\d+)/.exec(cov);
need(d2, 'covering.js no longer records the lids-only defect');
def('DefectTwoBound', d2[1]); def('LitValue', d2[2]);
need(Math.abs(Math.log((1 + Math.sqrt(5)) / 2) - Number(d2[1])) < 1e-4, 'the quoted ln phi is not ln phi');
def('LnPhi', dec(Math.log((1 + Math.sqrt(5)) / 2), 4));
need(Number(d1[1]) > Number(d2[2]) && Number(d2[1]) > Number(d2[2]), 'the defect numbers are not above the literature value');

/* ============================================= the proposer's settings */
const hunt = T('tools/hunt-entropy.js');
const op = /orbitPoints\((\d+)\)/.exec(hunt); need(op, 'no orbit sample size in the hunt');
def('OrbitPoints', int(op[1]));
const scales = (hunt.match(/\{ delta: [\d.]+, uHalf: [\d.]+, sHalf: [\d.]+ \}/g) || []).length;
need(scales > 0, 'no scale list in the hunt'); def('NScales', String(scales));
const rho = /candidates\(boxes, ([\d.]+) \* cfg\.delta, k\)/.exec(hunt); need(rho, 'no candidate radius in the hunt');
def('CandRho', rho[1]);
const trans = /for \(let i = 0; i < (\d+); i\+\+\) \{ const \[nx, ny\] = map\.fF\(x, y\); x = nx; y = ny; \}/.exec(hunt); need(trans, 'no transient length in the hunt');
def('Transient', int(trans[1]));
need(cert.huntedBy === 'tools/hunt-entropy.js', 'the record names another proposer');

/* =================================================== git: the two commits */
const hist = sh("git log --format='%h|%ad' --date=short -- certs/entropy-henon.json").split('\n').filter(Boolean).map((l) => l.split('|'));
need(hist.length >= 2, 'the record has fewer than two commits');
const first = hist[hist.length - 1], second = hist[hist.length - 2];
const old = JSON.parse(sh('git show ' + first[0] + ':certs/entropy-henon.json'));
const sound = JSON.parse(sh('git show ' + second[0] + ':certs/entropy-henon.json'));
need(old.hLB > cert.hLB, 'the first committed record did not carry a higher (tainted) bound');
need(sound.hLB === cert.hLB && sound.edges.length === edges.length, 'the second commit of the record is not the one in force');
def('RecordCommit', first[0]); def('RecordDate', first[1]); def('SoundCommit', second[0]); def('SoundDate', second[1]);
def('TaintedBound', dec(old.hLB, 6)); def('TaintedBoxes', int(old.boxes.length)); def('TaintedEdges', int(old.edges.length)); const oldK = old.composedTo || old.steps; need(oldK, 'the first record names no iterate'); def('TaintedK', String(oldK)); def('TaintedShape', old.composedTo ? 'composed' : 'uniform');
def('RecordCommits', String(hist.length));
const soundSubject = sh('git log -1 --format=%s ' + second[0]);
need(/sound bound/.test(soundSubject), 'the second commit does not name itself the sound bound');

/* ============================================= the figure's data sidecar */
{
  const mapF = E.henonSpec(cert.a, cert.b);
  const extent = (e) => { /* float, for choosing an example to draw; decides nothing */
    const [i, j, k] = e; const N1 = cert.boxes[i], N2 = cert.boxes[j], A = N2.A;
    const det = A[0][0] * A[1][1] - A[0][1] * A[1][0]; const inv = [[A[1][1] / det, -A[0][1] / det], [-A[1][0] / det, A[0][0] / det]];
    let umin = Infinity, umax = -Infinity;
    for (let a = -1; a <= 1.0001; a += 0.02) for (const b of [-1, 1]) for (const [tu, ts] of [[a, b], [b, a]]) {
      let x = N1.c[0] + N1.A[0][0] * tu + N1.A[0][1] * ts, y = N1.c[1] + N1.A[1][0] * tu + N1.A[1][1] * ts;
      for (let s = 0; s < k; s++) { const q = mapF.fF(x, y); x = q[0]; y = q[1]; }
      const u = inv[0][0] * (x - N2.c[0]) + inv[0][1] * (y - N2.c[1]); umin = Math.min(umin, u); umax = Math.max(umax, u);
    }
    return umax - umin;
  };
  const egOne = edges.find((e) => e[2] === 1);
  const sixes = edges.filter((e) => e[2] === durations[durations.length - 1]);
  const egSix = sixes.map((e) => ({ e, x: extent(e) })).sort((p, q) => p.x - q.x)[0].e;
  def('FigEdgeOne', egOne[0] + '\\to' + egOne[1]); def('FigEdgeSix', egSix[0] + '\\to' + egSix[1]);
  def('FigEdgeSixK', String(egSix[2]));
  const fig = { what: 'written by tools/paper-numbers/henon-entropy.js for henon-entropy-figs.py — the core of B_K at the recorded K, the two relations the figures draw, the calibration h-sets as the battery defines them; decides nothing', git, K: cert.composedTo, core: atK.keep, edgeOne: egOne, edgeSix: egSix, calibration: { a: Number(calA[1]), b: cert.b, H: CalH, w: CalW, x0: CalX, kappa: CalB * CalH / (CalDen * CalX) } };
  fs.mkdirSync(path.join(OUT, 'fig'), { recursive: true });
  fs.writeFileSync(path.join(OUT, 'fig', 'henon-entropy-figdata.json'), JSON.stringify(fig) + '\n');
}

fs.writeFileSync(path.join(OUT, 'henon-entropy-numbers.tex'), M.join('\n') + '\n');
console.log('wrote paper/tex/henon-entropy-numbers.tex (' + (M.length - 1) + ' macros) and paper/tex/fig/henon-entropy-figdata.json');
