#!/usr/bin/env node
/* lambda5.js — every number the lambda(5) pre-paper (paper/tex/lambda5.tex) quotes,
   read from the records that decided it and written as LaTeX macros:
     paper/tex/lambda5-numbers.tex
   Records read: certs/lambda56-campaign.json (the lambda(5)/lambda(6) campaign),
   certs/lambda5-audit.json (the independent walk), certs/lambda4-campaign.json and
   certs/lambda4-audit.json (the companion theorem, quoted only as calibration),
   certs/lambda-table.json, certs/mu-table.json, certs/mu-table-40.json,
   certs/mercer-mu5.json, certs/chowla-records.json (the Mercer-program landscape),
   and HANDOFF.md for the lambda(6) run facts that no certificate holds (the open
   family's hours, the traced twin), which are quoted as session-log facts.
   Live, sub-second, exactly as reports/lambda5.html re-derives them at every build:
   the target enclosures, the minimal polynomials (calibrated on Mercer's lambda(3)
   and the lambda(4) cubic before lambda(5) is read), the double-sum-core theorem with
   its comb weight and the eight classical refusals that justify it, the equality
   certificate M(0,1,2,6,9) = 1, and the lambda56 battery (about five seconds).
   The paper \inputs this file, so it cannot quote a number the machine did not record;
   a record that no longer says what a sentence needs makes this refuse (need()), as
   tools/build-paper-numbers.js does for the Elsevier manuscripts.
   usage: node tools/paper-numbers/lambda5.js                                      MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex', 'lambda5-numbers.tex');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const die = (m) => { console.error('LAMBDA5 PAPER NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
/* a small or large number in scientific form, as math: $5.3\times10^{-14}$ */
const sci = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return '$' + m[1] + '\\times10^{' + Number(m[2]) + '}$'; };
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();

const EN = require(path.join(ROOT, 'instruments', 'lambda4', 'engine.js'));
const D = require(path.join(ROOT, 'instruments', 'lambda4', 'dot.js'));
const F = require(path.join(ROOT, 'instruments', 'lambda4', 'forms.js'));
const MP = require(path.join(ROOT, 'instruments', 'trigmin', 'minpoly.js'));
const SW = require(path.join(ROOT, 'instruments', 'trigmin', 'sweep.js'));
const Q = require(path.join(ROOT, 'instruments', 'interval', 'rational.js'));
const q = D.q;

/* ---- exact decimal printing of rationals, rounded OUTWARD ------------------
   a lower end is rounded down, an upper end up, so a printed enclosure is still
   an enclosure; the rationals in the records are dyadic strings "n/d". */
const parseQ = (s) => { const m = String(s).split('/'); return { n: BigInt(m[0]), d: BigInt(m[1] || 1) }; };
const floorDiv = (a, b) => { const r = a / b; return (a % b !== 0n && ((a < 0n) !== (b < 0n))) ? r - 1n : r; };
const fmtScaled = (v, k) => { const neg = v < 0n; const s = (neg ? -v : v).toString().padStart(k + 1, '0'); return (neg ? '-' : '') + s.slice(0, s.length - k) + '.' + s.slice(s.length - k); };
const qFloor = (r, k) => fmtScaled(floorDiv(r.n * 10n ** BigInt(k), r.d), k);
const qCeil = (r, k) => fmtScaled(-floorDiv(-r.n * 10n ** BigInt(k), r.d), k);
const qCmp = (a, b) => { const s = a.n * b.d - b.n * a.d; return s < 0n ? -1 : s > 0n ? 1 : 0; };
const negQ = (r) => ({ n: -r.n, d: r.d });
const dblQ = (x) => { const r = Q.fromDouble(x); return { n: r.n, d: r.d }; };
/* lambda = -L: the LOWER end of lambda is -L.hi (rounded down), the UPPER end -L.lo (up) */
const lamLo = (L, k) => qFloor(negQ(parseQ(L.hi)), k);
const lamHi = (L, k) => qCeil(negQ(parseQ(L.lo)), k);
const fmtTime = (ms) => ms < 1000 ? '$<1$ s' : ms < 60000 ? dec(ms / 1000, 0) + ' s' : ms < 3600000 ? dec(ms / 60000, 1) + ' min' : dec(ms / 3600000, 2) + ' h';
const mset = (A) => '$\\{' + A.join(',') + '\\}$';
const mcond = (s) => '$' + s.replace(/ = /g, '=') + '$';
const mfrac = (s) => s;                       /* raw: used inside math in the paper */
const mfracT = (s) => '$' + s + '$';      /* text-mode: table cells and prose */
const poly = (s) => s.replace(/\^(\d+)/g, '^{$1}');

/* ---- the writer ------------------------------------------------------------- */
const M = ['%% generated by tools/paper-numbers/lambda5.js from certs/lambda56-campaign.json, certs/lambda5-audit.json, certs/lambda4-campaign.json, certs/lambda4-audit.json, certs/lambda-table.json, certs/mu-table.json, certs/mu-table-40.json, certs/mercer-mu5.json, certs/chowla-records.json and HANDOFF.md — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));
def('RepoCommit', git);

/* ======================================================================= */
/* 1. the campaign record                                                   */
/* ======================================================================= */
const REC = J('certs/lambda56-campaign.json');
const st = REC.stages || {};
for (const k of Object.keys(st)) need(st[k].ok === true, 'stage ' + k + ' is not ok in the campaign record');
need(REC.meta && REC.meta.failures === 0, 'the campaign record reports failures');
def('CampaignDate', REC.meta.date); def('CampaignGit', REC.meta.git); def('CampaignHours', dec(REC.meta.ms / 3600000, 1));

/* targets: recorded, and re-derived live (the page does the same) */
const T = st.targets;
need(T && T.L4 && T.L5 && T.L6 && T.initialSegments, 'the targets stage is incomplete');
const live5 = EN.targetEnclosure([1, 2, 4, 5, 6]), live6 = EN.targetEnclosure([1, 2, 4, 6, 7, 8]);
need(Q.toString(live5.lo) === T.L5.lo && Q.toString(live5.hi) === T.L5.hi, 'the live L(1,2,4,5,6) enclosure differs from the recorded one');
need(Q.toString(live6.lo) === T.L6.lo && Q.toString(live6.hi) === T.L6.hi, 'the live L(1,2,4,6,7,8) enclosure differs from the recorded one');
need(T.L5.A.join(',') === '1,2,4,5,6' && T.L6.A.join(',') === '1,2,4,6,7,8', 'the recorded target sets moved');
def('LfiveLoRat', T.L5.lo.replace('/', '/')); def('LfiveHiRat', T.L5.hi);
def('LfiveRatLo', '\\tfrac{' + T.L5.lo.split('/')[0] + '}{' + T.L5.lo.split('/')[1] + '}');
def('LfiveRatHi', '\\tfrac{' + T.L5.hi.split('/')[0] + '}{' + T.L5.hi.split('/')[1] + '}');
def('LamFiveLo', lamLo(T.L5, 14)); def('LamFiveHi', lamHi(T.L5, 14));
def('LamFiveShort', lamLo(T.L5, 7));
def('LamFiveLoTwelve', lamLo(T.L5, 12)); def('LamFiveHiTwelve', lamHi(T.L5, 12));
def('LamSixUp', lamHi(T.L6, 14)); def('LamSixUpShort', lamHi(T.L6, 7));
def('LamSixUpTwelve', lamHi(T.L6, 12)); def('LamSixLoTwelve', lamLo(T.L6, 12));
def('LsixRatLo', '\\tfrac{' + T.L6.lo.split('/')[0] + '}{' + T.L6.lo.split('/')[1] + '}');
def('LsixRatHi', '\\tfrac{' + T.L6.hi.split('/')[0] + '}{' + T.L6.hi.split('/')[1] + '}');
def('LamFourLo', lamLo(T.L4, 13)); def('LamFourHi', lamHi(T.L4, 13)); def('LamFourShort', lamLo(T.L4, 7));
/* the descent: L(1,2,4,5,6).hi < L(1,2,4,6,7,8).lo, i.e. lambda(6) <= -L6.lo < -L5.hi <= lambda(5) */
need(qCmp(parseQ(T.L5.hi), parseQ(T.L6.lo)) < 0, 'the non-monotonicity comparison L5.hi < L6.lo no longer holds');
need(/certified/.test(T.nonMonotonicity || ''), 'the record no longer certifies the non-monotonicity comparison');
/* and the sequence still rises at 5: L5.hi < L4.lo */
need(qCmp(parseQ(T.L5.hi), parseQ(T.L4.lo)) < 0, 'lambda(5) no longer sits above lambda(4)');
/* initial segments are not the optimisers */
const S5 = T.initialSegments.seg5, S6 = T.initialSegments.seg6;
need(S5.A.join(',') === '1,2,3,4,5' && S6.A.join(',') === '1,2,3,4,5,6', 'the initial-segment sets moved');
need(qCmp(parseQ(S5.hi), parseQ(T.L5.lo)) < 0, '{1..5} no longer dips strictly below {1,2,4,5,6}');
need(qCmp(parseQ(S6.hi), parseQ(T.L6.lo)) < 0, '{1..6} no longer dips strictly below {1,2,4,6,7,8}');
rows('SegRows', [
  [mset(S5.A), '$[' + lamLo(S5, 6) + ',\\ ' + lamHi(S5, 6) + ']$', mset(T.L5.A), '$[' + lamLo(T.L5, 6) + ',\\ ' + lamHi(T.L5, 6) + ']$'],
  [mset(S6.A), '$[' + lamLo(S6, 6) + ',\\ ' + lamHi(S6, 6) + ']$', mset(T.L6.A), '$[' + lamLo(T.L6, 6) + ',\\ ' + lamHi(T.L6, 6) + ']$']
]);
def('SegFiveLo', lamLo(S5, 6)); def('SegSixLo', lamLo(S6, 6));

/* the lambda(2), lambda(3) values and the lambda(4) record (calibration, quoted) */
const R4 = J('certs/lambda4-campaign.json');
need(R4.targets && R4.targets.L2exact === '-9/8', 'the lambda(4) record no longer carries lambda(2) = 9/8 exactly');
def('LamThreeLo', lamLo(R4.targets.L3, 7)); def('LamThreeHi', lamHi(R4.targets.L3, 7));
def('LamTwoLo', lamLo(R4.targets.L2, 6));
{
  const fams4 = R4.lambda4families || {};
  const names4 = Object.keys(fams4);
  need(names4.length === 9 && names4.every((n) => fams4[n].status === 'CLOSED'), 'the lambda(4) record does not hold nine CLOSED families');
  let fin = 0, sets = 0, skips = [];
  (function w(o) { if (!o || typeof o !== 'object') return; if (Array.isArray(o)) return o.forEach(w);
    if (o.enumerated !== undefined && o.undecided !== undefined) { fin++; sets += o.closed; need(!o.undecided.length, 'an undecided finite part in the lambda(4) record'); for (const s of (o.skipped || [])) skips.push(s); }
    Object.values(o).forEach(w); })(fams4);
  need(skips.every((s) => s === '1,2,3,4'), 'a set other than {1,2,3,4} is skipped in the lambda(4) record');
  const g4 = R4.lambda4generic;
  need(g4 && g4.exceptions.length === 14 && g4.worklist.length === 9 && g4.closedFree.length === 5, 'the lambda(4) generic structure moved');
  def('LfourFamilies', String(names4.length)); def('LfourFiniteParts', String(fin)); def('LfourSets', int(sets)); def('LfourSkips', String(skips.length));
  def('LfourConditions', String(g4.exceptions.length)); def('LfourNegative', String(g4.closedFree.length)); def('LfourDip', mfrac(g4.dip));
  def('LfourCampaignDate', R4.meta.date); def('LfourCampaignGit', R4.meta.git);
  const A4 = J('certs/lambda4-audit.json');
  need(A4.sweep && A4.sweep.refuters === 0, 'the lambda(4) audit records refuters');
  def('LfourAuditBox', String(A4.box)); def('LfourAuditSets', int(A4.setsWalked)); def('LfourAuditRecert', int(A4.finiteRecertified)); def('LfourAuditDate', A4.meta.date);
  const L3f = R4.lambda3 && R4.lambda3.families;
  need(Array.isArray(L3f) && L3f.length === 3, 'the lambda(3) calibration no longer discovers three exception families');
  def('LthreeFamilies', String(L3f.length));
}

/* the generic case */
const G = st['lambda5-generic'];
need(G.base === '0' && G.dip === '-5/3' && G.posBase === '3', 'the lambda(5) generic case moved (base, dip or weight average)');
need(G.exceptions.length === 15, 'the generic case no longer carries fifteen conditions');
const sgn = (s) => Math.sign(Number(parseQ(s).n));
const pos = G.exceptions.filter((e) => sgn(e.delta) > 0), negs = G.exceptions.filter((e) => sgn(e.delta) < 0);
need(pos.length === 8 && negs.length === 7 && G.worklist.length === 8 && G.closedFree.length === 7, 'the 15 = 8 + 7 split moved');
need(/g0 = 2\/3/.test(G.weight) && /2\(1-cos d\)\^2/.test(G.weight), 'the generic weight is no longer 2(1-cos d)^2 at g0 = 2/3');
def('GenConditions', String(G.exceptions.length)); def('GenPositive', String(pos.length)); def('GenNegative', String(negs.length));
def('GenBase', mfrac(G.base)); def('GenDip', mfrac(G.dip)); def('GenPosBase', mfrac(G.posBase));
rows('GenericRows', G.exceptions.map((e) => [mcond(e.label), mfracT(e.delta), sgn(e.delta) > 0 ? 'family, proof needed' : 'closes itself',
  mset(['a', 'b', 'c', 'd', 'e'].map((k) => e.example[k]))]));
const esc = G.extremizerEscape;
need(esc.set.join(',') === '1,2,4,5,6' && esc.active.length === 3 && sgn(esc.deltaSum) > 0, 'the extremizer no longer escapes the generic argument through three conditions');
def('EscapeCount', String(esc.active.length)); def('EscapeSum', mfrac(esc.deltaSum));
def('EscapeList', esc.active.map((s) => { const m = /^(.*) \((.*)\)$/.exec(s); return mcond(m[1]) + ' (delta ' + mfracT(m[2]) + ')'; }).join(', '));

/* the eight families: the tree walk, reconciled with the run's own stats */
const EXT = '1,2,4,5,6';
function walkTree(node, ext) {
  const o = { dots: 0, closures: 0, finiteParts: 0, sets: 0, walls: 0, depth: 0, rays: 0, delegates: 0, other: [] };
  (function w(n, d) {
    if (!n || typeof n !== 'object') return;
    if (Array.isArray(n)) return n.forEach((x) => w(x, d));
    if (n.kind === 'dot') o.dots++;
    if (n.kind === 'ray') o.rays++;
    if (n.kind === 'delegate') o.delegates++;
    if (n.closures) o.closures += n.closures.length;
    if (n.enumerated !== undefined && n.undecided !== undefined) {
      o.finiteParts++; o.sets += n.closed;
      if (n.undecided.length) o.other.push('UNDECIDED');
      for (const s of (n.skipped || [])) { if (s === ext) o.walls++; else o.other.push(s); }
    }
    if (d > o.depth) o.depth = d;
    Object.values(n).forEach((v) => w(v, d + 1));
  })(node, 0);
  o.rootParts = node && node.parts ? node.parts.length : 0;
  return o;
}
const fams = [];
for (const w of G.worklist) {
  const s = st['lambda5-family: ' + w.family];
  need(s && s.status === 'CLOSED' && s.rootKey === w.key, 'family ' + w.family + ' is not CLOSED under its own condition key');
  const o = walkTree(s.node, EXT);
  need(!o.other.length, 'family ' + w.family + ': an undecided part or a skipped non-extremizer');
  need(o.dots === s.stats.dots && o.closures === s.stats.closures && o.sets === s.stats.finiteSets, 'family ' + w.family + ': the tree walk and the recorded stats disagree');
  need(s.ontoChecked > 0, 'family ' + w.family + ' carries no coverage points');
  fams.push(Object.assign({ name: w.family, delta: w.delta, onto: s.ontoChecked, ms: s.ms }, o));
}
const tot = fams.reduce((a, f) => ({ dots: a.dots + f.dots, closures: a.closures + f.closures, sets: a.sets + f.sets, parts: a.parts + f.finiteParts, walls: a.walls + f.walls, onto: a.onto + f.onto, depth: Math.max(a.depth, f.depth) }), { dots: 0, closures: 0, sets: 0, parts: 0, walls: 0, onto: 0, depth: 0 });
const wallFams = fams.filter((f) => f.walls > 0);
const escLabels = new Set(esc.active.map((s) => s.replace(/ \(.*\)$/, '')));
need(wallFams.length > 0 && wallFams.every((f) => escLabels.has(f.name)), 'the extremizer is walled in a family whose condition it does not satisfy, or nowhere');
const adW = fams.find((f) => f.name === 'a+d = e');
need(adW && adW.walls === 4, 'the a+d = e tree no longer walls the extremizer four times');
def('FamDots', String(tot.dots)); def('FamClosures', String(tot.closures)); def('FamSets', int(tot.sets)); def('FamParts', String(tot.parts));
def('FamWalls', String(tot.walls)); def('FamOnto', int(tot.onto)); def('FamDepth', String(tot.depth)); def('FamWallFams', String(wallFams.length));
def('FamWallList', wallFams.map((f) => mcond(f.name) + ' (' + f.walls + ')').join(' and '));
def('AdWalls', String(adW.walls));
const famWord = { 1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six', 7: 'seven', 8: 'eight', 9: 'nine', 10: 'ten' };
def('FamWallsWord', famWord[tot.walls] || String(tot.walls));
rows('FamilyRows', fams.map((f) => [mcond(f.name), mfracT(f.delta), f.rootParts ? String(f.rootParts) : '1', String(f.dots), String(f.closures), String(f.finiteParts), int(f.sets), int(f.onto), String(f.depth), f.walls ? String(f.walls) : '--']));
const direct = fams.filter((f) => f.closures === 0 && f.sets === 0);
def('FamDirect', String(direct.length)); def('FamDirectList', direct.map((f) => mcond(f.name)).join(', '));
const famMaxSets = fams.reduce((a, f) => f.sets > a.sets ? f : a, fams[0]);
def('FamMaxSetsName', mcond(famMaxSets.name)); def('FamMaxSets', int(famMaxSets.sets));
const famMaxCones = fams.reduce((a, f) => f.rootParts > a.rootParts ? f : a, fams[0]);
def('FamMaxConesName', mcond(famMaxCones.name)); def('FamMaxCones', String(famMaxCones.rootParts));

/* the double-sum core: re-derived live with the comb weight, and the eight classical
   refusals that make the comb necessary (exactly the page's check) */
{
  const L5 = live5;
  const U = { n: 3, names: ['a', 'u', 'v'], member: { a: [1n, 0n, 0n], b: [1n, 1n, 0n], c: [1n, 1n, 1n], d: [1n, 2n, 1n], e: [2n, 2n, 1n] }, defs: {} };
  const ae = F.add(U.member.a, U.member.e), be = F.add(U.member.b, U.member.e);
  const terms = [];
  [1n, 1n].forEach((cj, j) => [5n, 7n, 5n].forEach((ck, k) => terms.push({ form: F.add(F.scale(ae, j), F.scale(be, k)), coeff: Q.R(cj * ck, 1n) })));
  const core = EN.dotTheorem({ C: U, S: { order: U.member.e, xi: D.XI_2PI3, Bmax: 14 }, W: [{ atom: { kind: 'sq', terms }, coeff: q(1) }], gConst: q(7, 6), gMembers: ['a', 'b', 'c', 'd'], anchored: ['e'], target: L5, witnessBox: 20 });
  need(core.ok && core.base === '-8' && core.dip === '-5/3', 'the double-sum core theorem no longer derives with base -8 and dip -5/3');
  const cpos = core.exceptions.filter((e) => e.deltaSign > 0);
  need(cpos.length === 6, 'the core theorem no longer carries six positive conditions');
  let refused = 0;
  for (const mm of ['a', 'b', 'c', 'd']) for (const xi of [D.XI_PI, D.XI_2PI3]) {
    const r = EN.dotTheorem({ C: U, S: { order: U.member.e, xi }, W: [{ atom: { kind: 'omcsq', form: U.member[mm] }, coeff: q(2) }], gConst: xi === D.XI_PI ? q(2, 3) : q(7, 6), gMembers: ['a', 'b', 'c', 'd'], anchored: ['e'], target: L5, witnessBox: 16 });
    need(!r.ok, 'a classical atom now closes the double-sum core: the comb weight would be unjustified');
    refused++;
  }
  def('CoreBase', mfrac(core.base)); def('CoreDip', mfrac(core.dip)); def('CorePositive', String(cpos.length)); def('CoreRefusals', String(refused));
  def('CoreConditions', String(core.exceptions.length));
}

/* ======================================================================= */
/* 2. the exact value: minimal polynomials, calibrated first                */
/* ======================================================================= */
{
  const L3 = EN.targetEnclosure([1, 2, 3]), L4 = EN.targetEnclosure([1, 2, 3, 4]);
  const c3 = MP.certifyMinPoly([1, 2, 3], L3), c4 = MP.certifyMinPoly([1, 2, 3, 4], L4);
  need(c3.ok && MP.fmt(c3.S, 'y') === '27y^2 - 34y - 2', 'the lambda(3) calibration polynomial no longer derives');
  need(c4.ok && MP.fmt(c4.S, 'y') === '512y^3 - 1227y^2 + 600y + 125', 'the lambda(4) calibration cubic no longer derives');
  const c5 = MP.certifyMinPoly([1, 2, 4, 5, 6], live5);
  need(c5.ok && c5.degree === 5 && c5.irreducible && c5.rootsInEnclosure === 1 && c5.crossChecked === true, 'the lambda(5) minimal-polynomial certificate weakened');
  def('PolyThree', poly(MP.fmt(c3.S, 'y'))); def('PolyFour', poly(MP.fmt(c4.S, 'y')));
  def('Quintic', poly(MP.fmt(c5.S, 'y'))); def('PolyP', poly(MP.fmt(c5.P, 'c')));
  def('QuinticDegree', String(c5.degree)); def('QuinticPrime', String(c5.prime));
  def('PolyPatOne', String(c5.endpoints.at1)); def('PolyPatMinusOne', String(c5.endpoints.atMinus1));
  def('PolyFourPrime', String(c4.prime)); def('PolyThreePrime', String(c3.prime));
  const c6 = MP.certifyMinPoly([1, 2, 4, 6, 7, 8], live6);
  need(c6.ok && c6.irreducible && c6.rootsInEnclosure === 1, 'the lambda(6) witness polynomial no longer certifies');
  def('SixDegree', String(c6.degree)); def('SixPrime', String(c6.prime)); def('SixPoly', poly(MP.fmt(c6.S, 'y')));
  /* the degree-7 polynomial is too wide for one line: split at a term boundary, four terms and the rest */
  { const terms = MP.fmt(c6.S, 'y').split(/ (?=[+-] )/); need(terms.length === 8, 'the lambda(6) witness polynomial no longer has eight terms'); def('SixPolyA', poly(terms.slice(0, 4).join(' '))); def('SixPolyB', poly(terms.slice(4).join(' '))); }
  def('SixCross', c6.crossChecked === true ? 'cross-checked' : 'not cross-checked (the exhaustive second test runs to degree five only)');
}

/* ======================================================================= */
/* 3. the independent audit                                                 */
/* ======================================================================= */
const A = J('certs/lambda5-audit.json');
need(A.refuters === 0, 'the audit records refuters of the theorem');
need(A.target.lo === T.L5.lo && A.target.hi === T.L5.hi, 'the audit ran against a different target enclosure');
need(A.genericClosed + A.familyReached === A.setsWalked, 'the audit\'s generic/family split does not cover the box');
need(A.screened + A.exactlyCertified === A.setsWalked, 'the audit\'s screened/certified split does not cover the box');
def('AudBox', String(A.box)); def('AudSets', int(A.setsWalked)); def('AudScreened', int(A.screened)); def('AudExact', String(A.exactlyCertified));
def('AudScreenAudited', int(A.screenAudited)); def('AudSampleEvery', String(A.sampleEvery)); def('AudRefuters', String(A.refuters));
def('AudGenericClosed', int(A.genericClosed)); def('AudFamilyReached', int(A.familyReached));
def('AudGenericPct', dec(100 * A.genericClosed / A.setsWalked, 1));
def('AudWorstGeneric', sci(A.worstGenericInnerProduct, 1)); def('AudMinWeight', dec(A.minGenericWeightAverage, 3));
def('AudSymGap', sci(A.symbolicVsNumeric.worstGap, 1)); def('AudCoreGap', sci(A.symbolicVsNumeric.coreWorstGap, 1));
def('AudSymWorstAt', mset(A.symbolicVsNumeric.worstAt));
def('AudCorePoints', String(A.obstruction.corePoints)); def('AudCancel', sci(A.obstruction.worstCancellationResidual, 1));
def('AudClassicalWorst', dec(A.obstruction.classicalWorstInnerProduct, 3)); def('AudCombPoints', String(A.obstruction.combGenericPoints));
def('AudCombWorst', dec(A.obstruction.combWorstInnerProduct, 3)); def('AudDilations', String(A.dilationsChecked));
def('AudDate', A.meta.date); def('AudGit', A.meta.git); def('AudSeconds', String(Math.round(A.meta.ms / 1000)));

/* ======================================================================= */
/* 4. the battery, live                                                     */
/* ======================================================================= */
{
  const r = cp.spawnSync('node', ['instruments/lambda56/battery.js'], { cwd: ROOT, maxBuffer: 1 << 26 });
  const out = String(r.stdout) + String(r.stderr);
  const m = /(\d+) pass, (\d+) fail, (\d+) red controls fired/.exec(out);
  need(r.status === 0 && m && Number(m[2]) === 0, 'the lambda56 battery did not pass clean:\n' + out.slice(-600));
  def('BatteryPass', m[1]); def('BatteryReds', m[3]);
}

/* ======================================================================= */
/* 5. lambda(6): the open front                                             */
/* ======================================================================= */
const G6 = st['lambda6-generic'];
need(G6.base === '0' && G6.dip === '-5/3', 'the lambda(6) generic case moved');
need(G6.exceptions.length === 19 && G6.worklist.length === 10 && G6.closedFree.length === 9, 'the lambda(6) 19 = 10 + 9 split moved');
def('SixConditions', String(G6.exceptions.length)); def('SixPositive', String(G6.worklist.length)); def('SixNegative', String(G6.closedFree.length));
const e6 = G6.extremizerEscape;
need(e6.set.join(',') === '1,2,4,6,7,8' && e6.active.length === 3 && sgn(e6.deltaSum) > 0, 'the lambda(6) witness no longer escapes through three conditions');
def('SixEscapeSum', mfrac(e6.deltaSum));
const six = []; let closed6 = 0, open6 = [];
const t6 = { dots: 0, closures: 0, sets: 0, onto: 0 };
for (const w of G6.worklist) {
  const s = st['lambda6-family: ' + w.family];
  if (!s) { open6.push(w.family); six.push([mcond(w.family), mfracT(w.delta), 'open', '--', '--', '--', '--', '--']); continue; }
  need(s.status === 'CLOSED' && s.rootKey === w.key, 'lambda(6) family ' + w.family + ' present but not CLOSED under its key');
  const o = walkTree(s.node, '1,2,4,6,7,8');
  need(!o.other.length, 'lambda(6) family ' + w.family + ': an undecided part or a skipped non-witness');
  closed6++; t6.dots += s.stats.dots; t6.closures += s.stats.closures; t6.sets += s.stats.finiteSets; t6.onto += s.ontoChecked;
  six.push([mcond(w.family), mfracT(w.delta), 'closed', String(s.stats.dots), String(s.stats.closures), int(s.stats.finiteSets), int(s.ontoChecked), fmtTime(s.ms)]);
}
need(closed6 === 9 && open6.length === 1 && open6[0] === 'a+2e = 2f', 'the lambda(6) state is no longer nine closed and a+2e = 2f open');
rows('SixRows', six);
def('SixClosed', String(closed6)); def('SixOpen', mcond(open6[0])); def('SixDots', String(t6.dots)); def('SixClosures', String(t6.closures));
def('SixSets', int(t6.sets)); def('SixOnto', int(t6.onto));
const heavy6 = G6.worklist.map((w) => st['lambda6-family: ' + w.family]).filter(Boolean).reduce((a, s) => s.ms > a.ms ? s : a);
def('SixHeaviest', mcond(heavy6.rootKey === '1,1,0,0,0,-2' ? 'b+2e = 2f' : heavy6.node.label)); def('SixHeaviestTime', fmtTime(heavy6.ms));
def('SixHeaviestSets', int(heavy6.stats.finiteSets));
/* the session-log facts about the open family, read from HANDOFF.md */
{
  const H = fs.readFileSync(path.join(ROOT, 'HANDOFF.md'), 'utf8');
  const h1 = /a\+2e = 2f at ~([\d.]+) h/.exec(H); need(h1, 'HANDOFF no longer records the a+2e = 2f run hours');
  const h2 = /pid 90265, (\d+)\+ hours at node (\d+)/.exec(H); need(h2, 'HANDOFF no longer records the stalled node of the a+2e = 2f run');
  const h3 = /Three runs\s+have died there/.exec(H); need(h3, 'HANDOFF no longer records that three runs died at that node');
  const h4 = /(\d+) nodes in the first (\d+) seconds/.exec(H); need(h4, 'HANDOFF no longer records the traced twin\'s first nodes');
  const h5 = /(\d+) nodes, ([\d.]+) min, steady ~(\d+) nodes\/min, max depth (\d+)/.exec(H); need(h5, 'HANDOFF no longer records the traced baseline family');
  const h6 = /#(\d+), at depth (\d+) with n=(\d+)/.exec(H); need(h6, 'HANDOFF no longer records the twin\'s stalled node');
  const h7 = /brute-force sweep to max ≤ (\d+)/.exec(H); need(h7, 'HANDOFF no longer records the outside audit\'s sweep bound');
  const h8 = /held the process for (\d+)\+ minutes/.exec(H); need(h8, 'HANDOFF no longer records how long the twin\'s stalled node held');
  def('LogStallMinutes', h8[1]);
  def('LogOpenHours', h1[1]); def('LogOpenHoursMax', h2[1]); def('LogOpenNode', h2[2]);
  def('LogTwinNodes', h4[1]); def('LogTwinSeconds', h4[2]);
  def('LogBaseNodes', h5[1]); def('LogBaseMinutes', h5[2]); def('LogBaseRate', h5[3]); def('LogBaseDepth', h5[4]);
  def('LogStallNode', h6[1]); def('LogStallDepth', h6[2]); def('LogStallDof', h6[3]);
  def('LfourOutsideSweep', h7[1]);
}

/* ======================================================================= */
/* 6. the Mercer-program landscape                                          */
/* ======================================================================= */
const consClose = (r, what) => {
  const mm = /^\s*([0-9+\s]+?)\s*=\s*([0-9]+)\s*$/.exec(String(r.conservation));
  need(mm, 'conservation identity unreadable on ' + what);
  const lhs = mm[1].split('+').reduce((s, x) => s + Number(x.trim()), 0), rhs = Number(mm[2]);
  need(lhs === rhs && rhs === r.totalSets, 'conservation identity does not close on ' + what);
  return rhs;
};
/* the lambda table: deepest box per n, upper bounds rounded UP */
{
  const LT = J('certs/lambda-table.json');
  const best = {};
  for (const k of Object.keys(LT.rows)) { const r = LT.rows[k]; consClose(r, 'lambda ' + k); need(r.certifiedBelow === 0 && r.survivors.length > 0, 'lambda row ' + k + ' has no survivor or a set below the bar'); if (!best[r.n] || r.M > best[r.n].M) best[r.n] = r; }
  const ns = Object.keys(best).map(Number).sort((a, b) => a - b);
  need(ns.length === 14 && ns[0] === 4 && ns[13] === 17, 'the lambda table is no longer n = 4..17');
  const keyA = (X) => X.join(',');
  let confirmed = 0, improved = [], deepened = 0, repro = 0, newRows = 0;
  const lrows = [];
  for (const n of ns) {
    const r = best[n]; const prev = LT.rows[n + '@25'];
    let prov;
    if (r.sourceLab) { need(r.reproduces === true && keyA(r.sourceLab.A) === keyA(r.optimiser.A), 'lambda n=' + n + ' claims a reproduction its optimiser does not match'); prov = 'reproduces the earlier table'; repro++; }
    else if (r.vsShallower && prev) {
      deepened++;
      const same = keyA(prev.optimiser.A) === keyA(r.optimiser.A), conf = /CONFIRMED/.test(r.vsShallower);
      need(same === conf, 'lambda ' + n + '@' + r.M + ': the deepening verdict disagrees with its optimisers');
      if (conf) { confirmed++; if (prev.sourceLab && prev.reproduces) { prov = 'reproduces the earlier table at $M=25$; confirmed at $M=30$'; repro++; } else { prov = 'new; confirmed at $M=30$'; newRows++; } }
      else { improved.push({ n, A: r.optimiser.A, prevA: prev.optimiser.A }); prov = 'new; improved at $M=30$'; newRows++; }
    } else { prov = 'new'; newRows++; }
    lrows.push([String(n), String(r.M), mset(r.optimiser.A), qCeil(dblQ(r.optimiser.lambda[1]), 12), int(r.totalSets), prov]);
  }
  rows('LambdaRows', lrows);
  need(improved.length === 1 && improved[0].n === 14, 'the deepening no longer improves exactly the n = 14 bound');
  def('LtDeepened', String(deepened)); def('LtConfirmed', String(confirmed)); def('LtImprovedN', String(improved[0].n));
  def('LtImprovedSet', mset(improved[0].A)); def('LtImprovedPrev', mset(improved[0].prevA));
  def('LtImprovedBound', qCeil(dblQ(best[14].optimiser.lambda[1]), 12)); def('LtImprovedPrevBound', qCeil(dblQ(LT.rows['14@25'].optimiser.lambda[1]), 12));
  def('LtRepro', String(repro)); def('LtNew', String(newRows));
  const deepSets = ns.reduce((s, n) => s + best[n].totalSets, 0);
  const allSets = Object.keys(LT.rows).reduce((s, k) => s + LT.rows[k].totalSets, 0);
  def('LtDeepSets', int(deepSets)); def('LtRedecided', int(allSets - deepSets)); def('LtRows', String(Object.keys(LT.rows).length));
  const confSets = ns.filter((n) => best[n].vsShallower && /CONFIRMED/.test(best[n].vsShallower)).reduce((s, n) => s + best[n].totalSets, 0);
  def('LtConfirmedSets', int(confSets));
  /* n = 5 and n = 6 rows: the theorem's set and the witness set are the box optimisers */
  need(keyA(best[5].optimiser.A) === '1,2,4,5,6' && keyA(best[6].optimiser.A) === '1,2,4,6,7,8', 'the box optimisers at n = 5, 6 are no longer the conjectured sets');
  def('LtFiveBox', String(best[5].M)); def('LtFiveSets', int(best[5].totalSets)); def('LtSixBox', String(best[6].M)); def('LtSixSets', int(best[6].totalSets));
  def('LtMaxN', String(ns[ns.length - 1]));
}
/* the Newman box maxima: floors rounded DOWN */
{
  const MU = J('certs/mu-table.json'), MU40 = J('certs/mu-table-40.json');
  const ENV = require(path.join(ROOT, 'instruments', 'trigmin', 'envelope.js'));
  const mrows = []; let mu30 = 0, mu40 = 0, nested = 0;
  for (const [tab, box] of [[MU, 30], [MU40, 40]]) for (const n of Object.keys(tab.rows).map(Number).sort((a, b) => a - b)) {
    const r = tab.rows[n]; const sets = consClose(r, 'mu box' + box + ' n=' + n);
    need(r.champion && r.champion.gcd === 1 && r.survivors.length > 0, 'mu row ' + n + '@' + box + ' has no primitive champion');
    if (box === 30) { mu30 += sets; if (MU40.rows[n]) nested += sets; } else mu40 += sets;
    mrows.push([String(n), String(box), mset(r.champion.A), qFloor(dblQ(r.champion.modulus[0]), 12), int(sets)]);
  }
  rows('MuRows', mrows);
  const n30 = Object.keys(MU.rows).map(Number), n40 = Object.keys(MU40.rows).map(Number);
  need(Math.min(...n30) === 9 && Math.max(...n30) === 17 && Math.min(...n40) === 10 && Math.max(...n40) === 12, 'the mu tables are no longer n = 9..17 (box 30) and 10..12 (box 40)');
  def('MuThirtyLo', String(Math.min(...n30))); def('MuThirtyHi', String(Math.max(...n30))); def('MuFortyLo', String(Math.min(...n40))); def('MuFortyHi', String(Math.max(...n40)));
  def('MuDistinctSets', int(mu30 + mu40 - nested)); def('MuNested', int(nested)); def('MuRowsCount', String(mrows.length));
  const lifts = n40.map((n) => ({ n, d: MU40.rows[n].champion.modulus[0] - MU.rows[n].champion.modulus[1] }));
  need(lifts.every((l) => l.d > 0), 'the box-40 sweep no longer lifts every floor it touched');
  def('MuLiftList', lifts.map((l) => '$n=' + l.n + '$: $+' + dec(l.d, 3) + '$').join(', '));
  const nineAnchor = ENV.ANCHORS.find((e) => e.n === 9);
  need(nineAnchor && MU.rows[9].survivors.some((s) => s.A.join(',') === nineAnchor.A.join(',')), 'Boyd\'s n = 9 witness is no longer a survivor of the box-30 sweep');
  def('BoydNine', mset(nineAnchor.A)); def('NineSurvivors', String(MU.rows[9].survivors.length));
  need(MU.rows[9].champion.modulus[0] > 0 && nineAnchor && MU.rows[9].survivors.find((s) => s.A.join(',') === nineAnchor.A.join(',')).modulus[1] < MU.rows[9].champion.modulus[0], 'the n = 9 box maximum no longer exceeds Boyd\'s witness');
  def('BoydNineFloor', qFloor(dblQ(MU.rows[9].survivors.find((s) => s.A.join(',') === nineAnchor.A.join(',')).modulus[0]), 6));
}
/* the mu(5) ladder */
{
  const LAD = J('certs/mercer-mu5.json');
  const ms = Object.keys(LAD.rows).map(Number).sort((a, b) => a - b);
  need(ms[0] === 5 && ms[ms.length - 1] === 20 && ms.length === 16 && ms.every((m, i) => m === 5 + i), 'the ladder is no longer m = 5..20 contiguous');
  for (const m of ms) need(LAD.rows[m].verdict === 'CERTIFIED' && LAD.rows[m].conservation.failed === 0 && LAD.rows[m].conservation.refused === 0, 'ladder rung m=' + m + ' is not CERTIFIED clean');
  need(LAD.rows[5].calibration && LAD.rows[5].calibration.matches === true && LAD.rows[6].calibration && LAD.rows[6].calibration.matches === true, 'the m = 5, 6 calibrations against Mercer\'s tables no longer match');
  const top = ms[ms.length - 1];
  def('LadderTop', String(top)); def('LadderRungs', String(ms.length));
  def('LadderBound', dec(Math.ceil((1 + Math.PI / top) * 1e6) / 1e6, 6));
  def('LadderTuples', int(ms.reduce((s, m) => s + LAD.rows[m].conservation.distinctTuples, 0)));
  def('LadderExamined', int(ms.reduce((s, m) => s + LAD.rows[m].search.examined, 0)));
  rows('LadderRows', ms.map((m) => [String(m), dec(Math.ceil((1 + Math.PI / m) * 1e6) / 1e6, 6), int(LAD.rows[m].search.examined), int(LAD.rows[m].conservation.distinctTuples), fmtTime(LAD.rows[m].elapsedMs)]));
  def('LadderPdfSha', LAD.sourcePdf.sha256.slice(0, 12));
  def('LadderTopTuples', int(LAD.rows[top].conservation.distinctTuples)); def('LadderTopExamined', int(LAD.rows[top].search.examined));
  def('LadderSixTuples', int(LAD.rows[6].conservation.distinctTuples)); def('LadderFiveTuples', int(LAD.rows[5].conservation.distinctTuples));
}
/* the equality, re-proved live */
{
  const EQ = SW.certifyMinEqualsOne([0, 1, 2, 6, 9]);
  need(EQ.verdict === 'EQUALITY', 'M(0,1,2,6,9) = 1 no longer re-proves');
  const m = /H\(-1\) = (\d+) > 0, H\(1\) = (\d+) > 0/.exec(EQ.proof); need(m, 'the equality proof string no longer carries H(-1), H(1)');
  def('EqK', String(EQ.k)); def('EqDegH', String(EQ.degreeH)); def('EqHm', m[1]); def('EqHp', m[2]);
}
/* the Chowla merits at fixed n */
{
  const CH = J('certs/chowla-records.json');
  need(Array.isArray(CH.rows) && CH.rows.length === 5 && CH.rows.every((r) => r.beatsClassical === true), 'the Chowla merit rows are not the five expected, each beating its classical set');
  rows('ChowlaRows', CH.rows.map((r) => [String(r.n), String(r.maxA), qCeil(dblQ(r.enclosure[1]), 6), r.classical.name === '{1..n}' ? '$\\{1,\\dots,n\\}$' : r.classical.name.replace(/QR mod (\d+)/, 'quadratic residues mod $$$1$$'), qCeil(dblQ(r.classical.certifiedC), 6)]));
  def('ChowlaFirstN', String(CH.rows[0].n)); def('ChowlaLastN', String(CH.rows[CH.rows.length - 1].n));
  def('ChowlaFirstC', qCeil(dblQ(CH.rows[0].enclosure[1]), 4)); def('ChowlaLastC', qCeil(dblQ(CH.rows[CH.rows.length - 1].enclosure[1]), 4));
  def('ChowlaDate', CH.generated);
}

fs.writeFileSync(OUT, M.join('\n') + '\n');
console.log('wrote paper/tex/lambda5-numbers.tex (' + (M.length - 1) + ' macros)');
