#!/usr/bin/env node
/* matmul-records.js — every number the pre-paper paper/tex/matmul-records.tex
   quotes, read from the records that decided it and written as LaTeX macros
   to paper/tex/matmul-records-numbers.tex.

   Records read (nothing is re-run that writes a record):
     certs/strassen-certificate.json      the detached fast-matmul certificates
     corpus/strassen-corpus.json          AlphaTensor factors, converted from the pinned npz
     corpus/alphaevolve-corpus.json       AlphaEvolve's rank-48 <4,4,4>, converted from the pinned notebook
     corpus/sources/PINS.json             the sha256 of every pinned source
     corpus/sources/add55-certificate.json   the 55-addition certificate (Karunaratne & Idamekorala)
     corpus/sources/wang_cert_matrix_q02_n{222,333}.pb.txt   Wang's lower-bound certificates
     certs/easota-ledger.json             the EinsteinArena table, decided
     corpus/easota/meta.json              its pinned files
     certs/bilinear-certificate.json      the F2 polynomial-multiplication schemes
     corpus/bilinear-bounds.json          the published bounds they are measured against

   Live, because each runs in seconds: the strassen-audit family re-certifies
   its whole corpus in-process (pins re-hashed); tools/verify_strassen.py (the
   stdlib verifier with no shared code) must pass with its red control fired;
   instruments/slp re-audits the 55-addition certificate; instruments/tensorlb
   re-runs both lower-bound audits; instruments/bilinear re-decides every stored
   scheme; and the five batteries (strassen, slp, tensorlb, easota, bilinear)
   must pass with every red control fired. The EinsteinArena ledger is READ,
   never re-run here (tools/run-easota-ledger.js rewrites it).

   A record that no longer says what a sentence of the paper needs makes this
   refuse (need()), exactly as tools/build-paper-numbers.js does.
   usage: node tools/paper-numbers/matmul-records.js                      MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex', 'matmul-records-numbers.tex');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const die = (m) => { console.error('MATMUL-RECORDS NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
const pct = (x, d) => Number(x).toFixed(d) + '\\%';
/* a small or large number in scientific form, as math: $3.1\times10^{-12}$ */
const sci = (x, d = 2) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return '$' + m[1] + '\\times10^{' + Number(m[2]) + '}$'; };
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();
/* plain text into LaTeX: the few characters the records use */
const tex = (s) => String(s).replace(/\\/g, '\\textbackslash{}').replace(/([&%$#_{}])/g, '\\$1').replace(/~/g, '\\textasciitilde{}').replace(/\^/g, '\\textasciicircum{}')
  .replace(/≥/g, '$\\ge$').replace(/≤/g, '$\\le$').replace(/→/g, '$\\to$').replace(/−/g, '$-$').replace(/×/g, '$\\times$').replace(/²/g, '$^2$').replace(/–/g, '--').replace(/—/g, '---').replace(/…/g, '\\ldots{}')
  .replace(/Σ/g, '$\\Sigma$').replace(/λ/g, '$\\lambda$').replace(/ő/g, '\\H{o}').replace(/⁺/g, '$^+$').replace(/₁/g, '$_1$').replace(/∗/g, '$*$');
const sha16 = (h) => '\\texttt{' + String(h).slice(0, 16) + '}\\ldots';

const M = ['%% generated by tools/paper-numbers/matmul-records.js — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));
function battery(cmd, args, re, what) {
  const r = cp.spawnSync(cmd, args, { cwd: ROOT, maxBuffer: 1 << 26 });
  const out = String(r.stdout) + String(r.stderr);
  const m = re.exec(out);
  if (r.status !== 0 || !m) die(what + ' did not pass clean:\n' + out.slice(-800));
  return { m: m.slice(1).map(Number), out };
}
def('RepoCommit', git);

/* ======================================================= 1. the fast-matmul registry */
{
  const S = J('certs/strassen-certificate.json');
  const PINS = J('corpus/sources/PINS.json');
  const FAM = require(path.join(ROOT, 'families', 'strassen-audit.js'));
  const T = require(path.join(ROOT, 'instruments', 'strassen', 'tensor.js'));
  /* re-certify the whole corpus in-process: every identity, every pin */
  const t0 = Date.now();
  const live = [];
  for (let i = 0; ; i++) { const o = FAM.enumerate(i); if (!o) break; const c = FAM.certify(o); need(c.verdict !== 'REFUSED', o.id + ' REFUSED: ' + c.why); live.push({ id: o.id, verdict: c.verdict, extra: c.extra, text: c.text }); }
  const msLive = Date.now() - t0;
  const by = Object.fromEntries(live.map((r) => [r.id, r]));
  const hits = live.filter((r) => r.verdict === 'HIT'), rejects = live.filter((r) => r.verdict === 'REJECT');
  need(live.length === 11 && hits.length === 10 && rejects.length === 1, 'the corpus is not 11 rows = 10 verified + 1 reject');
  need(rejects[0].id === 'naive-2x2x2' && /not below the naive/.test(rejects[0].text), 'the one REJECT is not the naive rank-8 correct-not-fast row');
  /* the detached certificate must carry exactly the ten verified rows, with the same ranks and rings */
  need(S.entries.length === 10, 'the detached certificate does not hold 10 entries');
  for (const e of S.entries) { const l = by[e.id]; need(l && l.verdict === 'HIT' && l.extra.rank === e.rank && l.extra.ring === e.ring && l.extra.layout === e.layout, 'certificate entry ' + e.id + ' disagrees with the live verdict'); }
  for (const [f, pin] of Object.entries(S.sourcePins)) need(PINS[f] === (pin.sha256 || pin), 'the certificate pin for ' + f + ' is not the PINS.json pin');
  const totalEq = hits.reduce((s, r) => s + r.extra.equations, 0);
  def('CorpusRows', String(live.length)); def('CorpusVerified', String(hits.length)); def('CorpusRejects', String(rejects.length));
  def('CorpusEquations', int(totalEq)); def('CorpusLiveMs', int(msLive));
  { const g = /^(\S+) @ git ([0-9a-f]+)$/.exec(S.generatedBy); need(g, 'generatedBy is not "<tool> @ git <sha>"'); def('CertGeneratedBy', '\\path{' + g[1] + '} at git \\texttt{' + g[2] + '}'); }

  const ae = by['alphaevolve-48-4x4x4'];
  need(ae.verdict === 'HIT' && ae.extra.rank === 48 && ae.extra.ring === 'Zi' && ae.extra.scale === 8 && ae.extra.equations === 4096 && ae.extra.layout === 'CA', 'the AlphaEvolve row moved');
  need(ae.extra.sourcePin && ae.extra.sourcePin.sha256 === PINS['alphaevolve_mathematical_results.ipynb'], 'the AlphaEvolve pin moved');
  const aeCommit = /@ commit ([0-9a-f]{7,})/.exec(ae.extra.source); need(aeCommit, 'the AlphaEvolve source string carries no commit');
  def('AERank', String(ae.extra.rank)); def('AEScale', String(ae.extra.scale)); def('AEEquations', int(ae.extra.equations)); def('AELayout', ae.extra.layout);
  def('AENaive', String(ae.extra.naive)); def('AEPin', sha16(ae.extra.sourcePin.sha256)); def('AECommit', '\\texttt{' + aeCommit[1] + '}');
  /* the coefficient alphabet, read from the converted corpus: doubled half-Gaussian entries */
  const AEC = J('corpus/alphaevolve-corpus.json').entries.find((e) => e.id === 'alphaevolve-48-4x4x4');
  const alphabet = new Set(); let nz = 0, total = 0;
  for (const Mx of [AEC.U, AEC.V, AEC.W]) for (const row of Mx) for (const [a, b] of row) { alphabet.add(a + ',' + b); total++; if (a || b) nz++; }
  for (const k of alphabet) { const [a, b] = k.split(',').map(Number); need(Math.abs(a) <= 1 && Math.abs(b) <= 1, 'an AlphaEvolve doubled coefficient is outside {0,±1,±i,±1±i}: ' + k); }
  def('AEAlphabet', String(alphabet.size)); def('AENonzero', int(nz)); def('AEEntries', int(total));

  const at = by['alphatensor-f2-4x4x4'];
  need(at.verdict === 'HIT' && at.extra.rank === 47 && at.extra.ring === 'F2' && at.extra.equations === 4096 && /REFUTED over Q/.test(at.extra.overQ || ''), 'the AlphaTensor rank-47 row moved');
  const at5 = by['alphatensor-f2-5x5x5'];
  need(at5.verdict === 'HIT' && at5.extra.rank === 96 && /REFUTED over Q/.test(at5.extra.overQ || ''), 'the AlphaTensor rank-96 row moved');
  def('ATRank', String(at.extra.rank)); def('ATEquations', int(at.extra.equations)); def('ATLayout', at.extra.layout);
  def('ATFiveRank', String(at5.extra.rank)); def('ATFiveEquations', int(at5.extra.equations)); def('ATFiveNaive', String(at5.extra.naive));
  def('ATPinF', sha16(PINS['alphatensor_f2.npz'])); def('ATPinR', sha16(PINS['alphatensor_r.npz']));
  /* the over-Q failure, located: the instrument reports the first failing equation under the
     recorded layout; the count of failing equations is a descriptive statistic computed here
     from the same factors in BigInt (the verdict itself is the instrument's) */
  const CORP = J('corpus/strassen-corpus.json');
  const overQ = (id) => {
    const e = CORP.entries.find((x) => x.id === id); need(e, 'no corpus entry ' + id);
    const q = T.audit({ dims: e.dims, rank: e.rank, U: e.U, V: e.V, W: e.W, ring: 'Q' });
    need(q.verdict === 'REFUTED', id + ' did not refute over Q');
    const m = /\(ab=(\d+), bc=(\d+), k=(\d+)\): sum (-?\d+), target (\d+)/.exec(q.why); need(m, 'cannot read the failing equation out of: ' + q.why);
    const [n, mm, p] = e.dims; let bad = 0, maxAbs = 0;
    for (let ab = 0; ab < n * mm; ab++) for (let bc = 0; bc < mm * p; bc++) for (let k = 0; k < n * p; k++) {
      let s = 0n; for (let t = 0; t < e.rank; t++) s += BigInt(e.U[ab][t]) * BigInt(e.V[bc][t]) * BigInt(e.W[k][t]);
      const want = BigInt(T.target(e.dims, by[id].extra.layout, ab, bc, k));
      if (s !== want) { bad++; const a = s < 0n ? -s : s; if (a > maxAbs) maxAbs = Number(a); }
      need((s - want) % 2n === 0n, id + ': an equation fails even mod 2');
    }
    return { ab: m[1], bc: m[2], k: m[3], sum: m[4], target: m[5], bad, maxAbs };
  };
  const f4 = overQ('alphatensor-f2-4x4x4'), f5 = overQ('alphatensor-f2-5x5x5');
  def('ATQFailAb', f4.ab); def('ATQFailBc', f4.bc); def('ATQFailK', f4.k); def('ATQFailSum', f4.sum); def('ATQFailTarget', f4.target);
  def('ATQFailCount', int(f4.bad)); def('ATQFailPct', pct(100 * f4.bad / at.extra.equations, 1)); def('ATQMaxAbs', String(f4.maxAbs));
  def('ATFiveQFailCount', int(f5.bad)); def('ATFiveQFailPct', pct(100 * f5.bad / at5.extra.equations, 1));

  const s7 = by['strassen-1969'], s49 = by['strassen-squared-4x4x4'], l23 = by['alphatensor-q-3x3x3'], q49 = by['alphatensor-q-4x4x4'];
  need(s7.extra.rank === 7 && s7.extra.equations === 64 && s49.extra.rank === 49 && l23.extra.rank === 23 && l23.extra.equations === 729 && q49.extra.rank === 49, 'a calibration row moved');
  def('StrassenRank', '7'); def('StrassenEquations', String(s7.extra.equations)); def('StrassenSqRank', String(s49.extra.rank)); def('StrassenSqEquations', int(s49.extra.equations));
  def('LadermanRank', String(l23.extra.rank)); def('LadermanEquations', String(l23.extra.equations)); def('ATQFourRank', String(q49.extra.rank));
  def('NaiveTwoRank', String(by['naive-2x2x2'].extra.rank));
  def('ATQRows', String(live.filter((r) => /^alphatensor-q-/.test(r.id)).length)); def('ATFRows', String(live.filter((r) => /^alphatensor-f2-/.test(r.id)).length));
  const SRC = { 'strassen-1969': 'Strassen 1969, textbook transcription', 'strassen-squared-4x4x4': 'Strassen $\\otimes$ Strassen, generated here', 'naive-2x2x2': 'the definition, generated here' };
  const src = (r) => SRC[r.id] || (/alphatensor/.test(r.id) ? 'AlphaTensor npz, key ' + r.id.replace(/^alphatensor-(q|f2)-/, '').split('x').join(',') : 'AlphaEvolve notebook @ ' + aeCommit[1]);
  const RING = { Q: '$\\Q$', F2: '$\\mathbb{F}_2$', Zi: '$\\Z[i]$' };
  rows('RegistryRows', live.map((r) => {
    const x = r.extra, d = x.dims ? '$' + x.dims.join('\\times') + '$' : '$2\\times2\\times2$';
    const ring = RING[x.ring] || (r.verdict === 'REJECT' ? '$\\Q$' : '---');
    const eq = x.equations !== undefined ? int(x.equations) : int(64);
    const verdict = r.verdict === 'HIT' ? ('VERIFIED' + (x.overQ && /REFUTED/.test(x.overQ) ? '; refuted over $\\Q$' : '')) : 'REJECT (correct, not fast)';
    return ['\\texttt{' + tex(r.id) + '}', d, String(x.rank), String(x.naive !== undefined ? x.naive : 8), ring, eq, x.layout || 'AC', verdict, src(r)];
  }));
  /* the dumbbell figure's data, and the stdlib verifier as a gate */
  const v = battery('python3', [path.join(ROOT, 'tools', 'verify_strassen.py'), 'certs/strassen-certificate.json'], /verify_strassen: (\d+) entries checked, (\d+) failures/, 'tools/verify_strassen.py');
  need(v.m[0] === 10 && v.m[1] === 0 && /RED control: one coefficient forged by \+1 is refuted/.test(v.out), 'the stdlib verifier did not pass with its red control');
  def('VerifierEntries', String(v.m[0])); def('VerifierFailures', String(v.m[1]));
  const sb = battery('node', [path.join(ROOT, 'instruments', 'strassen', 'battery.js')], /strassen battery: (\d+) pass, (\d+) fail/, 'the strassen battery');
  need(sb.m[1] === 0, 'strassen battery failures'); def('StrassenBatteryChecks', String(sb.m[0]));
  def('StrassenBatteryReds', String((sb.out.match(/PASS\s+RED/g) || []).length));
}

/* ============================================================ 2. the lower wall */
{
  const PINS = J('corpus/sources/PINS.json');
  const run = (f) => {
    const r = cp.spawnSync('python3', [path.join(ROOT, 'instruments', 'tensorlb', 'verify.py'), path.join(ROOT, 'corpus', 'sources', f)], { cwd: ROOT });
    const o = String(r.stdout); need(r.status === 0, 'tensorlb verify failed on ' + f + ':\n' + String(r.stderr).slice(-400));
    const g = (re) => { const m = re.exec(o); need(m, 'cannot read ' + re + ' from the tensorlb audit of ' + f); return Number(m[1]); };
    return { nodes: g(/nodes:\s*(\d+)/), wok: g(/witnesses re-verified:\s*(\d+) ok/), wbad: g(/re-verified:\s*\d+ ok,\s*(\d+) BAD/), conf: g(/CONFIRMED[^:]*:\s*(\d+)/),
      tight: g(/TIGHT-IF[^:]*:\s*(\d+)/), surv: g(/SURVIVES[^:]*:\s*(\d+)/), nat: g(/NOT-ATTACKED[^:]*:\s*(\d+)/), ref: g(/REFUTED[^:]*:\s*(\d+)/) };
  };
  const t0 = Date.now();
  const A3 = run('wang_cert_matrix_q02_n333.pb.txt'), A2 = run('wang_cert_matrix_q02_n222.pb.txt');
  const sec = (Date.now() - t0) / 1000;
  need(A3.ref === 0 && A2.ref === 0 && A2.wbad === 0, 'a lower-bound node was refuted or a witness failed — a finding, not a paper number');
  need(A3.conf + A3.tight + A3.surv + A3.nat === A3.nodes, 'the <3,3,3> node tallies do not sum to the node count');
  need(A2.conf + A2.tight + A2.surv + A2.nat === A2.nodes, 'the <2,2,2> node tallies do not sum to the node count');
  def('LBNodes', String(A3.nodes)); def('LBConfirmed', String(A3.conf)); def('LBTight', String(A3.tight)); def('LBSurvives', String(A3.surv)); def('LBNotAttacked', String(A3.nat)); def('LBRefuted', String(A3.ref));
  def('LBAttacked', String(A3.conf + A3.tight + A3.surv)); def('LBNotAttackedPct', pct(100 * A3.nat / A3.nodes, 1)); def('LBWitnesses', String(A3.wok + A3.wbad));
  def('CNodes', String(A2.nodes)); def('CWitnessesOk', String(A2.wok)); def('CWitnesses', String(A2.wok + A2.wbad)); def('CConfirmed', String(A2.conf)); def('CTight', String(A2.tight)); def('CSurvives', String(A2.surv)); def('CNotAttacked', String(A2.nat)); def('CRefuted', String(A2.ref));
  def('LBSeconds', dec(sec, 1));
  def('LBPin', sha16(PINS['wang_cert_matrix_q02_n333.pb.txt'])); def('CPin', sha16(PINS['wang_cert_matrix_q02_n222.pb.txt']));
  const b = battery('python3', [path.join(ROOT, 'instruments', 'tensorlb', 'battery.py')], /battery green: (\d+)\/(\d+) checks, (\d+)\/(\d+) red controls fired/, 'the tensorlb battery');
  need(b.m[0] === b.m[1] && b.m[2] === b.m[3], 'the tensorlb battery is not green'); def('LBBatteryChecks', String(b.m[0])); def('LBBatteryReds', String(b.m[2]));
  rows('WallRows', [
    ['$\\langle2,2,2\\rangle$ control (rank 7 optimal)', String(A2.nodes), A2.wok + ' / ' + (A2.wok + A2.wbad), String(A2.conf), String(A2.tight), String(A2.surv), String(A2.nat), String(A2.ref)],
    ['$\\langle3,3,3\\rangle$, the bound $\\ge 20$', String(A3.nodes), '---', String(A3.conf), String(A3.tight), String(A3.surv), String(A3.nat), String(A3.ref)]]);
}

/* ========================================================== 3. the 55 additions */
{
  const S = require(path.join(ROOT, 'instruments', 'slp', 'slp.js'));
  const T = require(path.join(ROOT, 'instruments', 'strassen', 'tensor.js'));
  const PINS = J('corpus/sources/PINS.json');
  const raw = fs.readFileSync(path.join(ROOT, 'corpus', 'sources', 'add55-certificate.json'));
  const sha = crypto.createHash('sha256').update(raw).digest('hex');
  need(PINS['add55-certificate.json'] === sha, 'the 55-addition certificate does not match its pin');
  const cert = JSON.parse(raw.toString('utf8'));
  const a = S.audit(cert, T);
  need(a.verdict === 'VERIFIED', 'the 55-addition audit came back ' + a.verdict + ': ' + a.why);
  need(a.counted === 55 && a.declared === 55 && a.rank === 23 && a.brent.equations === 729 && a.ternary, 'the 55-addition facts moved: ' + JSON.stringify({ c: a.counted, d: a.declared, r: a.rank, e: a.brent.equations, t: a.ternary }));
  const part = Object.fromEntries(a.parts.map((p) => [p.job, p]));
  def('AddCounted', String(a.counted)); def('AddDeclared', String(a.declared)); def('AddRank', String(a.rank)); def('AddBrent', String(a.brent.equations)); def('AddLayout', a.brent.layout);
  def('AddScalarOps', String(a.scalarOps)); def('AddNaive', String(a.naive));
  def('AddU', String(part.U_input.actual)); def('AddV', String(part.V_input.actual)); def('AddW', String(part.W_output.actual));
  def('AddNaiveU', String(part.U_input.naive)); def('AddNaiveV', String(part.V_input.naive)); def('AddNaiveW', String(part.W_output.naive));
  def('AddPin', sha16(sha));
  need(cert.source && cert.source.declared_reduced_additions === 58 && cert.source.replayed_side_costs, 'the certificate no longer names its 58-addition source scheme');
  def('AddSourceDeclared', String(cert.source.declared_reduced_additions));
  const rc = cert.source.replayed_side_costs; def('AddSourceU', String(rc.U)); def('AddSourceV', String(rc.V)); def('AddSourceW', String(rc.W));
  need(rc.U + rc.V + rc.W === cert.source.declared_reduced_additions, 'the source scheme side costs do not sum to its declared total');
  def('AddSourcePath', '\\texttt{' + tex(path.basename(cert.source.path)) + '}');
  need(cert.transposition && /^14 \+ 23 - 9 = 28$/.test(cert.transposition.formula), 'the transposition formula moved'); def('AddTransposition', '$' + cert.transposition.formula + '$');
  const lb = cert.lower_bound_searches_for_factor_maps; need(lb && lb.U && lb.V, 'the certificate carries no local lower-bound searches');
  def('AddLocalLBU', String(lb.U.lower_bound)); def('AddLocalLBV', String(lb.V.lower_bound));
  need(lb.U.lower_bound === lb.U.matching_upper_bound && lb.V.lower_bound === lb.V.matching_upper_bound, 'the local lower bounds do not match the circuits');
  rows('AddPartRows', a.parts.map((p) => ['\\texttt{' + tex(p.job) + '}', tex(p.role), String(p.declared), String(p.actual), String(p.naive), p.realizes ? 'exactly' : 'NO']).concat([['total', 'the whole linear cost', String(a.declared), String(a.counted), String(a.naive), 'agree']]));
  const b = battery('node', [path.join(ROOT, 'instruments', 'slp', 'battery.js')], /slp battery: (\d+) pass, (\d+) fail/, 'the slp battery');
  need(b.m[1] === 0, 'slp battery failures'); def('SlpBatteryChecks', String(b.m[0])); def('SlpBatteryReds', String((b.out.match(/PASS\s+RED:/g) || []).length));
}

/* ============================================== 4. polynomial multiplication over F2 */
{
  const C = J('certs/bilinear-certificate.json'), BO = J('corpus/bilinear-bounds.json');
  const B = require(path.join(ROOT, 'instruments', 'bilinear', 'tensor.js'));
  const F = require(path.join(ROOT, 'machine', 'generate', 'f2scheme.js'));
  const G = require(path.join(ROOT, 'machine', 'generate', 'targets.js'));
  let equations = 0;
  const rr = C.entries.map((e) => {
    const target = G.parse(e.target);
    const a = B.audit(F.toClaim(e.scheme, target, e.target));
    need(a.verdict === 'VERIFIED' && a.rank === e.rank, 'the stored scheme for ' + e.target + ' no longer certifies at rank ' + e.rank + ': ' + (a.why || a.verdict));
    equations += a.equations;
    const lit = BO.rows.find((r) => r.target === e.target) || null;
    if (lit) need(e.rank >= lit.lower, e.target + ' certifies below a published lower bound — stop');
    const standing = !lit ? 'unpublished' : e.rank < lit.upper ? 'BEAT' : e.rank === lit.upper ? 'MATCH' : 'above';
    need(standing === e.standing, 'the recorded standing of ' + e.target + ' is not the derived one');
    return Object.assign({}, e, { lit, standing });
  });
  const beat = rr.filter((r) => r.standing === 'BEAT'), match = rr.filter((r) => r.standing === 'MATCH'), above = rr.filter((r) => r.standing === 'above'), unp = rr.filter((r) => r.standing === 'unpublished');
  const tight = rr.filter((r) => r.lit && r.lit.lower === r.lit.upper);
  need(beat.length === 0 && match.length === 3 && above.length === 3 && unp.length === 3 && tight.length === 1 && tight[0].target === 'C7', 'the polynomial-multiplication standings moved');
  const untouched = BO.rows.filter((b) => !rr.some((r) => r.target === b.target)).map((b) => b.target);
  const ck = BO.chenKauersFullProduct.ranks;
  for (const r of unp) need(ck[r.target] === r.rank, r.target + ' does not match the Chen–Kauers ladder');
  const secs = rr.reduce((s, r) => s + (r.search ? r.search.seconds : 0), 0);
  def('BLTargets', String(rr.length)); def('BLBeat', String(beat.length)); def('BLMatch', String(match.length)); def('BLAbove', String(above.length)); def('BLUnpublished', String(unp.length)); def('BLTight', String(tight.length));
  def('BLEquations', int(equations)); def('BLSeconds', int(secs)); def('BLMinutes', dec(secs / 60, 0)); def('BLUntouched', String(untouched.length)); def('BLUntouchedList', untouched.map((t) => '\\texttt{' + t + '}').join(', '));
  def('BLMatchList', match.map((r) => '\\texttt{' + r.target + '}').join(', '));
  def('BLAboveList', above.map((r) => '\\texttt{' + r.target + '} (' + r.rank + ' against ' + r.lit.upper + ')').join(', '));
  def('BLPublishedRows', String(BO.rows.length)); def('BLRetrieved', BO.retrieved);
  const byT = Object.fromEntries(rr.map((r) => [r.target, r]));
  def('CSevenRank', String(byT.C7.rank)); def('CSevenNaive', String(byT.C7.naive)); def('CSevenSeconds', dec(byT.C7.search.seconds, 0));
  def('CEightRank', String(byT.C8.rank)); def('CEightUpper', String(byT.C8.lit.upper)); def('CEightSeconds', int(byT.C8.search.seconds));
  def('TNineRank', String(byT.T9.rank)); def('TNineUpper', String(byT.T9.lit.upper)); def('TEightRank', String(byT.T8.rank)); def('TEightUpper', String(byT.T8.lit.upper));
  const seeds = [...new Set(rr.map((r) => r.search.seeds))].sort((a, b) => a - b), steps = [...new Set(rr.map((r) => r.search.steps))].sort((a, b) => a - b);
  def('BLSeeds', seeds.map(String).join(' or ')); def('BLSteps', steps.map(int).join(' or '));
  need(rr.every((r) => r.search.costUsd === 0 && r.search.proposer === 'flip@v1'), 'a scheme was not found by the free flip walk at zero cost');
  const SHORT = { 12: 'Cenk--\\"Ozbudak 2011', 15: 'Fan--Hasan 2007', 26: 'Montgomery 2005', 27: 'Morgera 1990', 32: 'Wagh--Morgera 1983', 34: 'Winograd 1977', 'W-fn': 'Wang 2026, footnote' };
  for (const k of Object.keys(SHORT)) need(BO.refs[k], 'bounds corpus lost reference ' + k);
  const fam = { P: 'full', T: 'truncated', C: 'cyclic' };
  rows('BLRows', rr.map((r) => ['\\texttt{' + r.target + '}', fam[r.target[0]] + ', $n=' + r.target.slice(1) + '$', String(r.naive), r.lit ? r.lit.lower + '--' + r.lit.upper : (ck[r.target] !== undefined ? 'CK ' + ck[r.target] : '---'), String(r.rank), r.standing === 'unpublished' ? 'matches CK' : r.standing, r.lit ? r.lit.upperRef.map((k) => SHORT[k]).join('; ') : 'Chen--Kauers 2025 table']));
  rows('BLUntouchedRows', BO.rows.filter((b) => untouched.includes(b.target)).map((b) => ['\\texttt{' + b.target + '}', String(b.lower), String(b.lowerPrev), String(b.upper), b.upperRef.map((k) => SHORT[k]).join('; ')]));
  const b = battery('node', [path.join(ROOT, 'instruments', 'bilinear', 'battery.js')], /bilinear battery: (\d+) pass, (\d+) fail/, 'the bilinear battery');
  need(b.m[1] === 0, 'bilinear battery failures'); def('BLBatteryChecks', String(b.m[0])); def('BLBatteryReds', String((b.out.match(/PASS\s+RED:/g) || []).length)); def('BLBatteryLadder', String((b.out.match(/PASS\s+LADDER/g) || []).length));
}

/* ============================================================ 5. the EinsteinArena table */
{
  const L = J('certs/easota-ledger.json'), META = J('corpus/easota/meta.json');
  need(L.provenance.commit === META.commit && Object.keys(META.files).length === Object.keys(L.provenance.files).length, 'the ledger and the corpus meta disagree on the pinned files');
  const row = (id) => { const r = L.rows.find((x) => x.id === id); need(r, 'missing easota row ' + id); return r; };
  const tally = {}; for (const r of L.rows) tally[r.verdict] = (tally[r.verdict] || 0) + 1;
  const nW = tally.WITNESSED || 0, nR = tally.REPAIRED || 0, nU = tally.UNWITNESSED || 0;
  need(L.rows.length === 20 && nW === 16 && nR === 4 && nU === 0, 'the ledger tallies moved: ' + JSON.stringify(tally));
  need(L.improvements.length === 8 && L.improvements.every((i) => i.sign > 0), 'not every improvement is a positive exact difference');
  const problems = [...new Set(L.rows.map((r) => r.problem))];
  def('EARows', String(L.rows.length)); def('EAProblems', String(problems.length)); def('EAWitnessed', String(nW)); def('EARepaired', String(nR)); def('EAUnwitnessed', String(nU));
  def('EAImprovements', String(L.improvements.length)); def('EAFiles', String(Object.keys(L.provenance.files).length)); def('EACommit', '\\texttt{' + L.provenance.commit.slice(0, 8) + '}'); def('EAFetched', L.provenance.fetched);
  def('EAGenerated', L.generated.slice(0, 10)); def('EARepo', '\\path{' + L.provenance.repo + '}');
  def('EAUndecided', String(L.undecided.length));
  const printedRows = L.rows.filter((r) => r.printed), agree = printedRows.filter((r) => r.printedAgrees), disagree = printedRows.filter((r) => r.printedAgrees === false);
  need(disagree.length === 1 && disagree[0].id === 'circles/ours_2026', 'the "one printed digit" sentence would be false');
  def('EAPrinted', String(printedRows.length)); def('EAPrintedAgree', String(agree.length));
  const deltas = L.improvements.map((i) => Number(i.delta));
  const smallest = L.improvements[deltas.indexOf(Math.min(...deltas))], largest = L.improvements[deltas.indexOf(Math.max(...deltas))];
  need(smallest.problem === 'heilbronn-convex' && largest.problem === 'flat-polynomials', 'the smallest/largest improvement moved');
  /* the flat-polynomial delta is a gap between two disjoint enclosures; among the exact differences the largest is the hexagon side */
  const largestExact = L.improvements.filter((i) => i.problem !== 'flat-polynomials').reduce((m, i) => (Number(i.delta) > Number(m.delta) ? i : m));
  need(largestExact.problem === 'hexagon-packing', 'the largest exact difference is no longer the hexagon side');
  def('EALargestExact', sci(largestExact.delta, 1));
  def('EASmallest', sci(smallest.delta)); def('EALargest', sci(largest.delta));
  /* circles */
  const cir = row('circles/ours_2026'), cirAE = row('circles/alphaevolve_2025');
  need(cir.verdict === 'REPAIRED' && cir.printedAgrees === false && cirAE.verdict === 'WITNESSED', 'the circles finding moved');
  def('CirPairs', String(cir.asPublished.overlappingPairs)); def('CirAllPairs', String(21 * 20 / 2)); def('CirWorst', sci(Math.abs(Number(cir.asPublished.worstPairSlackSquared)))); def('CirWorstPair', cir.asPublished.worstPair.join('--'));
  need(/n = 21/.test(cir.claim), 'the circles claim is not n = 21');
  def('CirBox', sci(Math.abs(Number(cir.asPublished.boxSlack)))); def('CirLambda', tex(cir.repair.lambda.slice(0, 20)) + '\\ldots'); def('CirLambdaDeficit', sci(1 - Number(cir.repair.lambda)));
  def('CirSumPublished', tex(cir.asPublished.sumR)); def('CirSumRepaired', tex(cir.repair.sumR)); def('CirDeficit', sci(cir.repair.deficit)); def('CirPrinted', cir.printed); def('CirRepairRounded', cir.repair.sumR.slice(0, 12));
  def('CirAEWorst', sci(Number(cirAE.asPublished.worstPairSlackSquared))); def('CirAEBox', sci(Number(cirAE.asPublished.boxSlack))); def('CirAEPrinted', cirAE.printed); def('CirAEExact', tex(cirAE.exact));
  def('CirImprovement', sci(L.improvements.find((i) => i.problem === 'circles-rectangle').delta));
  /* overlap */
  const ov = L.rows.filter((r) => r.problem === 'erdos-minimum-overlap'), ovR = ov.filter((r) => r.verdict === 'REPAIRED');
  need(ov.length === 4 && ovR.length === 3 && row('overlap/haugland_2016').verdict === 'WITNESSED', 'the overlap rows moved');
  const ovMiss = ovR.map((r) => Math.abs(Number(r.asPublished.sumMinusHalfN))), ovDelta = ovR.map((r) => Math.abs(Number(r.repair.delta)));
  def('OvMissMin', sci(Math.min(...ovMiss), 1)); def('OvMissMax', sci(Math.max(...ovMiss), 1)); def('OvDeltaMax', sci(Math.max(...ovDelta), 1));
  const ovT = row('overlap/ttt_discover_2026'), ovO = row('overlap/together_ai_2026'), ovH = row('overlap/haugland_2016');
  need(ovT.printedAgrees && ovO.printedAgrees && ovH.printedAgrees, 'an overlap ceiling no longer stands');
  def('OvTPrinted', ovT.printed); def('OvTExact', tex(ovT.exact.slice(0, 12))); def('OvOPrinted', ovO.printed); def('OvOExact', tex(ovO.exact.slice(0, 12))); def('OvHSteps', String(ovH.asPublished.steps)); def('OvOSteps', String(ovO.asPublished.steps));
  def('OvImprovement', sci(L.improvements.find((i) => i.problem === 'erdos-minimum-overlap').delta));
  /* autocorrelation */
  const ac = row('autocorr/ours_2026'), acT = row('autocorr/ttt_discover_2026'), acV = row('autocorr/alphaevolve_v2_2025');
  need(ac.verdict === 'WITNESSED' && acT.verdict === 'WITNESSED' && acV.printed === null, 'the autocorrelation rows moved');
  def('AcN', int(ac.detail.n)); def('AcCandidates', String(ac.detail.candidatesDecidedExactly)); def('AcArgmax', int(ac.detail.argmax)); def('AcScreen', sci(ac.detail.screenErrorBound, 1));
  def('AcExact', tex(ac.exact)); def('AcPrinted', ac.printed); def('AcTExact', tex(acT.exact.slice(0, 14)) + '\\ldots'); def('AcTPrinted', acT.printed); def('AcVN', int(acV.detail.n)); def('AcVExact', tex(acV.exact.slice(0, 12)) + '\\ldots');
  def('AcImprovement', sci(L.improvements.find((i) => i.problem === 'first-autocorrelation').delta));
  /* flat polynomials */
  const fl = row('flat/ours_2026'), flAE = row('flat/alphaevolve_2025');
  need(fl.verdict === 'WITNESSED' && flAE.verdict === 'WITNESSED' && fl.printedAgrees && flAE.printedAgrees && Number(fl.detail.gridShortfall) > 0 && Number(flAE.detail.gridShortfall) > 0, 'the flat-polynomial rows moved');
  need(Number(fl.enclosure.hi) < Number(flAE.enclosure.lo), 'the two flat-polynomial enclosures are not disjoint');
  def('FlDegree', String(fl.detail.degree)); def('FlLo', tex(fl.enclosure.lo.slice(0, 20))); def('FlHi', tex(fl.enclosure.hi.slice(0, 20))); def('FlWidth', sci(fl.enclosure.width, 1)); def('FlGrid', tex(fl.detail.gridScore)); def('FlShortfall', sci(fl.detail.gridShortfall)); def('FlPrinted', fl.printed); def('FlCrit', String(fl.detail.counts.nCrit)); def('FlMs', int(fl.detail.ms));
  def('FlAELo', tex(flAE.enclosure.lo.slice(0, 18))); def('FlAEHi', tex(flAE.enclosure.hi.slice(0, 18))); def('FlAEShortfall', sci(flAE.detail.gridShortfall)); def('FlAEPrinted', flAE.printed); def('FlAECrit', String(flAE.detail.counts.nCrit));
  def('FlImprovement', sci(L.improvements.find((i) => i.problem === 'flat-polynomials').delta));
  /* hexagons */
  const hx = row('hexagons/ours_2026'), hxAE = row('hexagons/alphaevolve_2025');
  need(hx.verdict === 'WITNESSED' && hxAE.verdict === 'WITNESSED' && hx.detail.pairs.SEPARATED === 66 && hx.detail.vertices.INSIDE === 72, 'the hexagon rows moved');
  def('HxPairs', String(hx.detail.pairs.SEPARATED)); def('HxVertices', String(hx.detail.vertices.INSIDE)); def('HxGap', sci(hx.detail.closestPair.gapAtLeast, 1)); def('HxAEGap', sci(hxAE.detail.closestPair.gapAtLeast, 1)); def('HxCross', sci(hx.detail.tightestVertex.crossAtLeast, 1)); def('HxWidth', sci(hx.detail.enclosureWidth, 1));
  def('HxSide', hx.printed); def('HxAESide', hxAE.printed); def('HxImprovement', sci(L.improvements.find((i) => i.problem === 'hexagon-packing').delta, 1));
  def('HxPlatformTol', tex(hx.platformTolerance));
  /* edges vs triangles, heilbronn, min-distance: the exact-digit confirmations */
  const ed = row('edges/ours_2026'), edAE = row('edges/alphaevolve_2025');
  need(ed.printedAgrees && edAE.printedAgrees, 'an edges-vs-triangles printed score no longer agrees');
  def('EdImprovement', sci(L.improvements.find((i) => i.problem === 'edges-vs-triangles').delta)); def('EdPrinted', ed.printed); def('EdExact', tex(ed.exact.slice(0, 18)));
  def('HbImprovement', sci(L.improvements.find((i) => i.problem === 'heilbronn-convex').delta)); def('MdImprovement', sci(L.improvements.find((i) => i.problem === 'min-distance-ratio-2d').delta));
  /* the tables */
  const PROBLEM = { 'circles-rectangle': 'circles in a rectangle', 'heilbronn-convex': 'Heilbronn, convex region', 'min-distance-ratio-2d': 'min-distance ratio, 2-D', 'erdos-minimum-overlap': 'Erd\\H{o}s minimum overlap', 'edges-vs-triangles': 'edges vs triangles', 'first-autocorrelation': 'first autocorrelation', 'flat-polynomials': 'flat polynomial', 'hexagon-packing': 'hexagons in a hexagon' };
  for (const p of problems) need(PROBLEM[p], 'no label for problem ' + p);
  const who = (r) => r.claimant.replace(/ \(.*\)| —.*$/, '').replace(/, this repository$/, '').replace(/^J\. K\. /, '');
  const digits = (r) => r.enclosure ? (r.printedAgrees ? 'the supremum\'s rounding' : 'NOT the supremum\'s')
    : r.problem === 'hexagon-packing' ? 'exact decimal; packing certified'
      : r.printed ? (r.printedAgrees ? 'the exact value\'s ' + r.printedConvention : 'NOT the witness\'s ' + r.printedConvention) : 'none printed';
  rows('EATableRows', L.rows.map((r) => [PROBLEM[r.problem], tex(who(r)) + ', ' + r.date, r.printed ? '$' + r.printed + '$' : '---', '$' + tex(r.exact) + '$', r.verdict, digits(r)]));
  const PREV = { 'AlphaEvolve V2': 'AlphaEvolve V2', AlphaEvolve: 'AlphaEvolve', 'TTT-Discover': 'TTT-Discover' };
  rows('EAImprovementRows', L.improvements.map((i) => [PROBLEM[i.problem], i.direction, PREV[i.previous] || tex(i.previous), sci(i.delta), i.note ? tex(i.note) : '']));
  rows('EAUndecidedRows', L.undecided.map((u) => [tex(u.problem), tex(u.claim), tex(u.status), tex(u.why)]));
  const b = battery('node', [path.join(ROOT, 'instruments', 'easota', 'battery.js')], /easota battery: (\d+) pass, 0 fail, (\d+)\/(\d+) red controls fired/, 'the easota battery');
  need(b.m[1] === b.m[2], 'an easota red control did not fire'); def('EABatteryChecks', String(b.m[0])); def('EABatteryReds', String(b.m[1]));
  def('EAGrammarW', tex(L.grammar.WITNESSED)); def('EAGrammarR', tex(L.grammar.REPAIRED)); def('EAGrammarU', tex(L.grammar.UNWITNESSED));
}

fs.writeFileSync(OUT, M.join('\n') + '\n');
console.log('wrote paper/tex/matmul-records-numbers.tex (' + (M.length - 1) + ' macros)');
