#!/usr/bin/env node
/* tools/paper-numbers/ramsey-chain.js — every number the pre-paper paper/tex/ramsey-chain.tex quotes,
   read from the records that decided it and written as LaTeX macros (paper/tex/ramsey-chain-numbers.tex).
     certs/gnnw-certificate.json          the remark's G_AI round, decided (tools/run-gnnw-ledger.py)
     certs/gnnw-chain-certificate.json    the six-round chain, both programs
     corpus/gnnw/{meta,chain,second-run,m-nodes}.json   the pins, the remark, the second program's run
     instruments/gnnw/propose/chain_deg{6,9}.json       the float proposer's sequences (observations, never a verdict)
     certs/horizonmath-ledger.json        the benchmark's Ramsey certificate, decided (tools/run-horizonmath-ledger.py)
     corpus/horizonmath/{meta,ramsey-a3-printed}.json   the pins, the checker observations, the printed recipe
   The paper \inputs the output, so it cannot quote a number the machine did not record; a record that no
   longer says what a sentence needs makes this refuse (need()), as tools/build-paper-numbers.js does.
   The HorizonMath battery (about three seconds) runs here so its count is live; the GNNW battery (about a
   minute) runs with --battery, otherwise its count is read from the report's foot.
   usage: node tools/paper-numbers/ramsey-chain.js [--battery]                                        MIT */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'paper', 'tex', 'ramsey-chain-numbers.tex');
const J = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
const T = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const sha = (rel) => crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, rel))).digest('hex');
const die = (m) => { console.error('RAMSEY-CHAIN NUMBERS REFUSED: ' + m); process.exit(1); };
const need = (c, m) => { if (!c) die(m); };
const int = (x) => Math.round(Number(x)).toLocaleString('en-US').replace(/,/g, '{,}');
const dec = (x, d) => Number(x).toFixed(d);
/* a small or large number in scientific form, as math: $6.3\times10^{-5}$ */
const sciM = (x, d) => { const m = /^(-?[\d.]+)e([+-]?\d+)$/.exec(Number(x).toExponential(d)); return m[1] + '\\times10^{' + Number(m[2]) + '}'; };
const sci = (x, d) => '$' + sciM(x, d) + '$';   /* for text; the M form goes inside math */
/* plain text into LaTeX: the few characters the records use */
const tex = (s) => String(s).replace(/\\/g, '\\textbackslash{}').replace(/([&%$#_{}])/g, '\\$1').replace(/~/g, '\\textasciitilde{}').replace(/\^/g, '\\textasciicircum{}')
  .replace(/≥/g, '$\\ge$').replace(/≤/g, '$\\le$').replace(/→/g, '$\\to$').replace(/−/g, '$-$').replace(/×/g, '$\\times$').replace(/–/g, '--').replace(/—/g, '---').replace(/…/g, '\\ldots{}')
  .replace(/λ/g, '$\\lambda$').replace(/ℓ/g, '$\\ell$').replace(/"/g, "''");
/* a decimal string cut to d digits after the point (truncation, never rounding: the records hold enclosure ends) */
const cut = (s, d) => { const m = /^(-?\d+)\.(\d+)$/.exec(String(s)); need(m, 'not a decimal string: ' + s); return m[1] + '.' + m[2].slice(0, d); };
/* the number of decimal digits after the point in which two decimal strings agree */
const agree = (a, b) => { let n = 0; for (let i = 0; i < Math.min(a.length, b.length); i++) { if (a[i] !== b[i]) break; n++; } return n - 2; };
/* a polynomial sum c_i x^(i+1) from decimal strings, as LaTeX */
const poly = (cs, v) => cs.map((c, i) => { const s = String(c); const neg = s.startsWith('-'); const a = neg ? s.slice(1) : s; const pw = i === 0 ? v : v + '^{' + (i + 1) + '}'; return (i === 0 ? (neg ? '-' : '') : (neg ? ' - ' : ' + ')) + a + pw; }).join('');
const git = (() => { try { return cp.execSync('git rev-parse --short=12 HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return 'unknown'; } })();

const M = ['%% generated by tools/paper-numbers/ramsey-chain.js from certs/gnnw-certificate.json, certs/gnnw-chain-certificate.json, corpus/gnnw, instruments/gnnw/propose, certs/horizonmath-ledger.json, corpus/horizonmath — do not edit (git ' + git + ')'];
const def = (name, val) => { if (!/^[A-Za-z]+$/.test(name)) die('bad macro name ' + name); M.push('\\newcommand{\\' + name + '}{' + val + '}'); };
const rows = (name, rr) => def(name, rr.map((r) => r.join(' & ') + ' \\\\').join('\n'));
def('RepoCommit', git);

/* ======================================================================= the pins */
const meta = J('corpus/gnnw/meta.json');
for (const [f, h] of Object.entries(meta.files)) need(sha('corpus/gnnw/' + f) === h, 'corpus/gnnw/' + f + ' is not the pinned bytes');
const Z = J('certs/gnnw-certificate.json'), K = J('certs/gnnw-chain-certificate.json');
need(Z.source.sha256 === meta.source.sha256 && K.source.sha256 === meta.source.sha256, 'the certificates and the corpus pin different bytes of the paper');
need(Z.source.paper === 'arXiv:2407.19026v2', 'the certificate is not about arXiv 2407.19026v2');
need(Z.verifier.sha256 === sha('tools/verify_gnnw_gai.py') && K.verifier.sha256 === Z.verifier.sha256, 'the verifier on disk is not the one the certificates name');
const SR = J('corpus/gnnw/second-run.json');
need(SR.codeSha256 === sha('instruments/gnnw/second.js') && SR.chainSha256 === sha('corpus/gnnw/chain.json'), 'the second program\'s run is not for the code and the chain on disk');
need(JSON.stringify(SR.result) === JSON.stringify(K.second.result), 'the chain certificate does not carry the second run as recorded');
def('GnnwArxiv', '2407.19026v2'); def('GnnwSha', meta.source.sha256.slice(0, 12)); def('GnnwVoneSha', meta.source.v1.sha256.slice(0, 12));
def('VerifierSha', Z.verifier.sha256.slice(0, 12)); def('SecondSha', SR.codeSha256.slice(0, 12)); def('ChainSha', SR.chainSha256.slice(0, 12));
def('ZGenerated', Z.generated); def('KGenerated', K.generated); def('SecondRan', SR.ran);
const PREC = /PREC = (\d+)/.exec(T('tools/verify_gnnw_gai.py')); need(PREC, 'no PREC in the verifier');
const PJS = /const P = (\d+);/.exec(T('instruments/gnnw/second.js')); need(PJS, 'no precision in second.js');
def('PrecisionPy', PREC[1]); def('PrecisionJs', PJS[1]);

/* ======================================================================= round 1: the remark's G_AI */
const D = Z.decided, S = D.stats;
need(D.verdict === 'CERTIFIED' && D.printedDigitsHold, 'round 1 is not certified');
need(D.printedIs === 'its rounding', 'the printed 3.78233 is no longer the rounding of the decided base');
need(JSON.stringify(Z.q) === JSON.stringify(meta.remark.q), 'the certificate\'s q is not the remark\'s polynomial as transcribed');
need(Z.q.length === 6 && Z.m.N === 100 && Z.m.values.length === 100, 'the round-1 certificate changed shape');
need(cut(D.c[0], 14) === cut(D.c[1], 14), 'the round-1 enclosure is wider than 14 digits');
def('QaiPoly', poly(Z.q, '\\lambda'));
def('QaiSum', dec(Z.q.reduce((a, c) => a + Number(c), 0), 4));
def('PrintedBase', D.printedBase); def('PrintedIs', D.printedIs);
def('CroundOne', cut(D.c[0], 16)); def('CroundOneFull', cut(D.c[0], 28)); def('CroundOneSix', cut(D.c[0], 6));
def('MzeroOne', Z.m.m0); def('MN', int(Z.m.N)); def('MNodes', int(Z.m.N + 1)); def('MLast', Z.m.values[Z.m.values.length - 1]);
def('MaxM', dec(S.maxM, 4)); def('MinFp', dec(S.minFp, 3));
def('TailOne', int(S.tailIntervals)); def('MainOne', int(S.mainIntervals)); def('IntervalsOne', int(S.tailIntervals + S.mainIntervals));
def('MinTailSOne', sci(S.minTailS, 2)); def('MinMainLowerOne', sci(S.minMainLower, 2));
def('WorstLo', String(S.worst[0])); def('WorstHi', String(S.worst[1]));
def('SecondsOne', dec(D.seconds, 1));
/* the remark, in the paper's words, around its formula */
const rem = meta.remark.text;
const i1 = rem.indexOf('G_AI'), i2 = rem.indexOf('If verified');
need(i1 > 0 && i2 > i1, 'the remark\'s text no longer reads as transcribed');
def('RemarkPre', tex(rem.slice(0, i1).trim()));
def('RemarkPost', tex(rem.slice(i2).replace(/R\(k, k\) ≤ \(3\.78233 \. \. \.\)\^\{k\+o\(k\)\}/, '@@MATH@@')).replace('@@MATH@@', '$R(k,k)\\le(3.78233\\ldots)^{k+o(k)}$'));
need(M[M.length - 1].includes('(3.78233\\ldots)'), 'the remark\'s printed base is not where the transcription puts it');
const pg = /^(\d+)/.exec(meta.remark.page); need(pg, 'no page number for the remark'); def('RemarkPage', pg[1]);
/* the slack curve (round 1): lower ends of enclosures of slack/lambda */
const pts = Z.curve.points;
need(pts.length >= 100 && pts[0][0] === 1e-8 && pts[pts.length - 1][0] === 1, 'the curve does not span 1e-8 to 1');
const minPt = pts.reduce((a, b) => (b[1] < a[1] ? b : a)), maxPt = pts.reduce((a, b) => (b[1] > a[1] ? b : a));
need(pts.every((p) => p[1] > 0), 'the curve is not positive everywhere');
def('CurveN', int(pts.length)); def('SlackLim', sci(pts[0][1], 2)); def('SlackMin', sci(minPt[1], 2)); def('SlackMinAt', dec(minPt[0], 2));
def('SlackLimM', sciM(pts[0][1], 2)); def('SlackMinM', sciM(minPt[1], 2));
def('SlackMax', dec(maxPt[1], 4)); def('SlackMaxAt', dec(maxPt[0], 2)); def('SlackAtOne', sci(pts[pts.length - 1][1], 2));

/* ======================================================================= the chain */
const P = K.decided, Q = K.second;
need(P.verdict === 'CERTIFIED' && Q.agrees && Q.current && Q.result.verdict === 'CERTIFIED', 'the chain is not certified by both programs');
need(K.steps.length === 6 && P.bases.length === 6 && P.perStep.length === 6 && Q.result.steps.length === 6, 'the chain is not six rounds');
need(JSON.stringify(K.steps[0].q) === JSON.stringify(Z.q) && JSON.stringify(K.steps[0].m) === JSON.stringify(Z.m), 'the chain\'s first round is not the round-1 certificate');
need(K.steps.slice(1).every((s) => s.q.length === 9) && K.steps.every((s) => s.m.N === 100), 'the later rounds are not degree 9 on 100 pieces');
need(P.bases.every((b, i) => i === 0 || Number(b) < Number(P.bases[i - 1])), 'the bases do not decrease');
need(P.perStep.every((r) => r.region === P.perStep[0].region), 'the rounds do not share one region verdict');
const agreeFinal = agree(P.c[0], Q.result.c[0]);
need(agreeFinal >= 20, 'the two programs agree on fewer than 20 digits of the final base');
need(Number(cut(Q.result.c[0], 25)) <= Number(cut(P.c[0], 25)) && Number(cut(P.c[1], 25)) <= Number(cut(Q.result.c[1], 25)) + 1e-24, 'the first program\'s enclosure is not inside the second\'s');
P.bases.forEach((b, i) => need(agree(b, Q.result.steps[i].c[0]) >= 14, 'round ' + (i + 1) + ': the recorded bases disagree'));
const nPy = P.perStep.reduce((a, r) => a + r.tail + r.main, 0), nJs = Q.result.steps.reduce((a, r) => a + r.tail + r.main, 0);
def('NRounds', int(K.steps.length)); def('NNew', int(K.steps.length - 1)); def('DegNew', int(K.steps[1].q.length)); def('DegOne', int(Z.q.length));
def('RegionVerdict', tex(P.perStep[0].region));
def('AgreeDigits', int(agreeFinal));
def('CFinalPy', cut(P.c[0], 28)); def('CFinalJsLo', cut(Q.result.c[0], 25)); def('CFinalJsHi', cut(Q.result.c[1], 25));
def('BaseFinalTen', cut(P.c[0], 10)); def('BaseFinalFour', cut(P.c[0], 4)); def('BaseFinalSix', cut(P.c[0], 6)); def('BaseFinalFive', cut(P.c[0], 5));
/* a base that is VALID under an o(k) exponent must be rounded UP, never down: c^(k+o(k)) <= d^(k+o(k)) needs d >= c */
const up = Math.ceil(Number(cut(Q.result.c[1], 12)) * 1e4) / 1e4; need(up > Number(cut(Q.result.c[1], 12)), 'the rounded-up base is not above the enclosure');
def('BaseFinalUp', dec(up, 4));
def('BaseTwoSix', cut(P.bases[1], 6)); def('BaseThreeSix', cut(P.bases[2], 6)); def('BaseFourSix', cut(P.bases[3], 6)); def('BaseFiveSix', cut(P.bases[4], 6));
def('BasesArrow', P.bases.map((b) => cut(b, 6)).join(' $\\to$ '));
def('IntervalsPyTotal', int(nPy)); def('IntervalsJsTotal', int(nJs));
def('SecondsChainPy', int(P.seconds)); def('MinutesChainJs', int(Q.result.seconds / 60)); def('SecondsChainJs', int(Q.result.seconds));
const note = /margin ([\d.e-]+) l on (\d+) points/.exec(K.steps[1].note); need(note, 'the proposer\'s margin and grid are not in the step note');
need(K.steps.slice(1).every((s) => /degree 9, SLSQP/.test(s.note)), 'the later rounds are not noted as degree-9 SLSQP proposals');
def('DeltaMargin', sci(Number(note[1]), 0)); def('DeltaMarginM', sciM(Number(note[1]), 0)); def('GridPoints', int(note[2]));
Q.result.steps.forEach((r, i) => need(r.c[0].slice(0, -1) === r.c[1].slice(0, -1) && Number(r.c[1].slice(-1)) === Number(r.c[0].slice(-1)) + 1, 'round ' + (i + 1) + ': the second program\'s enclosure ends differ beyond the last digit'));
rows('ChainRows', K.steps.map((s, i) => [String(i + 1), String(s.q.length), s.m.m0, cut(P.bases[i], 14), cut(Q.result.steps[i].c[0], 25)]));
rows('IntervalRows', K.steps.map((s, i) => { const a = P.perStep[i], b = Q.result.steps[i]; return [String(i + 1), int(a.tail), int(a.main), sci(a.minTailS, 1), sci(a.minMainLower, 1), int(b.tail), int(b.main), sci(b.minTailS, 1), sci(b.minMainLB, 1)]; }));
rows('CoeffRows', K.steps.map((s, i) => [String(i + 1)].concat(Array.from({ length: 9 }, (_, j) => (j < s.q.length ? '$' + s.q[j] + '$' : '---')))));
const boxMax = Math.max(...K.steps.flatMap((s) => s.q.map((c) => Math.abs(Number(c)))));
def('FloatBox', String(boxMax)); def('BoxActiveLast', int(K.steps[5].q.filter((c) => Math.abs(Number(c)) === boxMax).length));

/* ======================================================================= the float proposer's sequences (observations) */
const F6 = J('instruments/gnnw/propose/chain_deg6.json'), F9 = J('instruments/gnnw/propose/chain_deg9.json');
need(F6.deg === 6 && F9.deg === 9 && F6.delta === F9.delta && Number(note[1]) === F9.delta, 'the proposer\'s files are not the degree-6 and degree-9 runs at the chain\'s margin');
need(F9.chain.slice(1, 6).every((q, i) => q.every((c, j) => Math.abs(c - Number(K.steps[i + 1].q[j])) < 5e-7)), 'the certified rounds are not the degree-9 proposals rounded to six decimals');
need(F6.base.every((b, i) => i === 0 || b < F6.base[i - 1]) && F9.base.every((b, i) => i === 0 || b < F9.base[i - 1]), 'a float sequence does not decrease');
def('FloatSixIters', int(F6.base.length - 1)); def('FloatNineIters', int(F9.base.length - 1));
def('FloatSixLast', dec(F6.base[F6.base.length - 1], 6)); def('FloatNineLast', dec(F9.base[F9.base.length - 1], 7));
def('FloatSixSettle', dec(F6.base[F6.base.length - 1], 4)); def('FloatNineSettle', dec(F9.base[F9.base.length - 1], 5));
def('FloatSixDrop', sci(F6.base[F6.base.length - 2] - F6.base[F6.base.length - 1], 1)); def('FloatNineDrop', sci(F9.base[F9.base.length - 2] - F9.base[F9.base.length - 1], 1));
def('FloatNineBeyond', sci(Number(cut(P.c[0], 12)) - F9.base[F9.base.length - 1], 1)); need(Number(cut(P.c[0], 12)) > F9.base[F9.base.length - 1], 'the last float iterate is not below the certified base');
rows('FloatRows', Array.from({ length: Math.max(F6.base.length, F9.base.length) }, (_, k) => [String(k), k < F6.base.length ? dec(F6.base[k], 6) : '---', k < F9.base.length ? dec(F9.base[k], 7) : '---']));

/* ======================================================================= the HorizonMath certificate */
const HM = J('corpus/horizonmath/meta.json');
for (const [f, h] of Object.entries(HM.files)) need(sha('corpus/horizonmath/' + f) === h, 'corpus/horizonmath/' + f + ' is not the pinned bytes');
need(HM.sources.gnnw.sha256 === meta.source.sha256, 'the two corpora pin different bytes of the GNNW paper');
const L = J('certs/horizonmath-ledger.json');
need(L.source.metaSha256 === sha('corpus/horizonmath/meta.json'), 'the ledger is not for the corpus meta on disk');
const R = L.rows.find((r) => r.id === 'ramsey-asymptotic'); need(R, 'no ramsey row');
const RD = R.decided, last = R.points[R.points.length - 1], first = R.points[0], w = last.outsideR;
need(R.verdict === 'REFUTED' && RD.verdict === 'REFUTED' && R.kind === 'checker-wider-than-definition', 'the Ramsey row is not the refutation this paper describes');
need(last.lambda === 1 && w && w.regime === 'k = ceil(e m)', 'the pair at lambda = 1 is no longer excluded as recorded');
need(RD.checks.length === 3 && RD.checks.every((c) => c.ok), 'the three checks are not all green');
need(RD.points === R.points.length && RD.outsideR + RD.notPlacedByU + RD.notRefutedHere === RD.points, 'the points do not partition');
need(R.points.filter((p) => p.outsideR).length === RD.outsideR && R.points.filter((p) => p.notPlacedByU).length === RD.notPlacedByU, 'the tallies are not the rows');
const PR = J('corpus/horizonmath/ramsey-a3-printed.json'), CERT = J('corpus/horizonmath/ramsey-a3-certificate.json');
need(JSON.stringify(CERT.polynomial_coeffs.map(Number)) === JSON.stringify(PR.coeffs.map(Number)), 'the rebuilt certificate\'s polynomial is not the printed one');
need(CERT.M.values.length === 200 && PR.M_values.length === 200, 'the certificate is not 200 intervals');
need(Math.abs(RD.eMinusU1[0] - Number(PR.c_hyp)) < 1e-15, 'e^-U(1) is not the printed c_hyp');
const UC = /U_CUBIC = \(Fr\((-?\d+), (\d+)\), Fr\((-?\d+), (\d+)\), Fr\((-?\d+), (\d+)\)\)/.exec(T('instruments/horizonmath/ramsey_region.py')); need(UC, 'no U_CUBIC in the decider');
const uc = [Number(UC[1]) / Number(UC[2]), Number(UC[3]) / Number(UC[4]), Number(UC[5]) / Number(UC[6])];
need(uc.every((c, i) => c === Number(PR.coeffs[i])), 'the decider\'s U is not the printed problem\'s cubic');
const quintic = PR.coeffs.slice(3);
need(Number(quintic[0]) === 0 && Number(quintic[1]) < 0, 'the certificate\'s correction is not a quintic on the cubic');
def('HmArxiv', '2603.15617v2'); def('HmSha', HM.sources.paper.sha256.slice(0, 12)); def('HmCommit', HM.sources.benchmark.commit.slice(0, 8)); def('HmCommitFull', HM.sources.benchmark.commit);
def('LGenerated', L.generated); def('HmObservedOn', HM.observed.ramseyValidator.on);
def('HmClaimant', tex(R.claimant.split(' (')[0]));
def('HmCEncLo', RD.cEnclosure[0].slice(0, 12)); def('HmC', cut(RD.cEnclosure[0], 10)); def('HmCFour', cut(RD.cEnclosure[0], 4));
const printedC = /c = e\^\{F\(1\)\} = ([\d.]+)/.exec(R.theirChecker); need(printedC && RD.cEnclosure[0].startsWith(printedC[1].slice(0, 12)), 'the checker\'s printed c is not the enclosed one');
def('HmCPrinted', printedC[1]);
def('HmUcubic', poly(PR.coeffs.slice(0, 3), '\\mu')); def('HmQuintic', String(PR.coeffs[4])); def('HmCoeffs', '(' + PR.coeffs.map((c) => String(Number(c))).join(',\\,') + ')');
def('HmShrinkPct', dec(100 * Number(PR.shrink), 2) + '\\%'); def('HmShrink', String(PR.shrink)); def('HmLambdaZero', '10^{-3}'); need(Number(PR.lambda0) === 1e-3, 'lambda0 is not 1e-3');
def('HmIntervals', int(CERT.M.values.length)); def('HmPoints', int(RD.points)); def('HmOutside', int(RD.outsideR)); def('HmNotPlaced', int(RD.notPlacedByU)); def('HmNotRefuted', int(RD.notRefutedHere));
def('HmEU', dec(RD.eMinusU1[0], 5)); def('HmEUlong', dec(RD.eMinusU1[0], 8)); def('HmChyp', PR.c_hyp);
def('HmLastX', dec(last.X[0], 5)); def('HmLastXlong', dec(last.X[0], 8)); def('HmLastY', String(last.Y)); def('HmLastM', dec(Number(last.M), 4));
def('HmE', w.e); def('HmEdec', dec(eval(w.e), 4)); def('HmP', w.p); def('HmPdec', dec(eval(w.p), 6));
def('HmErdosLo', dec(w.erdosRateLo, 6)); def('HmPairHi', dec(w.pairRateHi, 6)); def('HmGap', dec(w.gap, 5));
need(first.outsideR && first.lambda < 0.0011, 'the first point is no longer excluded');
def('HmFirstLambda', dec(first.lambda, 5)); def('HmFirstX', dec(first.X[0], 5)); def('HmFirstY', dec(first.Y, 5)); def('HmFirstE', first.outsideR.e); def('HmFirstP', first.outsideR.p);
const nr = R.points.filter((p) => !p.outsideR && !p.notPlacedByU);
need(nr.length === RD.notRefutedHere && nr.every((p, i) => i === 0 || p.lambda > nr[i - 1].lambda), 'the not-refuted points are not one window');
def('HmNrLamLo', dec(nr[0].lambda, 3)); def('HmNrLamHi', dec(nr[nr.length - 1].lambda, 3)); def('HmNrXLo', dec(nr[nr.length - 1].X[0], 4)); def('HmNrXHi', dec(nr[0].X[0], 4));
const sec = /\((\d+) s\)|, (\d+)\)|: (\d+),/.exec(''); void sec;
need(HM.observed.ramseyValidator.seconds === 107, 'the checker\'s recorded run time changed');
def('HmCheckerSeconds', int(HM.observed.ramseyValidator.seconds));
const line = /line (\d+)/.exec(R.theirCheckerWithAnd.change); need(line, 'no line number in the change');
def('HmCheckerLine', line[1]);
const wa = R.theirCheckerWithAnd.output;
const ivl = /\[([\d.]+), ([\d.]+)\]/.exec(wa), was = /\(the first interval; ([\d.]+) s\)/.exec(wa);
need(ivl && was && /valid: false/.test(wa), 'the with-and run did not refuse on a first interval as recorded');
def('HmWithAndSeconds', was[1]); def('HmFirstIntervalLo', String(Number(ivl[1]))); def('HmFirstIntervalHi', dec(ivl[2], 7));
need(/valid: true/.test(R.theirChecker), 'the checker as published did not accept');
def('HmCheckerOutput', tex(R.theirChecker.replace(/^valid: true — /, '').replace(/^"|"$/g, '')));
def('HmCheckerMin', tex('return max(mp.mpf(0), min(bu, bs))')); def('HmCheckerMax', tex('max(bu, bs)'));
need(R.theirCheckerWithAnd.change.includes('min(bu, bs)') && R.theirCheckerWithAnd.change.includes('max(bu, bs)'), 'the one-token change is not the recorded one');
/* Lemma 15's window for the problem's U, in floats, for the figure's caption only (never decided) */
const Uf = (t) => (1 + t) * Math.log(1 + t) - t * Math.log(t) + (uc[0] * t + uc[1] * t * t + uc[2] * t ** 3) * Math.exp(-t);
const Ufp = (t) => Math.log((1 + t) / t) + Math.exp(-t) * ((uc[0] + 2 * uc[1] * t + 3 * uc[2] * t * t) - (uc[0] * t + uc[1] * t * t + uc[2] * t ** 3));
def('HmAone', dec(Math.exp(-Ufp(1)), 4)); def('HmBone', dec(Math.exp(Ufp(1) - Uf(1)), 4));
const pick = [0, 40, 80, 100, 120, 150, 180, R.points.length - 1].map((i) => R.points[i]);
rows('HmSampleRows', pick.map((p) => [dec(p.lambda, 4), dec(p.X[0], 5), dec(p.Y, 5),
  p.outsideR ? 'outside $R$' : p.notPlacedByU ? 'not placed by $U$' : 'not refuted here',
  p.outsideR ? '$e = ' + p.outsideR.e + '$, $p = ' + p.outsideR.p + '$: gap ' + dec(p.outsideR.gap, 5)
    : p.notPlacedByU ? '$s = ' + p.notPlacedByU.s + '$: $U(s)$ exceeds the line by ' + dec(p.notPlacedByU.U_lo - p.notPlacedByU.line_hi, 4) : '---']));
/* the other rows of the same ledger, for one sentence of scope */
const KK = L.rows.find((r) => r.id === 'keich-thin-triangles-128'), GG = L.rows.find((r) => r.id === 'gpt56-closed-forms');
need(KK && KK.verdict === 'CERTIFIED' && GG && GG.verdict === 'NEEDS DATA', 'the other rows are not as described');
def('KakeyaNum', KK.decided.area.num); def('KakeyaDen', KK.decided.area.den); def('KakeyaDec', cut(KK.decided.area.decimal, 10));

/* ======================================================================= the batteries */
let gb;
if (process.argv.includes('--battery')) {
  const r = cp.spawnSync('python3', ['instruments/gnnw/battery.py'], { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26 });
  gb = /gnnw battery: (\d+) pass, 0 fail, (\d+)\/(\d+) red controls fired/.exec(String(r.stdout) + String(r.stderr));
  need(r.status === 0 && gb && gb[2] === gb[3], 'the gnnw battery did not pass clean');
} else {
  gb = /battery (\d+) checks, (\d+) red controls fired/.exec(T('reports/diagonal-ramsey.html'));
  need(gb, 'no battery count in the diagonal-ramsey report foot');
  gb = [null, gb[1], gb[2], gb[2]];
}
def('GnnwBattery', int(gb[1])); def('GnnwRed', int(gb[3]));
const hr = cp.spawnSync('python3', ['instruments/horizonmath/battery.py'], { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26 });
const hb = /horizonmath battery: (\d+) pass, 0 fail, (\d+)\/(\d+) red controls fired/.exec(String(hr.stdout) + String(hr.stderr));
need(hr.status === 0 && hb && hb[2] === hb[3], 'the horizonmath battery did not pass clean:\n' + (String(hr.stdout) + String(hr.stderr)).slice(-400));
def('HmBattery', int(hb[1])); def('HmRed', int(hb[3]));

fs.writeFileSync(OUT, M.join('\n') + '\n');
console.log('wrote paper/tex/ramsey-chain-numbers.tex (' + (M.length - 1) + ' macros); final base ' + cut(P.c[0], 10) + ', ' + agreeFinal + ' digits agreed; HorizonMath ' + RD.outsideR + '/' + RD.points + ' outside R');
