#!/usr/bin/env python
"""certnumbers.py — write paper/tex/erdos1-numbers.tex (LaTeX macros) FROM THE LEDGER; nothing is typed by hand.

cert-machine (2026-09-15): the bench's version read the certificates and re-applied the verified-instance rule
itself — the third copy of that rule. Here the rule lives once, in tools/run-erdos1-ledger.js, and this script
reads certs/erdos1-ledger.json, which the report page and the index card read too. A paper macro, a page number
and a card number therefore cannot disagree.

usage: python3 instruments/erdos1/certnumbers.py        (any python3; no dependencies)"""
import sys, json, os
getattr(sys, 'set_int_max_str_digits', lambda n: None)(0)   # absent before Python 3.11
from fractions import Fraction as Fr
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
LEDGER = os.path.join(ROOT, 'certs', 'erdos1-ledger.json')
OUT = os.path.join(ROOT, 'paper', 'tex', 'erdos1-numbers.tex')
BOHMAN = Fr(22002, 100000)
L = json.load(open(LEDGER))
inst = L['instances']                      # verified instances only, by construction of the ledger
below = [I for I in inst if I['belowBohman']]
assert below, "no verified instance below Bohman"
best = min(below, key=lambda I: Fr(I['ratio']))
small = min(below, key=lambda I: I['n'])
cert_of = {c['file']: c for c in L['certificates']}
def f6(x): return f"{float(x):.6f}"
def kfmt(c): return f"{c['Kfloat']:,.1f}".replace(",", "{,}")
def comma(n): return f"{int(n):,}".replace(",", "{,}")     # {,} is a comma in text AND in math mode (a bare comma in math sets a thin space after it)
def alpha_tex(a):
    p, q = a.split('/'); return a if q == '1' else f"\\tfrac{{{p}}}{{{q}}}"
Ls = []
def nc(name, val): Ls.append(f"\\newcommand{{\\{name}}}{{{val}}}")
cb = cert_of[best['file']]
nc('Bval', best['b']); nc('Sval', best['s']); nc('Dim', comma(best['d'])); nc('DimRaw', best['d']); nc('Rval', comma(best['r'])); nc('Dval', comma(best['D']))
nc('AlphaVal', alpha_tex(best['alpha'])); nc('AlphaText', best['alpha'])
nc('DeltaVal', f6(cb['delta'])); nc('DeltaHalf', f6(cb['deltaHalf']))
nc('Kval', f"{cb['Kfloat']:,.1f}".replace(",", "{,}")); nc('Tval', comma(best['t'])); nc('Kk', best['k']); nc('Nn', comma(best['n'])); nc('NnRaw', best['n'])
nc('Ndigits', comma(best['Ndigits'])); nc('Nbits', comma(best['Nbits']))
nc('Ratio', best['ratio6']); nc('RatioF', best['f']); nc('Gain', f"{best['percentBelowBohman']:.1f}")
nc('Spread', f"{best['spread'] * 100:.2e}")
cs = cert_of[small['file']]
nc('SmallN', comma(small['n'])); nc('SmallRatio', small['ratio6']); nc('SmallF', small['f']); nc('SmallK', small['k']); nc('SmallD', small['d'])
nc('SmallAlpha', alpha_tex(small['alpha'])); nc('SmallAlphaText', small['alpha']); nc('SmallB', small['b']); nc('SmallS', small['s'])
nc('SmallKval', f"{cs['Kfloat']:,.1f}".replace(",", "{,}")); nc('SmallGain', f"{small['percentBelowBohman']:.1f}")
nc('NumCerts', L['counts']['certificates']); nc('NumInstances', L['counts']['verified']); nc('NumBelow', L['counts']['verifiedBelowBohman'])
nc('NumUnverified', L['counts']['unverified'])
# the instance table, one row per verified instance, ordered as the ledger orders them (by dimension, tilt, k)
rows = " \\\\\n".join(
    f"{I['b']} & {I['s']} & ${alpha_tex(I['alpha'])}$ & {comma(I['d'])} & {I['k']} & {comma(I['n'])} & {comma(I['Ndigits'])} & {I['ratio6']} & {I['f']} & {'below' if I['belowBohman'] else 'above'}"
    for I in inst)
Ls.append("\\newcommand{\\InstanceRows}{" + rows + " \\\\}")
# the lattices: one row per (b, s, α) — Δ_s, D, the buffer K, and K/d
seen = []
for c in L['certificates']:
    key = (c['b'], c['s'], c['alpha'])
    if key in seen or not any(I['file'] == c['file'] for I in inst): continue
    seen.append(key)
lat = " \\\\\n".join(
    f"{c['b']} & {c['s']} & ${alpha_tex(c['alpha'])}$ & {comma(c['d'])} & {comma(c['D'])} & {f6(c['delta'])} & {kfmt(c)} & {c['Kfloat'] / c['d']:.2f}"
    for c in L['certificates'] if (c['b'], c['s'], c['alpha']) in seen and c['file'] == next(cc['file'] for cc in L['certificates'] if (cc['b'], cc['s'], cc['alpha']) == (c['b'], c['s'], c['alpha'])))
Ls.append("\\newcommand{\\LatticeRows}{" + lat + " \\\\}")
S = L['siegel']
letters = 'ABCDEFGHIJKLMNOP'
dims = sorted(S, key=int)
for idx, d in enumerate(dims):
    Ls.append(f"\\newcommand{{\\Siegel{letters[idx]}}}{{{S[d]['bound']}}}")
    Ls.append(f"\\newcommand{{\\SiegelDim{letters[idx]}}}{{{comma(d)}}}")
srows = " \\\\\n".join(f"{comma(d)} & ${alpha_tex(S[d]['alpha'])}$ & {S[d]['k']} & {S[d]['f']} & {S[d]['bound']}" for d in dims)
Ls.append("\\newcommand{\\SiegelRows}{" + srows + " \\\\}")
bd = max(dims, key=lambda d: Fr(S[d]['bound']))
nc('SiegelBestD', comma(bd)); nc('SiegelBest', S[bd]['bound']); nc('SiegelCount', len(dims))
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w').write("%% generated by instruments/erdos1/certnumbers.py from certs/erdos1-ledger.json — do not edit\n" + "\n".join(Ls) + "\n")
print("\n".join(Ls[:12])); print("..."); print("wrote", os.path.relpath(OUT, ROOT))
