/- GENERATED by tools/gen-lean-erdos852.py — chunk 196/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc196 : List Nat := [346369, 346373, 346391, 346393, 346397, 346399, 346417, 346421, 346429, 346433, 346439, 346441, 346447, 346453, 346469, 346501, 346529, 346543, 346547, 346553, 346559, 346561, 346589, 346601, 346607, 346627, 346639, 346649, 346651, 346657, 346667, 346669, 346699, 346711, 346721, 346739, 346751, 346763, 346793, 346831, 346849, 346867, 346873, 346877, 346891, 346903, 346933, 346939, 346943, 346961, 346963, 347003, 347033, 347041, 347051, 347057, 347059, 347063, 347069, 347071, 347099, 347129, 347131, 347141, 347143, 347161, 347167, 347173, 347177, 347183, 347197, 347201, 347209, 347227, 347233, 347239, 347251, 347257, 347287, 347297, 347299, 347317, 347329, 347341, 347359, 347401, 347411, 347437, 347443, 347489, 347509, 347513, 347519, 347533, 347539, 347561, 347563, 347579]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc196_all_prime : (Pc196).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc196 : Nat := (Pc196.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc196 : Nat := (Pc196.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
