/- GENERATED by tools/gen-lean-erdos852.py — chunk 227/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc227 : List Nat := [384619, 384623, 384641, 384673, 384691, 384697, 384701, 384719, 384733, 384737, 384751, 384757, 384773, 384779, 384817, 384821, 384827, 384841, 384847, 384851, 384889, 384907, 384913, 384919, 384941, 384961, 384973, 385001, 385013, 385027, 385039, 385057, 385069, 385079, 385081, 385087, 385109, 385127, 385129, 385139, 385141, 385153, 385159, 385171, 385193, 385199, 385223, 385249, 385261, 385267, 385279, 385289, 385291, 385321, 385327, 385331, 385351, 385379, 385391, 385393, 385397, 385403, 385417, 385433, 385471, 385481, 385493, 385501, 385519, 385531, 385537, 385559, 385571, 385573, 385579, 385589, 385591, 385597, 385607, 385621, 385631, 385639, 385657, 385661, 385663, 385709, 385739, 385741, 385771, 385783, 385793, 385811, 385817]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc227_all_prime : (Pc227).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc227 : Nat := (Pc227.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc227 : Nat := (Pc227.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
