/- GENERATED by tools/gen-lean-erdos852.py — chunk 208/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc208 : List Nat := [361409, 361411, 361421, 361433, 361441, 361447, 361451, 361463, 361469, 361481, 361499, 361507, 361511, 361523, 361531, 361541, 361549, 361561, 361577, 361637, 361643, 361649, 361651, 361663, 361679, 361687, 361723, 361727, 361747, 361763, 361769, 361787, 361789, 361793, 361799, 361807, 361843, 361871, 361873, 361877, 361901, 361903, 361909, 361919, 361927, 361943, 361961, 361967, 361973, 361979, 361993, 362003, 362027, 362051, 362053, 362059, 362069, 362081, 362093, 362099, 362107, 362137, 362143, 362147, 362161, 362177, 362191, 362203, 362213, 362221, 362233, 362237, 362281, 362291, 362293, 362303, 362309, 362333, 362339, 362347, 362353, 362357, 362363, 362371, 362377, 362381, 362393, 362407, 362419, 362429, 362431, 362443, 362449, 362459, 362473, 362521]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc208_all_prime : (Pc208).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc208 : Nat := (Pc208.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc208 : Nat := (Pc208.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
