/- GENERATED by tools/gen-lean-erdos852.py — chunk 201/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc201 : List Nat := [352483, 352489, 352493, 352511, 352523, 352543, 352549, 352579, 352589, 352601, 352607, 352619, 352633, 352637, 352661, 352691, 352711, 352739, 352741, 352753, 352757, 352771, 352813, 352817, 352819, 352831, 352837, 352841, 352853, 352867, 352883, 352907, 352909, 352931, 352939, 352949, 352951, 352973, 352991, 353011, 353021, 353047, 353053, 353057, 353069, 353081, 353099, 353117, 353123, 353137, 353147, 353149, 353161, 353173, 353179, 353201, 353203, 353237, 353263, 353293, 353317, 353321, 353329, 353333, 353341, 353359, 353389, 353401, 353411, 353429, 353443, 353453, 353459, 353471, 353473, 353489, 353501, 353527, 353531, 353557, 353567, 353603, 353611, 353621, 353627, 353629, 353641, 353653, 353657, 353677, 353681, 353687, 353699, 353711, 353737, 353747, 353767]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc201_all_prime : (Pc201).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc201 : Nat := (Pc201.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc201 : Nat := (Pc201.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
