/- GENERATED by tools/gen-lean-erdos852.py — chunk 218/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc218 : List Nat := [373823, 373837, 373859, 373861, 373903, 373909, 373937, 373943, 373951, 373963, 373969, 373981, 373987, 373999, 374009, 374029, 374039, 374041, 374047, 374063, 374069, 374083, 374089, 374093, 374111, 374117, 374123, 374137, 374149, 374159, 374173, 374177, 374189, 374203, 374219, 374239, 374287, 374291, 374293, 374299, 374317, 374321, 374333, 374347, 374351, 374359, 374389, 374399, 374441, 374443, 374447, 374461, 374483, 374501, 374531, 374537, 374557, 374587, 374603, 374639, 374641, 374653, 374669, 374677, 374681, 374683, 374687, 374701, 374713, 374719, 374729, 374741, 374753, 374761, 374771, 374783, 374789, 374797, 374807, 374819, 374837, 374839, 374849, 374879, 374887, 374893, 374903, 374909, 374929, 374939, 374953, 374977, 374981, 374987, 374989]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc218_all_prime : (Pc218).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc218 : Nat := (Pc218.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc218 : Nat := (Pc218.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
