/- GENERATED by tools/gen-lean-erdos852.py — chunk 216/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc216 : List Nat := [371311, 371321, 371333, 371339, 371341, 371353, 371359, 371383, 371387, 371389, 371417, 371447, 371453, 371471, 371479, 371491, 371509, 371513, 371549, 371561, 371573, 371587, 371617, 371627, 371633, 371639, 371663, 371669, 371699, 371719, 371737, 371779, 371797, 371831, 371837, 371843, 371851, 371857, 371869, 371873, 371897, 371927, 371929, 371939, 371941, 371951, 371957, 371971, 371981, 371999, 372013, 372023, 372037, 372049, 372059, 372061, 372067, 372107, 372121, 372131, 372137, 372149, 372167, 372173, 372179, 372223, 372241, 372263, 372269, 372271, 372277, 372289, 372293, 372299, 372311, 372313, 372353, 372367, 372371, 372377, 372397, 372401, 372409, 372413, 372443, 372451, 372461, 372473, 372481, 372497, 372511, 372523, 372539, 372607, 372611]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc216_all_prime : (Pc216).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc216 : Nat := (Pc216.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc216 : Nat := (Pc216.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
