/- GENERATED by tools/gen-lean-erdos852.py — chunk 197/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc197 : List Nat := [347587, 347591, 347609, 347621, 347629, 347651, 347671, 347707, 347717, 347729, 347731, 347747, 347759, 347771, 347773, 347779, 347801, 347813, 347821, 347849, 347873, 347887, 347891, 347899, 347929, 347933, 347951, 347957, 347959, 347969, 347981, 347983, 347987, 347989, 347993, 348001, 348011, 348017, 348031, 348043, 348053, 348077, 348083, 348097, 348149, 348163, 348181, 348191, 348209, 348217, 348221, 348239, 348241, 348247, 348253, 348259, 348269, 348287, 348307, 348323, 348353, 348367, 348389, 348401, 348407, 348419, 348421, 348431, 348433, 348437, 348443, 348451, 348457, 348461, 348463, 348487, 348527, 348547, 348553, 348559, 348563, 348571, 348583, 348587, 348617, 348629, 348637, 348643, 348661, 348671, 348709, 348731, 348739, 348757, 348763, 348769, 348779, 348811]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc197_all_prime : (Pc197).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc197 : Nat := (Pc197.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc197 : Nat := (Pc197.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
