/- GENERATED by tools/gen-lean-erdos852.py — chunk 206/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc206 : List Nat := [358727, 358733, 358747, 358753, 358769, 358783, 358793, 358811, 358829, 358847, 358859, 358861, 358867, 358877, 358879, 358901, 358903, 358907, 358909, 358931, 358951, 358973, 358979, 358987, 358993, 358999, 359003, 359017, 359027, 359041, 359063, 359069, 359101, 359111, 359129, 359137, 359143, 359147, 359153, 359167, 359171, 359207, 359209, 359231, 359243, 359263, 359267, 359279, 359291, 359297, 359299, 359311, 359323, 359327, 359353, 359357, 359377, 359389, 359407, 359417, 359419, 359441, 359449, 359477, 359479, 359483, 359501, 359509, 359539, 359549, 359561, 359563, 359581, 359587, 359599, 359621, 359633, 359641, 359657, 359663, 359701, 359713, 359719, 359731, 359747, 359753, 359761, 359767, 359783, 359837, 359851, 359869, 359897, 359911, 359929, 359981, 359987]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc206_all_prime : (Pc206).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc206 : Nat := (Pc206.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc206 : Nat := (Pc206.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
