/- GENERATED by tools/gen-lean-erdos852.py — chunk 237/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc237 : List Nat := [396427, 396437, 396443, 396449, 396479, 396509, 396523, 396527, 396533, 396541, 396547, 396563, 396577, 396581, 396601, 396619, 396623, 396629, 396631, 396637, 396647, 396667, 396679, 396703, 396709, 396713, 396719, 396733, 396833, 396871, 396881, 396883, 396887, 396919, 396931, 396937, 396943, 396947, 396953, 396971, 396983, 396997, 397013, 397027, 397037, 397051, 397057, 397063, 397073, 397093, 397099, 397127, 397151, 397153, 397181, 397183, 397211, 397217, 397223, 397237, 397253, 397259, 397283, 397289, 397297, 397301, 397303, 397337, 397351, 397357, 397361, 397373, 397379, 397427, 397429, 397433, 397459, 397469, 397489, 397493, 397517, 397519, 397541, 397543, 397547, 397549, 397567, 397589, 397591, 397597, 397633, 397643]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc237_all_prime : (Pc237).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc237 : Nat := (Pc237.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc237 : Nat := (Pc237.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
