/- GENERATED by tools/gen-lean-erdos852.py — chunk 222/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc222 : List Nat := [378593, 378601, 378619, 378629, 378661, 378667, 378671, 378683, 378691, 378713, 378733, 378739, 378757, 378761, 378779, 378793, 378809, 378817, 378821, 378823, 378869, 378883, 378893, 378901, 378919, 378929, 378941, 378949, 378953, 378967, 378977, 378997, 379007, 379009, 379013, 379033, 379039, 379073, 379081, 379087, 379097, 379103, 379123, 379133, 379147, 379157, 379163, 379177, 379187, 379189, 379199, 379207, 379273, 379277, 379283, 379289, 379307, 379319, 379333, 379343, 379369, 379387, 379391, 379397, 379399, 379417, 379433, 379439, 379441, 379451, 379459, 379499, 379501, 379513, 379531, 379541, 379549, 379571, 379573, 379579, 379597, 379607, 379633, 379649, 379663, 379667, 379679, 379681, 379693, 379699, 379703, 379721, 379723, 379727]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc222_all_prime : (Pc222).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc222 : Nat := (Pc222.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc222 : Nat := (Pc222.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
