/- GENERATED by tools/gen-lean-erdos852.py — chunk 235/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc235 : List Nat := [393961, 393977, 393989, 393997, 394007, 394019, 394039, 394049, 394063, 394073, 394099, 394123, 394129, 394153, 394157, 394169, 394187, 394201, 394211, 394223, 394241, 394249, 394259, 394271, 394291, 394319, 394327, 394357, 394363, 394367, 394369, 394393, 394409, 394411, 394453, 394481, 394489, 394501, 394507, 394523, 394529, 394549, 394571, 394577, 394579, 394601, 394619, 394631, 394633, 394637, 394643, 394673, 394699, 394717, 394721, 394727, 394729, 394733, 394739, 394747, 394759, 394787, 394811, 394813, 394817, 394819, 394829, 394837, 394861, 394879, 394897, 394931, 394943, 394963, 394967, 394969, 394981, 394987, 394993, 395023, 395027, 395039, 395047, 395069, 395089, 395093, 395107, 395111, 395113, 395119, 395137, 395141]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc235_all_prime : (Pc235).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc235 : Nat := (Pc235.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc235 : Nat := (Pc235.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
