/- GENERATED by tools/gen-lean-erdos852.py — chunk 221/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc221 : List Nat := [377329, 377339, 377347, 377353, 377369, 377371, 377387, 377393, 377459, 377471, 377477, 377491, 377513, 377521, 377527, 377537, 377543, 377557, 377561, 377563, 377581, 377593, 377599, 377617, 377623, 377633, 377653, 377681, 377687, 377711, 377717, 377737, 377749, 377761, 377771, 377779, 377789, 377801, 377809, 377827, 377831, 377843, 377851, 377873, 377887, 377911, 377963, 377981, 377999, 378011, 378019, 378023, 378041, 378071, 378083, 378089, 378101, 378127, 378137, 378149, 378151, 378163, 378167, 378179, 378193, 378223, 378229, 378239, 378241, 378253, 378269, 378277, 378283, 378289, 378317, 378353, 378361, 378379, 378401, 378407, 378439, 378449, 378463, 378467, 378493, 378503, 378509, 378523, 378533, 378551, 378559, 378569, 378571, 378583]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc221_all_prime : (Pc221).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc221 : Nat := (Pc221.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc221 : Nat := (Pc221.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
