/- GENERATED by tools/gen-lean-erdos852.py — chunk 220/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc220 : List Nat := [376097, 376099, 376127, 376133, 376147, 376153, 376171, 376183, 376199, 376231, 376237, 376241, 376283, 376291, 376297, 376307, 376351, 376373, 376393, 376399, 376417, 376463, 376469, 376471, 376477, 376483, 376501, 376511, 376529, 376531, 376547, 376573, 376577, 376583, 376589, 376603, 376609, 376627, 376631, 376633, 376639, 376657, 376679, 376687, 376699, 376709, 376721, 376729, 376757, 376759, 376769, 376787, 376793, 376801, 376807, 376811, 376819, 376823, 376837, 376841, 376847, 376853, 376889, 376891, 376897, 376921, 376927, 376931, 376933, 376949, 376963, 376969, 377011, 377021, 377051, 377059, 377071, 377099, 377123, 377129, 377137, 377147, 377171, 377173, 377183, 377197, 377219, 377231, 377257, 377263, 377287, 377291, 377297, 377327]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc220_all_prime : (Pc220).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc220 : Nat := (Pc220.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc220 : Nat := (Pc220.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
