/- GENERATED by tools/gen-lean-erdos852.py — chunk 213/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc213 : List Nat := [367357, 367369, 367391, 367397, 367427, 367453, 367457, 367469, 367501, 367519, 367531, 367541, 367547, 367559, 367561, 367573, 367597, 367603, 367613, 367621, 367637, 367649, 367651, 367663, 367673, 367687, 367699, 367711, 367721, 367733, 367739, 367751, 367771, 367777, 367781, 367789, 367819, 367823, 367831, 367841, 367849, 367853, 367867, 367879, 367883, 367889, 367909, 367949, 367957, 368021, 368029, 368047, 368059, 368077, 368083, 368089, 368099, 368107, 368111, 368117, 368129, 368141, 368149, 368153, 368171, 368189, 368197, 368227, 368231, 368233, 368243, 368273, 368279, 368287, 368293, 368323, 368327, 368359, 368363, 368369, 368399, 368411, 368443, 368447, 368453, 368471, 368491, 368507, 368513, 368521, 368531, 368539, 368551, 368579, 368593]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc213_all_prime : (Pc213).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc213 : Nat := (Pc213.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc213 : Nat := (Pc213.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
