/- GENERATED by tools/gen-lean-erdos852.py — chunk 233/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc233 : List Nat := [391823, 391847, 391861, 391873, 391879, 391889, 391891, 391903, 391907, 391921, 391939, 391961, 391967, 391987, 391999, 392011, 392033, 392053, 392059, 392069, 392087, 392099, 392101, 392111, 392113, 392131, 392143, 392149, 392153, 392159, 392177, 392201, 392209, 392213, 392221, 392233, 392239, 392251, 392261, 392263, 392267, 392269, 392279, 392281, 392297, 392299, 392321, 392333, 392339, 392347, 392351, 392363, 392383, 392389, 392423, 392437, 392443, 392467, 392473, 392477, 392489, 392503, 392519, 392531, 392543, 392549, 392569, 392593, 392599, 392611, 392629, 392647, 392663, 392669, 392699, 392723, 392737, 392741, 392759, 392761, 392767, 392803, 392807, 392809, 392827, 392831, 392837, 392849, 392851, 392857, 392879, 392893]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc233_all_prime : (Pc233).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc233 : Nat := (Pc233.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc233 : Nat := (Pc233.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
