/- GENERATED by tools/gen-lean-erdos852.py — chunk 224/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc224 : List Nat := [381011, 381019, 381037, 381047, 381061, 381071, 381077, 381097, 381103, 381167, 381169, 381181, 381209, 381221, 381223, 381233, 381239, 381253, 381287, 381289, 381301, 381319, 381323, 381343, 381347, 381371, 381373, 381377, 381383, 381389, 381401, 381413, 381419, 381439, 381443, 381461, 381467, 381481, 381487, 381509, 381523, 381527, 381529, 381533, 381541, 381559, 381569, 381607, 381629, 381631, 381637, 381659, 381673, 381697, 381707, 381713, 381737, 381739, 381749, 381757, 381761, 381791, 381793, 381817, 381841, 381853, 381859, 381911, 381917, 381937, 381943, 381949, 381977, 381989, 381991, 382001, 382003, 382021, 382037, 382061, 382069, 382073, 382087, 382103, 382117, 382163, 382171, 382189, 382229, 382231, 382241, 382253, 382267, 382271]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc224_all_prime : (Pc224).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc224 : Nat := (Pc224.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc224 : Nat := (Pc224.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
