/- GENERATED by tools/gen-lean-erdos852.py — chunk 202/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc202 : List Nat := [353777, 353783, 353797, 353807, 353813, 353819, 353833, 353867, 353869, 353879, 353891, 353897, 353911, 353917, 353921, 353929, 353939, 353963, 354001, 354007, 354017, 354023, 354031, 354037, 354041, 354043, 354047, 354073, 354091, 354097, 354121, 354139, 354143, 354149, 354163, 354169, 354181, 354209, 354247, 354251, 354253, 354257, 354259, 354271, 354301, 354307, 354313, 354317, 354323, 354329, 354337, 354353, 354371, 354373, 354377, 354383, 354391, 354401, 354421, 354439, 354443, 354451, 354461, 354463, 354469, 354479, 354533, 354539, 354551, 354553, 354581, 354587, 354619, 354643, 354647, 354661, 354667, 354677, 354689, 354701, 354703, 354727, 354737, 354743, 354751, 354763, 354779, 354791, 354799, 354829, 354833, 354839, 354847, 354869, 354877, 354881, 354883]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc202_all_prime : (Pc202).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc202 : Nat := (Pc202.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc202 : Nat := (Pc202.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
