/- GENERATED by tools/gen-lean-erdos852.py — chunk 215/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc215 : List Nat := [370009, 370021, 370033, 370057, 370061, 370067, 370081, 370091, 370103, 370121, 370133, 370147, 370159, 370169, 370193, 370199, 370207, 370213, 370217, 370241, 370247, 370261, 370373, 370387, 370399, 370411, 370421, 370423, 370427, 370439, 370441, 370451, 370463, 370471, 370477, 370483, 370493, 370511, 370529, 370537, 370547, 370561, 370571, 370597, 370603, 370609, 370613, 370619, 370631, 370661, 370663, 370673, 370679, 370687, 370693, 370723, 370759, 370793, 370801, 370813, 370837, 370871, 370873, 370879, 370883, 370891, 370897, 370919, 370949, 371027, 371029, 371057, 371069, 371071, 371083, 371087, 371099, 371131, 371141, 371143, 371153, 371177, 371179, 371191, 371213, 371227, 371233, 371237, 371249, 371251, 371257, 371281, 371291, 371299, 371303]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc215_all_prime : (Pc215).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc215 : Nat := (Pc215.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc215 : Nat := (Pc215.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
