/- GENERATED by tools/gen-lean-erdos852.py — chunk 203/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc203 : List Nat := [354911, 354953, 354961, 354971, 354973, 354979, 354983, 354997, 355007, 355009, 355027, 355031, 355037, 355039, 355049, 355057, 355063, 355073, 355087, 355093, 355099, 355109, 355111, 355127, 355139, 355171, 355193, 355211, 355261, 355297, 355307, 355321, 355331, 355339, 355343, 355361, 355363, 355379, 355417, 355427, 355441, 355457, 355463, 355483, 355499, 355501, 355507, 355513, 355517, 355519, 355529, 355541, 355549, 355559, 355571, 355573, 355591, 355609, 355633, 355643, 355651, 355669, 355679, 355697, 355717, 355721, 355723, 355753, 355763, 355777, 355783, 355799, 355811, 355819, 355841, 355847, 355853, 355867, 355891, 355909, 355913, 355933, 355937, 355939, 355951, 355967, 355969, 356023, 356039, 356077, 356093, 356101, 356113, 356123, 356129, 356137, 356141]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc203_all_prime : (Pc203).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc203 : Nat := (Pc203.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc203 : Nat := (Pc203.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
