/- GENERATED by tools/gen-lean-erdos852.py — chunk 240/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc240 : List Nat := [399953, 399979, 399983, 399989]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc240_all_prime : (Pc240).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc240 : Nat := (Pc240.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc240 : Nat := (Pc240.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
