/- GENERATED by tools/gen-lean-erdos852.py — chunk 238/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc238 : List Nat := [397673, 397687, 397697, 397721, 397723, 397729, 397751, 397753, 397757, 397759, 397763, 397799, 397807, 397811, 397829, 397849, 397867, 397897, 397907, 397921, 397939, 397951, 397963, 397973, 397981, 398011, 398023, 398029, 398033, 398039, 398053, 398059, 398063, 398077, 398087, 398113, 398117, 398119, 398129, 398143, 398149, 398171, 398207, 398213, 398219, 398227, 398249, 398261, 398267, 398273, 398287, 398303, 398311, 398323, 398339, 398341, 398347, 398353, 398357, 398369, 398393, 398407, 398417, 398423, 398441, 398459, 398467, 398471, 398473, 398477, 398491, 398509, 398539, 398543, 398549, 398557, 398569, 398581, 398591, 398609, 398611, 398621, 398627, 398669, 398681, 398683, 398693, 398711, 398729, 398731, 398759, 398771]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc238_all_prime : (Pc238).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc238 : Nat := (Pc238.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc238 : Nat := (Pc238.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
