/- GENERATED by tools/gen-lean-erdos852.py — chunk 195/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc195 : List Nat := [345089, 345109, 345133, 345139, 345143, 345181, 345193, 345221, 345227, 345229, 345259, 345263, 345271, 345307, 345311, 345329, 345379, 345413, 345431, 345451, 345461, 345463, 345473, 345479, 345487, 345511, 345517, 345533, 345547, 345551, 345571, 345577, 345581, 345599, 345601, 345607, 345637, 345643, 345647, 345659, 345673, 345679, 345689, 345701, 345707, 345727, 345731, 345733, 345739, 345749, 345757, 345769, 345773, 345791, 345803, 345811, 345817, 345823, 345853, 345869, 345881, 345887, 345889, 345907, 345923, 345937, 345953, 345979, 345997, 346013, 346039, 346043, 346051, 346079, 346091, 346097, 346111, 346117, 346133, 346139, 346141, 346147, 346169, 346187, 346201, 346207, 346217, 346223, 346259, 346261, 346277, 346303, 346309, 346321, 346331, 346337, 346349, 346361]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc195_all_prime : (Pc195).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc195 : Nat := (Pc195.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc195 : Nat := (Pc195.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
