/- GENERATED by tools/gen-lean-erdos852.py — chunk 7/8. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def PForgeCompositec7 : List Nat := [8191, 8209, 8219, 8221, 8231, 8233, 8237, 8243, 8263, 8269, 8273, 8287, 8291, 8293, 8297, 8311, 8317, 8329, 8353, 8363, 8369, 8377, 8387, 8389, 8419, 8423, 8429, 8431, 8443, 8447, 8461, 8467, 8501, 8513, 8521, 8527, 8537, 8539, 8543, 8563, 8573, 8581, 8597, 8599, 8609, 8623, 8627, 8629, 8641, 8647, 8663, 8669, 8677, 8681, 8689, 8693, 8699, 8707, 8713, 8719, 8731, 8737, 8741, 8747, 8753, 8761, 8779, 8783, 8803, 8807, 8819, 8821, 8831, 8837, 8839, 8849, 8861, 8863, 8867, 8887, 8893, 8923, 8929, 8933, 8941, 8951, 8963, 8969, 8971, 8999, 9001, 9007, 9011, 9013, 9029, 9041, 9043, 9049, 9059, 9067, 9091, 9103, 9109, 9127, 9133]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem PForgeCompositec7_all_prime : (PForgeCompositec7).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def NcForgeComposite7 : Nat := (PForgeCompositec7.map (fun p => (p - 1) ^ 3 + 1)).prod
def DcForgeComposite7 : Nat := (PForgeCompositec7.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
