/- GENERATED by tools/gen-lean-erdos852.py — chunk 207/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc207 : List Nat := [360007, 360023, 360037, 360049, 360053, 360071, 360089, 360091, 360163, 360167, 360169, 360181, 360187, 360193, 360197, 360223, 360229, 360233, 360257, 360271, 360277, 360287, 360289, 360293, 360307, 360317, 360323, 360337, 360391, 360407, 360421, 360439, 360457, 360461, 360497, 360509, 360511, 360541, 360551, 360589, 360593, 360611, 360637, 360649, 360653, 360749, 360769, 360779, 360781, 360803, 360817, 360821, 360823, 360827, 360851, 360853, 360863, 360869, 360901, 360907, 360947, 360949, 360953, 360959, 360973, 360977, 360979, 360989, 361001, 361003, 361013, 361033, 361069, 361091, 361093, 361111, 361159, 361183, 361211, 361213, 361217, 361219, 361223, 361237, 361241, 361271, 361279, 361313, 361321, 361327, 361337, 361349, 361351, 361357, 361363, 361373]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc207_all_prime : (Pc207).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc207 : Nat := (Pc207.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc207 : Nat := (Pc207.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
