/- GENERATED by tools/gen-lean-erdos852.py — chunk 229/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc229 : List Nat := [387017, 387031, 387047, 387071, 387077, 387083, 387089, 387109, 387137, 387151, 387161, 387169, 387173, 387187, 387197, 387199, 387203, 387227, 387253, 387263, 387269, 387281, 387307, 387313, 387329, 387341, 387371, 387397, 387403, 387433, 387437, 387449, 387463, 387493, 387503, 387509, 387529, 387551, 387577, 387587, 387613, 387623, 387631, 387641, 387659, 387677, 387679, 387683, 387707, 387721, 387727, 387743, 387749, 387763, 387781, 387791, 387799, 387839, 387853, 387857, 387911, 387913, 387917, 387953, 387967, 387971, 387973, 387977, 388009, 388051, 388057, 388067, 388081, 388099, 388109, 388111, 388117, 388133, 388159, 388163, 388169, 388177, 388181, 388183, 388187, 388211, 388231, 388237, 388253, 388259, 388273, 388277, 388301]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc229_all_prime : (Pc229).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc229 : Nat := (Pc229.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc229 : Nat := (Pc229.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
