/- GENERATED by tools/gen-lean-erdos852.py — chunk 231/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc231 : List Nat := [389539, 389561, 389563, 389567, 389569, 389579, 389591, 389621, 389629, 389651, 389659, 389663, 389687, 389699, 389713, 389723, 389743, 389749, 389761, 389773, 389783, 389791, 389797, 389819, 389839, 389849, 389867, 389891, 389897, 389903, 389911, 389923, 389927, 389941, 389947, 389953, 389957, 389971, 389981, 389989, 389999, 390001, 390043, 390067, 390077, 390083, 390097, 390101, 390107, 390109, 390113, 390119, 390151, 390157, 390161, 390191, 390193, 390199, 390209, 390211, 390223, 390263, 390281, 390289, 390307, 390323, 390343, 390347, 390353, 390359, 390367, 390373, 390389, 390391, 390407, 390413, 390419, 390421, 390433, 390437, 390449, 390463, 390479, 390487, 390491, 390493, 390499, 390503, 390527, 390539, 390553, 390581, 390647]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc231_all_prime : (Pc231).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc231 : Nat := (Pc231.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc231 : Nat := (Pc231.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
