/- GENERATED by tools/gen-lean-erdos852.py — chunk 225/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc225 : List Nat := [382303, 382331, 382351, 382357, 382363, 382373, 382391, 382427, 382429, 382457, 382463, 382493, 382507, 382511, 382519, 382541, 382549, 382553, 382567, 382579, 382583, 382589, 382601, 382621, 382631, 382643, 382649, 382661, 382663, 382693, 382703, 382709, 382727, 382729, 382747, 382751, 382763, 382769, 382777, 382801, 382807, 382813, 382843, 382847, 382861, 382867, 382871, 382873, 382883, 382919, 382933, 382939, 382961, 382979, 382999, 383011, 383023, 383029, 383041, 383051, 383069, 383077, 383081, 383083, 383099, 383101, 383107, 383113, 383143, 383147, 383153, 383171, 383179, 383219, 383221, 383261, 383267, 383281, 383291, 383297, 383303, 383321, 383347, 383371, 383393, 383399, 383417, 383419, 383429, 383459, 383483, 383489, 383519, 383521]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc225_all_prime : (Pc225).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc225 : Nat := (Pc225.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc225 : Nat := (Pc225.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
