/- GENERATED by tools/gen-lean-erdos852.py — chunk 205/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc205 : List Nat := [357569, 357571, 357583, 357587, 357593, 357611, 357613, 357619, 357649, 357653, 357659, 357661, 357667, 357671, 357677, 357683, 357689, 357703, 357727, 357733, 357737, 357739, 357767, 357779, 357781, 357787, 357793, 357809, 357817, 357823, 357829, 357839, 357859, 357883, 357913, 357967, 357977, 357983, 357989, 357997, 358031, 358051, 358069, 358073, 358079, 358103, 358109, 358153, 358157, 358159, 358181, 358201, 358213, 358219, 358223, 358229, 358243, 358273, 358277, 358279, 358289, 358291, 358297, 358301, 358313, 358327, 358331, 358349, 358373, 358417, 358427, 358429, 358441, 358447, 358459, 358471, 358483, 358487, 358499, 358531, 358541, 358571, 358573, 358591, 358597, 358601, 358607, 358613, 358637, 358667, 358669, 358681, 358691, 358697, 358703, 358711, 358723]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc205_all_prime : (Pc205).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc205 : Nat := (Pc205.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc205 : Nat := (Pc205.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
