/- GENERATED by tools/gen-lean-erdos852.py — chunk 209/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc209 : List Nat := [362561, 362569, 362581, 362599, 362629, 362633, 362657, 362693, 362707, 362717, 362723, 362741, 362743, 362749, 362753, 362759, 362801, 362851, 362863, 362867, 362897, 362903, 362911, 362927, 362941, 362951, 362953, 362969, 362977, 362983, 362987, 363017, 363019, 363037, 363043, 363047, 363059, 363061, 363067, 363119, 363149, 363151, 363157, 363161, 363173, 363179, 363199, 363211, 363217, 363257, 363269, 363271, 363277, 363313, 363317, 363329, 363343, 363359, 363361, 363367, 363371, 363373, 363379, 363397, 363401, 363403, 363431, 363437, 363439, 363463, 363481, 363491, 363497, 363523, 363529, 363533, 363541, 363551, 363557, 363563, 363569, 363577, 363581, 363589, 363611, 363619, 363659, 363677, 363683, 363691, 363719, 363731, 363751, 363757, 363761, 363767]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc209_all_prime : (Pc209).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc209 : Nat := (Pc209.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc209 : Nat := (Pc209.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
