/- GENERATED by tools/gen-lean-erdos852.py — chunk 236/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc236 : List Nat := [395147, 395159, 395173, 395189, 395191, 395201, 395231, 395243, 395251, 395261, 395273, 395287, 395293, 395303, 395309, 395321, 395323, 395377, 395383, 395407, 395429, 395431, 395443, 395449, 395453, 395459, 395491, 395509, 395513, 395533, 395537, 395543, 395581, 395597, 395611, 395621, 395627, 395657, 395671, 395677, 395687, 395701, 395719, 395737, 395741, 395749, 395767, 395803, 395849, 395851, 395873, 395887, 395891, 395897, 395909, 395921, 395953, 395959, 395971, 396001, 396029, 396031, 396041, 396043, 396061, 396079, 396091, 396103, 396107, 396119, 396157, 396173, 396181, 396197, 396199, 396203, 396217, 396239, 396247, 396259, 396269, 396293, 396299, 396301, 396311, 396323, 396349, 396353, 396373, 396377, 396379, 396413]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc236_all_prime : (Pc236).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc236 : Nat := (Pc236.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc236 : Nat := (Pc236.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
