/- GENERATED by tools/gen-lean-erdos852.py — chunk 219/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc219 : List Nat := [374993, 375017, 375019, 375029, 375043, 375049, 375059, 375083, 375091, 375097, 375101, 375103, 375113, 375119, 375121, 375127, 375149, 375157, 375163, 375169, 375203, 375209, 375223, 375227, 375233, 375247, 375251, 375253, 375257, 375259, 375281, 375283, 375311, 375341, 375359, 375367, 375371, 375373, 375391, 375407, 375413, 375443, 375449, 375451, 375457, 375467, 375481, 375509, 375511, 375523, 375527, 375533, 375553, 375559, 375563, 375569, 375593, 375607, 375623, 375631, 375643, 375647, 375667, 375673, 375703, 375707, 375709, 375743, 375757, 375761, 375773, 375779, 375787, 375799, 375833, 375841, 375857, 375899, 375901, 375923, 375931, 375967, 375971, 375979, 375983, 375997, 376001, 376003, 376009, 376021, 376039, 376049, 376063, 376081]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc219_all_prime : (Pc219).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc219 : Nat := (Pc219.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc219 : Nat := (Pc219.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
