/- GENERATED by tools/gen-lean-erdos852.py — chunk 239/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc239 : List Nat := [398813, 398819, 398821, 398833, 398857, 398863, 398887, 398903, 398917, 398921, 398933, 398941, 398969, 398977, 398989, 399023, 399031, 399043, 399059, 399067, 399071, 399079, 399097, 399101, 399107, 399131, 399137, 399149, 399151, 399163, 399173, 399181, 399197, 399221, 399227, 399239, 399241, 399263, 399271, 399277, 399281, 399283, 399353, 399379, 399389, 399391, 399401, 399403, 399409, 399433, 399439, 399473, 399481, 399491, 399493, 399499, 399523, 399527, 399541, 399557, 399571, 399577, 399583, 399587, 399601, 399613, 399617, 399643, 399647, 399667, 399677, 399689, 399691, 399719, 399727, 399731, 399739, 399757, 399761, 399769, 399781, 399787, 399793, 399851, 399853, 399871, 399887, 399899, 399911, 399913, 399937, 399941]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc239_all_prime : (Pc239).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc239 : Nat := (Pc239.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc239 : Nat := (Pc239.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
