/- GENERATED by tools/gen-lean-erdos852.py — chunk 211/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc211 : List Nat := [365003, 365017, 365021, 365039, 365063, 365069, 365089, 365107, 365119, 365129, 365137, 365147, 365159, 365173, 365179, 365201, 365213, 365231, 365249, 365251, 365257, 365291, 365293, 365297, 365303, 365327, 365333, 365357, 365369, 365377, 365411, 365413, 365419, 365423, 365441, 365461, 365467, 365471, 365473, 365479, 365489, 365507, 365509, 365513, 365527, 365531, 365537, 365557, 365567, 365569, 365587, 365591, 365611, 365627, 365639, 365641, 365669, 365683, 365689, 365699, 365747, 365749, 365759, 365773, 365779, 365791, 365797, 365809, 365837, 365839, 365851, 365903, 365929, 365933, 365941, 365969, 365983, 366001, 366013, 366019, 366029, 366031, 366053, 366077, 366097, 366103, 366127, 366133, 366139, 366161, 366167, 366169, 366173, 366181, 366193, 366199]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc211_all_prime : (Pc211).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc211 : Nat := (Pc211.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc211 : Nat := (Pc211.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
