/- GENERATED by tools/gen-lean-erdos852.py — chunk 223/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc223 : List Nat := [379751, 379777, 379787, 379811, 379817, 379837, 379849, 379853, 379859, 379877, 379889, 379903, 379909, 379913, 379927, 379931, 379963, 379979, 379993, 379997, 379999, 380041, 380047, 380059, 380071, 380117, 380129, 380131, 380141, 380147, 380179, 380189, 380197, 380201, 380203, 380207, 380231, 380251, 380267, 380269, 380287, 380291, 380299, 380309, 380311, 380327, 380329, 380333, 380363, 380377, 380383, 380417, 380423, 380441, 380447, 380453, 380459, 380461, 380483, 380503, 380533, 380557, 380563, 380591, 380621, 380623, 380629, 380641, 380651, 380657, 380707, 380713, 380729, 380753, 380777, 380797, 380803, 380819, 380837, 380839, 380843, 380867, 380869, 380879, 380881, 380909, 380917, 380929, 380951, 380957, 380971, 380977, 380983, 381001]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc223_all_prime : (Pc223).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc223 : Nat := (Pc223.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc223 : Nat := (Pc223.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
