/- GENERATED by tools/gen-lean-erdos852.py — chunk 210/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc210 : List Nat := [363773, 363799, 363809, 363829, 363833, 363841, 363871, 363887, 363889, 363901, 363911, 363917, 363941, 363947, 363949, 363959, 363967, 363977, 363989, 364027, 364031, 364069, 364073, 364079, 364103, 364127, 364129, 364141, 364171, 364183, 364187, 364193, 364213, 364223, 364241, 364267, 364271, 364289, 364291, 364303, 364313, 364321, 364333, 364337, 364349, 364373, 364379, 364393, 364411, 364417, 364423, 364433, 364447, 364451, 364459, 364471, 364499, 364513, 364523, 364537, 364541, 364543, 364571, 364583, 364601, 364607, 364621, 364627, 364643, 364657, 364669, 364687, 364691, 364699, 364717, 364739, 364747, 364751, 364753, 364759, 364801, 364829, 364853, 364873, 364879, 364883, 364891, 364909, 364919, 364921, 364937, 364943, 364961, 364979, 364993, 364997]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc210_all_prime : (Pc210).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc210 : Nat := (Pc210.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc210 : Nat := (Pc210.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
