/- GENERATED by tools/gen-lean-erdos852.py — chunk 199/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc199 : List Nat := [350033, 350039, 350087, 350089, 350093, 350107, 350111, 350137, 350159, 350179, 350191, 350213, 350219, 350237, 350249, 350257, 350281, 350293, 350347, 350351, 350377, 350381, 350411, 350423, 350429, 350431, 350437, 350443, 350447, 350453, 350459, 350503, 350521, 350549, 350561, 350563, 350587, 350593, 350617, 350621, 350629, 350657, 350663, 350677, 350699, 350711, 350719, 350729, 350731, 350737, 350741, 350747, 350767, 350771, 350783, 350789, 350803, 350809, 350843, 350851, 350869, 350881, 350887, 350891, 350899, 350941, 350947, 350963, 350971, 350981, 350983, 350989, 351011, 351023, 351031, 351037, 351041, 351047, 351053, 351059, 351061, 351077, 351079, 351097, 351121, 351133, 351151, 351157, 351179, 351217, 351223, 351229, 351257, 351259, 351269, 351287, 351289, 351293]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc199_all_prime : (Pc199).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc199 : Nat := (Pc199.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc199 : Nat := (Pc199.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
