/- GENERATED by tools/gen-lean-erdos852.py — chunk 232/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc232 : List Nat := [390653, 390671, 390673, 390703, 390707, 390721, 390727, 390737, 390739, 390743, 390751, 390763, 390781, 390791, 390809, 390821, 390829, 390851, 390869, 390877, 390883, 390889, 390893, 390953, 390959, 390961, 390967, 390989, 390991, 391009, 391019, 391021, 391031, 391049, 391057, 391063, 391067, 391073, 391103, 391117, 391133, 391151, 391159, 391163, 391177, 391199, 391217, 391219, 391231, 391247, 391249, 391273, 391283, 391291, 391301, 391331, 391337, 391351, 391367, 391373, 391379, 391387, 391393, 391397, 391399, 391403, 391441, 391451, 391453, 391487, 391519, 391537, 391553, 391579, 391613, 391619, 391627, 391631, 391639, 391661, 391679, 391691, 391693, 391711, 391717, 391733, 391739, 391751, 391753, 391757, 391789, 391801, 391817]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc232_all_prime : (Pc232).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc232 : Nat := (Pc232.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc232 : Nat := (Pc232.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
