/- GENERATED by tools/gen-lean-erdos852.py — chunk 230/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc230 : List Nat := [388313, 388319, 388351, 388363, 388369, 388373, 388391, 388403, 388459, 388471, 388477, 388481, 388483, 388489, 388499, 388519, 388529, 388541, 388567, 388573, 388621, 388651, 388657, 388673, 388691, 388693, 388697, 388699, 388711, 388727, 388757, 388777, 388781, 388789, 388793, 388813, 388823, 388837, 388859, 388879, 388891, 388897, 388901, 388903, 388931, 388933, 388937, 388961, 388963, 388991, 389003, 389023, 389027, 389029, 389041, 389047, 389057, 389083, 389089, 389099, 389111, 389117, 389141, 389149, 389161, 389167, 389171, 389173, 389189, 389219, 389227, 389231, 389269, 389273, 389287, 389297, 389299, 389303, 389357, 389369, 389381, 389399, 389401, 389437, 389447, 389461, 389479, 389483, 389507, 389513, 389527, 389531, 389533]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc230_all_prime : (Pc230).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc230 : Nat := (Pc230.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc230 : Nat := (Pc230.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
