/- GENERATED by tools/gen-lean-erdos852.py — chunk 204/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc204 : List Nat := [356143, 356171, 356173, 356197, 356219, 356243, 356261, 356263, 356287, 356299, 356311, 356327, 356333, 356351, 356387, 356399, 356441, 356443, 356449, 356453, 356467, 356479, 356501, 356509, 356533, 356549, 356561, 356563, 356567, 356579, 356591, 356621, 356647, 356663, 356693, 356701, 356731, 356737, 356749, 356761, 356803, 356819, 356821, 356831, 356869, 356887, 356893, 356927, 356929, 356933, 356947, 356959, 356969, 356977, 356981, 356989, 356999, 357031, 357047, 357073, 357079, 357083, 357103, 357107, 357109, 357131, 357139, 357169, 357179, 357197, 357199, 357211, 357229, 357239, 357241, 357263, 357271, 357281, 357283, 357293, 357319, 357347, 357349, 357353, 357359, 357377, 357389, 357421, 357431, 357437, 357473, 357503, 357509, 357517, 357551, 357559, 357563]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc204_all_prime : (Pc204).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc204 : Nat := (Pc204.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc204 : Nat := (Pc204.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
