/- GENERATED by tools/gen-lean-erdos852.py — chunk 214/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc214 : List Nat := [368597, 368609, 368633, 368647, 368651, 368653, 368689, 368717, 368729, 368737, 368743, 368773, 368783, 368789, 368791, 368801, 368803, 368833, 368857, 368873, 368881, 368899, 368911, 368939, 368947, 368957, 369007, 369013, 369023, 369029, 369067, 369071, 369077, 369079, 369097, 369119, 369133, 369137, 369143, 369169, 369181, 369191, 369197, 369211, 369247, 369253, 369263, 369269, 369283, 369293, 369301, 369319, 369331, 369353, 369361, 369407, 369409, 369419, 369469, 369487, 369491, 369539, 369553, 369557, 369581, 369637, 369647, 369659, 369661, 369673, 369703, 369709, 369731, 369739, 369751, 369791, 369793, 369821, 369827, 369829, 369833, 369841, 369851, 369877, 369893, 369913, 369917, 369947, 369959, 369961, 369979, 369983, 369991, 369997, 370003]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc214_all_prime : (Pc214).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc214 : Nat := (Pc214.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc214 : Nat := (Pc214.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
