/- GENERATED by tools/gen-lean-erdos852.py — chunk 217/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc217 : List Nat := [372613, 372629, 372637, 372653, 372661, 372667, 372677, 372689, 372707, 372709, 372719, 372733, 372739, 372751, 372763, 372769, 372773, 372797, 372803, 372809, 372817, 372829, 372833, 372839, 372847, 372859, 372871, 372877, 372881, 372901, 372917, 372941, 372943, 372971, 372973, 372979, 373003, 373007, 373019, 373049, 373063, 373073, 373091, 373127, 373151, 373157, 373171, 373181, 373183, 373187, 373193, 373199, 373207, 373211, 373213, 373229, 373231, 373273, 373291, 373297, 373301, 373327, 373339, 373343, 373349, 373357, 373361, 373363, 373379, 373393, 373447, 373453, 373459, 373463, 373487, 373489, 373501, 373517, 373553, 373561, 373567, 373613, 373621, 373631, 373649, 373657, 373661, 373669, 373693, 373717, 373721, 373753, 373757, 373777, 373783]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc217_all_prime : (Pc217).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc217 : Nat := (Pc217.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc217 : Nat := (Pc217.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
