/- GENERATED by tools/gen-lean-erdos852.py — chunk 212/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc212 : List Nat := [366211, 366217, 366221, 366227, 366239, 366259, 366269, 366277, 366287, 366293, 366307, 366313, 366329, 366341, 366343, 366347, 366383, 366397, 366409, 366419, 366433, 366437, 366439, 366461, 366463, 366467, 366479, 366497, 366511, 366517, 366521, 366547, 366593, 366599, 366607, 366631, 366677, 366683, 366697, 366701, 366703, 366713, 366721, 366727, 366733, 366787, 366791, 366811, 366829, 366841, 366851, 366853, 366859, 366869, 366881, 366889, 366901, 366907, 366917, 366923, 366941, 366953, 366967, 366973, 366983, 366997, 367001, 367007, 367019, 367021, 367027, 367033, 367049, 367069, 367097, 367121, 367123, 367127, 367139, 367163, 367181, 367189, 367201, 367207, 367219, 367229, 367231, 367243, 367259, 367261, 367273, 367277, 367307, 367309, 367313, 367321]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc212_all_prime : (Pc212).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc212 : Nat := (Pc212.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc212 : Nat := (Pc212.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
