/- GENERATED by tools/gen-lean-erdos852.py — chunk 200/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc200 : List Nat := [351301, 351311, 351341, 351343, 351347, 351359, 351361, 351383, 351391, 351397, 351401, 351413, 351427, 351437, 351457, 351469, 351479, 351497, 351503, 351517, 351529, 351551, 351563, 351587, 351599, 351643, 351653, 351661, 351667, 351691, 351707, 351727, 351731, 351733, 351749, 351751, 351763, 351773, 351779, 351797, 351803, 351811, 351829, 351847, 351851, 351859, 351863, 351887, 351913, 351919, 351929, 351931, 351959, 351971, 351991, 352007, 352021, 352043, 352049, 352057, 352069, 352073, 352081, 352097, 352109, 352111, 352123, 352133, 352181, 352193, 352201, 352217, 352229, 352237, 352249, 352267, 352271, 352273, 352301, 352309, 352327, 352333, 352349, 352357, 352361, 352367, 352369, 352381, 352399, 352403, 352409, 352411, 352421, 352423, 352441, 352459, 352463, 352481]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc200_all_prime : (Pc200).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc200 : Nat := (Pc200.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc200 : Nat := (Pc200.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
