/- GENERATED by tools/gen-lean-erdos852.py — chunk 228/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc228 : List Nat := [385831, 385837, 385843, 385859, 385877, 385897, 385901, 385907, 385927, 385939, 385943, 385967, 385991, 385997, 386017, 386039, 386041, 386047, 386051, 386083, 386093, 386117, 386119, 386129, 386131, 386143, 386149, 386153, 386159, 386161, 386173, 386219, 386227, 386233, 386237, 386249, 386263, 386279, 386297, 386299, 386303, 386329, 386333, 386339, 386363, 386369, 386371, 386381, 386383, 386401, 386411, 386413, 386429, 386431, 386437, 386471, 386489, 386501, 386521, 386537, 386543, 386549, 386569, 386587, 386609, 386611, 386621, 386629, 386641, 386647, 386651, 386677, 386689, 386693, 386713, 386719, 386723, 386731, 386747, 386777, 386809, 386839, 386851, 386887, 386891, 386921, 386927, 386963, 386977, 386987, 386989, 386993, 387007]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc228_all_prime : (Pc228).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc228 : Nat := (Pc228.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc228 : Nat := (Pc228.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
