/- GENERATED by tools/gen-lean-erdos852.py — chunk 198/240. Do not edit. -/
import Erdos852.Basic

namespace Erdos852

set_option maxRecDepth 1000000 in
def Pc198 : List Nat := [348827, 348833, 348839, 348851, 348883, 348889, 348911, 348917, 348919, 348923, 348937, 348949, 348989, 348991, 349007, 349039, 349043, 349051, 349079, 349081, 349093, 349099, 349109, 349121, 349133, 349171, 349177, 349183, 349187, 349199, 349207, 349211, 349241, 349291, 349303, 349313, 349331, 349337, 349343, 349357, 349369, 349373, 349379, 349381, 349387, 349397, 349399, 349403, 349409, 349411, 349423, 349471, 349477, 349483, 349493, 349499, 349507, 349519, 349529, 349553, 349567, 349579, 349589, 349603, 349637, 349663, 349667, 349697, 349709, 349717, 349729, 349753, 349759, 349787, 349793, 349801, 349813, 349819, 349829, 349831, 349837, 349841, 349849, 349871, 349903, 349907, 349913, 349919, 349927, 349931, 349933, 349939, 349949, 349963, 349967, 349981, 350003, 350029]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem Pc198_all_prime : (Pc198).all isPrime = true := by decide +kernel

/- per-chunk subproducts: the kernel evaluates the final N and D as a
   TREE of these, so no evaluation ever holds 33k growing bignums in
   its cache — the linear fold did, and page-churned for hours -/
def Nc198 : Nat := (Pc198.map (fun p => (p - 1) ^ 3 + 1)).prod
def Dc198 : Nat := (Pc198.map (fun p => (p - 1) ^ 3)).prod

end Erdos852
