/- GENERATED by tools/gen-lean-erdos852.py — do not edit.
   odd primes 3..400000 (33859 of them); claim window edge (752403861777+1)/10000000000000.
   Nothing in the emitted data is trusted: primality, ascent and oddness of
   P are kernel-re-proved below, and an omitted prime only weakens the bound. -/
import Erdos852.Chunk1
import Erdos852.Chunk2
import Erdos852.Chunk3
import Erdos852.Chunk4
import Erdos852.Chunk5
import Erdos852.Chunk6
import Erdos852.Chunk7
import Erdos852.Chunk8
import Erdos852.Chunk9
import Erdos852.Chunk10
import Erdos852.Chunk11
import Erdos852.Chunk12
import Erdos852.Chunk13
import Erdos852.Chunk14
import Erdos852.Chunk15
import Erdos852.Chunk16

namespace Erdos852

/-- the prime list: the chunks, in order -/
def P : List Nat := Pc1 ++ Pc2 ++ Pc3 ++ Pc4 ++ Pc5 ++ Pc6 ++ Pc7 ++ Pc8 ++ Pc9 ++ Pc10 ++ Pc11 ++ Pc12 ++ Pc13 ++ Pc14 ++ Pc15 ++ Pc16

set_option maxRecDepth 1000000 in
theorem P_all_prime : P.all isPrime = true := by
  simp only [P, List.all_append, Bool.and_eq_true]
  exact ⟨Pc1_all_prime, Pc2_all_prime, Pc3_all_prime, Pc4_all_prime, Pc5_all_prime, Pc6_all_prime, Pc7_all_prime, Pc8_all_prime, Pc9_all_prime, Pc10_all_prime, Pc11_all_prime, Pc12_all_prime, Pc13_all_prime, Pc14_all_prime, Pc15_all_prime, Pc16_all_prime⟩

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem P_ascending : ascending P = true := by decide +kernel

/-- strictly increasing, hence no prime is counted twice -/
theorem P_pairwise : List.Pairwise (· < ·) P :=
  ascending_sound _ P_ascending

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem P_all_odd : P.all (fun p => decide (2 < p)) = true := by decide +kernel

/-- every element of P is prime, by Mathlib's definition -/
theorem P_prime : ∀ p ∈ P, Nat.Prime p := fun p hp =>
  isPrime_correct (List.all_eq_true.mp P_all_prime p hp)

def N : Nat := P.foldl (fun a p => a * ((p - 1) ^ 3 + 1)) 1
def D : Nat := P.foldl (fun a p => a * (p - 1) ^ 3) 1

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- THE refutation inequality: the exact partial product's (N/D − 1)/2
    strictly exceeds (752403861777+1)/10000000000000 — the upper edge of the published
    claim's window under both truncation and rounding readings. -/
theorem cstar_refuted :
    (N - D) * 10000000000000 > 2 * 752403861778 * D := by decide +kernel

end Erdos852
