/- GENERATED by tools/gen-lean-erdos852.py — do not edit.
   odd primes 3..10000 (1228 of them); claim window edge (75239+1)/1000000.
   Nothing in the emitted data is trusted: primality, ascent and oddness of
   P are kernel-re-proved below, and an omitted prime only weakens the bound. -/
import Erdos852.ChunkForgeComposite1
import Erdos852.ChunkForgeComposite2
import Erdos852.ChunkForgeComposite3
import Erdos852.ChunkForgeComposite4
import Erdos852.ChunkForgeComposite5
import Erdos852.ChunkForgeComposite6
import Erdos852.ChunkForgeComposite7
import Erdos852.ChunkForgeComposite8

namespace Erdos852

/-- the chunks, in order, as REFERENCES — proofs below rewrite over this
    240-entry list, never over 33,859 literals -/
def chunksPForgeComposite : List (List Nat) := [PForgeCompositec1, PForgeCompositec2, PForgeCompositec3, PForgeCompositec4, PForgeCompositec5, PForgeCompositec6, PForgeCompositec7, PForgeCompositec8]

/-- the prime list -/
def PForgeComposite : List Nat := (chunksPForgeComposite).flatten

set_option maxRecDepth 1000000 in
theorem PForgeComposite_all_prime : PForgeComposite.all isPrime = true := by
  unfold PForgeComposite
  rw [all_flatten]
  unfold chunksPForgeComposite
  simp only [List.all_cons, List.all_nil, PForgeCompositec1_all_prime, PForgeCompositec2_all_prime, PForgeCompositec3_all_prime, PForgeCompositec4_all_prime, PForgeCompositec5_all_prime, PForgeCompositec6_all_prime, PForgeCompositec7_all_prime, PForgeCompositec8_all_prime, Bool.true_and, Bool.and_true, Bool.and_self]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem PForgeComposite_ascending : ascending PForgeComposite = true := by decide +kernel

/-- strictly increasing, hence no prime is counted twice -/
theorem PForgeComposite_pairwise : List.Pairwise (· < ·) PForgeComposite :=
  ascending_sound _ PForgeComposite_ascending

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
theorem PForgeComposite_all_odd : PForgeComposite.all (fun p => decide (2 < p)) = true := by decide +kernel

/-- every element of P is prime, by Mathlib's definition -/
theorem PForgeComposite_prime : ∀ p ∈ PForgeComposite, Nat.Prime p := fun p hp =>
  isPrime_correct (List.all_eq_true.mp PForgeComposite_all_prime p hp)

def NForgeComposite : Nat := ((chunksPForgeComposite).map (fun c => (c.map (fun p => (p - 1) ^ 3 + 1)).prod)).prod
def DForgeComposite : Nat := ((chunksPForgeComposite).map (fun c => (c.map (fun p => (p - 1) ^ 3)).prod)).prod

/-- N is EXACTLY the product of (p−1)³+1 over PForgeComposite — the generic flatten
    lemma instantiated; no arithmetic, no literal terms -/
theorem NForgeComposite_spec : NForgeComposite = (PForgeComposite.map (fun p => (p - 1) ^ 3 + 1)).prod := by
  unfold NForgeComposite PForgeComposite
  exact (prod_map_flatten _ (chunksPForgeComposite)).symm

/-- D is EXACTLY the product of (p−1)³ over PForgeComposite -/
theorem DForgeComposite_spec : DForgeComposite = (PForgeComposite.map (fun p => (p - 1) ^ 3)).prod := by
  unfold DForgeComposite PForgeComposite
  exact (prod_map_flatten _ (chunksPForgeComposite)).symm

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- THE refutation inequality: the exact partial product's (N/D − 1)/2
    strictly exceeds (75239+1)/1000000 — the upper edge of the published
    claim's window under both truncation and rounding readings. -/
theorem cstar_refutedForgeComposite :
    (NForgeComposite - DForgeComposite) * 1000000 > 2 * 75240 * DForgeComposite := by decide +kernel

end Erdos852
