/* make-figures.js — emit figures.tex (pgfplots) from the run data.
   Nothing is retyped: every coordinate below comes from out/page.json or
   out/witness.json. node make-figures.js && tectonic transit-paper.tex */
'use strict';
const fs = require('fs'), path = require('path');
const OUT = path.join(__dirname, '..', 'out');
const D = JSON.parse(fs.readFileSync(path.join(OUT, 'page.json'), 'utf8'));
const W = JSON.parse(fs.readFileSync(path.join(OUT, 'witness.json'), 'utf8'));

const T = D.targets.find(t => t.key === 'tres2');
const WT = W.targets.find(t => t.key === 'tres2');
const res = (t, o, r) => t.results.find(x => x.orbit === o && x.rung === r);
const wc = (o, r, s) => WT.curves.find(c => c.orbit === o && c.rung === r && c.side === s);

const pts = T.curve.map(p => `(${p[0].toFixed(4)},${((p[1] - 1) * 1e6).toFixed(1)})`).join(' ');
const mdl = c => c.depth.map(p => `(${p[0].toFixed(4)},${((p[1] - 1) * 1e6).toFixed(1)})`).join(' ');
const lo = wc('exact', 'monotone', 'lo'), hi = wc('exact', 'monotone', 'hi');

/* Figure 1: the curve and two admissible stars */
const fig1 = `\\begin{tikzpicture}
\\begin{axis}[width=\\linewidth,height=6.2cm,xlabel={hours from mid-transit},
  ylabel={relative flux $-1$ (ppm)},tick label style={font=\\scriptsize},
  label style={font=\\small},legend style={font=\\scriptsize,at={(0.02,0.05)},anchor=south west,draw=none,fill=none}]
\\addplot[only marks,mark=*,mark size=0.25pt,gray] coordinates {${pts}};
\\addlegendentry{Kepler short cadence, ${T.nBins} bins}
\\addplot[black,thick,smooth] coordinates {${mdl(lo)}};
\\addlegendentry{witness at $k=${lo.k.toFixed(4)}$}
\\addplot[black,thin,densely dotted] coordinates {${mdl(hi)}};
\\addlegendentry{witness at $k=${hi.k.toFixed(4)}$}
\\end{axis}
\\end{tikzpicture}`;

/* Figure 2: the ladder, as horizontal intervals, with the published values */
const rows = [];
for (const o of ['exact', 'stated', 'open']) for (const r of ['none', 'monotone']) {
  const x = res(T, o, r); if (x && x.ok) rows.push({ o, r, x });
}
const lab = rows.map((q, i) => `${i + 1}/${q.o} + ${q.r === 'none' ? '$\\mu\\ge0$' : 'monotone'}`).join(',');
const bars = rows.map((q, i) => `\\addplot+[only marks,mark=none] coordinates {};
\\draw[very thick] (axis cs:${q.x.outer[0].toFixed(4)},${i + 1}) -- (axis cs:${Math.min(1, q.x.outer[1]).toFixed(4)},${i + 1});
\\draw[line width=4pt,gray!45] (axis cs:${q.x.inner[0].toFixed(4)},${i + 1}) -- (axis cs:${q.x.inner[1].toFixed(4)},${i + 1});`).join('\n');
const pub = T.published.map(p => `\\draw[gray,dashed,line width=0.3pt] (axis cs:${p.k.toFixed(5)},0.4) -- (axis cs:${p.k.toFixed(5)},${rows.length + 0.6});`).join('\n');
const fig2 = `\\begin{tikzpicture}
\\begin{axis}[width=\\linewidth,height=6.4cm,xlabel={$R_p/R_\\star$},
  ytick={${rows.map((_, i) => i + 1).join(',')}},yticklabels={${lab}},
  ymin=0.4,ymax=${rows.length + 0.6},xmin=0,xmax=${Math.min(1, Math.max(...rows.map(q => Math.min(1, q.x.outer[1]))) * 1.05).toFixed(3)},
  tick label style={font=\\scriptsize},label style={font=\\small},y tick label style={font=\\tiny}]
\\addplot[draw=none] coordinates {(0,1)};
${pub}
${bars}
\\end{axis}
\\end{tikzpicture}`;

/* Figure 3: the two witnesses as cumulative light inside r */
const cum = c => c.profile.steps.map(p => `(${p[0].toFixed(4)},${p[1].toFixed(5)})`).join(' ');
const core = Math.max(0, T.fit.b - T.fit.k);
const fig3 = `\\begin{tikzpicture}
\\begin{axis}[width=\\linewidth,height=5.4cm,xlabel={radius $r$, in stellar radii},
  ylabel={light inside $r$},xmin=0,xmax=1,ymin=0,ymax=1.02,
  tick label style={font=\\scriptsize},label style={font=\\small},
  legend style={font=\\scriptsize,at={(0.02,0.98)},anchor=north west,draw=none,fill=none}]
\\addplot[fill=gray!18,draw=none] coordinates {(0,0) (${core.toFixed(4)},0) (${core.toFixed(4)},1.02) (0,1.02)} \\closedcycle;
\\addlegendentry{$r<b-k$: never occulted}
\\addplot[black,thick,const plot] coordinates {${cum(lo)}};
\\addlegendentry{$k=${lo.k.toFixed(4)}$}
\\addplot[black,thin,densely dotted,const plot] coordinates {${cum(hi)}};
\\addlegendentry{$k=${hi.k.toFixed(4)}$}
\\end{axis}
\\end{tikzpicture}`;

fs.writeFileSync(path.join(__dirname, 'figures.tex'),
  `% generated by make-figures.js — do not edit\n\\newcommand{\\figCurve}{${fig1}}\n\\newcommand{\\figLadder}{${fig2}}\n\\newcommand{\\figProfiles}{${fig3}}\n`);
console.log('figures.tex written');
