#!/usr/bin/env node
/* instruments/kissing/battery.js — calibrations that must certify, red
   controls that must fire, and a walk of the shipped ledger record.

   Calibrations re-prove known kissing witnesses from generated bytes at
   every run: D4 (24 in R^4) and E8 (240 in R^8). Reds tamper with inputs
   and the comparator's own blind spots; each one must be CAUGHT. */
'use strict';
const path = require('path');
const fs = require('fs');
const K = require('./kissing.js');
const ROOT = path.resolve(__dirname, '..', '..');

let pass = 0, fail = 0, reds = 0, redsFired = 0;
const ok = (cond, name) => { if (cond) { pass++; } else { fail++; console.error('FAIL ' + name); } };
const red = (fired, name) => { reds++; if (fired) { redsFired++; pass++; } else { fail++; console.error('RED DID NOT FIRE ' + name); } };

/* ---- calibrations ---- */
const d4 = K.certify(K.d4());
ok(d4.verdict === 'CERTIFIED' && d4.n === 24 && d4.dim === 4, 'D4: K(4) witness of 24 certifies');
const e8 = K.certify(K.e8());
ok(e8.verdict === 'CERTIFIED' && e8.n === 240 && e8.dim === 8, 'E8: K(8) witness of 240 certifies');
ok(e8.contacts > 0, 'E8 has exact contacts (60-degree pairs decided as equality, not float luck)');

/* ---- red 1: a 59-degree pair must refute with the right witness ---- */
{
  /* cos 60 = 1/2 exactly at [200,0],[100,173.2..]; push past it: dot 101 on norms 200^2/...
     use integers: x=(2,0), y=(1,1) in R^2 has cos = 2/(2*sqrt5)^... keep it exact: x=(1,0), y=(3,5):
     cos = 3/sqrt(34) = 0.514 > 1/2 -> must refute. */
  const r = K.certify(K.fromIntegers([[1, 0], [3, 5]]));
  red(r.verdict === 'REFUTED' && r.witness && r.witness.i === 0 && r.witness.j === 1, 'a 59-degree pair refutes with its witness');
}

/* ---- red 2: a duplicated direction must refute (cos = 1) ---- */
{
  const rows = K.d4(); rows.push(rows[0]);
  const r = K.certify(rows);
  red(r.verdict === 'REFUTED', 'a duplicated direction refutes');
}

/* ---- red 3: a zero vector must refuse ---- */
{
  const r = K.certify(K.fromIntegers([[1, 0, 0], [0, 0, 0]]));
  red(r.verdict === 'REFUTED' && r.reason === 'zero vector', 'a zero vector refuses');
}

/* ---- red 4: comparator edge — an exact contact passes, one past it fails ---- */
{
  /* x=(2,0), y=(1,s): cos = 2/(2*sqrt(1+s^2)); contact needs cos=1/2 -> s^2=3: irrational.
     Cleanest exact contact: D4's (1,1,0,0)&(1,0,1,0): dot 1, norms 2,2 -> 4*1 = 4 = 2*2. */
  const contact = K.certify(K.fromIntegers([[1, 1, 0, 0], [1, 0, 1, 0]]));
  const past = K.certify(K.fromIntegers([[1, 1, 0, 0], [2, 1, 1, 0]])); /* dot 3, norms 2*6=12 < 4*9 */
  red(contact.verdict === 'CERTIFIED' && contact.contacts === 1 && past.verdict === 'REFUTED',
    'the 4s^2 <= NxNy comparator holds at equality and fails one past it');
}

/* ---- red 5: the Z[sqrt2] sign test on mixed-sign values ---- */
{
  ok(K.Z.sign([3n, -2n]) === 1, 'sign(3 - 2sqrt2) = + (3^2 > 2*2^2)');
  ok(K.Z.sign([-3n, 2n]) === -1, 'sign(-3 + 2sqrt2) = -');
  ok(K.Z.sign([2n, -2n]) === -1, 'sign(2 - 2sqrt2) = - (4 < 8)');
  /* a sqrt2-aware refutation: directions (1,0) and ([1,0],[0,1]) i.e. (1, sqrt2):
     cos = 1/sqrt(3) = 0.577 > 1/2 -> must refute THROUGH the quadratic field */
  const r = K.certify(K.fromSqrt2Pairs([[[1, 0], [0, 0]], [[1, 0], [0, 1]]]));
  red(r.verdict === 'REFUTED', 'a Q(sqrt2) violation refutes through the field arithmetic');
}

/* ---- red 6: decimal literals are exact rationals, not float64 ---- */
{
  const p = K.parseDecimal('0.1');
  red(p.num === 1n && p.k === 1, 'the literal 0.1 parses to 1/10 exactly (never the float64 neighbor)');
  const q = K.parseDecimal('2.5e-3');
  ok(q.num === 25n && q.k === 4, 'scientific notation parses exactly (2.5e-3 = 25/10^4)');
}

/* ---- red 7: the flat sqrt2 adapter refuses a malformed row ---- */
{
  let threw = false; try { K.fromSqrt2Flat([[1, 0, 0]]); } catch (e) { threw = true; }
  red(threw, 'a flat sqrt2 row of odd length is refused');
}

/* ---- red 8: the Gram profile refuses non-uniform norms and separates non-congruent sets ---- */
{
  red(K.gramProfile(K.fromIntegers([[1, 0], [0, 2]])) === null, 'the Gram profile refuses a configuration without one shell norm');
  const a = K.gramProfile(K.d4()), b = K.gramProfile(K.d4().reverse());
  ok(a && a.multiset === '-1,0/1x12 -1,0/2x96 0,0/1x72 1,0/2x96', 'D4 profile is the textbook one (12 antipodal, 96 at 120°, 72 orthogonal, 96 contacts)');
  ok(b && b.sha256 === a.sha256, 'the profile is a function of the configuration, not of its listing');
}

/* ---- the shipped record, re-walked ---- */
const CERT = path.join(ROOT, 'certs', 'kissing-ledger.json');
if (fs.existsSync(CERT)) {
  const led = JSON.parse(fs.readFileSync(CERT, 'utf8'));
  ok(Array.isArray(led.rows) && led.rows.length >= 9, 'ledger has its rows');
  const byId = Object.fromEntries(led.rows.map((r) => [r.id, r]));
  ok(byId['alphaevolve-593'] && byId['alphaevolve-593'].verdict === 'CERTIFIED' && byId['alphaevolve-593'].n === 593, 'ledger: AlphaEvolve 593 certified');
  ok(byId['ea-594-winner'] && byId['ea-594-winner'].verdict === 'CERTIFIED' && byId['ea-594-winner'].n === 594, 'ledger: EinsteinArena 594 winner certified');
  for (const c of ['station-604-1', 'station-604-2', 'station-604-3']) {
    ok(byId[c] && byId[c].verdict === 'CERTIFIED' && byId[c].n === 604 && byId[c].uniformNorm === true, 'ledger: ' + c + ' certified at shell norm 4');
  }
  ok(byId['station-shell-582'] && byId['station-shell-582'].verdict === 'CERTIFIED' && byId['station-shell-582'].n === 582, 'ledger: the classical 582 shell certified');
  ok(byId['ea-604'] && byId['ea-604'].verdict === 'CERTIFIED' && byId['ea-604'].n === 604 && byId['ea-604'].uniformNorm === true,
    'ledger: the EinsteinArena 604 certified at shell norm 36 (NEEDS DATA until its bytes were published, 2026-09-07)');
  ok(byId['ea-604'] && byId['ea-604'].gram && byId['station-604-1'].gram && byId['ea-604'].gram.sha256 === byId['station-604-1'].gram.sha256
    && byId['ea-604'].gram.sha256 !== byId['station-604-2'].gram.sha256 && byId['ea-604'].gram.sha256 !== byId['station-604-3'].gram.sha256,
    'ledger: the EinsteinArena 604 shares its exact Gram profile with Station configuration 1 and with neither other');
  /* live re-certification of one full record row from the pinned corpus bytes */
  const st = JSON.parse(fs.readFileSync(path.join(ROOT, 'corpus', 'kissing', 'station-d11-604.json'), 'utf8'));
  const r1 = K.certify(K.fromSqrt2Pairs(st.configs[0]), { uniformNorm: [144, 0] });
  ok(r1.verdict === 'CERTIFIED' && r1.n === 604 && r1.uniformNorm === true, 'live: station config 1 re-certifies from the pinned bytes');
  ok(r1.contacts === byId['station-604-1'].contacts, 'live contact count matches the record');
  /* the EinsteinArena 604: the pinned file must hash to its upstream digest and re-decide */
  const meta = JSON.parse(fs.readFileSync(path.join(ROOT, 'corpus', 'kissing', 'ea-d11-604.meta.json'), 'utf8'));
  const raw = fs.readFileSync(path.join(ROOT, 'corpus', 'kissing', meta.file));
  ok(require('crypto').createHash('sha256').update(raw).digest('hex') === meta.upstream_sha256, 'live: the EinsteinArena file hashes to its pinned upstream sha256');
  const eaV = K.fromSqrt2Flat(JSON.parse(raw.toString('utf8')).vectors);
  const r6 = K.certify(eaV, { uniformNorm: [36, 0] });
  ok(r6.verdict === 'CERTIFIED' && r6.n === 604 && r6.uniformNorm === true && r6.contacts === byId['ea-604'].contacts, 'live: the EinsteinArena 604 re-certifies from the pinned bytes with the recorded contact count');
  const gE = K.gramProfile(eaV), g1 = K.gramProfile(K.fromSqrt2Pairs(st.configs[0]));
  ok(gE && g1 && gE.sha256 === g1.sha256 && gE.vertexSha256 === g1.vertexSha256, 'live: Gram profile (multiset and per-vector) identical to Station configuration 1');
  ok(K.sharedDirections(eaV, K.fromSqrt2Pairs(st.configs[0])) === byId['ea-604'].sharedDirectionsWith['station-604-1'], 'live: shared-direction count with configuration 1 matches the record');
} else {
  console.error('note: certs/kissing-ledger.json not present yet (pre-ledger run)');
}

console.log(`kissing battery: ${pass} pass, ${fail} fail, ${redsFired}/${reds} red controls fired`);
process.exit(fail ? 1 : 0);
