/* certs-shelf.js — the described certificate shelf, in ONE place.

   Two pages need this list: the landing page, which shows a handful and points
   at the rest, and /machine, which carries the whole thing. It lived inside
   tools/build-site.js and the second consumer would have meant a second copy —
   of seventy-five descriptions, each of which has to keep agreeing with a file
   on disk or the build refuses. Two copies of that WOULD have diverged, and the
   divergence would have been invisible: both would still have been tables.

   The description gate and the publication loop stay in build-site.js with the
   WORKING pattern they share. This module is the data and nothing else.
*/
'use strict';
const path = require('path');

/* strassenN, bilinearN and topM are counted upstream from the certificates
   themselves; they are passed in rather than recomputed here so each number
   still has exactly one origin. */
module.exports = function certs(ROOT, { strassenN, bilinearN, topM }) {

/* ---- the certificates, described -----------------------------------------
   Same rule as the shelf: the build refuses if certs/ holds a file this
   table cannot describe.

   The re-verify column ships exactly two kinds of link and one honest
   absence, and each link NAMES the repo file it is copied from so the build
   can refuse a link that would 404. It shipped two once: /verify/ holds ONLY
   the detached .py verifiers, and two rows pointed single-file JS/HTML
   artifacts at it. Those artifacts live under /reports/. */
const PY = (f) => ({ href: 'verify/' + f, label: f, src: path.join(ROOT, 'tools', f) });
const INPAGE = (f) => ({ href: 'reports/' + f, label: f, src: path.join(ROOT, 'reports', f) });
const NOVERIFIER = (f) => ({ tag: 'battery-gated', href: 'reports/' + f, label: 'the report', src: path.join(ROOT, 'reports', f) });
const CERTS = [
  ['erdos852-certificate.json', 'Both Erdős #852 constants as exact data: the c0 window re-decidable at 130 digits, the C∗ refutation as strict integer inequalities with no tail bound.', PY('verify_erdos852.py')],
  ['erdos852-h-records.json', 'Every record run of pairwise-distinct consecutive prime gaps the scan has closed \u2014 index, opening prime and length. The head reproduces OEIS A078515/A079889 term for term; the tail passes them. Each record beyond the published terms is re-proved at build by an independent Miller\u2013Rabin verifier.', null],
  ['ai-claims-summary.json', 'The six-lane AI-claim audit as the build recorded it: every lane\u2019s verdict, scope, check count and mutation-control count, written by the report builder from a live run of all six verifiers. Not a certificate \u2014 a record of what the verifiers said, so the shelf card and the page cannot quote different numbers.', null],
  ['keller-certificate.json', 'The Jacobian/Hessian counterexample corpus — every polynomial as explicit exact rational monomials; determinants and collisions re-derivable from the file alone.', PY('verify_keller.py')],
  ['erdos1038-inf.json', 'Erdős #1038, the INFIMUM side: the certified bracket 1.828 ≤ inf ≤ 1.8344304971959906 with both ends unconditional, Tao’s model Problem 4.1 answered affirmatively for every ε ∈ (0, 0.1] (624,275 chunks + a sliver lemma), and the thread’s three posted dual measures certified. Rebuilt live at every report build; the record carries the claim fence naming all three claimed proofs.', null],
  ['erdos1038-forcing-1.828.json', 'The forcing certificate behind inf ≥ 1.828 — every a₀-box with its comb, per-b-box frozen LP weights and certified margins. Re-checked by instruments/lemniscate/verify-forcing.js, which shares no code with the certifier and also hunts counterexamples in doubles.', null],
  ['ember-band.json', 'THE EMBER BAND: the hot-spots theorem extended from one trapezoid to every c in [0.845, 0.85] — 17 chunks tiling the interval with shared endpoints, 738 σ-cells inside them, μ₁ ≥ 11.85157 and μ₂ ≥ 13.90774 uniformly. An AUDIT record, not a re-derivation: the chain ran on the bench, and instruments/emberband/verify-band.js re-derives both covering ladders and every band-wide value from per-cell data, sharing no code with the producer.', null],
  ['kissing-ledger.json', 'The kissing ledger: every public record configuration for K(11) — AlphaEvolve’s 593, the EinsteinArena rung winner’s 594, the Station’s three exact 604s, the classical 582 shell and the D₁₂ lift — re-decided in exact Z[√2] BigInt arithmetic from sha-pinned claimant bytes, shared-nothing with every producer’s own verifier; contact counts exact, the byteless EinsteinArena 604 measured as NEEDS DATA. Rebuilt by tools/run-kissing-ledger.js at every report build.', null],
  ['strassen-certificate.json', strassenN + ' fast matrix-multiplication algorithms as exact tensor identities over Q and F2 — including AlphaTensor’s rank-47, decided both ways.', PY('verify_strassen.py')],
  ['bilinear-certificate.json', bilinearN + ' bilinear algorithms for POLYNOMIAL multiplication over F2 — full, truncated and cyclic products — each found by the generation front’s free flip-graph walk and decided by instruments/bilinear, which rebuilds the target tensor from its name rather than trusting the scheme handed to it. Every entry stores its scheme in full, so any reader can re-decide it; the published bounds each one is measured against live in corpus/bilinear-bounds.json and are not results of this repository.', NOVERIFIER('polynomial-multiplication.html')],
  ['lambda4-audit.json', 'The adversarial audit of the lambda(4) proof: an independent clause walk sharing no code with the engine — inner products by direct trigonometric summation, family and subfamily membership by plain integer arithmetic, thresholds read from the campaign record, finite-clause sets re-certified fresh by the calibrated instrument. Every gcd-reduced 4-set in the box must be reached by an explicit clause of the proof (generic, family dot, closure, finite, delegated, or the definitional witness); a set with no clause is a hole and aborts. Also carries the full theorem sweep of the box: zero refuters.', null],
  ['claims-ledger.json', 'The claims desk ledger: every externally published mathematical claim this machine has decided, one row per claim, each DERIVED from the record that decided it — a claim with no record gets no row. Origin is tracked separately from verdict, because everything decided so far was self-initiated and the submitted count stays published even while it is zero.', null],
  ['grader-pilot.json', 'The environment run against real models, and the reference policies run on the SAME seeds so the columns are the same tasks rather than a comparable sample: 360 calls at $1.92 of a $4.00 cap, worst case reserved before every one. Every row is scored by the shipped Python package \u2014 tools/run-grader-pilot.js picks tasks and pays for calls and decides nothing. Truncations and model refusals are recorded and excluded from the rates, because a harness artifact is not a model outcome.', null],
  ['gym-record.json', 'The shipped environment, measured by RUNNING it: the difficulty dial (band size against the tolerance multiple, with the point below which no representable double fits), the corpus it draws on, the mix of a 2,000-task sample, and the two standing answers with how much of the ladder each one loses. Produced by tools/run-gym-record.js, which executes the Python package the way a buyer would rather than describing it.', null],
  ['envs-record.json', 'The environments record: the fact corpus (every entry read out of a record in certs/ and sha256-pinned to it, because a canary asserts \u201cprovably wrong\u201d and that may not rest on a re-typed decimal), the grader QA measurement across four reference grader shapes and three tolerances, the uniformity gym\u2019s solver table, and the attacker ladder with the rungs that cannot be broken. Written by running the environments offline \u2014 no model is called and the harness refuses the network unless explicitly switched on.', null],
  ['envs-ledger.jsonl', 'The append-only environments ledger: one row per (environment, rung, model, k) cell with pass rate, Wilson interval, wrong/refused split and the forgery-gate result for the run. Rows so far are reference and stub solvers only; a row produced by a real model is a decision, not a default.', null],
  ['lambda5-audit.json', 'The independent audit of the lambda(5) theorem: a second walk sharing no code with the symbolic engine — inner products by direct trigonometric summation, condition membership by plain integer arithmetic on the record\u2019s own condition vectors, and every set the float screen prunes sampled and re-certified exactly, so the screen is audited rather than trusted. It decides three things and says so: the THEOREM (every gcd-reduced 5-set in the box dips strictly below L(1,2,4,5,6), except the extremizer, which attains it \u2014 a set that did not would be a refuter and aborts), the FIRST LEVEL of the reduction (the engine\u2019s symbolic model says an inner product is its base plus the deltas of the active conditions, and direct summation must agree at every set in the box; every set the generic argument does not close must satisfy one of the eight recorded family conditions), and the OBSTRUCTION by its mechanism rather than by search (on the double-sum core the cosines cancel identically on S(e, pi), so no nonnegative weight can start, and the comb closes every core point where no positive condition is active). It does NOT walk the interior of the eight closure trees; the lambda(4) audit does that for lambda(4).', null],
  ['lambda4-campaign.json', 'The lambda(4) campaign record. Phase 0: Mercer\'s Section-5 strategy (INTEGERS 19 (2019) #A4) executed mechanically — lambda(2) and the whole lambda(3) proof re-derived with exception families discovered and thresholds derived, not transcribed; the lambda(4) generic case with its 14 exception conditions discovered and matched against the paper\'s hand-written list; the measured reduction: five of the fourteen carry strictly negative delta, so NINE families remain. Phase 1, in progress: each family closed so far carries its full derivation here — second-level dot theorem, subfamily cones, derived thresholds, decided finite parts. d = 2c is CLOSED. Re-derived symbolically at every build by the lambda4 battery; finite parts pinned here and sampled at every run.', null],
  ['sublevel-tao179.json', 'The Tao #179 sublevel campaign (Erdős #1038, supremum side): rational-weight discrete measures on [-1,1] are monic root-constrained polynomials via |q| < 1, and this record holds certified sublevel measures — the 2√2 witness, grid champions including the interior cubic champion near 2.7542 and the quintic transition peak near 2.8011 — plus per-degree branch-and-bound THEOREMS: odd degrees strictly below 2.82 < 2√2, even degrees localized to [2√2, 2.82845] with (x²−1)^{N/2} attaining the left end. Every measure an outward enclosure from BigInt Sturm isolation; the box bound calibrated to equal the measure on thin boxes.', null],
  ['mercer-mu5.json', 'The mu(5) ladder, mu(5) ≤ 1 + π/m rung by rung to m = ' + topM + ' — every exceptional tuple closed by one exact rational evaluation.', null],
  ['mu-table.json', 'The Newman min-modulus table: every set in the named boxes exhausted, champions certified, orbits classified, conservation per row.', null],
  ['mu-table-40.json', 'The wider-box extension of the mu table — billions of sets exhausted, the narrow-box crowding artifacts corrected.', null],
  ['lambda-table.json', 'The lambda table: the source lab’s rows reproduced exactly, plus rows that lab’s record does not hold and no table this lab has read holds — a claim about the certificates, not about priority.', null],
  ['census-high-periods.json', 'The Hénon high-period census, p = 13..16: every period point of the classical map found and counted exactly, the plane exhausted box by box, each row re-checked with zero unmatched — the proving ground the interval instruments were calibrated on.', null],
  ['entropy-henon.json', 'The certified entropy lower bound for the classical Hénon map: h-sets, covering relations, and the exact spectral argument.', null],
  ['erdos290-tail-ext.json', 'The Erdős #290 sweep extension: degrees closed beyond the cited page, the constant’s enclosure tightened degree by degree.', null],
  ['mfg2p-regime-map.json', 'The TWO-population regime map: every cell of the coupling plane with its verdict and its exact witness — the symmetric cross-coupling s against the attack-defense asymmetry d, two disjoint enclosures where uniqueness provably fails, the Lasry-Lions monotone strip where it does not, and the refusal reason everywhere else. There is no single-file certifier for this map: it is decided by labs/mfg2p/box2p.js and re-gated by that lab’s battery at every build of its report.', NOVERIFIER('mfg-two-population.html')],
  ['mfg-regime-map.json', 'The mean-field-game regime map: every cell of the coupling–potential plane with its verdict and its exact witness — two disjoint enclosures where uniqueness provably fails, the monotone enclosure where it does not, and the refusal reason everywhere else.', INPAGE('mfg-certify.js')],
  ['matmul-eval-ledger.jsonl', 'The matmul eval’s append-only ledger — every campaign row, every verdict, every tag; the leaderboard is built from this file.', null],
  ['chowla-records.json', 'Certified Chowla merits c(A) = -min_x sum cos(ax) / sqrt|A|, one row per set size n, each an exact UPPER bound proved by instruments/trigmin for the set stored beside it. THIS FILE MAKES NO CLAIM ABOUT CHOWLA’S COSINE PROBLEM. Chowla’s question is asymptotic — whether c can be driven to 0 as n grows — and a low c at one n is a fact about that n. The measured trend here RISES with n (0.6558 at n=10 to 0.8205 at n=30), which is consistent with Chowla’s conjecture that the order is sharp, i.e. evidence against the direction, not for it. Explicit sets with small c are occupied literature (Mercer, INTEGERS 2019; Bedert, arXiv:2509.05260); these rows beat only the classical families recomputed here beside them.', null],
  ['matmul-eval-corrections.json', 'Corrections to rows already written in the matmul eval ledger. The ledger is append-only and is never rewritten, so a row that turns out to be MISLABELLED is corrected here and the correction is applied when the report displays it — currently one: 90 rows tagged v4-effort-low ran at the API’s DEFAULT effort, because the harness dropped its --effort argument in campaign mode. A correction naming a tag no row carries, or claiming a row count the ledger does not hold, refuses the report build.', null],
  ['matmul-loop-ledger.jsonl', 'The verifier-in-the-loop ledger — every trajectory round with its verdict and the exact feedback sent; the loop report is built from this file.', null],
  ['skyaudit-forecast-ledger.jsonl', 'The prediction ledger — interval FORECASTS committed before their target day (sha-pinned, append-only) and scored after in exact rationals; coverage claims are conformal counting theorems, never model faith. Wrong forecasts stay forever.', null],
  ['forecast-gym-ledger.jsonl', 'The Forecast Gym’s append-only ledger — every proposer’s forecast sha-committed before its outcome exists, every score an exact Winkler rational; the gym report and its admission board are built from this file.', null],
  ['lambda56-campaign.json', 'The lambda(5)/lambda(6) campaign record (Chowla’s cosine dip, the non-monotonicity program): lambda(5) = −L(1,2,4,5,6) closed in full — the generic case certified, all eight exception families closed with derived thresholds, 1725 finite sets decided, the extremizer walled — and lambda(6) in progress with nine of its ten families closed in this record. The double-sum-core obstruction theorem (no classical weight works on b+c = a+d = e) and the Fejér–Riesz comb weight that beats it are re-proved by the battery at every run.', null],
  ['terra-sigmastar.json', 'The exact crossover of the MFG splitting program: σ* = 1/(8π²), discount-free, DECIDED IN EXACT RATIONALS — the crossover polynomial factors, the γ-coefficient is identically zero (checked k = 2..12), the band-pass identity and both harmonic windows are exact, π enters only as a Machin bracket of width 1.3e-44.', NOVERIFIER('terra.html')],
  ['terra-bracket-table.json', 'The bracket table under the splitting theorems: seven certified rows straddling both predicted thresholds — negatives below the amplitude threshold and past the crossover, replications, and the threshold pin r_c ∈ [0.13, 0.14] with the exact-rational prediction landing inside. Honest counting lives here: two theorems plus a table, never eight.', NOVERIFIER('terra.html')],
  ['mfg-cap-multiplicity.json', 'Certified multiplicity for the ergodic quadratic MFG past its pitchfork: at each of six couplings, at least THREE distinct exact solutions enclosed in pairwise disjoint uniqueness balls with certified positive density — exactly where Lasry–Lions monotonicity is silent. The c = −9.5 monotone-regime boundary, where the branch collapses and no claim is made, is recorded too.', NOVERIFIER('terra.html')],
  ['attnflow-theorems.json', 'The attention-wing theorems: a rational-kernel token flow chosen so equilibrium and stability are DECIDABLE in exact ℚ — the consensus spectrum proved β- and p-free by exact dual-number expansion, the two-cluster cross-weights identically zero with the honest p = 1 boundary, the reduced flow’s double zero decided by exact division (every pitchfork claim refuted), and the phantom-bifurcation taxonomy with its live artifact.', NOVERIFIER('terra.html')],
  ['facelaw-theorem.json', 'The face-dimension law k = |shared| − cons + z, decided against the exact ℚ null space on two seeded 4,000-network ensembles; every instance where the natural shortcut fails (precisely the z > 0 cases) is ENUMERATED here so any reader can re-run any one.', NOVERIFIER('terra.html')],
];
/* the terra enclosure + peak-count records, one pair per instance */
for (const t of ['t1', 't2', 't3', 't4', 't5', 't6', 't7', 't8']) {
  const T = t.toUpperCase();
  CERTS.push([
    'terra-recert-' + t + '.json',
    'The ' + T + ' enclosure of the congestion-MFG splitting program: a radii-polynomial certificate around the stored candidate — exact instance parameters, certified ℓ¹_ν ball radius, contraction bound Z₁, closure margin, and density floor — re-certified here against the frozen published verifier extended with the data terms; nine falsifiers fire per instance at every battery run.',
    NOVERIFIER('terra.html')]);
  CERTS.push([
    'terra-peakcount-' + t + '.json',
    'The certified peak count for ' + T + ': the exact number of strict maxima of EVERY density in the ' + T + ' enclosure ball, derived from CERTIFIED region signs only (instruments/critcount) — outward coefficient products, ball Lipschitz folded into the cell pad, never a float sign.',
    NOVERIFIER('terra.html')]);
}
/* the mfg-cap census, one record per truncation level */
for (const N of [2, 3, 4, 5]) {
  CERTS.push([
    'mfg-cap-census-N' + N + '-c-12.json',
    'The Krawczyk exhaustion census at Galerkin level N = ' + N + ': every subbox of the printed box eliminated by interval residual or Krawczyk exclusion, each survivor isolated by K(X) ⊂ int(X) — EXACTLY three solutions of the truncated even system at c = −12, matched one-to-one to the candidates. Box-bounded, truncation-level; the PDE-level count is the stated open problem.',
    NOVERIFIER('terra.html')]);
}
/* the ember chain, one record per stage */
{
  const E = {
    spectrum: 'Stage 1 of the hot-spots chain: two-sided spectrum localization for the trapezoid — interval Galerkin Rayleigh–Ritz uppers (floats only pick the subspace), exact-rational Crouzeix–Raviart assembly with interval LDLᵀ inertia counts and Liu’s framework for the lowers; the certified gap makes μ₁ SIMPLE. The rectangle regression encloses π² at every run.',
    defect: 'Stage 2: the frozen Helmholtz trial’s boundary defect — order-2 interval Taylor jets along every edge with Bessel-ODE closure, a certified midpoint-Taylor cell rule, value AND derivative bridges against an independent float evaluation, and the exact trial coefficients frozen for every downstream stage.',
    eigenpair: 'Stage 3: the eigenpair certificate — the boundary-residual identity with the rational star-shaped trace constant and the CR localization tightens μ₁ by a factor of ~105 and encloses the eigenfunction in L²; also the H¹ error and the δλ bound the pointwise machinery consumes.',
    pointwise: 'Stage 4: the solid-mean pointwise machinery — kernel norm I₀ = 5/48 DERIVED in exact rationals, witness balls decided inside Ω in exact rationals, and every CORE cell of the 1/100 grid (corner-min depth ≥ 3/40, exact by concavity) killed on both sides with zero survivors.',
    collar: 'Stage 5: the collar sweep — every sub-core cell killed by the value argument with REFLECTED pointwise bounds across its nearest open edge (the single layer bounded by the certified per-edge flux sups), kill-or-refine to 1/800, ZERO residual cells.',
    corner: 'Stage 6: the four corner-tip certificates — Bessel–Fourier coefficients certified by annulus L² extraction AND re-extracted at a second annulus (the enclosures must intersect — a condition of entry), value kills at B/C/D, radial monotonicity at A, and the ladder-identity wedge bound at C where the boundary minimum lives.',
    cross: 'The independent cross-derivations: I₀ = 5/48 in exact rationals, the trace constant re-derived on directed dyadic big-floats from the exact-rational star geometry, μ₁ bounded above on an independent conforming P1 basis, and the two-annulus corner condition re-asserted.',
    theorem: 'The assembled hot-spots theorem: cross-record chain consistency (every stage’s inputs equal the upstream outputs), the interior partition RE-DECIDED IN EXACT RATIONALS, every sweep and tip verdict re-checked, the honest framing with its fence list, and the sha256 of every input record.',
  };
  for (const [st, d] of Object.entries(E)) CERTS.push(['ember-' + st + '.json', d, NOVERIFIER('ember.html')]);
}
  return CERTS;
};
