#!/usr/bin/env python3
"""gen-lean-erdos852.py — emit the Lean data + theorem files for the C* refutation.

The Lean side re-proves, in one kernel run, the same integer inequality
tools/verify_erdos852.py decides: the exact partial product N/D over the odd
primes <= limit satisfies (N/D - 1)/2 > (num+1)/den, the upper edge of the
published claim's window. The prime list emitted here needs NO trust: Lean
re-proves primality of every element (Basic.lean's isPrime + its correctness
theorem), strict ascent (distinctness), and oddness — a wrong list can only
FAIL the build, never falsely pass, because omissions merely weaken the
lower bound and every other defect is caught by a kernel-checked property.

usage:
  python3 tools/gen-lean-erdos852.py                # full: limit + claim from the certificate
  python3 tools/gen-lean-erdos852.py --limit 10000 --num 75239 --den 1000000
                                                    # calibration rung (weaker claim)
  ... --forge composite|order|claim                 # red controls: emit a file that MUST fail
"""
import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
LEANDIR = ROOT / "lean" / "erdos852" / "Erdos852"


def odd_primes(limit):
    sieve = bytearray([1]) * (limit + 1)
    for i in range(2, int(limit ** 0.5) + 1):
        if sieve[i]:
            sieve[i * i::i] = bytearray(len(sieve[i * i::i]))
    return [p for p in range(3, limit + 1, 2) if sieve[p]]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--num", type=int, default=None, help="claim numerator (window: refute above (num+1)/den)")
    ap.add_argument("--den", type=int, default=None)
    ap.add_argument("--forge", choices=["composite", "order", "claim"], default=None,
                    help="emit a deliberately broken variant that the Lean build MUST reject")
    args = ap.parse_args()

    cert = json.loads((ROOT / "certs" / "erdos852-certificate.json").read_text())
    limit = args.limit or cert["cstar"]["refutation"]["limit"]
    if args.num is None or args.den is None:
        ip, fp = cert["cstar"]["published"]["value"].split(".")
        num, den = int(ip + fp), 10 ** len(fp)
    else:
        num, den = args.num, args.den

    ps = odd_primes(limit)
    if args.forge == "composite":
        # replace a mid-list prime with the next odd composite: P_all_prime must fail
        i = len(ps) // 2
        c = ps[i] + 2
        while _is_prime(c):
            c += 2
        ps[i] = c
    if args.forge == "order":
        ps[3], ps[4] = ps[4], ps[3]  # ascent broken: P_ascending must fail
    if args.forge == "claim":
        num += 10 * den  # a claim 10 above the constant: the inequality must fail

    suffix = {"composite": "ForgeComposite", "order": "ForgeOrder", "claim": "ForgeClaim"}.get(args.forge, "")
    modname = "Refutation" + suffix

    # Primality is the expensive kernel evaluation, so the list ships in
    # CHUNKS, one module each — lake builds modules in parallel across
    # cores — and the combining theorem is List.all_append, not re-evaluation.
    # contiguous chunks balanced by trial-division weight (~sqrt p), so the
    # slowest chunk does not dominate the parallel build
    # FINE grain on purpose: the kernel's whnf cache grows across ONE decide,
    # and past ~1000 primes the evaluation goes superlinear and page-churns
    # (measured: 2116 primes = 635s, 347s of it SYSTEM time; 614 primes = 16s).
    # ~140 primes per module keeps every decide small, fast and memory-light,
    # and lake parallelizes the modules.
    nchunks = max(1, min(240, len(ps) // 140))
    total_w = sum(p ** 0.5 for p in ps)
    chunks, cur, acc = [], [], 0.0
    for p in ps:
        cur.append(p)
        acc += p ** 0.5
        if acc >= total_w / nchunks and len(chunks) < nchunks - 1:
            chunks.append(cur)
            cur, acc = [], 0.0
    chunks.append(cur)
    nchunks = len(chunks)

    chunk_files = []
    for ci, chunk in enumerate(chunks, 1):
        cname = f"Chunk{suffix}{ci}"
        cl = []
        cl.append(f"/- GENERATED by tools/gen-lean-erdos852.py — chunk {ci}/{nchunks}. Do not edit. -/")
        cl.append("import Erdos852.Basic")
        cl.append("")
        cl.append("namespace Erdos852")
        cl.append("")
        cl.append("set_option maxRecDepth 1000000 in")
        cl.append(f"def P{suffix}c{ci} : List Nat := [" + ", ".join(map(str, chunk)) + "]")
        cl.append("")
        cl.append("set_option maxRecDepth 1000000 in")
        cl.append("set_option maxHeartbeats 0 in")
        cl.append(f"theorem P{suffix}c{ci}_all_prime : (P{suffix}c{ci}).all isPrime = true := by decide +kernel")
        cl.append("")
        cl.append("/- per-chunk subproducts: the kernel evaluates the final N and D as a")
        cl.append("   TREE of these, so no evaluation ever holds 33k growing bignums in")
        cl.append("   its cache — the linear fold did, and page-churned for hours -/")
        cl.append(f"def Nc{suffix}{ci} : Nat := (P{suffix}c{ci}.map (fun p => (p - 1) ^ 3 + 1)).prod")
        cl.append(f"def Dc{suffix}{ci} : Nat := (P{suffix}c{ci}.map (fun p => (p - 1) ^ 3)).prod")
        cl.append("")
        cl.append("end Erdos852")
        (LEANDIR / (cname + ".lean")).write_text("\n".join(cl) + "\n")
        chunk_files.append(cname)

    P = "P" + suffix
    # The inequality in the certificate's reduced spelling:
    #   (N - D) * den > 2 * (num + 1) * D
    lines = []
    lines.append("/- GENERATED by tools/gen-lean-erdos852.py — do not edit.")
    lines.append(f"   odd primes 3..{limit} ({len(ps)} of them); claim window edge ({num}+1)/{den}.")
    lines.append("   Nothing in the emitted data is trusted: primality, ascent and oddness of")
    lines.append("   P are kernel-re-proved below, and an omitted prime only weakens the bound. -/")
    for c in chunk_files:
        lines.append(f"import Erdos852.{c}")
    lines.append("")
    lines.append("namespace Erdos852")
    lines.append("")
    lines.append("/-- the chunks, in order, as REFERENCES — proofs below rewrite over this")
    lines.append("    240-entry list, never over 33,859 literals -/")
    lines.append(f"def chunks{P} : List (List Nat) := [" + ", ".join(f"P{suffix}c{i}" for i in range(1, nchunks + 1)) + "]")
    lines.append("")
    lines.append("/-- the prime list -/")
    lines.append(f"def {P} : List Nat := (chunks{P}).flatten")
    lines.append("")
    all_thms = ", ".join(f"P{suffix}c{i}_all_prime" for i in range(1, nchunks + 1))
    lines.append("set_option maxRecDepth 1000000 in")
    lines.append(f"theorem {P}_all_prime : {P}.all isPrime = true := by")
    lines.append(f"  unfold {P}")
    lines.append("  rw [all_flatten]")
    lines.append(f"  unfold chunks{P}")
    lines.append(f"  simp only [List.all_cons, List.all_nil, {all_thms}, Bool.true_and, Bool.and_true, Bool.and_self]")
    lines.append("")
    lines.append("set_option maxRecDepth 1000000 in")
    lines.append("set_option maxHeartbeats 0 in")
    lines.append(f"theorem {P}_ascending : ascending {P} = true := by decide +kernel")
    lines.append("")
    lines.append("/-- strictly increasing, hence no prime is counted twice -/")
    lines.append(f"theorem {P}_pairwise : List.Pairwise (· < ·) {P} :=")
    lines.append(f"  ascending_sound _ {P}_ascending")
    lines.append("")
    lines.append("set_option maxRecDepth 1000000 in")
    lines.append("set_option maxHeartbeats 0 in")
    lines.append(f"theorem {P}_all_odd : {P}.all (fun p => decide (2 < p)) = true := by decide +kernel")
    lines.append("")
    lines.append("/-- every element of P is prime, by Mathlib's definition -/")
    lines.append(f"theorem {P}_prime : ∀ p ∈ {P}, Nat.Prime p := fun p hp =>")
    lines.append(f"  isPrime_correct (List.all_eq_true.mp {P}_all_prime p hp)")
    lines.append("")
    lines.append(f"def N{suffix} : Nat := ((chunks{P}).map (fun c => (c.map (fun p => (p - 1) ^ 3 + 1)).prod)).prod")
    lines.append(f"def D{suffix} : Nat := ((chunks{P}).map (fun c => (c.map (fun p => (p - 1) ^ 3)).prod)).prod")
    lines.append("")
    lines.append(f"/-- N is EXACTLY the product of (p−1)³+1 over {P} — the generic flatten")
    lines.append("    lemma instantiated; no arithmetic, no literal terms -/")
    lines.append(f"theorem N{suffix}_spec : N{suffix} = ({P}.map (fun p => (p - 1) ^ 3 + 1)).prod := by")
    lines.append(f"  unfold N{suffix} {P}")
    lines.append(f"  exact (prod_map_flatten _ (chunks{P})).symm")
    lines.append("")
    lines.append(f"/-- D is EXACTLY the product of (p−1)³ over {P} -/")
    lines.append(f"theorem D{suffix}_spec : D{suffix} = ({P}.map (fun p => (p - 1) ^ 3)).prod := by")
    lines.append(f"  unfold D{suffix} {P}")
    lines.append(f"  exact (prod_map_flatten _ (chunks{P})).symm")
    lines.append("")
    lines.append("set_option maxRecDepth 1000000 in")
    lines.append("set_option maxHeartbeats 0 in")
    lines.append("/-- THE refutation inequality: the exact partial product's (N/D − 1)/2")
    lines.append(f"    strictly exceeds ({num}+1)/{den} — the upper edge of the published")
    lines.append("    claim's window under both truncation and rounding readings. -/")
    lines.append(f"theorem cstar_refuted{suffix} :")
    lines.append(f"    (N{suffix} - D{suffix}) * {den} > 2 * {num + 1} * D{suffix} := by decide +kernel")
    lines.append("")
    lines.append("end Erdos852")
    out = LEANDIR / (modname + ".lean")
    out.write_text("\n".join(lines) + "\n")
    root = "import Erdos852.Basic\n" + "".join(f"import Erdos852.{c}\n" for c in chunk_files) + f"import Erdos852.{modname}\n"
    if not suffix:
        (LEANDIR.parent / "Erdos852.lean").write_text(root)
    print(f"wrote {out} + {nchunks} chunk(s) ({len(ps)} primes, limit {limit}, claim {num}/{den}, forge={args.forge})")


def _is_prime(n):
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True


if __name__ == "__main__":
    main()
